### ISSUE TITLE
make new UnitList,UnitInfo

### ISSUE THREAD

**Issue by logisprosolution** [logisprosolution/WMS#1]
make new UnitList,UnitInfo
-insert search in UnitList
- missing fields
- insert update delete permission
- add view permission

**Comment by Patthamaporn** [comment]
-เพิ่มช่องและปุ่มค้นหาหน้า unitlist 
-เพิ่มปุ่มดูและกำหนดสิทธิ์ใช้งานแต่ละปุ่ม
-ปุ่มยังไม่สามารถใช้สิทธิ์ตามที่กำหนดหรือจากDBได้
