### ISSUE TITLE
ใบสั่งซื้อ_Field ราคาสั่ง,ทั้งหมด,ภาษีมูลค่าเพิ่ม,สุทธิ สามารถกรอกได้_เมื่อกดปุ่มแก้ไข

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#101]
Summary   Name | ใบสั่งซื้อ_Field   ราคาสั่ง,ทั้งหมด,ภาษีมูลค่าเพิ่ม,สุทธิ สามารถกรอกได้_เมื่อกดปุ่มแก้ไข
-- | --
Defect No. |  101
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/PurchaseInfo.aspx?dataId=8237&subDoc=18
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำ
  | 3.   เลือกเมนูย่อย ใบสั่งซื้อสินค้า
  | 4. เลือก   สั่งซื้อทั่วไป
  | 5. กดปุ่ม   แก้ไข หลังรายการ
  | 6.กรอกข้อมูลใน   Field ราคาสั่ง กรอกมากว่า 999
  | 7.กรอกข้อมูลใน   Field ทั้งหมด
  | 8.กรอกข้อมูลใน   Field ช่องตัวเลข หลังภาษีมูลค่าเพิ่ม
  | 9.กรอกข้อมูลใน   Field สุทธิ
  |  
Actual   Result | Field   ราคาสั่ง,ทั้งหมด,ภาษีมูลค่าเพิ่ม,สุทธิ สามารถกรอกได้_เมื่อกดปุ่มแก้ไข
  |  
Expected   Result | Field   ราคาสั่ง,ทั้งหมด,ภาษีมูลค่าเพิ่ม,สุทธิ ต้องกรอกไม่ได้_เมื่อกดปุ่มแก้ไข
  |  
Tester   Name | Phatchanok.Sun

![image](https://user-images.githubusercontent.com/45878758/53898233-3fa50080-406a-11e9-8035-38865ceeda9f.png)

**Comment by Patthamaporn** [comment]
Field_ราคาสั่ง เปิดให้สามารถ แก้ไข ได้ครับ
ตัวอย่าง : ในกรณีที่สั่งของจากคู่ค้าแล้ว มีการปรับราคาขึ้นลง ในแต่ละรอบการสั่งไม่เหมือนกัน

**Comment by Vermouthz** [comment]
Retest-Pass
![image](https://user-images.githubusercontent.com/45878758/54069172-8c195780-4287-11e9-8219-5425d276bfd1.png)
