### ISSUE TITLE
ใบสั่งซื้อ_Field ส่วนเพิ่ม,ส่วนลด ใส่ตัวเลขเกิน 21 หลัก ขึ้น Error_เมื่อกดปุ่มแก้ไข

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#102]
Summary   Name | ใบสั่งซื้อ_Field   ส่วนเพิ่ม,ส่วนลด ใส่ตัวเลขเกิน 21 หลัก ขึ้น Error_เมื่อกดปุ่มแก้ไข
-- | --
Defect No. |  102
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/PurchaseInfo.aspx?dataId=8237&subDoc=18
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำ
  | 3.   เลือกเมนูย่อย ใบสั่งซื้อสินค้า
  | 4. เลือก   สั่งซื้อทั่วไป
  | 5. กดปุ่ม   แก้ไข หลังรายการ
  | 6.กรอกข้อมูลใน   Field ส่วนเพิ่ม ใส่ตัวเลขเกิน 21 หลัก "1234567890123456789012"
  | 7.กรอกข้อมูลใน   Field ส่วนลด ใส่ตัวเลขเกิน 21 หลัก "1234567890123456789012"
  |  
Actual   Result | Field   ส่วนเพิ่ม,ส่วนลด ใส่ตัวเลขเกิน 21 หลัก แสดง Error   "1.2,345,678,901,234,568e+21"
  |  
Expected   Result | Field   ส่วนเพิ่ม,ส่วนลด ต้องสามารถใส่ตัวเลขได้ 30 หลัก "1234567890123456789012.00"
  |  
Tester   Name | Phatchanok.Sun

![image](https://user-images.githubusercontent.com/45878758/53898580-ee494100-406a-11e9-84f5-57adecc260a0.png)

**Comment by Patthamaporn** [comment]
แก้ไขให้กำหนดกรอกได้ไม่เกิน16ตัวอักษร
