### ISSUE TITLE
ใบสั่งซื้อ_จำนวน*รหัสสินค้า_กรอกตัวเลขน้อยกว่า 1 และมากกว่า 10000_เมื่อกดปุ่มแก้ไข

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#105]
Summary   Name | ใบสั่งซื้อ_จำนวน*รหัสสินค้า_กรอกตัวเลขน้อยกว่า   1 และมากกว่า 10000_เมื่อกดปุ่มแก้ไข
-- | --
Defect No. |  105
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/PurchaseInfo.aspx?subDoc=18
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำ
  | 3.   เลือกเมนูย่อย ใบสั่งซื้อสินค้า
  | 4. เลือก   สั่งซื้อทั่วไป
  | 5. กดปุ่ม แก้ไข   หลังรายการ
  |  
Actual   Result | จำนวน*รหัสสินค้า   กรอกตัวเลขน้อยกว่า 1 และมากกว่า 10000 ได้
  |  
Expected   Result | จำนวน*รหัสสินค้า   ไม่สามารถกรอกตัวเลขน้อยกว่า 1 และมากกว่า 10000 ได้
  |  
Tester   Name | Phatchanok.Sun

![image](https://user-images.githubusercontent.com/45878758/53899232-53e9fd00-406c-11e9-9eee-673e2ff8174e.png)

**Comment by Patthamaporn** [comment]
สามารถกรอกให้น้อยกว่าและมากกว่าได้ แต่จะมี valisate แจ้งเตือนแล้วไม่สามารถบันทึกได้

**Comment by Vermouthz** [comment]
Retest Pass 21/4/2562
![image](https://user-images.githubusercontent.com/45878758/56462685-96d01c00-63f1-11e9-9395-4265cf1cf546.png)

![image](https://user-images.githubusercontent.com/45878758/56462747-af8d0180-63f2-11e9-9970-fe64ca5e05fe.png)
![image](https://user-images.githubusercontent.com/45878758/56462755-b61b7900-63f2-11e9-9ff1-0c660e436643.png)
