### ISSUE TITLE
ใบสั่งซื้อสินค้า_Field_ราคาสั่ง,ทั้งหมด,ช่องแสดงตัวเลขหลังภาษีมูลค่าเพิ่ม,สุทธิ สามารถกรอกได้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#108]
Summary   Name | ใบสั่งซื้อสินค้า_Field_ราคาสั่ง,ทั้งหมด,ช่องแสดงตัวเลขหลังภาษีมูลค่าเพิ่ม,สุทธิ   สามารถกรอกได้
-- | --
Defect No. |  108
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/PurchaseInfo.aspx?subDoc=18
Step | 1.   Login
  | 2.   เลือกเมนู งานประจำ
  | 3.   เลือกเมนูย่อย ใบสั่งซื้อสินค้า
  | 4. เลือก   สั่งซื้อทั่วไป
  | 5. กดปุ่ม   เพิ่มใบสั่งซื้อ
  |  
Actual   Result | Field_ราคาสั่ง,ทั้งหมด,ช่องแสดงตัวเลขหลังภาษีมูลค่าเพิ่ม,สุทธิ   สามารถกรอกได้
  |  
  |  
Expected   Result | Field_ราคาสั่ง,ทั้งหมด,ช่องแสดงตัวเลขหลังภาษีมูลค่าเพิ่ม,สุทธิ   ต้องไม่สามารถกรอกได้
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/53900257-b512d000-406e-11e9-83fa-b26e286b863b.png)
![image](https://user-images.githubusercontent.com/45878758/53900260-b93eed80-406e-11e9-903e-a74416faed31.png)

**Comment by logisprosolution** [comment]
Field_ราคาสั่ง เปิดให้สามารถกรอกได้ครับ
ตัวอย่าง : ในกรณีที่สั่งของจากคู่ค้าแล้ว มีการปรับราคาขึ้นลง ในแต่ละรอบการสั่งไม่เหมือนกัน

**Comment by Patthamaporn** [comment]
Field ราคาสั่ง สามารถแก้ไขได้ เนื่องจาก 1บาร์โค้ดมีได้หลายราคาหรือมีการเปลี่ยนแปลงราคามาจากฝั่ง Supplier แต่ยังไม่ได้ทำการแก้ไขราคาที่ข้อมูลสินค้า
