### ISSUE TITLE
SKU

### ISSUE THREAD

**Issue by logisprosolution** [logisprosolution/WMS#11]
1 add search  
2 add -permission
3 add SKU_Supplier on Skuinfo tab
     3.1 add upplier btn ---> popup
          3.1.1 popup SKU_Supplier 
               - search code/name , suplierType
               - select btn
     3.2 use default at one
     3.3 set value to saveInfo() for save on this page
4. improve designed
5. make sure to don't have losing fields.

**Comment by Patthamaporn** [comment]
Filed ในตาราง SKU_SKU ที่ยังไม่ได้ทำการบันทึก
-skuCostAVG
-fileNameTopView
-ImageTopView

**Comment by Patthamaporn** [comment]
wait for test
