### ISSUE TITLE
เมนูใบสั่งซื้อสินค้า_สอบถามเรื่อง Field รหัส/ชื่อ , ยอด และการแสดงหน้าจอค้นหา

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#114]
1. Field รหัส/ชื่อ กรอกได้มากสุดกี่ตัวอักษร  http://nps001.homeip.net:8085/PurchaseInfo.aspx?dataId=8237&subDoc=18
2. Field ที่ใช้สำหรับค้นหา 
- รหัส/ชื่อ
- หน่วย
- จำนวน
แสดงในหน้าจอไหนบ้าง (เพิ่ม , ดู , อนุมัติ , แก้ไข)
![image](https://user-images.githubusercontent.com/45878758/53973943-4435eb80-4134-11e9-9e69-4443795acfee.png)

3. Field ยอด ใช้ Keyword ค้นหาจากอะไร และแสดงได้กี่ตัวอักษร  http://nps001.homeip.net:8085/PurchaseList.aspx?subDoc=18&menuID=2085
![image](https://user-images.githubusercontent.com/45878758/53973798-ff11b980-4133-11e9-9312-641f1104b031.png)
Tester : Phatcharat.Sun

**Comment by logisprosolution** [comment]
ยังไม่ต้องสนใจ ค้นหาครับ ณ ตอนนี้
