### ISSUE TITLE
นำเข้าสินค้า_Tab รายการ ไม่มีปุ่มค้นหา_เมื่อกดปุ่ม รับสินค้าเข้า

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#116]
Summary   Name | นำเข้าสินค้า_Tab   รายการ ไม่มีปุ่มค้นหา_เมื่อกดปุ่ม รับสินค้าเข้า
-- | --
Defect No. |  116
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?subDoc=3&ref=8219
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย นำเข้าสินค้า
  | 4. เลือก   นำเข้าสินค้าจากใบสั่งซื้อ
  | 5.   แสดงหน้าจอ รายการนำเข้าสินค้า
  | 6. กดปุ่ม   รับสินค้าเข้า หลังรายการ
  | 7. เลือก   Tab รายการ
  |  
Actual   Result | Tab รายการ   ไม่มีปุ่มค้นหา
  |  
Expected   Result | Tab รายการ   ต้องมีปุ่มค้นหา

![image](https://user-images.githubusercontent.com/45878758/53982314-2f168800-4147-11e9-8b11-743ffce6469c.png)
![image](https://user-images.githubusercontent.com/45878758/54186372-d5fb7b00-44dd-11e9-8984-b2e9d8de8253.png)

**Comment by Patthamaporn** [comment]
ช่องค้นหาจะแสดงต่อเมื่อกดแก้ไขรายการเท่านั้น หากเพิ่มข้อมูลใหม่จะไม่สามารถค้นหาได้
