### ISSUE TITLE
ค้นหาสินค้า_ สอบถาม สามารถเลือก สินค้าพร้อมกัน และเลือกมากสุดกี่รายการคะะ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#119]
1.ค้นหาสินค้า สามารถเลือกทีเดียว พร้อมกันได้มั้ยคะ
URL : http://nps001.homeip.net:8085/PopupGoodsSelectNoPrice.aspx
![image](https://user-images.githubusercontent.com/45878758/54067016-9d089f80-426c-11e9-8648-8919e9b77f0f.png)
2. เลือกสินค้าได้มากสุดกี่รายการคะ
URL : http://nps001.homeip.net:8085/PurchaseInfo.aspx?subDoc=18
![image](https://user-images.githubusercontent.com/45878758/54067025-c88b8a00-426c-11e9-9fc3-9df9bd4e92d2.png)

**Comment by logisprosolution** [comment]
1. เลือกได้ทีละรายการ
2. เลือกได้ไม่จำกัด
