### ISSUE TITLE
สอบถาม แสดงภาษาไทย หรือภาษาอังกฤษใน ข้อมูลแสดงผล และจำนวนหน้าค่ะ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#120]
1. ใช้ภาษาไทย หรืออังกฤษคะ
URL : http://nps001.homeip.net:8085/PurchaseList.aspx?subDoc=18&menuID=2085
- ไม่พบรายการ หรือ No matching records found
- แสดง 1 ถึง 10 จาก 11 รายการ หรือ Showing 1 to 10 of 11 entries
- ค้นหา หรือ Search
![image](https://user-images.githubusercontent.com/45878758/54067862-f9bd8780-4277-11e9-8b5c-0bd24beb9032.png)
![image](https://user-images.githubusercontent.com/45878758/54067865-0e018480-4278-11e9-9cfb-28a37c4c02b4.png)
![image](https://user-images.githubusercontent.com/45878758/54068781-e6fc8000-4282-11e9-9092-31f2c072ce7e.png)

**Comment by Patthamaporn** [comment]
ภาษาไทยค่ะ
![image](https://user-images.githubusercontent.com/37695403/54099268-f39be800-43ea-11e9-93ed-72351e27fbd9.png)

**Comment by logisprosolution** [comment]
รบกวนอุ๊ช่วยตรวจการตั้งค่า ภาษาของ windows 
และการตั้งค่าภาษาของ google chrome พร้อมทั้งส่งรูปให้ทีครับ
