### ISSUE TITLE
ใบสั่งซื้อ_Field ราคาสั่ง ส่วนลดรายการ กรอกมากกว่า 5 ตัวอักษร_เมื่อกดปุ่ม แก้ไข

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#121]
Summary   Name | ใบสั่งซื้อ_Field   ราคาสั่ง ส่วนลดรายการ กรอกมากกว่า 5 ตัวอักษร_เมื่อกดปุ่ม แก้ไข
-- | --
Defect No. |  121
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/PurchaseInfo.aspx?dataId=11262&subDoc=18
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำ
  | 3.   เลือกเมนูย่อย ใบสั่งซื้อสินค้า
  | 4. เลือก   สั่งซื้อทั่วไป
  | 5. กดปุ่ม แก้ไข   หลังรายการ
  |  
Actual   Result | Field ราคาสั่ง   ส่วนลดรายการ กรอกมากกว่า 5 ตัวอักษร
  |  
Expected   Result | Field ราคาสั่ง   ส่วยลดรายการ ต้องกรอกได้ไม่เกิน 5 ตัวอักษร
  |  
Tester   Name | Phatchanok.Sun

![image](https://user-images.githubusercontent.com/45878758/54070394-0949ca00-4292-11e9-8cbf-be8ee12d3fb0.png)

**Comment by Patthamaporn** [comment]
แก้ไข : เมื่อกรอกราคาสั่งซื้อและส่วนลดรายการ
จะไม่สามารถกรอกได้เกิน5ตัวอักษร
