### ISSUE TITLE
สอบถาม Message เลือกคู่ค้า และเลือกสินค้า

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#122]
1. Message "โปรดเลือกคู่ค้าที่จะเก็บก่อนบันทึก" เปลี่ยนเป็น "กรุณาเลือกคู่ก่อนบันทึก" ดีมั้ยหรือแบบเดิมดีอยู่แล้วคะ
![image](https://user-images.githubusercontent.com/45878758/54070680-6dba5880-4295-11e9-842d-36f8e7e1a04b.png)
2. Message "โปรดเลือกสินค้าก่อนบันทึก" เปลี่ยนเป็น "กรุณาเลือกสินค้าก่อนบันทึก" ดีมั้ยหรือแบบเดิมดีอยู่แล้วคะ
![image](https://user-images.githubusercontent.com/45878758/54070695-c38f0080-4295-11e9-9538-2ec0109af3e9.png)

**Comment by logisprosolution** [comment]
แก้ไขตามนี้

**Comment by Mickrepick** [comment]
แก้ไข : Message "โปรดเลือกคู่ค้าที่จะเก็บก่อนบันทึก" เปลี่ยนเป็น "กรุณาเลือกคู่ค้าก่อนบันทึก"
           Message "โปรดเลือกสินค้าก่อนบันทึก" เปลี่ยนเป็น "กรุณาเลือกสินค้าก่อนบันทึก" ครับ
