### ISSUE TITLE
สอบถาม ข้อความแจ้งเตือนด้านล่างของ เลขที่เอกสาร,วันที่เอกสาร,จำนวนสั่งซื้อ,ราคาสั่ง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#123]
1. ข้อความแจ้งเตือนด้านล่าง จาก Field เลขที่เอกสาาร , วันที่เอกสาร , จำนวนสั่งซื้อ , ราคาสั่ง
- "กรุณากรอกข้อมูล" เป็น "กรุณาระบุข้อมูล เลขที่เอกสาร ให้ถูกต้อง"
- "กรุณากรอกข้อมูล" เป็น "กรุณาระบุข้อมูล วันที่เอกสาร ให้ถูกต้อง" 
- "จำนวนต้องมีค่า 1-10,000" เป็น "กรุณาระบุข้อมูล จำนวนสั่งซื้อ ให้ถูกต้อง"
URL : http://nps001.homeip.net:8085/PurchaseInfo.aspx?subDoc=18
![image](https://user-images.githubusercontent.com/45878758/54071171-a9f0b780-429b-11e9-859e-6219ed57a94b.png)

2. Field วันที่นัดรับ เป็น Field บังคับหรือไม่เป็นคะ
![image](https://user-images.githubusercontent.com/45878758/54071177-ba089700-429b-11e9-9825-2f08109a8165.png)

**Comment by logisprosolution** [comment]
วันที่นัดรับ ไม่ต้อง require
แต่ข้อความต้องแก้ครับ

**Comment by Mickrepick** [comment]
แก้ไข : ข้อความแจ้งเตือนด้านล่าง เปลี่ยนเป็น
- กรุณาระบุข้อมูล เลขที่เอกสาร ให้ถูกต้อง
- กรุณาระบุข้อมูล วันที่เอกสาร ให้ถูกต้อง
- กรุณาระบุข้อมูล จำนวนสั่งซื้อ ให้ถูกต้อง
- กรุณาระบุข้อมูล ราคาสั่ง ให้ถูกต้อง
