### ISSUE TITLE
รายการตรวจสินค้าเข้า_เลือก สถานะ รอนุมัติ สถานะแสดงรายการ เรียบร้อย,รอนุมัติ 

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#125]
Summary   Name | รายการตรวจสินค้าเข้า_เลือก   สถานะ รอนุมัติ สถานะแสดงรายการ เรียบร้อย,รอนุมัติ
-- | --
Defect No. |  125
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/CheckerInList.aspx?subDoc=21&menuID=2090
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย ตรวจสอบสินค้นค้าเข้า
  | 4. เลือก   ตรวจสอบสินค้าเข้า
  | 5.   แสดงหน้าจอ รายการตรวจสินค้าเข้า
  |  
Actual   Result | เลือก สถานะ   รอนุมัติ  สถานะแสดงรายการ   เรียบร้อย,รอนุมัติ
  |  
Expected   Result | เลือก สถานะ   รอนุมัติ  สถานะต้องแสดงรายการ   รอนุมัติ  เท่านั้น

![image](https://user-images.githubusercontent.com/45878758/54190275-1c54d800-44e6-11e9-9b95-07bf3575f796.png)

**Comment by Malatoo** [comment]
Edit >> [WebWMSDB20190323].[dbo].[udp_DOC_Trans_Header_lst]
Before >> or (d.subDocTypeID = @subDocTypeIDRef and d.docStatusID = @docStatusSuccess or @docStatusSuccess = 0)
After>> or  (@docStatusID = 0 AND @docStatusID = 1) AND (d.subDocTypeID = @subDocTypeIDRef and d.docStatusID = @docStatusSuccess or @docStatusSuccess = 0)

**Comment by Malatoo** [comment]
Edit >> [WebWMSDB20190323].[dbo].[udp_DOC_Trans_Header_lst]
Before >> or (d.subDocTypeID = @subDocTypeIDRef and d.docStatusID = @docStatusSuccess or @docStatusSuccess = 0)
After>> or  (@docStatusID = 0 AND @docStatusID = 1) AND (d.subDocTypeID = @subDocTypeIDRef and d.docStatusID = @docStatusSuccess or @docStatusSuccess = 0)
