### ISSUE TITLE
รายการตรวจสินค้าเข้า_Colume   วันที่นัดส่ง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#127]
Summary   Name | รายการตรวจสินค้าเข้า_Colume   วันที่นัดส่ง
-- | --
Defect No. |  127
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/CheckerInList.aspx?subDoc=21&menuID=2090
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย ตรวจสอบสินค้นค้าเข้า
  | 4. เลือก   ตรวจสอบสินค้าเข้า
  | 5.   แสดงหน้าจอ รายการตรวจสินค้าเข้า
  |  
Actual   Result | Colume วันที่นัดส่ง
  |  
Expected   Result | Colume วันที่นัดส่ง   ต้องเป็น วันที่นัดรับ

![image](https://user-images.githubusercontent.com/45878758/54190622-c59bce00-44e6-11e9-929c-3eb4a599dd50.png)

**Comment by Mickrepick** [comment]
แก้ไข : Column วันที่นัดส่ง เป็น วันที่นัดรับ

**Comment by Vermouthz** [comment]
Retest-Failed

![image](https://user-images.githubusercontent.com/45878758/56473257-bc613200-6492-11e9-8950-75804e681833.png)

**Comment by Mickrepick** [comment]
แก้ไข : Column วันที่นัดส่ง เป็น วันที่นัดรับ
