### ISSUE TITLE
ตรวจสินค้าเข้า_จำนวนที่เช็คแล้ว   กรอกเกิน 5 หลัก

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#128]
Summary   Name | ตรวจสินค้าเข้า_จำนวนที่เช็คแล้ว   กรอกเกิน 5 หลัก
-- | --
Defect No. |  128
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/CheckerInInfo.aspx?subDoc=21
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย ตรวจสอบสินค้นค้าเข้า
  | 4. เลือก   ตรวจสอบสินค้าเข้า
  | 5.   แสดงหน้าจอ รายการตรวจสินค้าเข้า
  |  
Actual   Result | จำนวนที่เช็คแล้ว   กรอกเกิน 5 หลัก "12345678..."
  |  
Expected   Result | จำนวนที่เช็คแล้ว ต้องกรอกได้ไม่เกิน 5 หลัก "12345"

![image](https://user-images.githubusercontent.com/45878758/54190764-19a6b280-44e7-11e9-991d-3ca77ee9af5b.png)

**Comment by acryforever** [comment]
จำนวนที่เช็คแล้ว กรอกไม่ได้ ขอปิด issuse
