### ISSUE TITLE
ตรวจสินค้าเข้า_จำนวนที่เช็คแล้ว   ใส่จำนวนติดลบได้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#129]
Summary   Name | ตรวจสินค้าเข้า_จำนวนที่เช็คแล้ว   ใส่จำนวนติดลบได้
-- | --
Defect No. |  129
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/CheckerInInfo.aspx?subDoc=21
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย ตรวจสอบสินค้นค้าเข้า
  | 4. เลือก   ตรวจสอบสินค้าเข้า
  | 5.   แสดงหน้าจอ รายการตรวจสินค้าเข้า
  |  
Actual   Result | Fieldจำนวนที่เช็คแล้ว ใส่จำนวนติดลบได้ เมื่อ Field จำนวนที่เช็คแล้ว มีค่าเป็น "0"
  |  
Expected   Result | จำนวนที่เช็คแล้ว ต้องไม่สามารถใส่จำนวนติดลบได้ เมื่อ Field จำนวนที่เช็คแล้ว มีค่าเป็น "0" เพราะเมื่อใส่ จำนวนติดลบ "-1" ระบบจะไปบวกเพิ่ม Field จำนวนคงเหลือมากกว่า Field จำนวนสั่งซื้อ เช่น จำนวนสั่งซื้อ "20" เมื่อใส่จำนวนที่เช็คแล้ว "-1" Field จำนวนคงเหลือจาก 20 จะเป็น 21

![image](https://user-images.githubusercontent.com/45878758/54190881-5a9ec700-44e7-11e9-9ffb-5816e77608d8.png)

**Comment by Mickrepick** [comment]
Field จำนวนที่เช็คแล้ว เป็น Field ปิด ไม่สามารถกรอกข้อมูลได้ ขอปิด Issues ครับ
