### ISSUE TITLE
ตรวจสินค้าเข้า_หมายเหตุ   กรอกข้อมูลได้_เมื่อกดปุ่ม ดู

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#138]
Summary   Name | ตรวจสินค้าเข้า_หมายเหตุ   กรอกข้อมูลได้_เมื่อกดปุ่ม ดู
-- | --
Defect No. |  138
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/CheckerInInfo.aspx?dataId=11272&view=1
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย ตรวจสอบสินค้นค้าเข้า
  | 4. เลือก   ตรวจสอบสินค้าเข้า
  | 5.   แสดงหน้าจอ รายการตรวจสินค้าเข้า
  | 6. กดปุ่ม   ดู หลังรายการ
  |  
Actual   Result | หมายเหตุ   กรอกข้อมูลได้
  |  
Expected   Result | หมายเหตุ ต้องเป็น   Field ปิด ไม่สามารถกรอกข้อมูลได้

![image](https://user-images.githubusercontent.com/45878758/54192024-a7839d00-44e9-11e9-91c5-084cdc31c508.png)

**Comment by Mickrepick** [comment]
แก้ไข : Field หมายเหตุ เป็น Field ปิด ไม่สามารถกรอกข้อมูลได้
