### ISSUE TITLE
ตรวจสินค้าเข้า_เลขที่เอกสาร   กรอกข้อมูลได้_เมื่อกดปุ่ม อนุมัติ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#140]
Summary   Name | ตรวจสินค้าเข้า_เลขที่เอกสาร   กรอกข้อมูลได้_เมื่อกดปุ่ม อนุมัติ
-- | --
Defect No. |  140
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/CheckerInInfo.aspx?dataId=11252&subDoc=21&approve=1
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย ตรวจสอบสินค้นค้าเข้า
  | 4. เลือก   ตรวจสอบสินค้าเข้า
  | 5.   แสดงหน้าจอ รายการตรวจสินค้าเข้า
  | 6. กดปุ่ม   ดู หลังรายการ
  | 7. Tab รูป
  |  
Actual   Result | เลขที่เอกสาร   กรอกข้อมูลได้
  |  
Expected   Result | เลขที่เอกสาร ต้องเป็น   Field ปิด ไม่สามารถกรอกข้อมูลได้

![image](https://user-images.githubusercontent.com/45878758/54192226-0b0dca80-44ea-11e9-8c02-06a986c83496.png)

**Comment by Mickrepick** [comment]
แก้ไข : Field เลขที่เอกสาร เป็น Field ปิด ไม่สามารถกรอกข้อมูลได้
