### ISSUE TITLE
ตรวจสินค้าเข้า_จำนวนที่เช็คแล้ว   กรอกเกิน 5 หลัก_เมื่อกดปุ่มตรวจสอบ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#141]
Summary   Name | ตรวจสินค้าเข้า_จำนวนที่เช็คแล้ว   กรอกเกิน 5 หลัก_เมื่อกดปุ่มตรวจสอบ
-- | --
Defect No. |  141
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/CheckerInInfo.aspx?subDoc=21&ref=11243
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย ตรวจสอบสินค้นค้าเข้า
  | 4. เลือก   ตรวจสอบสินค้าเข้า
  | 5.   แสดงหน้าจอ รายการตรวจสินค้าเข้า
  | 6. กดปุ่ม   ตรวจสอบ
  | 7. กด Tab   รายการ
  |  
Actual   Result | จำนวนที่เช็คแล้ว   กรอกเกิน 5 หลัก
  |  
Expected   Result | จำนวนที่เช็คแล้ว   ต้องกรอกได้ไม่เกิน 5 หลัก

![image](https://user-images.githubusercontent.com/45878758/54192482-a010c380-44ea-11e9-95d7-d8df229b4fc0.png)

**Comment by Mickrepick** [comment]
Field จำนวนที่เช็คแล้ว เป็น Field ปิด ไม่สามารถกรอกข้อมูลได้ ขอปิด Issues ครับ
