### ISSUE TITLE
ตรวจสินค้าเข้า_จำนวนที่เช็คแล้ว   ใส่จำนวนติดลบได้_เมื่อกดปุ่ม ตรวจสอบ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#142]
Summary   Name | ตรวจสินค้าเข้า_จำนวนที่เช็คแล้ว   ใส่จำนวนติดลบได้_เมื่อกดปุ่ม ตรวจสอบ
-- | --
Defect No. |  142
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/CheckerInInfo.aspx?subDoc=21&ref=11243
Step | 1. Login WMS on   Chorme
  | 2. เลือกเมนู   งานประจำวัน
  | 3. เลือกเมนูย่อย   ตรวจสอบสินค้นค้าเข้า
  | 4. เลือก   ตรวจสอบสินค้าเข้า
  | 5. แสดงหน้าจอ   รายการตรวจสินค้าเข้า
  | 6. กดปุ่ม ตรวจสอบ
  | 7. กด Tab รายการ
  |  
Actual Result | จำนวนที่เช็คแล้ว   ใส่จำนวนติดลบได้
  |  
Expected   Result | จำนวนที่เช็คแล้ว   ต้องไม่สามารถใส่จำนวนติดลบได้

![image](https://user-images.githubusercontent.com/45878758/54192564-dcdcba80-44ea-11e9-9e84-6c4cba2796de.png)

**Comment by acryforever** [comment]
TEXT เป็นฟิวปิดไม่สามารถกรอกข้อมูลได้
