### ISSUE TITLE
ตรวจสินค้าเข้า_จำนวน*รหัสสินค้า   ใส่จำนวนติดลบได้ โดยที่ จำนวนคงเหลือ 0

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#143]
Summary   Name | ตรวจสินค้าเข้า_จำนวน*รหัสสินค้า   ใส่จำนวนติดลบได้ โดยที่ จำนวนคงเหลือ 0
-- | --
Defect No. |  143
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/CheckerInInfo.aspx?subDoc=21
Step | 1. Login WMS on   Chorme
  | 2. เลือกเมนู   งานประจำวัน
  | 3. เลือกเมนูย่อย   ตรวจสอบสินค้นค้าเข้า
  | 4. เลือก   ตรวจสอบสินค้าเข้า
  | 5. แสดงหน้าจอ   รายการตรวจสินค้าเข้า
  |  
Actual Result | จำนวน*รหัสสินค้า   ใส่จำนวนติดลบได้ โดยที่ จำนวนคงเหลือ 0
  |  
Expected   Result | จำนวน*รหัสสินค้า   ไม่สามารถใส่จำนวนติดลบได้ ถ้า จำนวนคงเหลือ 0

![image](https://user-images.githubusercontent.com/45878758/54192717-2f1ddb80-44eb-11e9-982b-d6a6c5d181cb.png)

**Comment by acryforever** [comment]
แก้ไข้แล้วไม่สามารถติดลบได้ จาก อิชู144
