### ISSUE TITLE
ตรวจสินค้า_จำนวน*รหัสสินค้า   ใส่จำนวนติดลบได้ โดยที่ จำนวนคงเหลือ 0 _ เมื่อกดปุ่มตรวจสอบ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#144]
Summary   Name | ตรวจสินค้า_จำนวน*รหัสสินค้า   ใส่จำนวนติดลบได้ โดยที่ จำนวนคงเหลือ 0 _ เมื่อกดปุ่มตรวจสอบ
-- | --
Defect No. |  144
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/CheckerInInfo.aspx?subDoc=21&ref=11243
Step | 1. Login WMS on   Chorme
  | 2. เลือกเมนู   งานประจำวัน
  | 3. เลือกเมนูย่อย   ตรวจสอบสินค้นค้าเข้า
  | 4. เลือก   ตรวจสอบสินค้าเข้า
  | 5. แสดงหน้าจอ   รายการตรวจสินค้าเข้า
  | 6. กดปุ่ม ตรวจสอบ
  | 7. กด Tab รายการ
  |  
Actual Result | จำนวน*รหัสสินค้า   ใส่จำนวนติดลบได้ โดยที่ จำนวนคงเหลือ 0
  |  
Expected   Result | จำนวน*รหัสสินค้า   ไม่สามารถใส่จำนวนติดลบได้ ถ้า จำนวนคงเหลือ 0

![image](https://user-images.githubusercontent.com/45878758/54217323-006d2880-451e-11e9-8f37-fe53c076afdb.png)

**Comment by acryforever** [comment]
รหัสสินค้า ไม่สามารถใส่จำนวนติดลบได้ ถ้า จำนวนคงเหลือ 0 เพิ่ม loop
