### ISSUE TITLE
ตรวจสินค้าเข้า_ปฎิทิน ใส่ พ.ศ.   มากกว่า 4 หลัก ใน เพิ่มใบตรวจสินค้า,แก้ไข

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#145]
Summary   Name | ปฎิทิน ใส่ พ.ศ.   มากกว่า 4 หลัก ใน เพิ่มใบตรวจสินค้า,แก้ไข
-- | --
Defect No. |  145
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/CheckerInInfo.aspx?subDoc=21
  | http://nps001.homeip.net:8085/CheckerInInfo.aspx?dataId=11272&subDoc=21
  |  
Actual Result | ปฎิทิน ใส่ พ.ศ.   มากกว่า 4 หลัก ใน เพิ่มใบตรวจสินค้า,แก้ไข
  |  
Expected   Result | ปฎิทิน ต้องใส่ พ.ศ.   ได้ไม่เกิน 4 หลัก

![image](https://user-images.githubusercontent.com/45878758/54193649-1f06fb80-44ed-11e9-9ac3-04b7823f3b84.png)

**Comment by Mickrepick** [comment]
แก้ไข :  Field วันที่เอกสาร, วันที่ใบส่งของ ปฎิทิน จะใส่ พ.ศ. ได้ไม่เกิน 4 หลัก

**Comment by Vermouthz** [comment]
ไม่มีปุ่ม เพิ่มใบตรวจ แล้ว ต้องกด ตรวจสอบ หลังรายการอย่างเดียว
