### ISSUE TITLE
นำเข้าสินค้า_ปฎิทิน ใส่ พ.ศ.   มากกว่า 4 หลัก ใน เพิ่มใบนำเข้า,แก้ไข

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#146]
Summary   Name | ปฎิทิน ใส่ พ.ศ.   มากกว่า 4 หลัก ใน เพิ่มใบนำเข้า,แก้ไข
-- | --
Defect No. |  146
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?subDoc=3
  | http://nps001.homeip.net:8085/InboundInfo.aspx?dataId=11261&subDoc=3
  |  
Actual Result | ปฎิทิน ใส่ พ.ศ.   มากกว่า 4 หลัก ใน เพิ่มใบนำเข้า,แก้ไข
  |  
Expected   Result | ปฎิทิน ต้องใส่ พ.ศ.   ได้ไม่เกิน 4 หลัก

![image](https://user-images.githubusercontent.com/45878758/54193739-478ef580-44ed-11e9-8e72-4e387cb4a7ce.png)

**Comment by Mickrepick** [comment]
แก้ไข :  Field วันที่เอกสาร, วันที่ใบกำกับภาษี , วันที่ใบส่งของ ปฎิทิน จะใส่ พ.ศ. ได้ไม่เกิน 4 หลัก
