### ISSUE TITLE
ใบสั่งซื้อ_ปฎิทิน ใส่ พ.ศ.   มากกว่า 4 หลัก ใน เพิ่มใบสั่งซื้อ,แก้ไข

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#147]
Summary   Name | ปฎิทิน ใส่ พ.ศ.   มากกว่า 4 หลัก ใน เพิ่มใบสั่งซื้อ,แก้ไข
-- | --
Defect No. |  147
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/PurchaseInfo.aspx?subDoc=18
  | http://nps001.homeip.net:8085/PurchaseInfo.aspx?dataId=11267&subDoc=18
  |  
Actual Result | ปฎิทิน ใส่ พ.ศ.   มากกว่า 4 หลัก ใน เพิ่มใบสั่งซื้อ,แก้ไข
  |  
Expected   Result | ปฎิทิน ต้องใส่ พ.ศ.   ได้ไม่เกิน 4 หลัก

![image](https://user-images.githubusercontent.com/45878758/54193814-6e4d2c00-44ed-11e9-95eb-45173b3df313.png)

**Comment by Mickrepick** [comment]
แก้ไข :  Field วันที่เอกสาร, วันที่นัดรับ ปฎิทิน จะใส่ พ.ศ. ได้ไม่เกิน 4 หลัก
