### ISSUE TITLE
ใบสั่งซื้อ_กรอกข้อมูลใน Field ส่วนลด และส่วนเพิ่ม เมื่อกด Enter ระบบแสดง Error Message "ไม่พบข้อมูล" กรณีกดปุ่ม เพิ่มใบสั่งซื้อ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#148]
Summary   Name | ใบสั่งซื้อ_กรอกข้อมูลใน   Field ส่วนลด และส่วนเพิ่ม เมื่อกด Enter ระบบแสดง Error Message   "ไม่พบข้อมูล" กรณีกดปุ่ม เพิ่มใบสั่งซื้อ
-- | --
Defect No. |  148
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/PurchaseInfo.aspx?subDoc=18
Step | 1. เลือกเมนู   งานประจำวัน
  | 2.   เลือกเมนูย่อย ใบสั่งซื้อสินค้า
  | 3. เลือก   สั่งซื้อทั่วไป
  | 4. แสดงหน้าจอ   รายการใบสั่งซื้อสินค้า
  | 5. กด เพิ่มใบสั่งซื้อ
  | 6. กด ค้นหาสินค้า
  | 7. เลือกสินค้า
  | 8. กรอกข้อมูลใน Field   ส่วนลด
  | 9. กด Enter   ที่คีย์บอร์ด
  | 10. กรอกข้อมูลใน   Field ส่วนเพิ่ม
  | 11. กด Enter   ที่คีย์บอร์ด
  |  
  |  
Actual   Result | กรอกข้อมูลใน Field   ส่วนลด และส่วนเพิ่ม เมื่อกด Enter ระบบแสดง Error Message   "ไม่พบข้อมูล"
  |  
  |  
Expected   Result | ระบบต้องไม่แสดง Error   Message
  |  

![image](https://user-images.githubusercontent.com/45878758/54218262-d0bf2000-451f-11e9-971b-c04baaf0c8f9.png)
![image](https://user-images.githubusercontent.com/45878758/54218323-efbdb200-451f-11e9-8c6e-4cb99d328271.png)

**Comment by acryforever** [comment]
ระบบต้องไม่แสดง Error Message แก้ไข Check loop AddProductToCart เนื่องจากค่าที่รับมีการแอดค่าเข้า Event อื่นๆ

**Comment by acryforever** [comment]
กำลังแก้ไข ในส่วนกรอกที่เป็นบัคเพิ่มจำนวนสั่งซื้อ

**Comment by Patthamaporn** [comment]
สามารถกรอกส่วนลดโดยไม่ลงปุ่มเพิ่มสินค้าได้
