### ISSUE TITLE
pricecondition/ pricecondition_detail

### ISSUE THREAD

**Issue by logisprosolution** [logisprosolution/WMS#15]
-PriceconditionList
-PriceconditionInfo
--[table Pricecondition Detail]
-----PriceconditionDetailInfo

db
DOC_PriceCondition
DOC_PriceCondition_Detail

**Comment by logisprosolution** [comment]
**change priceCondition to payCondition**
เงื่อนไขการชำระเงิน

**Comment by logisprosolution** [comment]
![apcondition](https://user-images.githubusercontent.com/30793831/40291364-d0ab757e-5cee-11e8-89e0-4e019c7a4c69.png)
![apcondition2](https://user-images.githubusercontent.com/30793831/40291365-d322bdbc-5cee-11e8-87be-78a4c3d557bd.png)
![apcondition3](https://user-images.githubusercontent.com/30793831/40291368-d5baacc4-5cee-11e8-83fa-aff43cc07ced.png)

**Comment by Patthamaporn** [comment]
wait for test
