### ISSUE TITLE
รายการใบสั่งซื้อ_เมื่อกดปุ่ม พิมพ์ หลังรายการ ระบบแสดง Error Message "โหลดรายการไม่สำเร็จ"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#150]
Summary   Name | รายการใบสั่งซื้อ_เมื่อกดปุ่ม   พิมพ์ หลังรายการ ระบบแสดง Error Message "โหลดรายการไม่สำเร็จ"
-- | --
Defect No. |  150
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/PurchaseList.aspx?subDoc=18&menuID=2085
Step | 1. เลือกเมนู   งานประจำวัน
  | 2.   เลือกเมนูย่อย ใบสั่งซื้อสินค้า
  | 3. เลือก   สั่งซื้อทั่วไป
  | 4. แสดงหน้าจอ   รายการใบสั่งซื้อสินค้า
  | 5. กดปุ่ม พิมพ์   หลังรายการ
  |  
  |  
  |  
  |  
Actual   Result | เมื่อกดปุ่ม พิมพ์   ระบบแสดง Error Message "โหลดรายงานไม่สำเร็จ"
  |  
  |  
Expected   Result | ต้องสามารถ   โหลดรายงานได้ และปุ่ม "พิมพ์" ต้องเป็น "ดาวน์โหลด"   หรือป่าวคะ หรือเป็นปุ่มสำหรับ พิมพ์เอกสาร
  |  

![image](https://user-images.githubusercontent.com/45878758/54220670-796f7e80-4524-11e9-93b8-148e9b33ac7a.png)

**Comment by Mickrepick** [comment]
แก้ไข : ปุ่ม พิมพ์ สามารถดาวน์โหลดรายงานได้

**Comment by Vermouthz** [comment]
Version ปัจจุบันยังไม่เปิดให้ใช้งนาน
