### ISSUE TITLE
นำเข้าสินค้า_เมื่อเลื่อนเมาส์ไปชี้ที่_Field_ไม่แสดงข้อความ_ความยาวไม่เกิน 24 ตัวอักษร

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#151]
Summary   Name | นำเข้าสินค้า_เมื่อเลื่อนเมาส์ไปชี้ที่_Field_ไม่แสดงข้อความ_ความยาวไม่เกิน   24 ตัวอักษร
-- | --
Defect No. |  151
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?dataId=11261&subDoc=3
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย นำเข้าสินค้า
  | 3. เลือก   นำเข้าสินค้าจากใบสั่งซื้อ
  | 4. แสดงหน้าจอ   รายการนำเข้าสินค้า
  | 5. กดปุ่ม แก้ไข   หลังรายการ
  | 6. กด ค้นหา
  | 7.   เมื่อเลื่อนเมาส์ไปชี้ที่ Field แสดงข้อความ “ความยาวไม่เกิน 24 ตัวอักษร
  |  
Actual   Result | เมื่อเลื่อนเมาส์ไปชี้ที่Fieldไม่แสดงข้อความ_ความยาวไม่เกิน   24 ตัวอักษร
  |  
  |  
Expected   Result | เมื่อเลื่อนเมาส์ไปชี้ที่_Field_แสดงข้อความ_ความยาวไม่เกิน   24 ตัวอักษร
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/54220871-e8e56e00-4524-11e9-8559-908a7c8257c8.png)
![image](https://user-images.githubusercontent.com/45878758/54220877-ec78f500-4524-11e9-96bb-ab596a275e28.png)
![image](https://user-images.githubusercontent.com/45878758/54220883-f1d63f80-4524-11e9-9b29-69cf14b9d660.png)

**Comment by Mickrepick** [comment]
แก้ไข : เมื่อเลื่อนเมาส์ไปชี้ที่ Field จะแสดงข้อความ "ความยาวไม่เกิน 24 ตัวอักษร"

**Comment by Vermouthz** [comment]
![image](https://user-images.githubusercontent.com/45878758/55574303-480a5d00-5736-11e9-877c-0205900a143f.png)

http://nps001.homeip.net:8085/InboundInfo.aspx?dataId=11829&subDoc=3

**Comment by Mickrepick** [comment]
แก้ไข : เมื่อเลื่อนเมาส์ไปชี้ที่ Field จะแสดงข้อความ "ความยาวไม่เกิน 24 ตัวอักษร"
