### ISSUE TITLE
ใบสั่งซื้อ_เมื่อกดปุ่ม ดู หลังรายการ ระบบไม่มี field ค้นหา เพื่อค้นหารายการสินค้นที่ต้องการ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#153]
Summary   Name | ใบสั่งซื้อ_เมื่อกดปุ่ม   ดู หลังรายการ ระบบไม่มี field ค้นหา เพื่อค้นหารายการสินค้นที่ต้องการ
-- | --
Defect No. |  153
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/PurchaseInfo.aspx?dataId=11267&view=1
Step | 1. เลือกเมนู   งานประจำวัน
  | 2.   เลือกเมนูย่อย ใบสั่งซื้อสินค้า
  | 3. เลือก   สั่งซื้อทั่วไป
  | 4. แสดงหน้าจอ   รายการใบสั่งซื้อสินค้า
  | 5. กด เพิ่มใบสั่งซื้อ
  | 6. กรอกข้อมูลใน Field   ใบสั่งซื้อทั้งหมด
  | 7. กดปุ่ม บันทึก
  | 8. แสดงหน้าจอ   รายการใบสั่งซื้อ
  | 9. กดปุ่ม ดู   หลังรายการ
  |  
  |  
  |  
Actual   Result | เมื่อกดปุ่ม ดู   หลังรายการ ระบบไม่มี field ค้นหา เพื่อค้นหารายการสินค้นที่ต้องการ
  |  
  |  
Expected   Result | เมื่อกดปุ่ม ดู   หลังรายการ ต้องมี field ค้นหา (รหัส/ชื่อ , หน่วย , จำนวน)   สำหรับค้นหารายการสินค้าที่ต้องการ
  |  

![image](https://user-images.githubusercontent.com/45878758/54223993-3b298d80-452b-11e9-958e-93ba7852af52.png)
![image](https://user-images.githubusercontent.com/45878758/54223997-3f55ab00-452b-11e9-8d02-cdef0e140433.png)

**Comment by acryforever** [comment]
Close funtion "role.Menu.Search" ขอปิด งาน
