### ISSUE TITLE
รายการใบสั่งซื้อสินค้า__ค้นหาใน   Field วันที่ ระบบแสดง วันที่ออกใบสั่งซื้อ    ทุกรายการ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#154]
Summary   Name | รายการใบสั่งซื้อสินค้า__ค้นหาใน   Field วันที่ ระบบแสดง วันที่ออกใบสั่งซื้อ    ทุกรายการ
-- | --
Defect No. |  154
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/PurchaseList.aspx?subDoc=18&menuID=2085
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย ตรวจสอบสินค้นค้าเข้า
  | 4. เลือก   ตรวจสอบสินค้าเข้า
  | 5.   แสดงหน้าจอ รายการตรวจสินค้าเข้า
  |  
Actual   Result | ค้นหาใน Field วันที่   ระบบแสดง วันที่ออกใบสั่งซื้อ  ทุกรายการ
  |  
Expected   Result | วันที่ออกใบสั่งซื้อ  ต้องแสดงตั้งแต่วันที่ ที่ค้นหาเป็นต้นไป

![image](https://user-images.githubusercontent.com/45878758/54273264-23e4b180-45b8-11e9-81a7-fa5bc61ae655.png)
![image](https://user-images.githubusercontent.com/45878758/54273232-1cbda380-45b8-11e9-9783-0bc9f4050e9f.png)
![image](https://user-images.githubusercontent.com/45878758/54273283-2cd58300-45b8-11e9-8165-5ff9a519db63.png)

**Comment by Mickrepick** [comment]
Test แล้วใช้งานได้
