### ISSUE TITLE
รายการใบสั่งซื้อสินค้า__ค้นหาใน   Field ถึง ตั้งเป็นวันที่ปัจจุบัน ระบบแสดง วันที่ออกใบสั่งซื้อ  ทุกรายการ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#155]
Summary   Name | รายการใบสั่งซื้อสินค้า__ค้นหาใน   Field ถึง ตั้งเป็นวันที่ปัจจุบัน ระบบแสดง วันที่ออกใบสั่งซื้อ  ทุกรายการ
-- | --
Defect No. |  155
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/PurchaseList.aspx?subDoc=18&menuID=2085
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย ตรวจสอบสินค้นค้าเข้า
  | 4. เลือก   ตรวจสอบสินค้าเข้า
  | 5.   แสดงหน้าจอ รายการตรวจสินค้าเข้า
  |  
Actual   Result | ค้นหาใน Field ถึง   ตั้งเป็นวันที่ปัจจุบัน ระบบแสดง วันที่ออกใบสั่งซื้อ  ทุกรายการ
  |  
Expected   Result | วันที่ออกใบสั่งซื้อ  ต้องแสดงวันที่ น้อยกว่าวันที่ทำการค้นหา

![image](https://user-images.githubusercontent.com/45878758/54273511-9f466300-45b8-11e9-9c1a-d69c3f586f63.png)
![image](https://user-images.githubusercontent.com/45878758/54273524-a8373480-45b8-11e9-82b5-0960477abe69.png)
![image](https://user-images.githubusercontent.com/45878758/54273540-b2f1c980-45b8-11e9-9297-0ce18e48991a.png)

**Comment by Mickrepick** [comment]
Test แล้วใช้งานได้
