### ISSUE TITLE
รายการใบสั่งซื้อสินค้า__ไม่มี   Column ยอด

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#156]
Summary   Name | รายการใบสั่งซื้อสินค้า__ไม่มี   Column ยอด
-- | --
Defect No. |  156
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/PurchaseList.aspx?subDoc=18&menuID=2085
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย ตรวจสอบสินค้นค้าเข้า
  | 4. เลือก   ตรวจสอบสินค้าเข้า
  | 5.   แสดงหน้าจอ รายการตรวจสินค้าเข้า
  |  
Actual   Result | ไม่มี Column ยอด
  |  
Expected   Result |  ต้องมี Column ยอด

![image](https://user-images.githubusercontent.com/45878758/54273738-18de5100-45b9-11e9-8567-c4d96330a182.png)
![image](https://user-images.githubusercontent.com/45878758/54273756-1f6cc880-45b9-11e9-8193-6b26f3609509.png)
![image](https://user-images.githubusercontent.com/45878758/54273772-23004f80-45b9-11e9-96eb-d7e401f78397.png)
![image](https://user-images.githubusercontent.com/45878758/54273780-272c6d00-45b9-11e9-894f-4b19c23ab597.png)

**Comment by Patthamaporn** [comment]
แก้ไข หน้ารายการสั่งซื้อเพิ่ม column ยอด
หน้า checkerin ไม่มีปุ่มนำเข้าจาก
