### ISSUE TITLE
นำเข้าสินค้า_เมื่อกดปุ่มดู_หลังรายการ_ระบบไม่มี_field_ค้นหา_เพื่อค้นหารายการสินค้นที่ต้องการ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#158]
Summary   Name | นำเข้าสินค้า_เมื่อกดปุ่มดู_หลังรายการ_ระบบไม่มี_field_ค้นหา_เพื่อค้นหารายการสินค้นที่ต้องการ
-- | --
Defect No. |  158
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?dataId=11275&view=1
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย นำเข้าสินค้า
  | 3. เลือก   นำเข้าสินค้าจากใบสั่งซื้อ
  | 4. แสดงหน้าจอ   รายการนำเข้าสินค้า
  | 5. กดปุ่ม ดู   หลังรายการ
  |  
  |  
  |  
Actual   Result | ไม่มี Field   ค้นหา(รหัส/ชื่อ,หน่วย,จำนวน) รายการสินค้า
  |  
  |  
Expected   Result | นำเข้าสินค้า_เมื่อกดปุ่มดู_หลังรายการ_ระบบต้องมี_field_ค้นหา_เพื่อค้นหารายการสินค้นที่ต้องการ
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/54286408-61f0ce00-45d6-11e9-914e-1d46a5bb1899.png)
![image](https://user-images.githubusercontent.com/45878758/54286410-65845500-45d6-11e9-8a6b-48a17f20bc32.png)

**Comment by acryforever** [comment]
Close funtion "role.Menu.Search" ขอปิด งาน
