### ISSUE TITLE
ใบสั่งซื้อ_เมื่อกดปุ่ม แก้ไข หลังรายการ กรณีไม่กรอก field บังคับ เปลี่ยนข้อความเตือน "กรุณากรอกข้อมูล" เป็น "กรุณากรอกข้อมูล (ชื่อfield)

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#159]
Summary   Name | ใบสั่งซื้อ_เมื่อกดปุ่ม   แก้ไข หลังรายการ กรณีไม่กรอก field บังคับ เปลี่ยนข้อความเตือน   "กรุณากรอกข้อมูล" เป็น "กรุณากรอกข้อมูล (ชื่อfield)
-- | --
Defect No. |  159
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/PurchaseInfo.aspx?dataId=11273&subDoc=18
Step | 1. เลือกเมนู   งานประจำวัน
  | 2.   เลือกเมนูย่อย ใบสั่งซื้อสินค้า
  | 3. เลือก   สั่งซื้อทั่วไป
  | 4. แสดงหน้าจอ   รายการใบสั่งซื้อสินค้า
  | 5. กดปุ่ม แก้ไข   หลังรายการ
  | 6. ลบข้อมูลใน field   บังคับออก
  | 7. กดปุ่ม บันทึก
  | 8. กด ตกลง
  |  
  |  
Actual   Result | ระบบแสดง   ข้อความแจ้งเตือนด้านล่าง ดังนี้
  | ไม่สามารถบันทึกข้อมูลได้ :
  | กรุณากรอกข้อมูล
  | กรุณากรอกข้อมูล
  | จำนวนต้องมีค่า   1-10,000
  | จำนวนต้องมีค่า   1-10000
  | จำนวนต้องมีค่า   1-10,000
  | จำนวนต้องมีค่า   1-10000
  |  
Expected   Result | ต้องแสดง   ข้อความแจ้งเตือนด้านล่าง ดังนี้
  | ไม่สามารถบันทึกข้อมูลได้ :
  | กรุณากรอกข้อมูล   เลขที่เอกสาร
  | กรุณากรอกข้อมูล   วันที่เอกสาร
  | กรุณากรอกข้อมูล   จำนวนสั่งซื้อ ตั้งแต่ 1-10,000
  | กรุณากรอกข้อมูล   ราคาสั่ง ตั้งแต่ 1-10,000
  | กรุณากรอกข้อมูล   จำนวนสั่งซื้อ ตั้งแต่ 1-10,000
  | กรุณากรอกข้อมูล   ราคาสั่ง ตั้งแต่ 1-10,000
  |  

![image](https://user-images.githubusercontent.com/45878758/54289052-1260d100-45db-11e9-83d4-097b3f80dccb.png)
![image](https://user-images.githubusercontent.com/45878758/54289059-17258500-45db-11e9-84ee-7623cbe64313.png)

**Comment by Mickrepick** [comment]
แก้ไข : ข้อความแจ้งเตือนด้านล่าง ดังนี้
ไม่สามารถบันทึกข้อมูลได้ :
- กรุณากรอกข้อมูล เลขที่เอกสาร
- กรุณากรอกข้อมูล วันที่เอกสาร
- กรุณากรอกจำนวน จำนวนสั่งซื้อ ตั้งแต่ 1-10,000
- กรุณากรอกจำนวน ราคาสั่ง ตั้งแต่ 1-10,000
