### ISSUE TITLE
geo/province/district/sub-d/contry

### ISSUE THREAD

**Issue by logisprosolution** [logisprosolution/WMS#16]
do master setting webpage

GeographyList
GeographyInfo
----------------------
ProvinceList
ProvinceInfo
----------------------
DistrictList
DistrictInfo
----------------------
SubDistrictList
SubDistrictInfo
----------------------
CountryList
CountryInfo
----------------------

**Comment by Patthamaporn** [comment]
**NationalityList
NationalityInfo**

**ReligionList
ReligionInfo**

**Comment by Patthamaporn** [comment]
wait for test
