### ISSUE TITLE
นำเข้าสินค้า_เมื่อกดปุ่มอนุมัติ_หลังรายการต้องไม่สามารถแก้ไขข้อมูลใน_Field ได้ เป็น field ปิด

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#160]
Summary   Name | นำเข้าสินค้า_เมื่อกดปุ่มอนุมัติ_หลังรายการต้องไม่สามารถแก้ไขข้อมูลใน_Field   ได้ เป็น field ปิด
-- | --
Defect No. |  160
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?dataId=11275&subDoc=3&approve=1
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย นำเข้าสินค้า
  | 3. เลือก   นำเข้าสินค้าจากใบสั่งซื้อ
  | 4. แสดงหน้าจอ   รายการนำเข้าสินค้า
  | 5. กดปุ่ม อนุมัติ   หลังรายการ
  |  
  |  
  |  
Actual   Result | นำเข้าสินค้า_เมื่อกดปุ่มอนุมัติ_หลังรายการสามารถแก้ไขข้อมูลใน   Field ได้
  |  
  |  
Expected   Result | นำเข้าสินค้า_เมื่อกดปุ่มอนุมัติ_หลังรายการต้องไม่สามารถแก้ไขข้อมูลใน   Field ได้ เป็น field ปิด
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/54290274-44733280-45dd-11e9-979d-845c7511d65b.png)
![image](https://user-images.githubusercontent.com/45878758/54290281-476e2300-45dd-11e9-850c-cd4b7371c682.png)
![image](https://user-images.githubusercontent.com/45878758/54290291-4b01aa00-45dd-11e9-893e-d151c7cb980a.png)

**Comment by Patthamaporn** [comment]
ดัก juqery แบบ block code โดยเช็ค จาก approve และเรียกใช้ function ที่ btnsearch ให้อ่าน js ใหม่ เนื่องจากมีการ update panel
