### ISSUE TITLE
ใบสั่งซื้อ_เมื่อกดปุ่ม อนุมัติ หลังรายการ ต้องไม่สามารถแกไขข้อมูลใน Field ได้ เป็น field ปิด

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#162]
Summary   Name | ใบสั่งซื้อ_เมื่อกดปุ่ม   อนุมัติ หลังรายการ ต้องไม่สามารถแกไขข้อมูลใน Field ได้ เป็น field ปิด
-- | --
Defect No. |  162
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/PurchaseInfo.aspx?dataId=11267&subDoc=18&approve=1
Step | 1. เลือกเมนู   งานประจำวัน
  | 2.   เลือกเมนูย่อย ใบสั่งซื้อสินค้า
  | 3. เลือก   สั่งซื้อทั่วไป
  | 4. แสดงหน้าจอ   รายการใบสั่งซื้อสินค้า
  | 5. กด เพิ่มใบสั่งซื้อ
  | 6. กรอกข้อมูลใน Field   ใบสั่งซื้อทั้งหมด
  | 7. กดปุ่ม บันทึก
  | 8. แสดงหน้าจอ   รายการใบสั่งซื้อ
  | 9. กดปุ่ม อนุมัติ   หลังรายการ
  |  
  |  
  |  
Actual   Result | เมื่อกดปุ่ม อนุมัติ   หลังรายการ สามารถใส่ข้อมูลใน field ได้
  |  
  |  
Expected   Result | เมื่อกดปุ่ม อนุมัติ   หลังรายการ ต้องไม่สามารถแกไขข้อมูลใน Field ได้ เป็น field ปิด
  |  

![image](https://user-images.githubusercontent.com/45878758/54296146-ef3c1e80-45e6-11e9-81c2-98d82b8adafc.png)
![image](https://user-images.githubusercontent.com/45878758/54296153-f2370f00-45e6-11e9-9328-9936ddb385d2.png)

**Comment by Patthamaporn** [comment]
ดัก juqery แบบ block code โดยเช็ค จาก approve และเรียกใช้ function ที่ btnsearch ให้อ่าน js ใหม่ เนื่องจากมีการ update panel
