### ISSUE TITLE
นำเข้าสินค้า_เพิ่มนำเข้าจาก   กดปุ่ม ค้นหาสินค้า เลือกสินค้า ไม่สามารถเพิ่มสินค้าได้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#164]
Summary   Name | นำเข้าสินค้า_เพิ่มนำเข้าจาก   กดปุ่ม ค้นหาสินค้า เลือกสินค้า ไม่สามารถเพิ่มสินค้าได้
-- | --
Defect No. |  164
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?subDoc=3
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย นำเข้าสินค้า
  | 4. เลือก   นำเข้าสินค้าจากใบสั่งซื้อ
  | 5.   แสดงหน้าจอ รายการนำเข้าสินค้า
  | 6. กดปุ่ม   เพิ่มใบนำเข้า
  | 7. กดปุ่ม   นำเข้าจาก...
  | 8. กดปุ่ม   ค้นหาสินค้า
  | 9. เลือก   สินค้า
  |  
Actual   Result | เพิ่มนำเข้าจาก กดปุ่ม   ค้นหาสินค้า เลือกสินค้า ไม่สามารถเพิ่มสินค้าได้
  |  
Expected   Result | เพิ่มนำเข้าจาก กดปุ่ม   ค้นหาสินค้า เลือกสินค้า ต้องสามารถเพิ่มสินค้าได้
  |  
Tester   Name | Phatchanok.Sun

![image](https://user-images.githubusercontent.com/45878758/54307455-54e7d500-45fe-11e9-8295-1bf6a4b4e2e2.png)

**Comment by acryforever** [comment]
เปลี่ยนตัวแปร์ ในการดีแคร์ CODE ที่ ConvertHelper.ToInt(ConvertHelper.InitialValueDB(dr, "transDTID"))
เป็น transDTID เพื่อเรียกใช้ข้อมูล
