### ISSUE TITLE
นำเข้าสินค้า_ไม่กรอกข้อมูลใน   Field mandatory ระบบแสดงข้อความด้านล่าง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#165]
Summary   Name | นำเข้าสินค้า_ไม่กรอกข้อมูลใน   Field mandatory ระบบแสดงข้อความด้านล่าง
-- | --
Defect No. |  165
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?subDoc=3
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย นำเข้าสินค้า
  | 4. เลือก   นำเข้าสินค้าจากใบสั่งซื้อ
  | 5.   แสดงหน้าจอ รายการนำเข้าสินค้า
  | 6. กดปุ่ม   เพิ่มใบนำเข้า
  | 7. กดปุ่ม   นำเข้าจาก...
  | 8.   ระบุข้อมูลใน Field
  | เลขทีใบกำกับภาษี
  | วันที่ใบกำกับภาษี
  | เลขที่ใบส่งของ
  | วันที่ใบส่งของ
  | ส่งโดย
  | 9.   เลือกตำแหน่งเก็บ
  | 10. กดปุ่ม   บันทึก
  | 11. กดปุ่ม   ตกลง
  |  
Actual   Result | ไม่กรอกข้อมูลใน Field   mandatory ระบบแสดงข้อความด้านล่าง ไม่สามารถบันทึกข้อมูลได้
  | - กรุณากรอกข้อมูล
  | - กรุณากรอกข้อมูล
  | - กรุณากรอกข้อมูล
  | - กรุณากรอกข้อมูล
  |  
Expected   Result | ระบบแสดงข้อความด้านล่าง   ต้องแสดงว่า ไม่สามารถบันทึกข้อมูลได้
  | - กรุณากรอกข้อมูล เลขที่เอกสาร
  | - กรุณากรอกข้อมูล วันที่เอกสาร
  | - กรุณากรอกข้อมูล วันที่ผลิต
  | - กรุณากรอกข้อมูล วันที่หมดอายุ
Tester   Name | Phatchanok.Sun

![image](https://user-images.githubusercontent.com/45878758/54307766-06870600-45ff-11e9-8263-f69cd3021a59.png)

**Comment by Mickrepick** [comment]
แก้ไข : ErrorMessage ของ 
txtTrans_No เป็น -กรุณากรอกข้อมูล เลขที่เอกสาร
txtTrans_Date เป็น - กรุณากรอกข้อมูล วันที่เอกสาร
txtMfd_date เป็น - กรุณากรอกข้อมูล วันที่ผลิต
txtExp_date เป็น - กรุณากรอกข้อมูล วันที่หมดอายุ
