### ISSUE TITLE
นำเข้าสินค้า_ไม่กดปุ่ม   นำเข้าจาก.... กดปุ่ม ค้นหาสินค้า กดเลือกรายการ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#166]
Summary   Name | นำเข้าสินค้า_ไม่กดปุ่ม   นำเข้าจาก.... กดปุ่ม ค้นหาสินค้า กดเลือกรายการ
-- | --
Defect No. |  166
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?subDoc=3
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย นำเข้าสินค้า
  | 4. เลือก   นำเข้าสินค้าจากใบสั่งซื้อ
  | 5.   แสดงหน้าจอ รายการนำเข้าสินค้า
  | 6. กดปุ่ม   เพิ่มใบนำเข้า
  | 7.   ไม่กดปุ่ม นำเข้าจาก...
  | 8. กดปุ่ม   ค้นหาสินค้า
  | 9. เลือก   สินค้า 1 รายการ
  |  
Actual   Result | ไม่กดปุ่ม   นำเข้าจาก.... กดปุ่ม ค้นหาสินค้า กดเลือกรายการ ขึ้น ข้อความแจ้งเตือน
  |  
Expected   Result | ไม่กดปุ่ม   นำเข้าจาก.... กดปุ่ม ค้นหาสินค้า กดเลือกรายการ ระบบต้องแสดงรายการสินค้าใน   Column แสดงผล
Tester   Name | Phatchanok.Sun

![image](https://user-images.githubusercontent.com/45878758/54307942-7e553080-45ff-11e9-9e95-ba02484c0289.png)

**Comment by acryforever** [comment]
งานมีการแก้ไขแล้ว ได้ทดสอบโปรแกรมไม่มีการปิดงาน จึงขอปิดงานออก

**Comment by acryforever** [comment]
ปิดงานทดสอบแล้ว
