### ISSUE TITLE
นำเข้าสินค้า_ไม่กดปุ่ม   นำเข้าจาก.... ใส่ จำนวน*รหัสสินค้า กดปุ่ม เพิ่มรายการเบิก+ ขึ้นข้อความ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#167]
Summary   Name | นำเข้าสินค้า_ไม่กดปุ่ม   นำเข้าจาก.... ใส่ จำนวน*รหัสสินค้า กดปุ่ม เพิ่มรายการเบิก+ ขึ้นข้อความ
-- | --
Defect No. |  167
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?subDoc=3
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย นำเข้าสินค้า
  | 4. เลือก   นำเข้าสินค้าจากใบสั่งซื้อ
  | 5.   แสดงหน้าจอ รายการนำเข้าสินค้า
  | 6. กดปุ่ม   เพิ่มใบนำเข้า
  | 7.   ไม่กดปุ่ม นำเข้าจาก...
  | 8.   กรอกข้อมูลใน Field
  | จำนวน*รหัสสินค้า
  | 9. กดปุ่ม   เพิ่มรายการเบิก+
  |  
Actual   Result | 1. ค้นหาจากรหัสสินค้า   ขึ้นข้อความ ไม่พบสินค้า
  | 2.   ค้นหาจากบาร์โค๊ดขายสินค้า ขึ้นข้อความ Column    GoodsName  does not belong to   table productSearch.
  |  
Expected   Result | 1. เมื่อค้นหาจาก รหัสสินค้่า ต้องพบ และเพิ่มสินค้าได้
  | 2.   เมื่อค้นหาจาก บาร์โค๊ดขายสินค้า ต้องพบ และเพิ่มสินค้าได้
  |  
Tester   Name | Phatchanok.Sun

![image](https://user-images.githubusercontent.com/45878758/54308128-e9066c00-45ff-11e9-8601-b495b62979bf.png)

**Comment by Patthamaporn** [comment]
แก้ไข ให้ปุ่มค้นหาสินค้า และ เพิ่มรายการ สารมาเลือกสินค้าที่ใช้งานได้
