### ISSUE TITLE
นำเข้าสินค้า_เพิ่มนำเข้าจาก   กดปุ่ม ค้นหาสินค้า เลือกสินค้าที่ จำนวนคงเหลือ เป็น "0" ไม่สามารถเลือกสินค้าได้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#168]
Summary   Name | นำเข้าสินค้า_เพิ่มนำเข้าจาก   กดปุ่ม ค้นหาสินค้า เลือกสินค้าที่ไม่มีจำนวนคงเหลือ ไม่สามารถเพิ่มสินค้าได้
-- | --
Defect No. |  168
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?subDoc=3
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย นำเข้าสินค้า
  | 4. เลือก   นำเข้าสินค้าจากใบสั่งซื้อ
  | 5.   แสดงหน้าจอ รายการนำเข้าสินค้า
  | 6. กดปุ่ม   เพิ่มใบนำเข้า
  | 7. กดปุ่ม   นำเข้าจาก...
  | 8. กดปุ่ม   ค้นหาสินค้า
  | 9. เลือก   สินค้า
  |  
Actual   Result | เพิ่มนำเข้าจาก กดปุ่ม   ค้นหาสินค้า เลือกสินค้าที่ไม่มีจำนวนคงเหลือ ไม่สามารถเพิ่มสินค้าได้
  |  
Expected   Result | เพิ่มนำเข้าจาก กดปุ่ม   ค้นหาสินค้า เลือกสินค้าที่ไม่มีจำนวนคงเหลือ ต้องสามารถเพิ่มสินค้าได้
  |  
Tester   Name | Phatchanok.Sun

![image](https://user-images.githubusercontent.com/45878758/54308250-2ff46180-4600-11e9-859c-0344662ea8d0.png)

**Comment by Mickrepick** [comment]
แก้ไข : เพิ่มนำเข้าจาก กดปุ่ม ค้นหาสินค้า เลือกสินค้าที่ไม่มีจำนวนคงเหลือ สามารถเพิ่มสินค้าได้
