### ISSUE TITLE
นำเข้าสินค้า_เพิ่มนำเข้าจาก...   กรอกข้อมูลใน Field จำนวน*รหัสสินค้า ไม่สามารถเพิ่มสินค้าได้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#169]
Summary   Name | นำเข้าสินค้า_เพิ่มนำเข้าจาก...   กรอกข้อมูลใน Field จำนวน*รหัสสินค้า ไม่สามารถเพิ่มสินค้าได้
-- | --
Defect No. |  169
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?subDoc=3
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย นำเข้าสินค้า
  | 4. เลือก   นำเข้าสินค้าจากใบสั่งซื้อ
  | 5.   แสดงหน้าจอ รายการนำเข้าสินค้า
  | 6. กดปุ่ม   เพิ่มใบนำเข้า
  | 7. กดปุ่ม   นำเข้าจาก...
  | 8.   กรอกข้อมูลใน Field
  | จำนวน*รหัสสินค้า
  | 9. กดปุ่ม   เพิ่มรายการเบิก+
  |  
Actual   Result | 1. เพิ่มนำเข้าจาก...   กรอกข้อมูลใน Field จำนวน*รหัสสินค้า ใส่รหัสสินค้า ไม่สามารถเพิ่มสินค้าได้
  | 2. เพิ่มนำเข้าจาก...   กรอกข้อมูลใน Field จำนวน*รหัสสินค้า ใส่บาร์โค๊ดขายสินค้า   ไม่สามารถเพิ่มสินค้าได้
  |  
Expected   Result | 1. เพิ่มนำเข้าจาก...   กรอกข้อมูลใน Field จำนวน*รหัสสินค้า ใส่รหัสสินค้า ต้องสามารถเพิ่มสินค้าได้
  | 2. เพิ่มนำเข้าจาก...   กรอกข้อมูลใน Field จำนวน*รหัสสินค้า ใส่บาร์โค๊ดขายสินค้า   ต้องสามารถเพิ่มสินค้าได้
Tester   Name | Phatchanok.Sun

![image](https://user-images.githubusercontent.com/45878758/54308395-86fa3680-4600-11e9-9c0e-8058188ffa14.png)

**Comment by acryforever** [comment]
เปลี่ยนตัวแปร์ ในการดีแคร์ CODE ที่ ConvertHelper.ToInt(ConvertHelper.InitialValueDB(dr, "transDTID"))
เป็น transDTID เพื่อเรียกใช้ข้อมูล
