### ISSUE TITLE
นำเข้าสินค้า_กรอกข้อมูลใน   Field mandatory เลขทีเอกสาร,วันที่เอกสาร,วันที่ผลิต,วันที่หมดอายุ   ไม่สารถบันทึกได้และขึ้น Error Massger_เมื่อกดปุ่ม รับสินค้าเข้า

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#170]
Summary   Name | นำเข้าสินค้า_กรอกข้อมูลใน   Field mandatory เลขทีเอกสาร,วันที่เอกสาร,วันที่ผลิต,วันที่หมดอายุ   ไม่สารถบันทึกได้และขึ้น Error Massger_เมื่อกดปุ่ม รับสืนค้าเข้า
-- | --
Defect No. |  170
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?subDoc=3&ref=11283
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย นำเข้าสินค้า
  | 4. เลือก   นำเข้าสินค้าจากใบสั่งซื้อ
  | 5.   แสดงหน้าจอ รายการนำเข้าสินค้า
  | 6. กดปุ่ม   รับสินค้าเข้า หลังรายการ
  | 7. กดปุ่ม   นำเข้าจาก...
  | 8.   ระบุข้อมูลใน Field
  | เลขที่เอกสาร
  | วันที่เอกสาร
  | วันที่ผลิต
  | วันที่หมดอายุ
  | 9. กดปุ่ม   บันทึก
  | 10. กดปุ่ม   ตกลง
  |  
Actual   Result | กรอกข้อมูลใน Field   เลขทีเอกสาร,วันที่เอกสาร,วันที่ผลิต,วันที่หมดอายุ ไม่สารถบันทึกได้
  |  
Expected   Result | กรอกข้อมูลใน Field   เลขทีเอกสาร,วันที่เอกสาร,วันที่ผลิต,วันที่หมดอายุ ต้องสามารถบันทึกได้
  |  
Tester   Name | Phatchanok.Sun

![image](https://user-images.githubusercontent.com/45878758/54308677-10aa0400-4601-11e9-8d54-1b1a896fd7bd.png)

**Comment by Patthamaporn** [comment]
ขออนุญาติถามก่อนค่ะว่าได้มีการตั้งค่า วันที่ของ windows ให้เป็นปีพ.ศ.หรือยังคะ

**Comment by Vermouthz** [comment]
Field วันที่ใบกำกับภาษี,วันที่ใบส่งของ เป็น Field Mandatory หรือเปล่าค่ะ เพราะถ้าไม่กรอก Field ใด Field หนึ่ง และกดบันทึก จะขึ้น Error Message "Error ToDateTime"

![image](https://user-images.githubusercontent.com/45878758/55319429-090eaa00-549f-11e9-9441-9632193d687b.png)
![image](https://user-images.githubusercontent.com/45878758/55319397-fac08e00-549e-11e9-98a3-0ea017396ef7.png)

**Comment by Vermouthz** [comment]
Field วันที่ใบกำกับภาษี,วันที่ใบส่งของ เป็น Field Mandatory หรือเปล่าค่ะ เพราะถ้าไม่กรอก Field ใด Field หนึ่ง และกดบันทึก จะขึ้น Error Message "Error ToDateTime"

![image](https://user-images.githubusercontent.com/45878758/55319429-090eaa00-549f-11e9-9441-9632193d687b.png)
![image](https://user-images.githubusercontent.com/45878758/55319397-fac08e00-549e-11e9-98a3-0ea017396ef7.png)
.

**Comment by Patthamaporn** [comment]
แก้ไข สามารถบันทึกข้อมูลได้หากไม่ได้กรอกวันที่ใบกำกับภาษี และ วันที่ใบส่งของ
