### ISSUE TITLE
นำเข้าสินค้า_ไม่กรอกข้อมูลใน   Field mandatory ระบบแสดงข้อความด้านล่าง_เมื่อกดปุ่ม รับสินค้าเข้า

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#171]
Summary   Name | นำเข้าสินค้า_ไม่กรอกข้อมูลใน   Field mandatory ระบบแสดงข้อความด้านล่าง_เมื่อกดปุ่ม รับสินค้าเข้า
-- | --
Defect No. |  171
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?subDoc=3&ref=11283
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย นำเข้าสินค้า
  | 4. เลือก   นำเข้าสินค้าจากใบสั่งซื้อ
  | 5.   แสดงหน้าจอ รายการนำเข้าสินค้า
  | 6. กดปุ่ม   รับสินค้าเข้า หลังรายการ
  | 7.   ระบุข้อมูลใน Field
  | เลขทีใบกำกับภาษี
  | วันที่ใบกำกับภาษี
  | เลขที่ใบส่งของ
  | วันที่ใบส่งของ
  | ส่งโดย
  | 8.   เลือกตำแหน่งเก็บ
  | 9. กดปุ่ม   บันทึก
  | 10. กดปุ่ม   ตกลง
  |  
Actual   Result | ไม่กรอกข้อมูลใน Field   mandatory ระบบแสดงข้อความด้านล่าง ไม่สามารถบันทึกข้อมูลได้
  | - กรุณากรอกข้อมูล
  | - กรุณากรอกข้อมูล
  | - กรุณากรอกข้อมูล
  | - กรุณากรอกข้อมูล
  |  
Expected   Result | ระบบแสดงข้อความด้านล่าง   ต้องแสดงว่า ไม่สามารถบันทึกข้อมูลได้
  | - กรุณากรอกข้อมูล เลขที่เอกสาร
  | - กรุณากรอกข้อมูล วันที่เอกสาร
  | - กรุณากรอกข้อมูล วันที่ผลิต
  | - กรุณากรอกข้อมูล วันที่หมดอายุ
Tester   Name | Phatchanok.Sun

![image](https://user-images.githubusercontent.com/45878758/54308808-5961bd00-4601-11e9-8bdb-acbc4754035b.png)

**Comment by Mickrepick** [comment]
แก้ไข : Field เลขที่เอกสาร, วันที่เอกสาร 
ErrorMessage จาก "กรุณากรอกข้อมูล" เป็น "กรุณากรอกข้อมูล เลขที่เอกสาร, กรุณากรอกข้อมูล วันที่เอกสาร"
ส่วน  Field วันที่ผลิต, วันหมดอายุ ไม่มีแล้วครับ
