### ISSUE TITLE
นำเข้าสินค้า_กดปุ่มค้นหา   เลือกสินค้า 1 รายการ ขึ้น Error Messenger_เมื่อกดปุ่ม รับสินค้าเข้า

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#172]
Summary   Name | นำเข้าสินค้า_กดปุ่มค้นหา   เลือกสินค้า 1 รายการ ขึ้น Error Messenger_เมื่อกดปุ่ม รับสินค้าเข้า
-- | --
Defect No. |  172
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?subDoc=3&ref=11283
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย นำเข้าสินค้า
  | 4. เลือก   นำเข้าสินค้าจากใบสั่งซื้อ
  | 5.   แสดงหน้าจอ รายการนำเข้าสินค้า
  | 6. กดปุ่ม   รับสินค้าเข้า หลังรายการ
  | 7. กดปุ่ม   ค้นหาสินค้า
  | 8. เลือก   สินค้า 1 รายการ
  |  
Actual   Result | กดปุ่มค้นหา   เลือกสินค้า 1 รายการ ขึ้น Error Messenger
  |  
Expected   Result | ต้องสามรถเพิ่มสินค้าได้
  |  
Tester   Name | Phatchanok.Sun

![image](https://user-images.githubusercontent.com/45878758/54308938-b6f60980-4601-11e9-9d13-c942c49594e6.png)

**Comment by Mickrepick** [comment]
Test แล้วใช้งานได้
