### ISSUE TITLE
นำเข้าสินค้า_   ใส่ จำนวน*รหัสสินค้า กดปุ่ม เพิ่มรายการเบิก+ ขึ้นข้อความ _เมื่อกดปุ่ม   รับสินค้าเข้า

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#173]
Summary   Name | นำเข้าสินค้า_   ใส่ จำนวน*รหัสสินค้า กดปุ่ม เพิ่มรายการเบิก+ ขึ้นข้อความ _เมื่อกดปุ่ม   รับสินค้าเข้า
-- | --
Defect No. |  173
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?subDoc=3&ref=11283
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย นำเข้าสินค้า
  | 4. เลือก   นำเข้าสินค้าจากใบสั่งซื้อ
  | 5.   แสดงหน้าจอ รายการนำเข้าสินค้า
  | 6. กดปุ่ม   รับสินค้าเข้า หลังรายการ
  | 7.   กรอกข้อมูลใน Field
  | จำนวน*รหัสสินค้า
  | 8. กดปุ่ม   เพิ่มรายการเบิก+
  |  
Actual   Result | 1. ค้นหาจากรหัสสินค้า   ขึ้นข้อความ ไม่พบสินค้า
  | 2.   ค้นหาจากบาร์โค๊ดขายสินค้า ขึ้นข้อความ Column    GoodsName  does not belong to   table productSearch.
  |  
Expected   Result | 1. ต้องพบสินค้า
  | 2.   ต้องพบสินค้า
Tester   Name | Phatchanok.Sun

![image](https://user-images.githubusercontent.com/45878758/54309074-00deef80-4602-11e9-8f8e-7f9f9d767b99.png)

**Comment by Mickrepick** [comment]
Test แล้วใช้งานได้
