### ISSUE TITLE
นำเข้าสินค้า_   กรอก วันที่ผลิต แต่วันที่หมดอายุไม่ขึ้นออโต้ _เมื่อกดปุ่ม รับสินค้าเข้า

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#174]
Summary   Name | นำเข้าสินค้า_   กรอก วันที่ผลิต แต่วันที่หมดอายุไม่ขึ้นออโต้ _เมื่อกดปุ่ม รับสินค้าเข้า
-- | --
Defect No. |  174
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?subDoc=3
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย นำเข้าสินค้า
  | 4. เลือก   นำเข้าสินค้าจากใบสั่งซื้อ
  | 5.   แสดงหน้าจอ รายการนำเข้าสินค้า
  | 6. กดปุ่ม   รับสินค้าเข้า หลังรายการ
  | 7. เลือก   ใบสั่งซื้อ
  | 8.   กรอกข้อมูลใน Field
  | วันที่ผลิต
  |  
Actual   Result | 1. กรอก วันที่ผลิต   แต่วันที่หมดอายุไม่ขึ้นออโต้
  |  
Expected   Result | 1. กรอก วันที่ผลิต   วันที่หมดอายุต้องขึ้นออโต้
  |  
Tester   Name | Phatchanok.Sun

![image](https://user-images.githubusercontent.com/45878758/54309281-6501b380-4602-11e9-98da-7372f571ddf0.png)

**Comment by Mickrepick** [comment]
หน้า InboundInfo ไม่มี Field วันที่ผลิต, วันที่หมดอายุ แล้วครับ ขอปิด Issues ครับ
