### ISSUE TITLE
นำเข้าสินค้า_กรอก   วันที่หมดอายุ ไม่กรอกวันที่ผลิต ข้อความใต้ Field กรุณากรอกข้อมูล   แสดงขึ้นมาแค่เพียงเสี้ยววิ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#176]
Summary   Name | นำเข้าสินค้า_กรอก   วันที่หมดอายุ ไม่กรอกวันที่ผลิต ข้อความใต้ Field กรุณากรอกข้อมูล   แสดงขึ้นมาแค่เพียงเสี้ยววิ
-- | --
Defect No. |  176
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?subDoc=3
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย นำเข้าสินค้า
  | 4. เลือก   นำเข้าสินค้าจากใบสั่งซื้อ
  | 5.   แสดงหน้าจอ รายการนำเข้าสินค้า
  | 6. กดปุ่ม   เพิ่มใบนำเข้า
  | 7. กดปุ่ม   นำเข้าจาก..
  | 8. เลือก   ใบสั่งซื้อ
  | 9.   กรอกข้อมูลใน Field
  | วันที่หมดอายุ
  |  
Actual   Result | กรอก วันที่หมดอายุ   ไม่กรอกวันที่ผลิต ข้อความใต้ Field กรุณากรอกข้อมูล แสดงขึ้นมาแค่เพียงเสี้ยววิ
  |  
Expected   Result | ข้อความ   กรุณากรอกข้อมูล ต้องแสดงจนกว่าจะทำการกรอกข้อมูล
  |  
Tester   Name | Phatchanok.Sun

![image](https://user-images.githubusercontent.com/45878758/54309596-0c7ee600-4603-11e9-8241-07ba09eff157.png)

Retest-Pass 05/05/2562-----------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/45878758/57197761-78435680-6f95-11e9-9a31-72769742f826.png)

**Comment by acryforever** [comment]
เนื่องจาก InboundInfo ไม่มีการใช้งาน วันที่ผลิต และ วันที่หมดอายุ 
แต่ได้มีการแก้ไข้ที่มีการเรียกข้อมูลการใช้งาน วันที่ผลิต และ วันที่หมดอายุ  
ในหน้า CheckerInInfo โดยการปิด AutoPostBack
