### ISSUE TITLE
ตรวจสินค้าเข้า_ไม่กรอกข้อมูลใน Field mandatory ระบบแสดงข้อความด้านล่าง_เมื่อกดปุ่ม รับสินค้าเข้า

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#179]
Summary   Name | ตรวจสินค้าเข้า_ไม่กรอกข้อมูลใน   Field mandatory ระบบแสดงข้อความด้านล่าง_เมื่อกดปุ่ม รับสินค้าเข้า
-- | --
Defect No. |  179
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/CheckerInInfo.aspx?dataId=11289&subDoc=21
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย ตรวจสอบสินค้าเข้า
  | 3. เลือก ตรวจสอบสินค้าเข้า
  | 4.   แสดงหน้าจอ รายการตรวจสินค้าเข้า
  | 5.   กดปุ่ม เพิ่มใบตรวจจสินค้า
  | 6.   กดปุ่ม นำเข้าจาก...
  | 7.   เลือก ใบสั่งซื้อ โดยสถานะเป็น "เรียบร้อย"
  | 8.   ระบุข้อมูลใน Field ทั้งหมด
  | 9.   กดปุ่ม บันทึก
  | 10.   กดปุ่ม ตกลง
  | 11.   กดปุ่ม แก้ไข หลังรายการ
  | 12.   แก้ไขข้อมูลใน Field ทั้งหมด
  | 13.   กดปุ่ม บันทึก
  |  
  |  
Actual Result | ไม่กรอกข้อมูลใน Field mandatory   ระบบแสดงข้อความด้านล่าง ดั้งนี้
  | ไม่สามารถบันทึกข้อมูลได้
  | - กรุณากรอกข้อมูล
  | - กรุณากรอกข้อมูล
  |  
Expected Result | ระบบแสดงข้อความด้านล่าง   ต้องแสดงว่า
  | ไม่สามารถบันทึกข้อมูลได้
  | กรุณากรอกข้อมูล   เลขที่เอกสาร
  | กรุณากรอกข้อมูล   วันที่เอกสาร
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/54374210-3c84c280-46b1-11e9-9811-8f6d8f83a70b.png)
![image](https://user-images.githubusercontent.com/45878758/54374220-40184980-46b1-11e9-921c-9b85bad4cbed.png)
![image](https://user-images.githubusercontent.com/45878758/54374227-43133a00-46b1-11e9-8462-94b1da8a6c68.png)
![image](https://user-images.githubusercontent.com/45878758/54374237-45759400-46b1-11e9-8310-dfa01421bd13.png)

**Comment by Mickrepick** [comment]
Field เลขที่เอกสาร เป็น Field ปิด ไม่สามารถแก้ไขได้
Field วันที่เอกสาร แก้ไข ErrorMessage จาก "กรุณากรอกข้อมูล" เป็น "กรุณากรอกข้อมูล วันที่เอกสาร"

**Comment by Vermouthz** [comment]
ขอคอนเฟิร์มว่า ในหน้าจอรายการตรวจสินค้า ไม่มีปุ่ม เพิ่มใบตรวจสินค้า โดย comment และ ปิด Defect ขอบคุณครับ

![image](https://user-images.githubusercontent.com/45878758/56461577-654e5500-63df-11e9-9ffe-c5065a04cb0f.png)

http://nps001.homeip.net:8085/CheckerInList.aspx?subDoc=21&menuID=2090

**Comment by Mickrepick** [comment]
Confirm ในหน้าจอรายการตรวจสินค้า ไม่มีปุ่ม เพิ่มใบตรวจสินค้า
