### ISSUE TITLE
ตรวจสินค้าเข้า_เมื่อกดปุ่มแก้ไข_หลังรายการ_ระบบไม่มี_field_ค้นหา_เพื่อค้นหารายการสินค้นที่ต้องการ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#180]
Summary   Name | ตรวจสินค้าเข้า_เมื่อกดปุ่มแก้ไข_หลังรายการ_ระบบไม่มี_field_ค้นหา_เพื่อค้นหารายการสินค้นที่ต้องการ
-- | --
Defect No. |  180
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/CheckerInInfo.aspx?dataId=11289&subDoc=21
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย ตรวจสอบสินค้าเข้า
  | 3. เลือก ตรวจสอบสินค้าเข้า
  | 4.   แสดงหน้าจอ รายการตรวจสินค้าเข้า
  | 5.   กดปุ่ม เพิ่มใบตรวจจสินค้า
  | 6.   กดปุ่ม นำเข้าจาก...
  | 7.   เลือก ใบสั่งซื้อ โดยสถานะเป็น "เรียบร้อย"
  | 8.   ระบุข้อมูลใน Field ทั้งหมด
  | 9.   กดปุ่ม บันทึก
  | 10.   กดปุ่ม ตกลง
  | 11.   กดปุ่ม แก้ไข หลังรายการ
  | 12.   ตรวจสอบ Field กดปุ่ม -------ค้นหา--
  |  
  |  
  |  
Actual   Result | ตรวจสินค้าเข้า_เมื่อกดปุ่มแก้ไข_หลังรายการ_ระบบไม่มี_field_ค้นหา_เพื่อค้นหารายการสินค้นที่ต้องการ
  |  
  |  
Expected   Result | เมื่อกดปุ่มแก้ไข_หลังรายการ_ระบบต้องมี_field_ค้นหา_เพื่อค้นหารายการสินค้นที่ต้องการ
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/54375359-78b92280-46b3-11e9-8d83-cd8eeaffabf5.png)
![image](https://user-images.githubusercontent.com/45878758/54375364-7bb41300-46b3-11e9-833c-41aca900696f.png)

**Comment by acryforever** [comment]
แก้ไขใน อิชู 178

**Comment by Vermouthz** [comment]
ขอคอนเฟิร์มว่า ในหน้าจอรายการตรวจสินค้า ไม่มีปุ่ม เพิ่มใบตรวจสินค้า โดย comment และ ปิด Defect ขอบคุณครับ

![image](https://user-images.githubusercontent.com/45878758/56461577-654e5500-63df-11e9-9ffe-c5065a04cb0f.png)

http://nps001.homeip.net:8085/CheckerInList.aspx?subDoc=21&menuID=2090

**Comment by acryforever** [comment]
![12](https://user-images.githubusercontent.com/47658214/56482586-26a7c000-64ef-11e9-9205-a3f4e0739883.png)
ตรวจสอบ issue เรียบร้อย

**Comment by Vermouthz** [comment]
[รายการตรวจสินค้าเข้า][ตรวจสินค้าเข้า]ไม่มีปุ่ม เพิ่มใบตรวจ กับ Tab รูป แล้วหรอคะ #242
Description Confirm : นำปุ่ม เพิ่มใบตรวจสินค้า ออกจากระบบแล้ว
![image](https://user-images.githubusercontent.com/45878758/56482944-07aa2d80-64f1-11e9-9492-96f453c35abb.png)
