### ISSUE TITLE
[รายการขายสินค้า][เพิ่มรายการขาย]เพิ่มสินค้าไม่ได้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#181]
Summary   Name | [รายการขายสินค้า][เพิ่มรายการขาย]เพิ่มสินค้าไม่ได้
-- | --
Defect No. |  181
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?subDoc=7
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย รายการขายสินค้า
  | 3.  เลือก     ขายสด
  | 4.   แสดงหน้าจอ รายการขาย
  | 5.  กดปุ่ม     เพิ่มรายการขาย
  | 6.   แสงหน้าจอ ขายสินค้า
  | 7.  กดปุ่ม ค้นหาสินค้า
  | 8.  กดปุ่ม เลือก สินค้า
  | 9.  แสดง Error Message
  | 10. กรอกข้อมูลใน   field จำนวน*รหัสสินค้า
  | 11. กดปุ่ม   เพิ่มรายการเบิก+
  |  
Actual   Result | 1. ไม่สามารถเลือกสินค้าจากปุ่ม   ค้นหาสินค้าได้
  | 2.   ไม่สามารถเพิ่มสินค้าจาก Field จำนวน*รหัสสินค้า
Expected   Result | 1.   สามารถเลือกสินค้าจากปุ่ม ค้นหาสินค้าได้
  | 2.   สามารถเพิ่มสินค้าจาก Field จำนวน*รหัสสินค้า
  |  
TesterName | Phatchanok
  |  

![image](https://user-images.githubusercontent.com/45878758/54879373-d6472f00-4e6a-11e9-9b71-0a9a9198fc0f.png)
![image](https://user-images.githubusercontent.com/45878758/54879376-d9dab600-4e6a-11e9-86ea-cd2f298ca797.png)
![image](https://user-images.githubusercontent.com/45878758/54879377-dd6e3d00-4e6a-11e9-849a-8d8598e509bf.png)
![image](https://user-images.githubusercontent.com/45878758/54879378-e2cb8780-4e6a-11e9-8936-6be105161a50.png)
![image](https://user-images.githubusercontent.com/45878758/54879381-e5c67800-4e6a-11e9-8629-2d0ee0b3eec6.png)
![image](https://user-images.githubusercontent.com/45878758/54879382-ebbc5900-4e6a-11e9-98dd-96f07233ec83.png)

**Comment by acryforever** [comment]
Error ใน AddProductToCart ช่วง unitNameTH
เพราะ ได้ JOIN ข้อมูลจาก SKU_Goods ข้อมูลที่ใช้จอย unitNameTH
มีการเปลี่ยนชื่อ unitName ใน BASE แล้ว แต่เรียกใช้ ผิดชื่อของ ID
