### ISSUE TITLE
[รายการขาย]ค้นหาใน   Field วันที่ ระบบแสดง วันที่ออกใบสั่งซื้อ    ทุกรายการ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#182]
Summary   Name | [รายการขาย]ค้นหาใน   Field วันที่ ระบบแสดง วันที่ออกใบสั่งซื้อ    ทุกรายการ
-- | --
Defect No. |  182
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleList.aspx?subDoc=7&menuID=2086
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6.   เลือกข้อมูลใน Field วันที่
  | 7. กดปุ่ม   ค้นหา
  |  
Actual   Result | ค้นหาใน Field วันที่   ระบบแสดง วันที่ออกใบสั่งซื้อ  ทุกรายการ
  |  
Expected   Result | วันที่ออกใบสั่งซื้อ  ต้องแสดงตั้งแต่วันที่ ที่ค้นหาเป็นต้นไป
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54914682-18827600-4f28-11e9-8292-072bc1ba23b8.png)
![image](https://user-images.githubusercontent.com/45878758/54914685-1ae4d000-4f28-11e9-8f7a-42105cd14f52.png)

**Comment by Mickrepick** [comment]
Test แล้วใช้งานได้
