### ISSUE TITLE
ค้นหาใน   Field ถึง ระบบแสดง วันที่ออกใบสั่งซื้อ    ทุกรายการ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#183]
Summary   Name | [รายการขาย]ค้นหาใน   Field ถึง ระบบแสดง วันที่ออกใบสั่งซื้อ    ทุกรายการ
-- | --
Defect No. |  183
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleList.aspx?subDoc=7&menuID=2086
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6.   เลือกข้อมูลใน Field ถึง
  | 7. กดปุ่ม   ค้นหา
  |  
Actual   Result | ค้นหาใน Field ถึง   ตั้งเป็นวันที่ปัจจุบัน ระบบแสดง วันที่ออกใบสั่งซื้อ  ทุกรายการ
  |  
Expected   Result | วันที่ออกใบสั่งซื้อ  ต้องแสดงวันที่ ก่อนวันที่ทำการค้นหา
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54914998-d0178800-4f28-11e9-8542-ed3425275ca7.png)
![image](https://user-images.githubusercontent.com/45878758/54915004-d279e200-4f28-11e9-9d7d-2ece9d089729.png)

**Comment by Mickrepick** [comment]
Test แล้วใช้งานได้
