### ISSUE TITLE
[รายการขาย][เพิ่มรายการขาย]เพิ่มรายการเบิก+   2 รายการ Field ทั้งหมด คำนวณถูกต้อง เมื่อลบ 1 รายการ Field ทั้งหมด   ไม่คำนวณให้ใหม่

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#184]
Summary   Name | [รายการขาย][เพิ่มรายการขาย]เพิ่มรายการเบิก+   2 รายการ Field ทั้งหมด คำนวณถูกต้อง เมื่อลบ 1 รายการ Field ทั้งหมด   ไม่คำนวณให้ใหม่
-- | --
Defect No. |  184
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กดปุ่ม   เพิ่มรายการขาย
  | 7.   กรอกข้อมูลใน Field
  | จำนวน*รหัสสินค้า
  | 8. กดปุ่ม   เพิ่มรายการเบิก+
  | 9.   กรอกข้อมูลใน Field
  | จำนวนสั่ง
  | ราคาสั่ง
  | ส่วนลดรายการ
  | 10. กดปุ่ม   ลบ หลังรายการ
  | 11. กดปุ่ม   ตกลง
  |  
Actual   Result | 1. เพิ่มรายการเบิก+ 2   รายการ Field ทั้งหมด คำนวณถูกต้อง เมื่อลบ 1 รายการ Field ทั้งหมด   ไม่คำนวณให้ใหม่
  |  
Expected   Result | 1. เพิ่มรายการเบิก+ 2   รายการ Field ทั้งหมด คำนวณถูกต้อง เมื่อลบ 1 รายการ Field ทั้งหมด   ต้องคำนวณให้ใหม่
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54915150-15d45080-4f29-11e9-805e-d578ed1f22fe.png)
![image](https://user-images.githubusercontent.com/45878758/54915154-1836aa80-4f29-11e9-843b-e312f9c0d12c.png)
![image](https://user-images.githubusercontent.com/45878758/54915157-1a990480-4f29-11e9-8119-2624d594eecf.png)
![image](https://user-images.githubusercontent.com/45878758/54915166-1e2c8b80-4f29-11e9-9660-62051fa96aa7.png)
![image](https://user-images.githubusercontent.com/45878758/54915170-1ff64f00-4f29-11e9-83ea-e64e15ba569e.png)
![image](https://user-images.githubusercontent.com/45878758/54915174-22f13f80-4f29-11e9-8007-1599a4cada12.png)
![image](https://user-images.githubusercontent.com/45878758/54915177-25ec3000-4f29-11e9-802b-d099be26d5a4.png)
![image](https://user-images.githubusercontent.com/45878758/54915180-28e72080-4f29-11e9-9a30-70a03de4a9ad.png)
![image](https://user-images.githubusercontent.com/45878758/54915189-2be21100-4f29-11e9-91ce-6e57daa3da88.png)

**Comment by Mickrepick** [comment]
แก้ไข : เมื่อลบออก 1 รายการ
จะคำนวณ Field ทั้งหมดใหม่และถูกต้อง
