### ISSUE TITLE
[รายการขาย][เพิ่มรายการขาย]เลือกสินค้ามากกว่า   1 รายการ Field สุทธิ คำนวณถูกต้อง เมื่อลบ 1 รายการ Field ทั้งหมด   คำนวนไม่ถูกต้อง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#185]
Summary   Name | [รายการขาย][เพิ่มรายการขาย]เลือกสินค้ามากกว่า   1 รายการ Field สุทธิ คำนวณถูกต้อง เมื่อลบ 1 รายการ Field ทั้งหมด   คำนวนไม่ถูกต้อง
-- | --
Defect No. |  185
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กดปุ่ม   เพิ่มรายการขาย
  | 7. กดปุ่ม   ค้นหาสินค้า
  | 8. แสดง   PopUp ค้นหาสินค้า
  | 9.   เลือกสินค้า
  | 10.   กรอกข้อมูลใน Field
  | จำนวนสั่ง
  | ราคาสั่ง
  | ส่วนลดรายการ
  | 11. กดปุ่ม   ลบ หลังรายการ
  | 12. กดปุ่ม   ตกลง
  |  
Actual   Result | เมื่อลบ สินค้าออก 1 รายการ ระบบแสดง field สุทธิ "1,490,005,005.00" จาก "1,490.00"
  |  
Expected   Result | เมื่อลบ สินค้าออก 1 รายการ ระบบแสดง field สุทธิ "490.00"
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54915362-811e2280-4f29-11e9-882e-22b3fcf12f7f.png)
![image](https://user-images.githubusercontent.com/45878758/54915366-82e7e600-4f29-11e9-8136-cfbd0dd8b4f6.png)
![image](https://user-images.githubusercontent.com/45878758/54915390-8aa78a80-4f29-11e9-9221-2ec934728a97.png)
![image](https://user-images.githubusercontent.com/45878758/54915392-8c714e00-4f29-11e9-8005-83f31ccef78e.png)
![image](https://user-images.githubusercontent.com/45878758/54915397-8ed3a800-4f29-11e9-85ef-6ca17e194048.png)
![image](https://user-images.githubusercontent.com/45878758/54915399-909d6b80-4f29-11e9-8516-fbd678006ac6.png)
![image](https://user-images.githubusercontent.com/45878758/54915405-9430f280-4f29-11e9-8c8b-d9007f670f6a.png)

**Comment by Vermouthz** [comment]
เพราะดึงค่าจาก field ทั้งหมด มาคำนวนให้ได้ สุทธิ เมื่อ field ทั้

**Comment by Mickrepick** [comment]
แก้ไข : เมื่อลบออก 1 รายการ
จะคำนวณ Field สุทธิ ใหม่และถูกต้อง
