### ISSUE TITLE
[รายการขาย][เพิ่มรายการขาย]ใน   PopUp ค้นหาสินค้า เลือกสินค้าที่มีจำนวนคงเหลือ น้อยกว่าหรือเท่ากับ   "0" ระบบแสดงข้อความไม่เหมือนกัน

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#186]
Summary   Name | [รายการขาย][เพิ่มรายการขาย]ใน   PopUp ค้นหาสินค้า เลือกสินค้าที่มีจำนวนคงเหลือ น้อยกว่าหรือเท่ากับ   "0" ระบบแสดงข้อความไม่เหมือนกัน
-- | --
Defect No. |  186
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กดปุ่ม   เพิ่มรายการขาย
  | 7. กดปุ่ม   ค้นหาสินค้า
  | 8. แสดง   PopUp ค้นหาสินค้า
  | 9.   เลือกสินค้า
  |  
Actual   Result | 1. ใน PopUp   ค้นหาสินค้า เลือกสินค้าที่มีจำนวนคงเหลือ น้อยกว่าหรือเท่ากับ "0"   ระบบแสดงข้อความไม่เหมือนกัน
  |  
Expected   Result | 1. ใน PopUp   ค้นหาสินค้า เลือกสินค้าที่มีจำนวนคงเหลือ น้อยกว่าหรือเท่ากับ   "0"ระบบต้องแสดงข้อความ สินค้าไม่เพียงพอ
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54915504-de19d880-4f29-11e9-9e32-e19b5aea14b3.png)
![image](https://user-images.githubusercontent.com/45878758/54915506-dfe39c00-4f29-11e9-8a0c-7ddf3a4e28e8.png)
![image](https://user-images.githubusercontent.com/45878758/54915511-e245f600-4f29-11e9-92d8-3f4240f34957.png)
![image](https://user-images.githubusercontent.com/45878758/54915517-e4a85000-4f29-11e9-98c4-4d75617c2c42.png)

**Comment by Mickrepick** [comment]
แก้ไข : ใน PopUp ค้นหาสินค้า เลือกสินค้าที่มีจำนวนคงเหลือ น้อยกว่าหรือเท่ากับ "0" ระบบต้องแสดงข้อความ สินค้าไม่เพียงพอ
