### ISSUE TITLE
[รายการขายสินค้า][เพิ่มรายการขาย]ไม่กรอกข้อมูลใน   Field เลขที่เอกสาร วันที่เอกสาร เลขทีสั่งซื้อ จำนวนสั่งซื้อ ราคาสั่ง ระบบแสดง   ข้อความแจ้งเตือนด้านล่าง ไม่ถูกต้อง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#187]
Summary   Name | [รายการขายสินค้า][เพิ่มรายการขาย]ไม่กรอกข้อมูลใน   Field เลขที่เอกสาร วันที่เอกสาร เลขทีสั่งซื้อ จำนวนสั่งซื้อ ราคาสั่ง ระบบแสดง   ข้อความแจ้งเตือนด้านล่าง ไม่ถูกต้อง
-- | --
Defect No. |  187
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กดปุ่ม   เพิ่มรายการขาย
  | 7. กดปุ่ม   เลือกลูกค้า
  | 8. แสดง   PopUp ค้นหาลูกค้า
  | 9. เลือก   ลูกค้า
  | 10.   ไม่กรอกข้อมูลขายสินค้าใน field
  | 11. กดปุ่ม   ค้นหาสินค้า
  | 12. แสดง   PopUp ค้นหาสินค้า
  | 13. เลือก   สินค้า
  | 14   ไม่กรอกข้อมูลรายการสินค้าใน field
  | 15. กดปุ่ม   บันทึก
  | 16. กด   ตกลง
  |  
Actual   Result | 1. ไม่กรอกข้อมูลใน   Field จำนวนสั่งซื้อ ไม่แสดงข้องความแจ้งเตือน
  | 2. ไม่กรอกข้อมูลใน   Field เลขที่เอกสาร วันที่เอกสาร เลขทีสั่งซื้อ จำนวนสั่งซื้อ ราคาสั่ง ระบบแสดง   ข้อความแจ้งเตือนด้านล่าง ไม่ถูกต้อง
  |  
Expected   Result | 1. ไม่กรอกข้อมูลใน   Field จำนวนสั่งซื้อ ต้องแสดงข้อความ "จำนวนต้องมีค่า 1-10000"
  | 2  ไม่กรอกข้อมูลใน Field เลขที่เอกสาร   วันที่เอกสาร เลขทีสั่งซื้อ จำนวนสั่งซื้อ ราคาสั่ง ระบบแสดง   ข้อความแจ้งเตือนด้านล่าง ดังนี้
  | - กรุณากรอกข้อมูล เลขที่เอกสาร
  | - กรุณากรอกข้อมูล วันที่เอกสาร
  | - กรุณากรอกข้อมูล เลขที่สั่งซือ
  | - กรุณากรอกข้อมูลา จำนวนสั่งซื้อ   มีค่าตั้งแต่ 1-10,000
  | - กรุณากรอกข้อมูล ราคาสั่ง มีค่าตั้งแต่   1-10,000
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54915616-246f3780-4f2a-11e9-8ff4-243d6c079bff.png)
![image](https://user-images.githubusercontent.com/45878758/54915619-2638fb00-4f2a-11e9-9d0d-14fa5aa9380d.png)
![image](https://user-images.githubusercontent.com/45878758/54915620-2933eb80-4f2a-11e9-967c-6903eafbe0a7.png)
![image](https://user-images.githubusercontent.com/45878758/54915626-2c2edc00-4f2a-11e9-9653-424700a45111.png)
![image](https://user-images.githubusercontent.com/45878758/54915629-2df89f80-4f2a-11e9-969c-85c486cd4981.png)
![image](https://user-images.githubusercontent.com/45878758/54915633-2fc26300-4f2a-11e9-8a7c-17e5cc468bfb.png)
![image](https://user-images.githubusercontent.com/45878758/54915638-318c2680-4f2a-11e9-893a-882c43f07218.png)
![image](https://user-images.githubusercontent.com/45878758/54915642-34871700-4f2a-11e9-9cb5-95d4ec8c9d47.png)

**Comment by Mickrepick** [comment]
แก้ไข : ข้อความแจ้งเตือนด้านล่าง ดังนี้
ไม่สามารถบันทึกข้อมูลได้ :
กรุณากรอกข้อมูล เลขที่เอกสาร
กรุณากรอกข้อมูล วันที่เอกสาร
กรุณากรอกข้อมูล เลขที่สั่งซื้อ
กรุณากรอกจำนวน จำนวนสั่งซื้อ มีค่าตั้งแต่ 1-10,000
กรุณากรอกจำนวน ราคาสั่ง มีค่าตั้งแต่ 1-10,000
