### ISSUE TITLE
[รายการขาย][เพิ่มรายการขาย]กรอกข้อมูลใน   Field Mandatory ทั้งหมด ไม่สามารถบันทึกข้อมูลได้ ระบบขึ้นข้อความ Error

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#188]
Summary   Name | [รายการขาย][เพิ่มรายการขาย]กรอกข้อมูลใน   Field Mandatory ทั้งหมด ไม่สามารถบันทึกข้อมูลได้ ระบบขึ้นข้อความ Error
-- | --
Defect No. |  188
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กดปุ่ม   เพิ่มรายการขาย
  | 7. กดปุ่ม   เลือกลูกค้า
  | 8. แสดง   PopUp ค้นหาลูกค้า
  | 9. เลือก   ลูกค้า
  | 10.   กรอกข้อมูลขายสินค้าใน field
  | เลขที่เอกสาร
  | วันที่เอกสาร
  | ข้อตกลง
  | 11. กดปุ่ม   ค้นหาสินค้า
  | 12. แสดง   PopUp ค้นหาสินค้า
  | 13. เลือก   สินค้า
  | 14   กรอกข้อมูลรายการสินค้าใน field
  | จำนวนสั่งซื้อ
  | ราคาสั่ง
  | 15. กดปุ่ม   บันทึก
  | 16. กด   ตกลง
  |  
Actual   Result | 1. กรอกข้อมูลใน Field   Mandatory ทั้งหมด ไม่สามารถบันทึกข้อมูลได้ ระบบขึ้นข้อความ Error
  |  
Expected   Result | 1.  กรอกข้อมูลใน Field Mandatory ทั้งหมด   ต้องสามารถบันทึกข้อมูลได้
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54915764-8039c080-4f2a-11e9-868b-6dc8eb2d9835.png)
![image](https://user-images.githubusercontent.com/45878758/54915766-8334b100-4f2a-11e9-8846-9f03267bd249.png)
![image](https://user-images.githubusercontent.com/45878758/54915767-84fe7480-4f2a-11e9-92c6-dfcfbf98758d.png)
![image](https://user-images.githubusercontent.com/45878758/54915771-86c83800-4f2a-11e9-9300-79c5380005b4.png)
![image](https://user-images.githubusercontent.com/45878758/54915777-892a9200-4f2a-11e9-997d-82d7b21e8f62.png)
![image](https://user-images.githubusercontent.com/45878758/54915785-8cbe1900-4f2a-11e9-9238-214585e154a7.png)

**Comment by acryforever** [comment]
แก้ไข้ (!(HttpContext.Current.Session[CartList_SaveState] is List<Trans_Detail>))
เพิ่มการกรอก 
                else if (txtPopUpCus.Text == "")
                {
                    LogFile.WriteLogFile("", "Purchase", "SaveToDB", "โปรดเลือกคู่ค้าที่จะเก็บก่อนบันทึก");
                    return "โปรดเลือกคู่ค้าที่จะเก็บก่อนบันทึก";
                }
ในการตรวจสอบ การเลือกคู่
