### ISSUE TITLE
[รายการขาย][เพิ่มรายการขาย]กรอกข้อมูลจำนวนสินค้ามากกว่าจำนวนคงเหลือ   เป็น "0" ข้อความแจ้งเตือน ไม่พบสินค้า

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#189]
Summary   Name | [รายการขาย][เพิ่มรายการขาย]กรอกข้อมูลจำนวนสินค้ามากกว่าจำนวนคงเหลือ   เป็น "0" ข้อความแจ้งเตือน ไม่พบสินค้า
-- | --
Defect No. |  189
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กดปุ่ม   เพิ่มรายการขาย
  | 7.   กรอกข้อมูลใน Field
  | จำนวน*รหัสสินค้า
  | 8. กดปุ่ม   เพิ่มรายการเบิก+
  |  
Actual   Result | 1.   กรอกข้อมูลจำนวนสินค้ามากกว่าจำนวนคงเหลือ เป็น "0" ข้อความแจ้งเตือน   ไม่พบสินค้า
  |  
Expected   Result | 1.   เมื่อกรอกข้อมูลจำนวนสินค้ามากกว่าจำนวนคงเหลือ เป็น "0"   ข้อความต้องแจ้งเตือน สินค้าไม่เพียงพอ
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54915944-df97d080-4f2a-11e9-96a6-a7cc9a355290.png)
![image](https://user-images.githubusercontent.com/45878758/54915946-e1fa2a80-4f2a-11e9-9672-4f9e907cc411.png)
![image](https://user-images.githubusercontent.com/45878758/54915950-e45c8480-4f2a-11e9-9562-88617a5e1ed7.png)
![image](https://user-images.githubusercontent.com/45878758/54915953-e6264800-4f2a-11e9-801b-189f2b91d66c.png)

**Comment by Mickrepick** [comment]
แก้ไข : เมื่อกรอกข้อมูลจำนวนสินค้ามากกว่าจำนวนคงเหลือ เป็น "0" ข้อความต้องแจ้งเตือน สินค้าไม่เพียงพอ
