### ISSUE TITLE
[รายการขาย][เพิ่มรายการขาย]กรอกจำนวนสั่งซื้อ   มากกว่าจำหน่วยคงเหลือ สามารถกรอกได้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#190]
Summary   Name | [รายการขาย][เพิ่มรายการขาย]กรอกจำนวนสั่งซื้อ   มากกว่าจำหน่วยคงเหลือ สามารถกรอกได้
-- | --
Defect No. |  190
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กดปุ่ม   เพิ่มรายการขาย
  | 7. กดปุ่ม   ค้นหาสินค้า
  | 8. แสดง   PopUp ค้นหาสินค้า
  | 9.   เลือกสินค้า
  | 10.   กรอกข้อมูลใน Field
  | จำนวนสั่งซื้อ มากกว่าจำนวนคงเหลือ
  |  
Actual   Result | กรอกจำนวนสั่งซื้อ   มากกว่าจำนวนคงเหลือ สามารถกรอกได้
  |  
Expected   Result | กรอกจำนวนสั่งซื้อ   มากกว่าจำนวนคงเหลือ ระบบต้องแจ้งเตือน สินค้าไม่เพียงพอ
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54916035-24bc0280-4f2b-11e9-92d4-c73c56b31a5a.png)
![image](https://user-images.githubusercontent.com/45878758/54916044-2685c600-4f2b-11e9-98b8-c91ed261bfa9.png)
![image](https://user-images.githubusercontent.com/45878758/54916050-28e82000-4f2b-11e9-8ca0-c06be1994339.png)
![image](https://user-images.githubusercontent.com/45878758/54916060-2ab1e380-4f2b-11e9-9f26-b9a97d395946.png)

**Comment by Patthamaporn** [comment]
แก้ไข: เปลี่ยนจำนวนขายที่มากกว่าจำนวนในสต็อกจะมี messenge แจ้งเตือนว่า สินค้าไม่เพียงพอ
