### ISSUE TITLE
[รายการขาย][แก้ไข   หลังรายการ]Filed รวมยอด ไม่หักส่วนลดรายการ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#191]
Summary   Name | [รายการขาย][แก้ไข   หลังรายการ]Filed รวมยอด ไม่หักส่วนลดรายการ
-- | --
Defect No. |  191
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=11326&subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กดปุ่ม   เพิ่มรายการขาย
  | 7.   ระบุข้อมูลใน หน้าจอขายสินค้า ทั้งหมด
  | 8. กดปุ่ม   บันทึก
  | 9.   แสดงหน้าจอ รายการขาย
  | 10. กดปุ่ม   แก้ไข หลังรายการ
  |  11. กรอก field ส่วนลดรายการ "100.00"
Actual   Result | 1. Filed รวมยอด   ไม่หักส่วนลดรายการ
  |  
Expected   Result | 1. Filed   รวมยอด ต้องหักส่วนลดรายการ "4,000-100 = 3900.00"
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54916154-74023300-4f2b-11e9-9ae2-c52ea58a8de3.png)
![image](https://user-images.githubusercontent.com/45878758/54916158-7795ba00-4f2b-11e9-9a50-62eac97a38b5.png)
![image](https://user-images.githubusercontent.com/45878758/54916162-795f7d80-4f2b-11e9-9452-8cf9b9145ee6.png)
![image](https://user-images.githubusercontent.com/45878758/54916163-7b294100-4f2b-11e9-84f8-f63dc4646c4c.png)
![image](https://user-images.githubusercontent.com/45878758/54916168-7cf30480-4f2b-11e9-8156-830d8a3a9b29.png)
![image](https://user-images.githubusercontent.com/45878758/54916174-841a1280-4f2b-11e9-98f7-cd17c72987b8.png)

**Comment by Mickrepick** [comment]
แก้ไข : เมื่อใส่ส่วนลดรายการ 
Filed รวมยอด จะหักส่วนลดรายการ

**Comment by Vermouthz** [comment]
Retest-Failed 21/04/2562

![image](https://user-images.githubusercontent.com/45878758/56473214-0dbcf180-6492-11e9-8cdc-13742d14685c.png)
![image](https://user-images.githubusercontent.com/45878758/56473218-1b727700-6492-11e9-9f91-76cc98699c3a.png)

**Comment by Mickrepick** [comment]
แก้ไข : เมื่อใส่ส่วนลดรายการ
Filed รวมยอด จะหักส่วนลดรายการ
