### ISSUE TITLE
[รายการขาย][แก้ไข   หลังรายการ]เพิ่มรายการสินค้าจาก PopUp 2 รายการ Field ทั้งหมด คำนวณถูกต้อง   เมื่อลบ 1 รายการ Field ทั้งหมด ไม่คำนวณให้ใหม่

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#192]
Summary   Name | [รายการขาย][แก้ไข   หลังรายการ]เพิ่มรายการสินค้าจาก PopUp 2 รายการ Field ทั้งหมด คำนวณถูกต้อง   เมื่อลบ 1 รายการ Field ทั้งหมด ไม่คำนวณให้ใหม่
-- | --
Defect No. |  192
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=11326&subDoc=7
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย รายการขายสินค้า
  | 3. เลือก   ขายสด
  | 4.   แสดงหน้าจอ รายการขาย
  | 5. กดปุ่ม   เพิ่มรายการขาย
  | 6.   กรอกข้อมูลใน Field ทั้งหมด
  | 7. กดปุ่ม   บันทึก
  | 8.   แสดงหน้าจอ รายการขาย
  | 9. กดปุ่ม   แก้ไข หลังรายการ
  | 10. กดปุ่ม   ค้นหาสินค้า
  | 11. แสดง   PopUp ค้นหาสินค้า
  | 12.   เลือกสินค้า
  | 13.   กรอกข้อมูลใน Field
  | จำนวนสั่ง
  | ราคาสั่ง
  | ส่วนลดรายการ
  | 14. กดปุ่ม   ลบ หลังรายการ
  | 15. กดปุ่ม   ตกลง
  |  
Actual   Result | 1.   เพิ่มรายการสินค้าจาก PopUp 2 รายการ Field ทั้งหมด คำนวณถูกต้อง เมื่อลบ 1   รายการ Field ทั้งหมด ไม่คำนวณให้ใหม่
  |  
Expected   Result | 1.   เพิ่มรายการสินค้าจาก PopUp 2 รายการ Field ทั้งหมด คำนวณถูกต้อง เมื่อลบ 1   รายการ Field ทั้งหมด ต้องคำนวณให้ใหม่
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54916393-086c9580-4f2c-11e9-8b0a-7857b5f5a244.png)
![image](https://user-images.githubusercontent.com/45878758/54916396-0aceef80-4f2c-11e9-9d11-e7d477832eaa.png)
![image](https://user-images.githubusercontent.com/45878758/54916402-0c98b300-4f2c-11e9-8d53-7a0d8b8e95fc.png)
![image](https://user-images.githubusercontent.com/45878758/54916406-0efb0d00-4f2c-11e9-9240-383455a708ba.png)
![image](https://user-images.githubusercontent.com/45878758/54916415-10c4d080-4f2c-11e9-8081-a76234948500.png)
![image](https://user-images.githubusercontent.com/45878758/54916425-17534800-4f2c-11e9-85e5-94f996125f5e.png)
![image](https://user-images.githubusercontent.com/45878758/54916435-19b5a200-4f2c-11e9-8f20-bc0cdde30ef7.png)
![image](https://user-images.githubusercontent.com/45878758/54916442-1e7a5600-4f2c-11e9-9ec8-a987442bc2eb.png)

**Comment by Mickrepick** [comment]
แก้ไข : เมื่อลบ 1 รายการ
Field ทั้งหมด จะคำนวณใหม่
