### ISSUE TITLE
[รายการขาย][แก้ไข   หลังรายการ]เพิ่มสินค้าจาก จำนวน*รหัสสินค้า 2 รายการ Field ทั้งหมด   คำนวณถูกต้อง เมื่อลบ 1 รายการ Field ทั้งหมด ไม่คำนวณให้ใหม่

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#193]
Summary   Name | [รายการขาย][แก้ไข   หลังรายการ]เพิ่มสินค้าจาก จำนวน*รหัสสินค้า 2 รายการ Field ทั้งหมด   คำนวณถูกต้อง เมื่อลบ 1 รายการ Field ทั้งหมด ไม่คำนวณให้ใหม่
-- | --
Defect No. |  193
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=11326&subDoc=7
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กดปุ่ม   เพิ่มรายการขาย
  | 7.   กรอกข้อมูลใน Field ทั้งหมด
  | 8. กดปุ่ม   บันทึก
  | 9.   แสดงหน้าจอ รายการขาย
  | 10. กดปุ่ม   แก้ไข หลังรายการ
  | 11.   กรอกข้อมูลใน Field
  | จำนวน*รหัสสินค้า
  | 12. กดปุ่ม   เพิ่มรายการเบิก+
  | 13.   กรอกข้อมูลใน Field
  | จำนวนสั่ง
  | ราคาสั่ง
  | ส่วนลดรายการ
  | 14. กดปุ่ม   ลบ หลังรายการ
  | 15. กดปุ่ม   ตกลง
  |  
Actual   Result | เมื่อลบ 1 รายการ Field   ทั้งหมด ไม่คำนวณให้ใหม่
  |  
Expected   Result | 1. เพิ่มสินค้าจาก   จำนวน*รหัสสินค้า 2 รายการ Field ทั้งหมด คำนวณถูกต้อง เมื่อลบ 1 รายการ Field   ทั้งหมด ต้องคำนวณให้ใหม่
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54916546-55506c00-4f2c-11e9-9723-cc3aac9489f8.png)
![image](https://user-images.githubusercontent.com/45878758/54916550-584b5c80-4f2c-11e9-8de8-dce7f5aae157.png)
![image](https://user-images.githubusercontent.com/45878758/54916554-5aadb680-4f2c-11e9-844d-511c7152547c.png)
![image](https://user-images.githubusercontent.com/45878758/54916560-5d101080-4f2c-11e9-956a-c29ec522554d.png)
![image](https://user-images.githubusercontent.com/45878758/54916568-5f726a80-4f2c-11e9-99ba-b78e5b038b12.png)
![image](https://user-images.githubusercontent.com/45878758/54916571-6305f180-4f2c-11e9-9572-3dd8950b8c0f.png)
![image](https://user-images.githubusercontent.com/45878758/54916575-64cfb500-4f2c-11e9-8721-8953b51057f1.png)
![image](https://user-images.githubusercontent.com/45878758/54916578-66997880-4f2c-11e9-9e19-32903e08416f.png)
![image](https://user-images.githubusercontent.com/45878758/54916586-68fbd280-4f2c-11e9-9800-bb7985c375d7.png)
![image](https://user-images.githubusercontent.com/45878758/54916590-6ac59600-4f2c-11e9-984a-776d7418d005.png)
![image](https://user-images.githubusercontent.com/45878758/54916593-6d27f000-4f2c-11e9-894a-b456817723f8.png)
![image](https://user-images.githubusercontent.com/45878758/54916601-73b66780-4f2c-11e9-81e5-7d995fd0449e.png)
![image](https://user-images.githubusercontent.com/45878758/54916608-7618c180-4f2c-11e9-9e4e-fe54a922aa11.png)
![image](https://user-images.githubusercontent.com/45878758/54916614-7c0ea280-4f2c-11e9-9dd3-c1a33bd1d3bc.png)

**Comment by Mickrepick** [comment]
แก้ไข : เมื่อลบ 1 รายการ 
Field ทั้งหมด จะคำนวณใหม่
