### ISSUE TITLE
[รายการขาย][แก้ไข   หลังรายการ]เพิ่มสินค้าจาก จำนวน*รหัสสินค้า เลือกสินค้าที่มีจำนวนคงเหลือ   น้อยกว่าหรือเท่ากับ "0" ระบบแสดงข้อความไม่เหมือนกัน

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#194]
Summary   Name | [รายการขาย][แก้ไข   หลังรายการ]เพิ่มสินค้าจาก จำนวน*รหัสสินค้า เลือกสินค้าที่มีจำนวนคงเหลือ   น้อยกว่าหรือเท่ากับ "0" ระบบแสดงข้อความไม่เหมือนกัน
-- | --
Defect No. |  194
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=11326&subDoc=7
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กดปุ่ม   เพิ่มรายการขาย
  | 7.   กรอกข้อมูลใน Field ทั้งหมด
  | 8. กดปุ่ม   บันทึก
  | 9.   แสดงหน้าจอ รายการขาย
  | 10. กดปุ่ม   แก้ไข หลังรายการ
  | 11.   กรอกข้อมูลใน Field
  | จำนวน*รหัสสินค้า
  | 12. กดปุ่ม   เพิ่มรายการเบิก+
  |  
Actual   Result | 1. เพิ่มสินค้าจาก   จำนวน*รหัสสินค้า เลือกสินค้าที่มีจำนวนคงเหลือ น้อยกว่าหรือเท่ากับ   "0" ระบบแสดงข้อความไม่เหมือนกัน
  |  
Expected   Result | 1. เพิ่มสินค้าจาก   จำนวน*รหัสสินค้า เลือกสินค้าที่มีจำนวนคงเหลือ น้อยกว่าหรือเท่ากับ   "0" ระบบต้องแสดง สินค้าไม่เพียงพอ
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54916730-c7c14c00-4f2c-11e9-8060-30f01f4ced00.png)
![image](https://user-images.githubusercontent.com/45878758/54916732-ca23a600-4f2c-11e9-8d2d-814d793cd84c.png)
![image](https://user-images.githubusercontent.com/45878758/54916734-cc860000-4f2c-11e9-9085-643794860de0.png)
![image](https://user-images.githubusercontent.com/45878758/54916742-cf80f080-4f2c-11e9-8ae9-9be69b5c1074.png)
![image](https://user-images.githubusercontent.com/45878758/54916748-d1e34a80-4f2c-11e9-8b3d-5d222e9eab74.png)
![image](https://user-images.githubusercontent.com/45878758/54916750-d3ad0e00-4f2c-11e9-8163-7bd63aa23d0a.png)
![image](https://user-images.githubusercontent.com/45878758/54916762-d6a7fe80-4f2c-11e9-8200-0470ade6d871.png)
![image](https://user-images.githubusercontent.com/45878758/54916773-ddcf0c80-4f2c-11e9-95cd-9f18a7fc5888.png)
![image](https://user-images.githubusercontent.com/45878758/54916779-e0316680-4f2c-11e9-9b7e-404c8229a9d3.png)
![image](https://user-images.githubusercontent.com/45878758/54916788-e7587480-4f2c-11e9-9fcf-f2fcce3e8be2.png)

**Comment by acryforever** [comment]
ทดสอบผ่าน ดีบัค เนื่องจากก่อนหน้าได้ไปแก้ไข อิชู188
