### ISSUE TITLE
[รายการขาย][แก้ไข   หลังรายการ]เลือกสินค้ามากกว่า 1 รายการ Field สุทธิ คำนวณถูกต้อง เมื่อลบ 1   รายการ Field ทั้งหมด คำนวนไม่ถูกต้อง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#195]
Summary   Name | [รายการขาย][แก้ไข   หลังรายการ]เลือกสินค้ามากกว่า 1 รายการ Field สุทธิ คำนวณถูกต้อง เมื่อลบ 1   รายการ Field ทั้งหมด คำนวนไม่ถูกต้อง
-- | --
Defect No. |  195
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?subDoc=7
Step | 1. Login   WMS on Chorme
  | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย รายการขายสินค้า
  | 3. เลือก   ขายสด
  | 4.   แสดงหน้าจอ รายการขาย
  | 5. กดปุ่ม   เพิ่มรายการขาย
  | 6.   กรอกข้อมูลใน Field ทั้งหมด
  | 7. กดปุ่ม   บันทึก
  | 8.   แสดงหน้าจอ รายการขาย
  | 9. กดปุ่ม   แก้ไข หลังรายการ
  | 10. กดปุ่ม   ค้นหาสินค้า
  | 11. แสดง   PopUp ค้นหาสินค้า
  | 12.   เลือกสินค้า
  | 13.   กรอกข้อมูลใน Field
  | จำนวนสั่ง
  | ราคาสั่ง
  | ส่วนลดรายการ
  | ภาษีมูลค่าเพิ่ม
  | 11. กดปุ่ม   ลบ หลังรายการ
  | 12. กดปุ่ม   ตกลง
  |  
Actual   Result | 1. เลือกสินค้ามากกว่า   1 รายการ Field ทั้งหมด คำนวณถูกต้อง เมื่อลบ 1 รายการ Field ทั้งหมด   คำนวนไม่ถูกต้อง
  |  
Expected   Result | 1. เลือกสินค้ามากกว่า   1 รายการ Field ทั้งหมด คำนวณถูกต้อง เมื่อลบ 1 รายการ Field ทั้งหมด   ต้องคำนวนถูกต้อง
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54916902-22f33e80-4f2d-11e9-8684-0248e259462c.png)
![image](https://user-images.githubusercontent.com/45878758/54916909-25559880-4f2d-11e9-8f52-dcaa4fb633d7.png)
![image](https://user-images.githubusercontent.com/45878758/54916914-271f5c00-4f2d-11e9-8180-e741f212039c.png)
![image](https://user-images.githubusercontent.com/45878758/54916916-2981b600-4f2d-11e9-90c8-f255dbbccfab.png)
![image](https://user-images.githubusercontent.com/45878758/54916921-2be41000-4f2d-11e9-96f0-4d25e4cd14ec.png)
![image](https://user-images.githubusercontent.com/45878758/54916923-2d153d00-4f2d-11e9-8ea5-ada4bebb1b6a.png)
![image](https://user-images.githubusercontent.com/45878758/54916926-2f779700-4f2d-11e9-836b-d86ff8178314.png)
![image](https://user-images.githubusercontent.com/45878758/54916933-356d7800-4f2d-11e9-9ece-674870dc9150.png)
![image](https://user-images.githubusercontent.com/45878758/54916935-369ea500-4f2d-11e9-87e5-c508b078c09f.png)
![image](https://user-images.githubusercontent.com/45878758/54916946-3b635900-4f2d-11e9-9b33-3bd580202945.png)

**Comment by Mickrepick** [comment]
แก้ไข : เมื่อลบออก 1 รายการ 
Field ทั้งหมด จะคำนวนใหม่และถูกต้อง
