### ISSUE TITLE
[รายการขาย][แก้ไข   หลังรายการ]ใน PopUp ค้นหาสินค้า เลือกสินค้าที่มีจำนวนคงเหลือ   น้อยกว่าหรือเท่ากับ "0" ระบบแสดงข้อความไม่เหมือนกัน -- | --

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#196]
Summary   Name | [รายการขาย][แก้ไข   หลังรายการ]ใน PopUp ค้นหาสินค้า เลือกสินค้าที่มีจำนวนคงเหลือ   น้อยกว่าหรือเท่ากับ "0" ระบบแสดงข้อความไม่เหมือนกัน
-- | --
Defect No. |  196
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=11326&subDoc=7
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย รายการขายสินค้า
  | 3. เลือก   ขายสด
  | 4.   แสดงหน้าจอ รายการขาย
  | 5. กดปุ่ม   เพิ่มรายการขาย
  | 6.   กรอกข้อมูลใน Field ทั้งหมด
  | 7. กดปุ่ม   บันทึก
  | 8.   แสดงหน้าจอ รายการขาย
  | 9. กดปุ่ม   แก้ไข หลังรายการ
  | 10. กดปุ่ม   ค้นหาสินค้า
  | 11. แสดง   PopUp ค้นหาสินค้า
  | 12.   เลือกสินค้า 1 รายการ
  |  
Actual   Result | 1. ใน PopUp   ค้นหาสินค้า เลือกสินค้าที่มีจำนวนคงเหลือ น้อยกว่าหรือเท่ากับ "0"   ระบบแสดงข้อความไม่เหมือนกัน
  |  
Expected   Result | 1. ใน PopUp   ค้นหาสินค้า เลือกสินค้าที่มีจำนวนคงเหลือ น้อยกว่าหรือเท่ากับ   "0"ระบบต้องแสดงข้อความ สินค้าไม่เพียงพอ
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54917022-736a9c00-4f2d-11e9-864f-3b101e0347ba.png)
![image](https://user-images.githubusercontent.com/45878758/54917023-75345f80-4f2d-11e9-81b3-6aeaa7e9c865.png)
![image](https://user-images.githubusercontent.com/45878758/54917030-782f5000-4f2d-11e9-836b-f4380a030f22.png)
![image](https://user-images.githubusercontent.com/45878758/54917035-79f91380-4f2d-11e9-9b79-9a5d3cb0731e.png)
![image](https://user-images.githubusercontent.com/45878758/54917039-7bc2d700-4f2d-11e9-9a5f-192765d98e81.png)
![image](https://user-images.githubusercontent.com/45878758/54917042-7e253100-4f2d-11e9-99d6-08612c57cded.png)
![image](https://user-images.githubusercontent.com/45878758/54917049-7feef480-4f2d-11e9-9196-a941b801b2d0.png)
![image](https://user-images.githubusercontent.com/45878758/54917062-867d6c00-4f2d-11e9-9ee9-4e99b9411097.png)
![image](https://user-images.githubusercontent.com/45878758/54917077-8ed5a700-4f2d-11e9-8ee3-a6ca81c71b0f.png)

**Comment by Mickrepick** [comment]
แก้ไข :ใน PopUp ค้นหาสินค้า เมื่อเลือกสินค้าที่มีจำนวนคงเหลือ น้อยกว่าหรือเท่ากับ "0" ระบบจะแสดงข้อความ 
"สินค้าไม่เพียงพอ"
