### ISSUE TITLE
[รายการขาย][แก้ไข   หลังรายการ]ไม่กรอกข้อมูลใน Field เลขที่เอกสาร วันที่เอกสาร เลขทีสั่งซื้อ   จำนวนสั่งซื้อ ราคาสั่ง ระบบแสดง ข้อความแจ้งเตือนด้านล่าง ไม่ถูกต้อง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#197]
Summary   Name | [รายการขาย][แก้ไข   หลังรายการ]ไม่กรอกข้อมูลใน Field เลขที่เอกสาร วันที่เอกสาร เลขทีสั่งซื้อ   จำนวนสั่งซื้อ ราคาสั่ง ระบบแสดง ข้อความแจ้งเตือนด้านล่าง ไม่ถูกต้อง
-- | --
Defect No. |  197
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=11326&subDoc=7
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย รายการขายสินค้า
  | 3. เลือก   ขายสด
  | 4.   แสดงหน้าจอ รายการขาย
  | 5. กดปุ่ม   เพิ่มรายการขาย
  | 6.   กรอกข้อมูลใน Field ทั้งหมด
  | 7. กดปุ่ม   บันทึก
  | 8.   แสดงหน้าจอ รายการขาย
  | 9. กดปุ่ม   แก้ไข หลังรายการ
  | 10.   ลบข้อมูลใน Field ทั้งหมด
  | เลขที่เอกสาร
  | วันที่เอกสาร
  | เลขที่สั่งซื้อ
  | จำนวนสั่งซื้อ
  | ราคาสั่ง
  | 11. กด   บันทึก
  | 12. กดปุ่ม   ตกลง
  |  
Actual   Result | 1. ไม่กรอกข้อมูลใน   Field จำนวนสั่งซื้อ ไม่แสดงข้องความแจ้งเตือน
  | 2. ไม่กรอกข้อมูลใน   Field เลขที่เอกสาร วันที่เอกสาร เลขทีสั่งซื้อ จำนวนสั่งซื้อ ราคาสั่ง ระบบแสดง   ข้อความแจ้งเตือนด้านล่าง ไม่ถูกต้อง
  |  
Expected   Result | 1. ไม่กรอกข้อมูลใน   Field จำนวนสั่งซื้อ ต้องแสดงข้อความ "จำนวนต้องมีค่า 1-10000"
  | 2  ไม่กรอกข้อมูลใน Field เลขที่เอกสาร   วันที่เอกสาร เลขทีสั่งซื้อ จำนวนสั่งซื้อ ราคาสั่ง ระบบแสดง   ข้อความแจ้งเตือนด้านล่าง ดังนี้
  | - กรุณากรอกข้อมูล เลขที่เอกสาร
  | - กรุณากรอกข้อมูล วันที่เอกสาร
  | - กรุณากรอกข้อมูล เลขที่สั่งซือ
  | - กรุณากรอกข้อมูลา จำนวนสั่งซื้อ   มีค่าตั้งแต่ 1-10,000
  | - กรุณากรอกข้อมูล ราคาสั่ง มีค่าตั้งแต่   1-10,000
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54917158-c3496300-4f2d-11e9-8c84-506a0717e540.png)
![image](https://user-images.githubusercontent.com/45878758/54917162-c5abbd00-4f2d-11e9-9243-d2f93f9ae708.png)
![image](https://user-images.githubusercontent.com/45878758/54917164-c7758080-4f2d-11e9-9391-0433789ed6c5.png)
![image](https://user-images.githubusercontent.com/45878758/54917169-c93f4400-4f2d-11e9-8181-030cd1eebc72.png)
![image](https://user-images.githubusercontent.com/45878758/54917173-cb090780-4f2d-11e9-8ec8-9163078c826a.png)
![image](https://user-images.githubusercontent.com/45878758/54917178-ccd2cb00-4f2d-11e9-893e-82f8b0dc3b60.png)
![image](https://user-images.githubusercontent.com/45878758/54917183-cf352500-4f2d-11e9-94f8-9eed4d9b507c.png)
![image](https://user-images.githubusercontent.com/45878758/54917192-d1977f00-4f2d-11e9-85ba-e066aa41bd4c.png)
![image](https://user-images.githubusercontent.com/45878758/54917202-d825f680-4f2d-11e9-80d5-577ede04beea.png)

**Comment by Mickrepick** [comment]
แก้ไข : 
ถ้าไม่กรอกข้อมูลใน Field จำนวนสั่งซื้อ ต้องแสดงข้อความ "กรุณากรอกข้อมูล จำนวนสั่งซื้อ มีค่าตั้งแต่ 1-10,000"
ถ้าไม่กรอกข้อมูลใน Field เลขที่เอกสาร วันที่เอกสาร เลขทีสั่งซื้อ จำนวนสั่งซื้อ ราคาสั่ง ระบบแสดง ข้อความแจ้งเตือนด้านล่าง ดังนี้
 - กรุณากรอกข้อมูล เลขที่เอกสาร
 - กรุณากรอกข้อมูล วันที่เอกสาร
 - กรุณากรอกข้อมูล เลขที่สั่งซือ
 - กรุณากรอกข้อมูล จำนวนสั่งซื้อ มีค่าตั้งแต่ 1-10,000
 - กรุณากรอกข้อมูล ราคาสั่ง มีค่าตั้งแต่ 1-10,000
