### ISSUE TITLE
[รายการขาย][แก้ไข   หลังรายการ]กรอกข้อมูลจำนวนสินค้ามากกว่าจำนวนคงเหลือ ที่สินค้ามีในระบบ  ระบบแสดง Error Message "ไม่พบสินค้า"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#198]
Summary   Name | [รายการขาย][แก้ไข   หลังรายการ]กรอกข้อมูลจำนวนสินค้ามากกว่าจำนวนคงเหลือ ที่สินค้ามีในระบบ  ระบบแสดง Error Message "ไม่พบสินค้า"
-- | --
Defect No. |  198
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=11326&subDoc=7
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กดปุ่ม   เพิ่มรายการขาย
  | 7.   กรอกข้อมูลใน Field ทั้งหมด
  | 8. กดปุ่ม   บันทึก
  | 9.   แสดงหน้าจอ รายการขาย
  | 10. กดปุ่ม   แก้ไข หลังรายการ
  | 11.   กรอกข้อมูลใน Field
  | จำนวน*รหัสสินค้า
  | 12. กดปุ่ม   เพิ่มรายการเบิก+
  |  
Actual   Result | กรอกข้อมูลจำนวนสินค้ามากกว่าจำนวนคงเหลือ ที่สินค้ามีในระบบ  ระบบแสดง Error Message "ไม่พบสินค้า"
  |  
Expected   Result | กรอกข้อมูลจำนวนสินค้ามากกว่าจำนวนคงเหลือ ที่สินค้ามีในระบบ ต้องแสดง Error Message "สินค้าไม่เพียงพอ"
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54917271-073c6800-4f2e-11e9-843b-bb3ff5c8f547.png)
![image](https://user-images.githubusercontent.com/45878758/54917277-09062b80-4f2e-11e9-9221-59ffba70857a.png)
![image](https://user-images.githubusercontent.com/45878758/54917279-0b688580-4f2e-11e9-85c4-fb81abc117da.png)
![image](https://user-images.githubusercontent.com/45878758/54917284-0d324900-4f2e-11e9-8ff8-21997a2d0f38.png)
![image](https://user-images.githubusercontent.com/45878758/54917287-0efc0c80-4f2e-11e9-8570-925bbfc0ed9f.png)
![image](https://user-images.githubusercontent.com/45878758/54917293-10c5d000-4f2e-11e9-897b-6b614183c6ca.png)
![image](https://user-images.githubusercontent.com/45878758/54917295-128f9380-4f2e-11e9-91ad-9d5424558c41.png)
![image](https://user-images.githubusercontent.com/45878758/54917299-14595700-4f2e-11e9-906e-f3c3be440773.png)
![image](https://user-images.githubusercontent.com/45878758/54917307-19b6a180-4f2e-11e9-8295-88e3e7dab092.png)

**Comment by acryforever** [comment]
เทส ของโฟม  Error Message สินค้าไม่เพียงพอ
