### ISSUE TITLE
[รายการขาย][แก้ไข   หลังรายการ]กรอกจำนวนสั่งซื้อ มากกว่าจำนวนคงเหลือ ระบบแสดง Error Message "ไม่พบสินค้า"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#199]
Summary   Name | [รายการขาย][แก้ไข หลังรายการ]กรอกจำนวนสั่งซื้อ มากกว่าจำนวนคงเหลือ ระบบแสดง Error Message "ไม่พบสินค้า"
-- | --
Defect No. |  199
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=11326&subDoc=7
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กดปุ่ม   เพิ่มรายการขาย
  | 7.   กรอกข้อมูลใน Field ทั้งหมด
  | 8. กดปุ่ม   บันทึก
  | 9.   แสดงหน้าจอ รายการขาย
  | 10. กดปุ่ม   แก้ไข หลังรายการ
  | 11.   กรอกข้อมูลใน Field
  | จำนวน*รหัสสินค้า
  | 12. กดปุ่ม   เพิ่มรายการเบิก+
  | 13.   กรอกข้อมูลใน Field
  | จำนวนสั่งซื้อ มากกว่าจำนวนคงเหลือ
  |  
Actual   Result | กรอกจำนวนสั่งซื้อ มากกว่าจำนวนคงเหลือ ระบบแสดง Error Message "ไม่พบสินค้า
  |  
Expected   Result | กรอกจำนวนสั่งซื้อ   มากกว่าจำนวนคงเหลือ ต้องไม่สามารถกรอกเกิน ระบบแจ้งเตือน "สินค้าไม่เพียงพอ"
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54917469-76b25780-4f2e-11e9-9633-fe7f62669e56.png)
![image](https://user-images.githubusercontent.com/45878758/54917475-787c1b00-4f2e-11e9-8c42-faf6f9ed481b.png)
![image](https://user-images.githubusercontent.com/45878758/54917479-7a45de80-4f2e-11e9-834d-d4cd9429b06f.png)
![image](https://user-images.githubusercontent.com/45878758/54917483-7ca83880-4f2e-11e9-8146-4d961893d336.png)
![image](https://user-images.githubusercontent.com/45878758/54917491-7e71fc00-4f2e-11e9-87a4-6327e527dbbf.png)
![image](https://user-images.githubusercontent.com/45878758/54917497-82058300-4f2e-11e9-8736-b0aab26df924.png)
![image](https://user-images.githubusercontent.com/45878758/54917499-8467dd00-4f2e-11e9-9d36-f1832bed1afe.png)
![image](https://user-images.githubusercontent.com/45878758/54917502-8631a080-4f2e-11e9-9cf1-78fcfdf35d0e.png)
![image](https://user-images.githubusercontent.com/45878758/54917504-8893fa80-4f2e-11e9-8583-8f38bf19ab9b.png)

**Comment by Mickrepick** [comment]
แก้ไข : กรอกจำนวนสั่งซื้อ มากกว่าจำนวนคงเหลือ ไม่สามารถกรอกเกินได้ ระบบจะแจ้งเตือน "สินค้าไม่เพียงพอ"
