### ISSUE TITLE
edit outboundList, Info

### ISSUE THREAD

**Issue by logisprosolution** [logisprosolution/WMS#2]
edit popup select product (SKU)
adjust new UI list, info, popup
add permission on their pages

**Comment by Patthamaporn** [comment]
missing filed PayAgreementdate

**Comment by Patthamaporn** [comment]
งานที่ยังไม่เสร็จ
- แก้ไข Layout V.Mobile

- ปฏิทิน

**Comment by Patthamaporn** [comment]
..\WebWMS\WebWMS\assets\global\plugins\bootstrap\css\bootstrap.min.css

- {position:relative;min-height:1px; **padding-left:15px;padding-right:15px** }

**Comment by Patthamaporn** [comment]
wait for test
