### ISSUE TITLE
[รายการขาย][แก้ไข   หลังรายการ]กรอกจำนวนสั่งซื้อ มากกว่าจำนวนคงเหลือ ระบบแสดง Error Message "ไม่พบสินค้า"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#200]
Summary   Name | [รายการขาย][แก้ไข   หลังรายการ]กรอกจำนวนสั่งซื้อ มากกว่าจำนวนคงเหลือ ระบบแสดง Error Message "ไม่พบสินค้า"
-- | --
Defect No. |  200
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=11326&subDoc=7
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย รายการขายสินค้า
  | 3. เลือก   ขายสด
  | 4.   แสดงหน้าจอ รายการขาย
  | 5. กดปุ่ม   เพิ่มรายการขาย
  | 6.   กรอกข้อมูลใน Field ทั้งหมด
  | 7. กดปุ่ม   บันทึก
  | 8.   แสดงหน้าจอ รายการขาย
  | 9. กดปุ่ม   แก้ไข หลังรายการ
  | 10. กดปุ่ม   ค้นหาสินค้า
  | 11. แสดง   PopUp ค้นหาสินค้า
  | 12.   เลือกสินค้า
  | 13.   กรอกข้อมูลใน Field
  | จำนวนสั่งซื้อ น้อยกว่าจำนวนคงเหลือ
  | จำนวนสั่งซื้อ เท่ากับจำนวนคงเหลือ
  |  
Actual   Result | กรอกจำนวนสั่งซื้อ มากกว่าจำนวนคงเหลือ ระบบแสดง Error Message "ไม่พบสินค้า"
  |  
Expected   Result | กรอกจำนวนสั่งซื้อ   มากกว่าจำนวนคงเหลือ ต้องไม่สามารถกรอกเกิน "ระบบแจ้งเตือน สินค้าไม่เพียงพอ"
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54917586-b711d580-4f2e-11e9-95c1-4008ba73102b.png)
![image](https://user-images.githubusercontent.com/45878758/54917590-b9742f80-4f2e-11e9-9c27-66c79121a010.png)
![image](https://user-images.githubusercontent.com/45878758/54917593-bb3df300-4f2e-11e9-9dda-d95a9e9bda12.png)
![image](https://user-images.githubusercontent.com/45878758/54917600-bda04d00-4f2e-11e9-82be-0a9b913bdb4a.png)
![image](https://user-images.githubusercontent.com/45878758/54917605-bf6a1080-4f2e-11e9-823f-8027195b9155.png)
![image](https://user-images.githubusercontent.com/45878758/54917608-c1cc6a80-4f2e-11e9-9919-89421ab1bf0a.png)
![image](https://user-images.githubusercontent.com/45878758/54917613-c3962e00-4f2e-11e9-8604-b396d9aadaf2.png)
![image](https://user-images.githubusercontent.com/45878758/54917619-c5f88800-4f2e-11e9-8205-d3113a15f08b.png)
![image](https://user-images.githubusercontent.com/45878758/54917631-cbee6900-4f2e-11e9-9268-b2ec8fa70704.png)

**Comment by Mickrepick** [comment]
แก้ไข : กรอกจำนวนสั่งซื้อ มากกว่าจำนวนคงเหลือ ไม่สามารถกรอกเกินได้ ระบบจะแจ้งเตือน "สินค้าไม่เพียงพอ"
