### ISSUE TITLE
[รายการขาย][ดู   หลังรายการ] ทุก Field สารมารถกรอกข้อมูลได้ และ Field รวมยอด ไม่หักส่วนลดรายการ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#201]
Summary   Name | [รายการขาย][ดู หลังรายการ] ทุก Field สารมารถกรอกข้อมูลได้ และ Field รวมยอด ไม่หักส่วนลดรายการ
-- | --
Defect No. |  201
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=11326&view=1
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กดปุ่ม   เพิ่มรายการขาย
  | 7.   ระบุข้อมูลใน หน้าจอขายสินค้า ทั้งหมด
  | 8. กดปุ่ม   บันทึก
  | 9.   แสดงหน้าจอ รายการขาย
  | 10. กดปุ่ม   ดู หลังรายการ
  |  
Actual   Result | 1. ทุก Field   สารมารถกรอกข้อมูลได้
  | 2. Field รวมยอด   ไม่หักส่วนลดรายการ
Expected   Result | 1. ทุก Field   ต้องไม่สามารถกรอกข้อมูลได้
  | 2. Field   รวมยอด ต้องหักส่วนลดรายการ
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54917722-035d1580-4f2f-11e9-9e51-43df3dffd447.png)
![image](https://user-images.githubusercontent.com/45878758/54917726-03f5ac00-4f2f-11e9-9243-e8f3677402c1.png)
![image](https://user-images.githubusercontent.com/45878758/54917730-06f09c80-4f2f-11e9-8872-22cc177ca7b4.png)
![image](https://user-images.githubusercontent.com/45878758/54917733-0952f680-4f2f-11e9-89f9-b376e84b131d.png)
![image](https://user-images.githubusercontent.com/45878758/54917735-0bb55080-4f2f-11e9-9416-29545a0c89c4.png)
![image](https://user-images.githubusercontent.com/45878758/54917743-153eb880-4f2f-11e9-8c0a-14da38867d95.png)
![image](https://user-images.githubusercontent.com/45878758/54917755-18d23f80-4f2f-11e9-9340-0ec6a33286b9.png)

**Comment by Patthamaporn** [comment]
แก้ไข 1.สามารถหักราคาส่วนลดได้
2.รายการดูสามารถกรอกได้แต่บันทึกไม่ได้

**Comment by Vermouthz** [comment]
Retest-Failed

![image](https://user-images.githubusercontent.com/45878758/56473245-74420f80-6492-11e9-91d7-34984e15376a.png)

**Comment by Patthamaporn** [comment]
หักส่วนลดได้ในหน้าดูสินค้า
