### ISSUE TITLE
[รายการขาย][ดู   หลังรายการ]ไม่มี ปุ่มค้นหา

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#202]
Summary   Name | [รายการขาย][ดู   หลังรายการ]ไม่มี ปุ่มค้นหา สำหรับค้นหารายการสินค้า
-- | --
Defect No. |  202
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=11326&view=1
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กดปุ่ม   เพิ่มรายการขาย
  | 7.   ระบุข้อมูลใน หน้าจอขายสินค้า ทั้งหมด
  | 8. กดปุ่ม   บันทึก
  | 9.   แสดงหน้าจอ รายการขาย
  | 10. กดปุ่ม   ดู หลังรายการ
  | 11. กดปุ่ม   -------ค้นหา--
  |  
Actual   Result | ไม่มีปุ่ม ค้นหา สำหรับค้นหารายการสินค้า
  |  
Expected   Result | ต้องมีปุ่ม ค้นหา สำหรับค้นหารายการสินค้า
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54917843-49b27480-4f2f-11e9-9b45-5547bb0dd844.png)
![image](https://user-images.githubusercontent.com/45878758/54917847-4b7c3800-4f2f-11e9-8cf9-e88333276fec.png)
![image](https://user-images.githubusercontent.com/45878758/54917850-4dde9200-4f2f-11e9-88ba-0dbaebd537a3.png)
![image](https://user-images.githubusercontent.com/45878758/54917854-50d98280-4f2f-11e9-8b69-94c5b2185fd5.png)

![image](https://user-images.githubusercontent.com/45878758/54917862-56cf6380-4f2f-11e9-82ee-2de4158281c0.png)
![image](https://user-images.githubusercontent.com/45878758/54917871-5c2cae00-4f2f-11e9-8bab-cce771cd26ee.png)

**Comment by acryforever** [comment]
SaleInfo แก้ไข้แล้ว ขอปิด
