### ISSUE TITLE
Summary   Name | [เบิกสินค้า]_[เพิ่มใบเบิก]เพิ่มสินค้าไม่ได้   ระบบแสดง Error Message "Column    unitNameTH  does not belong to   table productSearch."

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#203]
Summary   Name | [เบิกสินค้า]_[เพิ่มใบเบิก]เพิ่มสินค้าไม่ได้   ระบบแสดง Error Message "Column    unitNameTH  does not belong to   table productSearch."
-- | --
Defect No. |  203
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/OutboundInfo.aspx?subDoc=14
  | http://nps001.homeip.net:8085/PopupGoodsSelectNoPrice.aspx
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย ใบหยิบเบิกสินค้า
  | 3.   เลือก ใบหยิบเบิกสินค้า
  | 4.   แสดงหน้าจอ รายการเบิกสินค้า
  | 5.   กดปุ่ม เพิ่มใบเบิก หลังรายการ
  | 6.   แสดงหน้าจอ เบิกสินค้า
  | 7.   กดปุ่ม ค้นหาสินค้า
  | 8.   แสดง PopUp ค้นหาสินค้า
  | 9.   เลือก สินค้า
  | 10.   ระบบแสดง Error Message
  | 11.   กรอกข้อมูลสินค้าใน field จำนวน*รหัสสินค้า
  | 12.   กดปุ่ม เพิ่มรายการเบิก+
  | 13.   ระบบแสดง Error Message
  |  
  |  
Actual Result | 1.   เมื่อเลือกสินค้าจากปุ่ม ค้นหาสินค้า ระบบแสดง Error Message "Column  unitNameTH    does not belong to table productSearch."
  | 2.   เมื่อเพิ่มสินค้าจาก field จำนวน*รหัสสินค้า ระบบแสดง Error Message   "Column  unitNameTH  does not belong to table   productSearch."
  |  
Expected   Result | 1.   สามารถเลือกสินค้าจาก PopUp ค้นหาสินค้า ได้
  | 2.   สามารถเพิ่มสินค้าจาก field จำนวน*รหัสสินค้า ได้
  |  

![image](https://user-images.githubusercontent.com/45878758/54929301-ea149300-4f47-11e9-81b4-fd98cba627b0.png)
![image](https://user-images.githubusercontent.com/45878758/54929311-ed0f8380-4f47-11e9-88a1-b9f2632c6f0b.png)
![image](https://user-images.githubusercontent.com/45878758/54929316-f00a7400-4f47-11e9-89ad-06da7e6cc1ff.png)
![image](https://user-images.githubusercontent.com/45878758/54929327-f4369180-4f47-11e9-9822-1ed88e5242eb.png)

**Comment by acryforever** [comment]
แก้ไข้ข้อมูลจากเมื่อ วานในอิชูอื่น ทำTable ID ให้ตรงกับ BASE และเพิ่มใน Filed SQL ให้สามารถ JOIN  ข้อมูลจาก Admin สมหญิงได้
