### ISSUE TITLE
[เบิกสินค้า]_[เพิ่มใบเบิก]กดปุ่มนำเข้าจาก   ระบบแสดง Error Message "Column    GoodsNameTH  does not belong to   table SELECT_DETAIL."

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#204]
Summary   Name | [เบิกสินค้า]_[เพิ่มใบเบิก]กดปุ่มนำเข้าจาก   ระบบแสดง Error Message "Column    GoodsNameTH  does not belong to   table SELECT_DETAIL."
-- | --
Defect No. |  204
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/OutboundInfo.aspx?subDoc=14
  | http://nps001.homeip.net:8085/PopupDocSelect.aspx?dataId=2
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย ใบหยิบเบิกสินค้า
  | 3.   เลือก ใบหยิบเบิกสินค้า
  | 4.   แสดงหน้าจอ รายการเบิกสินค้า
  | 5.   กดปุ่ม เพิ่มใบเบิก หลังรายการ
  | 6.   แสดงหน้าจอ เบิกสินค้า
  | 7.   กดปุ่ม นำเข้าจาก...
  | 8.   แสดง PopUp ค้นหาเอกสาร
  | 9.   เลือก เอกสาร "APS4003 ใบจองทั่วไป (001)สมหญิง ลูกค้าทั่วไป 0.00"
  |  
  |  
  |  
Actual Result | 1.   เมื่อเลือกเอกสารจากปุ่ม นำเข้าจาก... ระบบแสดง Error Message "Column  GoodsNameTH    does not belong to table SELECT_DETAIL."
  | 2.   Field รายละเอียดอ้างอิง แสดง "APS4003 ใบจองทั่วไป (001)สมหญิง   ลูกค้าทั่วไป 0.00" ที่เลือก แต่ไม่ดึงสินค้ามาแสดงใน Column แสดงผล
  |  
Expected   Result | สามารถดึงข้อมูลมาแสดงใน   Column แสดงผลได้ เมื่อเลือกเอกสารจากปุ่ม นำเข้าจาก...
  

![image](https://user-images.githubusercontent.com/45878758/54929706-948cb600-4f48-11e9-9e83-5120da816731.png)
![image](https://user-images.githubusercontent.com/45878758/54929708-96ef1000-4f48-11e9-97b2-35a26f262340.png)
![image](https://user-images.githubusercontent.com/45878758/54929716-99ea0080-4f48-11e9-8910-c934ef62cd6f.png)
![image](https://user-images.githubusercontent.com/45878758/54929720-9c4c5a80-4f48-11e9-8197-eec89e300713.png)
![image](https://user-images.githubusercontent.com/45878758/54929737-a1110e80-4f48-11e9-9409-4800948bf875.png)

**Comment by acryforever** [comment]
แก้ไข                         
                        goodsName = ConvertHelper.InitialValueDB(dr, "GoodsNameTH"),
                        unitName = ConvertHelper.InitialValueDB(dr, "unitNameTH"),
มีการเปลี่ยนใน BASE เรียกใช้ 
                        goodsName = ConvertHelper.InitialValueDB(dr, "GoodsName"),
                        unitName = ConvertHelper.InitialValueDB(dr, "unitName"),
