### ISSUE TITLE
รายการเบิกสินค้า_Column ชื่อบริษัทต้องเป็นชื่อลูกค้า

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#205]
Summary   Name | รายการเบิกสินค้า_Column   ชื่อบริษัทต้องเป็นชื่อลูกค้า
-- | --
Defect No. |  205
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/OutboundList.aspx?subDoc=14&menuID=2091
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย ใบหยิบเบิกสินค้า
  | 3. เลือก ใบหยิบเบิกสินค้า
  | 4.   แสดงหน้าจอ รายการเบิกสินค้า
  |  
Actual   Result | รายการเบิกสินค้า_Column   แสดง"ชื่อบริษัท"
  |  
  |  
Expected   Result | รายการเบิกสินค้า_Column   "ชื่อบริษัท" ต้องแสดงเป็น "ชื่อลูกค้า"
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/54932036-b12aed00-4f4c-11e9-8a38-10fabdd6551b.png)

**Comment by Mickrepick** [comment]
แก้ไข : Column "ชื่อบริษัท" เป็น "ชื่อลูกค้า"
