### ISSUE TITLE
เบิกสินค้า_ดู หลังรายการ_ระบบไม่มี_field_ค้นหา_เพื่อค้นหารายการสินค้นที่ต้องการ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#206]
Summary   Name | เบิกสินค้า_ดู   หลังรายการ_ระบบไม่มี_field_ค้นหา_เพื่อค้นหารายการสินค้นที่ต้องการ
-- | --
Defect No. |  206
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/OutboundInfo.aspx?dataId=11246&view=1
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย ใบหยิบเบิกสินค้า
  | 3. เลือก   ใบหยิบเบิกสินค้า
  | 4. แสดงหน้าจอ   รายการเบิกสินค้า
  | 5. กด ดู หลังรายการ
  | 6. แสดงหน้าจอ   เบิกสินค้า
  |  
  |  
Actual   Result | เบิกสินค้า_ดู   หลังรายการ_ระบบไม่มี_field_ค้นหา_เพื่อค้นหารายการสินค้นที่ต้องการ
  |  
  |  
Expected   Result | ต้องมี field   ค้นหาเพื่อค้นหารายการสินค้นที่ต้องการ
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/54933257-e1738b00-4f4e-11e9-828f-dad70ce02950.png)
![image](https://user-images.githubusercontent.com/45878758/54933260-e46e7b80-4f4e-11e9-8b6f-3e7c34a6d4fa.png)

**Comment by acryforever** [comment]
แก้ไข ตามอิชู 208
