### ISSUE TITLE
[รายการขาย]Column   ชื่อบริษัท ต้องแสดงชื่อลูกค้า

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#207]
Summary   Name | [รายการขาย]Column   ชื่อบริษัท ต้องแสดงชื่อลูกค้า
-- | --
Defect No. |  207
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleList.aspx?subDoc=7&menuID=2086
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กดปุ่ม   ดู หลังรายการ
  | 7.   แสดงหน้าจอ ขายสินค้า
  |  
Actual   Result | 1. Column แสดงชื่อบริษัท
  |  
Expected   Result | 1. Column ชื่อบริษัท   ต้องเป็น ชื่อลูกค้า
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54935251-7cba2f80-4f52-11e9-9f41-c92fca267f3a.png)

**Comment by Mickrepick** [comment]
แก้ไข : Column ชื่อบริษัท เป็น ชื่อลูกค้า
