### ISSUE TITLE
เบิกสินค้า_แก้ไข หลังรายการ_ระบบไม่มี_field_ค้นหา_เพื่อค้นหารายการสินค้นที่ต้องการ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#208]
Summary   Name | เบิกสินค้า_แก้ไข   หลังรายการ_ระบบไม่มี_field_ค้นหา_เพื่อค้นหารายการสินค้นที่ต้องการ
-- | --
Defect No. |  208
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/OutboundInfo.aspx?dataId=11246&subDoc=14
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย ใบหยิบเบิกสินค้า
  | 3. เลือก ใบหยิบเบิกสินค้า
  | 4.   แสดงหน้าจอ รายการเบิกสินค้า
  | 5.   กด แก้ไข หลังรายการ
  | 6.   แสดงหน้าจอ เบิกสินค้า
  |  
  |  
Actual Result | เบิกสินค้า_แก้ไข   หลังรายการ_ระบบไม่มี_field_ค้นหา_เพื่อค้นหารายการสินค้นที่ต้องการ
  |  
  |  
Expected Result | ต้องมี   field ค้นหาเพื่อค้นหารายการสินค้นที่ต้องการ
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/54935155-4ed4eb00-4f52-11e9-9027-24b5bafabdf9.png)
![image](https://user-images.githubusercontent.com/45878758/54935172-54cacc00-4f52-11e9-8041-f76bb0e074fa.png)

**Comment by acryforever** [comment]
Close funtion "role.Menu.Search" ขอปิด งาน
