### ISSUE TITLE
[รายการขาย][เพิ่มรายการขาย]Field   วันที่ใบกำกับ ต้องเป็น วันที่ใบกำกับภาษี

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#209]
Summary   Name | [รายการขาย][เพิ่มรายการขาย]Field   วันที่ใบกำกับ ต้องเป็น วันที่ใบกำกับภาษี
-- | --
Defect No. |  209
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กด   เพิ่มรายการขาย
  | 7.   แสดงหน้าจอ ขายสินค้า
  |  
Actual   Result | Field   วันที่ใบกำกับ
  |  
Expected   Result | Field   วันที่ใบกำกับ ต้องเป็น วันที่ใบกำกับภาษี
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54935318-a83d1a00-4f52-11e9-934e-f82e20c36bdb.png)
![image](https://user-images.githubusercontent.com/45878758/54935338-b0955500-4f52-11e9-9dc1-cfb49687c62e.png)

**Comment by Mickrepick** [comment]
แก้ไข : จาก Field "วันที่ใบกำกับ" เป็น Field "วันที่ใบกำกับภาษี" ครับ
