### ISSUE TITLE
[รายการขาย][แก้ไข   หลังรายการ]Field วันที่ใบกำกับ ต้องเป็น วันที่ใบกำกับภาษี

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#210]
Summary   Name | [รายการขาย][แก้ไข   หลังรายการ]Field วันที่ใบกำกับ ต้องเป็น วันที่ใบกำกับภาษี
-- | --
Defect No. |  210
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=11253&subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กด   แก้ไข หลังรายการ
  | 7.   แสดงหน้าจอ ขายสินค้า
  |  
Actual   Result | Field   วันที่ใบกำกับ
  |  
Expected   Result | Field   วันที่ใบกำกับ ต้องเป็น วันที่ใบกำกับภาษี
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54935437-e33f4d80-4f52-11e9-8e73-fb707b5ae129.png)
![image](https://user-images.githubusercontent.com/45878758/54935445-ea665b80-4f52-11e9-9fdd-4bbe1dda7224.png)

**Comment by Mickrepick** [comment]
แก้ไข : จาก Field "วันที่ใบกำกับ" เป็น Field "วันที่ใบกำกับภาษี" ครับ
