### ISSUE TITLE
 [รายการขาย][ดู   หลังรายการ]Field วันที่ใบกำกับ ต้องเป็น วันที่ใบกำกับภาษี

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#211]
Summary   Name | [รายการขาย][ดู   หลังรายการ]Field วันที่ใบกำกับ ต้องเป็น วันที่ใบกำกับภาษี
-- | --
Defect No. |  211
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=11253&view=1
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กด ดู   หลังรายการ
  | 7.   แสดงหน้าจอ ขายสินค้า
  |  
Actual   Result | Field   วันที่ใบกำกับ
  |  
Expected   Result | Field   วันที่ใบกำกับ ต้องเป็น วันที่ใบกำกับภาษี
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54935536-15e94600-4f53-11e9-856f-b8be4feba342.png)
![image](https://user-images.githubusercontent.com/45878758/54935559-200b4480-4f53-11e9-9cda-0d0d97803f0f.png)

**Comment by Mickrepick** [comment]
แก้ไข : จาก Field "วันที่ใบกำกับ" เป็น Field "วันที่ใบกำกับภาษี" ครับ
