### ISSUE TITLE
[รายการขาย][อนุมัติ   หลังรายการ]Field วันที่ใบกำกับ ต้องเป็น วันที่ใบกำกับภาษี

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#212]
Summary   Name | [รายการขาย][อนุมัติ   หลังรายการ]Field วันที่ใบกำกับ ต้องเป็น วันที่ใบกำกับภาษี
-- | --
Defect No. |  212
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=11253&subDoc=7&approve=1
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กด   อนุมัติ หลังรายการ
  | 7.   แสดงหน้าจอ ขายสินค้า
  |  
Actual   Result | Field   วันที่ใบกำกับ
  |  
Expected   Result | Field   วันที่ใบกำกับ ต้องเป็น วันที่ใบกำกับภาษี
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/54935662-53e66a00-4f53-11e9-8d22-68418644e21b.png)
![image](https://user-images.githubusercontent.com/45878758/54935681-5d6fd200-4f53-11e9-8cc6-298fe2eb908c.png)

**Comment by Mickrepick** [comment]
แก้ไข : จาก Field "วันที่ใบกำกับ" เป็น Field "วันที่ใบกำกับภาษี" ครับ
