### ISSUE TITLE
เบิกสินค้า_อนุมัติ หลังรายการ_ระบบไม่มี_field_ค้นหา_เพื่อค้นหารายการสินค้นที่ต้องการ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#213]
Summary   Name | เบิกสินค้า_อนุมัติ   หลังรายการ_ระบบไม่มี_field_ค้นหา_เพื่อค้นหารายการสินค้นที่ต้องการ
-- | --
Defect No. |  213
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/OutboundInfo.aspx?dataId=11246&subDoc=14&approve=1
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย ใบหยิบเบิกสินค้า
  | 3. เลือก ใบหยิบเบิกสินค้า
  | 4.   แสดงหน้าจอ รายการเบิกสินค้า
  | 5.   กด อนุมัติ หลังรายการ
  | 6.   แสดงหน้าจอ เบิกสินค้า
  |  
  |  
Actual Result | เบิกสินค้า_อนุมัติ   หลังรายการ_ระบบไม่มี_field_ค้นหา_เพื่อค้นหารายการสินค้นที่ต้องการ
  |  
  |  
Expected Result | ต้องมี   field ค้นหาเพื่อค้นหารายการสินค้นที่ต้องการ
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/54937275-aecd9080-4f56-11e9-80f9-b506a1f82cdc.png)
![image](https://user-images.githubusercontent.com/45878758/54937292-b5f49e80-4f56-11e9-8888-d62cf9ea1327.png)

**Comment by acryforever** [comment]
แก้ไข ตามอิชู 208
