### ISSUE TITLE
[รายการตรวจสินค้าออก]   field วันที่ และ field ถึง กรอกวันที่เกิน 10 หลักได้ "25/03/256212"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#214]
Summary   Name | [รายการตรวจสินค้าออก]   field วันที่ และ field ถึง กรอกวันที่เกิน 10 หลักได้ "25/03/256212"
-- | --
Defect No. |  214
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/CheckerOutList.aspx?subDoc=22&menuID=2078
  |  
Step | 1.   สร้างรายการขายสินค้า จากเมนูรายการเบิกสินค้า
  | 2.   กด อนุมัติ สำเร็จ
  | 3.   เลือกเมนู งานประจำวัน
  | 4.   เลือกเมนูย่อย ตรวจสอบสินค้าออก
  | 5.   เลือก ตรวจสอบสินค้าออก
  | 6.   แสดงหน้าจอ รายการตรวจสินค้าออก
  | 7.   กรอกวันที่ใน field
  | -   วันที่ "25/03/256212"
  | -   ถึง "25/03/256212"
  |  
  |  
  |  
  |  
  |  
Actual Result | field   วันที่ และ field ถึง กรอกวันที่เกิน 10 หลักได้ "25/03/256212"
  |  
  |  
  |  
Expected   Result | field   วันที่ และ field ถึง ต้องกรอกวันที่ 10 หลัก "25/03/2562"
  |  
  |  
Tester | Phatcharat.Sun
  |  

![image](https://user-images.githubusercontent.com/45878758/54939114-526c7000-4f5a-11e9-8d6c-0c811f2f76e1.png)

**Comment by Mickrepick** [comment]
แก้ไข : Field วันที่, ถึง จะสามารถกรอกได้ 10 ตัวอักษร
