### ISSUE TITLE
เบิกสินค้า_นำเข้าจาก_สะกด"สถานะ"ผิด

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#215]
Summary   Name | เบิกสินค้า_นำเข้าจาก_สะกด"สถานะ"ผิด
-- | --
Defect No. |  215
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/PopupDocSelect.aspx?dataId=2
Step | 1. เลือกเมนู   งานประจำวัน
  | 2.   เลือกเมนูย่อย ใบหยิบเบิกสินค้า
  | 3. เลือก ใบหยิบเบิกสินค้า
  | 4.   แสดงหน้าจอ รายการเบิกสินค้า
  | 5.   กดปุ่ม เพิ่มใบเบิก
  | 6.   แสดงหน้าจอ เบิกสินค้า
  | 7.   กดปุ่ม นำเข้าจาก..
  | 8.   แสดง PopUp ค้นหาเอกสาร
  |  
Actual   Result | เบิกสินค้า_นำเข้าจาก_สะกด"สถานะ"ผิด
  |  
  |  
Expected   Result | "สถาณะ"   ต้องสะกดว่า "สถานะ"
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/54939721-da9f4500-4f5b-11e9-980f-c3602dc4edc4.png)
![image](https://user-images.githubusercontent.com/45878758/54939724-dd9a3580-4f5b-11e9-80ab-2bac2b17d87a.png)
![image](https://user-images.githubusercontent.com/45878758/54939727-dffc8f80-4f5b-11e9-82ef-9b92494861ea.png)

**Comment by Mickrepick** [comment]
แก้ไข : จาก "สถาณะ" เป็น "สถานะ" แล้วครับ
