### ISSUE TITLE
ค้นหาสินค้า_เมื่อกดปุ่ม Enter ระบบไม่ค้นหาให้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#218]
Summary   Name | ค้นหาสินค้า_เมื่อกดปุ่ม   Enter ระบบไม่ค้นหาให้
-- | --
Defect No. |  218
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/PopupGoodsSelectNoPrice.aspx
Step | 1. เลือกเมนู   งานประจำวัน
  | 2.   เลือกเมนูย่อย ใบหยิบเบิกสินค้า
  | 3. เลือก ใบหยิบเบิกสินค้า
  | 4.   แสดงหน้าจอ รายการเบิกสินค้า
  | 5.   กดุปุ่ม เพิ่มใบเบิก
  | 6.   แสดงหน้าจอ เบิกสินค้า
  | 7.   กด ค้นหาสินค้า
  | 8.   แสดง PopUp ค้นหาสินค้า
  | 9.   กรอกข้อมูลใน Field รหัส/ชื่อ
  | 10.   กดปุ่ม Enter บนคีบอร์ด
  |  
  |  
Actual Result | เมื่อกดปุ่ม   Enter ระบบไม่ค้นหาให้
  |  
  |  
Expected Result | เมื่อกดปุ่ม   Enter ระบบต้องค้นหาข้อมูลให้
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/55020128-cb39fd80-5028-11e9-8c4d-03d5783b34bf.png)

**Comment by Patthamaporn** [comment]
แก้ไข เมื่อกรอกข้อมูลในช่อง รหัส/ชื่อ แล้วกด enter จะสามารถค้นหาสินค้าได้
