### ISSUE TITLE
[รายการขายสินค้า][เพิ่มรายการขาย]   Field ส่วนเพิ่ม กรอกได้มากกว่า 16 ตัวอักษร

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#219]
Summary   Name | [รายการขายสินค้า][เพิ่มรายการขาย]   Field ส่วนเพิ่ม กรอกได้มากกว่า 16 ตัวอักษร
-- | --
Defect No. |  219
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขายสินค้า
  | 6. กดุปุ่ม   เพิ่มรายการขาย
  | 7.แสดงหน้าจอ   ขายสินค้า
  | 8.   กรอกข้อมูลใน field
  | ส่วนเพิ่ม
  |  
Actual   Result | Field ส่วนเพิ่ม กรอกได้มากกว่า 16 ตัวอักษร
  |  
Expected   Result | Field ส่วนเพิ่ม ต้องกรอกได้ไม่เกิน 16   ตัวอักษร
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/55020818-3cc67b80-502a-11e9-8bca-58a5b5d6411f.png)
![image](https://user-images.githubusercontent.com/45878758/55020841-4354f300-502a-11e9-9fdd-06156896670c.png)
![image](https://user-images.githubusercontent.com/45878758/55020846-45b74d00-502a-11e9-872d-27c43b556dfe.png)
![image](https://user-images.githubusercontent.com/45878758/55020858-4bad2e00-502a-11e9-8b48-cd045de9e23d.png)

**Comment by Mickrepick** [comment]
แก้ไข : Field ส่วนเพิ่ม จะกรอกได้ไม่เกิน 16 ตัวอักษร
