### ISSUE TITLE
[รายการขายสินค้า][เพิ่มรายการขาย]   Field ส่วนลด กรอกได้มากกว่า 16 ตัวอักษร

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#220]
Summary   Name | [รายการขายสินค้า][เพิ่มรายการขาย]   Field ส่วนลด กรอกได้มากกว่า 16 ตัวอักษร
-- | --
Defect No. |  220
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขายสินค้า
  | 6. กดุปุ่ม   เพิ่มรายการขาย
  | 7.แสดงหน้าจอ   ขายสินค้า
  | 8.   กรอกข้อมูลใน field
  | ส่วนลด
  |  
Actual   Result | Field ส่วนลด กรอกได้มากกว่า 16 ตัวอักษร
  |  
Expected   Result | Field ส่วนลด ต้องกรอกได้ไม่เกิน 16 ตัวอักษร
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/55020974-89aa5200-502a-11e9-99b6-d8bf3f2871af.png)
![image](https://user-images.githubusercontent.com/45878758/55020990-90d16000-502a-11e9-861f-839a1f571f47.png)
![image](https://user-images.githubusercontent.com/45878758/55021000-97f86e00-502a-11e9-9e0c-b4bb4745a6e6.png)
![image](https://user-images.githubusercontent.com/45878758/55021009-9c248b80-502a-11e9-9a10-f33a6c1502d7.png)

**Comment by Mickrepick** [comment]
แก้ไข : Field ส่วนลด จะกรอกได้ไม่เกิน 16 ตัวอักษร
