### ISSUE TITLE
[รายการขายสินค้า][เพิ่มรายการขาย]เมื่อเลื่อนเมาส์ไปชี้ที่   Field ส่วนเพิ่ม แสดงข้อความ “ความยาวไม่เกิน 30 ตัวอักษร”

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#221]
Summary   Name | [รายการขายสินค้า][เพิ่มรายการขาย]เมื่อเลื่อนเมาส์ไปชี้ที่   Field ส่วนเพิ่ม แสดงข้อความ “ความยาวไม่เกิน 30 ตัวอักษร”
-- | --
Defect No. |  221
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขายสินค้า
  | 6. กดุปุ่ม   เพิ่มรายการขาย
  | 7.แสดงหน้าจอ   ขายสินค้า
  | 8.   กรอกข้อมูลใน field
  | ส่วนเพิ่ม
  |  
Actual   Result | เมื่อเลื่อนเมาส์ไปชี้ที่ Field ส่วนเพิ่ม แสดงข้อความ “ความยาวไม่เกิน 30   ตัวอักษร”
  |  
Expected   Result | เมื่อเลื่อนเมาส์ไปชี้ที่ Field ส่วนเพิ่ม ต้องแสดงข้อความ “ความยาวไม่เกิน 16   ตัวอักษร”
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/55021123-d2faa180-502a-11e9-9f33-90231f39ec16.png)
![image](https://user-images.githubusercontent.com/45878758/55021138-d7bf5580-502a-11e9-8a3c-32f8366e71fd.png)
![image](https://user-images.githubusercontent.com/45878758/55021172-e279ea80-502a-11e9-8eb2-8c207c406152.png)

**Comment by Mickrepick** [comment]
แก้ไข : เมื่อเลื่อนเมาส์ไปชี้ที่ Field ส่วนเพิ่ม จะแสดงข้อความ “ความยาวไม่เกิน 16 ตัวอักษร”
