### ISSUE TITLE
[รายการขายสินค้า][เพิ่มรายการขาย]เมื่อเลื่อนเมาส์ไปชี้ที่   Field ส่วนลด แสดงข้อความ “ความยาวไม่เกิน 30 ตัวอักษร” -

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#222]
Summary   Name | [รายการขายสินค้า][เพิ่มรายการขาย]เมื่อเลื่อนเมาส์ไปชี้ที่   Field ส่วนลด แสดงข้อความ “ความยาวไม่เกิน 30 ตัวอักษร”
-- | --
Defect No. |  222
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขายสินค้า
  | 6. กดุปุ่ม   เพิ่มรายการขาย
  | 7.แสดงหน้าจอ   ขายสินค้า
  | 8.   กรอกข้อมูลใน field
  | ส่วนลด
  |  
Actual   Result | เมื่อเลื่อนเมาส์ไปชี้ที่ Field ส่วนลด แสดงข้อความ “ความยาวไม่เกิน 30   ตัวอักษร”
  |  
Expected   Result | เมื่อเลื่อนเมาส์ไปชี้ที่ Field ส่วนลด ต้องแสดงข้อความ “ความยาวไม่เกิน 16   ตัวอักษร”
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/55021335-266cef80-502b-11e9-9a82-f14d3b3e0d0c.png)
![image](https://user-images.githubusercontent.com/45878758/55021351-2b31a380-502b-11e9-9c6e-d571f3ea1b9a.png)
![image](https://user-images.githubusercontent.com/45878758/55021364-2ff65780-502b-11e9-877b-4581345f2b1f.png)

**Comment by Mickrepick** [comment]
แก้ไข : เมื่อเลื่อนเมาส์ไปชี้ที่ Field ส่วนลด แสดงข้อความ “ความยาวไม่เกิน 16 ตัวอักษร”
