### ISSUE TITLE
[รายการขายสินค้า][เพิ่มรายการขาย]ช่องแสดงตัวเลข   หลังภาษีมูลค่าเพิ่ม สามารถกรอกข้อมูลได้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#223]
Summary   Name | [รายการขายสินค้า][เพิ่มรายการขาย]ช่องแสดงตัวเลข   หลังภาษีมูลค่าเพิ่ม สามารถกรอกข้อมูลได้
-- | --
Defect No. |  223
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขายสินค้า
  | 6. กดุปุ่ม   เพิ่มรายการขาย
  | 7.แสดงหน้าจอ   ขายสินค้า
  | 8.   เลือกข้อมูลใน field
  | ภาษีมูลค่าเพิ่ม
  | 9. ตรวจสอบ   ช่องแสดงตัวเลข หลังภาษีมูลค่าเพิ่ม
  |  
Actual   Result | ช่องแสดงตัวเลข   หลังภาษีมูลค่าเพิ่ม สามารถกรอกข้อมูลได้
  |  
Expected   Result | ช่องแสดงตัวเลข   หลังภาษีมูลค่าเพิ่ม ต้องไม่สามารถกรอกข้อมูลได้
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/55021466-5caa6f00-502b-11e9-9f82-ae297b3e4ea9.png)
![image](https://user-images.githubusercontent.com/45878758/55021473-5e743280-502b-11e9-8700-41bffbf4f622.png)
![image](https://user-images.githubusercontent.com/45878758/55021485-63d17d00-502b-11e9-9017-60af874fec4a.png)
![image](https://user-images.githubusercontent.com/45878758/55021499-69c75e00-502b-11e9-88b9-0e01e442018b.png)

**Comment by Mickrepick** [comment]
แก้ไข : ช่องแสดงตัวเลข หลังภาษีมูลค่าเพิ่ม เปลี่ยนเป็น Field ปิดครับ
