### ISSUE TITLE
[รายการขายสินค้า][แก้ไข   หลังรายการ] Field ส่วนลด กรอกได้มากกว่า 16 ตัวอักษร

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#224]
Summary   Name | [รายการขายสินค้า][แก้ไข   หลังรายการ] Field ส่วนลด กรอกได้มากกว่า 16 ตัวอักษร
-- | --
Defect No. |  224
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=11253&subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขายสินค้า
  | 6. กดุปุ่ม   แก้ไข หลังรายการ
  | 7.แสดงหน้าจอ   ขายสินค้า
  | 8.   กรอกข้อมูลใน field
  | ส่วนลด
  |  
Actual   Result | Field ส่วนลด กรอกได้มากกว่า 16 ตัวอักษร
  |  
Expected   Result | Field ส่วนลด ต้องกรอกได้ไม่เกิน 16 ตัวอักษร
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/55021576-97140c00-502b-11e9-9d98-825256d9b931.png)
![image](https://user-images.githubusercontent.com/45878758/55021590-9b402980-502b-11e9-8d43-1572c27e82f8.png)
![image](https://user-images.githubusercontent.com/45878758/55021597-9e3b1a00-502b-11e9-8060-b4346a412b2f.png)
![image](https://user-images.githubusercontent.com/45878758/55021615-a4c99180-502b-11e9-877f-49c73f9d8b27.png)

**Comment by Mickrepick** [comment]
แก้ไข : Field ส่วนลด กรอกได้ไม่เกิน 16 ตัวอักษร
