### ISSUE TITLE
[รายการขายสินค้า][แก้ไข   หลังรายการ]field เลือกลูกค้า กรอกข้อมูลได้ไม่จำกัด

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#225]
Summary   Name | [รายการขายสินค้า][แก้ไข   หลังรายการ]field เลือกลูกค้า กรอกข้อมูลได้ไม่จำกัด
-- | --
Defect No. |  225
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=11253&subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขายสินค้า
  | 6. กดุปุ่ม   แก้ไข หลังรายการ
  | 7.   แสดงหน้าจอ ขายสินค้า
  | 8.   กรอกข้อมูลใน field
  | เลือกลูกค้า
  |  
Actual   Result | field เลือกลูกค้า   กรอกข้อมูลได้ไม่จำกัด
  |  
Expected   Result | field เลือกลูกค้า   กำหนดจำนวนตัวอักษรให้ด้วยค่ะ
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/55021709-d6425d00-502b-11e9-89ec-704fcfb2f682.png)
![image](https://user-images.githubusercontent.com/45878758/55021723-db9fa780-502b-11e9-850b-d49b7c002864.png)

**Comment by Mickrepick** [comment]
แก้ไข : เมื่อคลิกที่ Field เลือกลูกค้า จะเป็น Popup ขึ้นมาให้เลือกลูกค้า และกำหนดจำนวนตัวอักษร 100 ตัวอักษร
