### ISSUE TITLE
[รายการขายสินค้า][แก้ไข   หลังรายการ]field ราคาสั่ง กรอกได้มากกว่า 5 ตัวอักษร

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#226]
Summary   Name | [รายการขายสินค้า][แก้ไข   หลังรายการ]field ราคาสั่ง กรอกได้มากกว่า 5 ตัวอักษร
-- | --
Defect No. |  226
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/PurchaseInfo.aspx?dataId=11744&subDoc=18
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขายสินค้า
  | 6. กดุปุ่ม   แก้ไข หลังรายการ
  | 7.   แสดงหน้าจอ ขายสินค้า
  | 8.   กรอกข้อมูลใน field
  | ราคาสั่ง
  |  
Actual   Result | 1. field ราคาสั่ง   กรอกได้มากกว่า 5 ตัวอักษร
  |  
Expected   Result | 1. field ราคาสั่ง   ต้องกรอกได้ไม่เกิน 5 ตัวอักษร
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/55021849-0c7fdc80-502c-11e9-8eef-3e26f594b28f.png)
![image](https://user-images.githubusercontent.com/45878758/55021866-11dd2700-502c-11e9-9a07-3b74eca35b2f.png)

**Comment by Mickrepick** [comment]
แก้ไข : Field ราคาสั่ง กรอกได้ไม่เกิน 5 ตัวอักษร ครับ

**Comment by Mickrepick** [comment]
ใส่ link ผิดครับ  ต้องเป็นหน้า SaleInfo ครับ
