### ISSUE TITLE
[รายการขายสินค้า][แก้ไข   หลังรายการ]field ส่วนเพิ่ม กรอกได้มากกว่า 16 ตัวอักษร

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#227]
Summary   Name | [รายการขายสินค้า][แก้ไข   หลังรายการ]field ส่วนเพิ่ม กรอกได้มากกว่า 5 ตัวอักษร
-- | --
Defect No. |  227
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/PurchaseInfo.aspx?dataId=11744&subDoc=18
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขายสินค้า
  | 6. กดุปุ่ม   แก้ไข หลังรายการ
  | 7.   แสดงหน้าจอ ขายสินค้า
  | 8.   กรอกข้อมูลใน field
  | ส่วนเพิ่ม
  |  
Actual   Result | 1. field ส่วนเพิ่ม   กรอกได้มากกว่า 16 ตัวอักษร
  |  
Expected   Result | 1. field ส่วนเพิ่ม   ต้องกรอกได้ไม่เกิน 16 ตัวอักษร
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/55021986-451fb600-502c-11e9-8cd9-b0e50e495a5c.png)
![image](https://user-images.githubusercontent.com/45878758/55022003-494bd380-502c-11e9-86a2-545de98a1d46.png)
![image](https://user-images.githubusercontent.com/45878758/55022013-4bae2d80-502c-11e9-983b-5dccdb358181.png)
![image](https://user-images.githubusercontent.com/45878758/55022023-5072e180-502c-11e9-9d60-5119e9759c5d.png)

**Comment by Mickrepick** [comment]
แก้ไข : Field ส่วนเพิ่ม กรอกได้ไม่เกิน 16 ตัวอักษร ครับ

**Comment by Mickrepick** [comment]
ใส่ link ผิดครับ ต้องเป็นหน้า SaleInfo ครับ
