### ISSUE TITLE
[รายการขายสินค้า][แก้ไข   หลังรายการ]เมื่อเลื่อนเมาส์ไปชี้ที่ Field ส่วนเพิ่ม แสดงข้อความ   “ความยาวไม่เกิน 30 ตัวอักษร”

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#229]
Summary   Name | [รายการขายสินค้า][แก้ไข   หลังรายการ]เมื่อเลื่อนเมาส์ไปชี้ที่ Field ส่วนเพิ่ม แสดงข้อความ   “ความยาวไม่เกิน 30 ตัวอักษร”
-- | --
Defect No. |  229
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=11253&subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขายสินค้า
  | 6. กดุปุ่ม   แก้ไข หลังรายการ
  | 7.แสดงหน้าจอ   ขายสินค้า
  | 8.   กรอกข้อมูลใน field
  | ส่วนเพิ่ม
  |  
Actual   Result | 1.   เมื่อเลื่อนเมาส์ไปชี้ที่ Field ส่วนเพิ่ม แสดงข้อความ “ความยาวไม่เกิน 30   ตัวอักษร”
  |  
Expected   Result | 1.   เมื่อเลื่อนเมาส์ไปชี้ที่ Field ส่วนเพิ่ม ต้องแสดงข้อความ “ความยาวไม่เกิน 16   ตัวอักษร”
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/55022223-b6f7ff80-502c-11e9-8b91-53e4434dc48b.png)
![image](https://user-images.githubusercontent.com/45878758/55022233-bbbcb380-502c-11e9-8c22-e59942d7bc07.png)
![image](https://user-images.githubusercontent.com/45878758/55022247-c119fe00-502c-11e9-970c-9106a3fe4c08.png)

**Comment by Mickrepick** [comment]
แก้ไข : เมื่อเลื่อนเมาส์ไปชี้ที่ Field ส่วนเพิ่ม จะแสดงข้อความ “ความยาวไม่เกิน 16 ตัวอักษร”
