### ISSUE TITLE
[รายการขายสินค้า][แก้ไข   หลังรายการ]เมื่อเลื่อนเมาส์ไปชี้ที่ Field ส่วนลด แสดงข้อความ “ความยาวไม่เกิน   30 ตัวอักษร”

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#230]
Summary   Name |[รายการขายสินค้า][แก้ไข   หลังรายการ]เมื่อเลื่อนเมาส์ไปชี้ที่ Field ส่วนลด แสดงข้อความ “ความยาวไม่เกิน   30 ตัวอักษร”
-- | -- 
Defect No. |  230
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=11253&subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขายสินค้า
  | 6. กดุปุ่ม   แก้ไข หลังรายการ
  | 7.แสดงหน้าจอ   ขายสินค้า
  | 8.   กรอกข้อมูลใน field
  | ส่วนลด
  |  
Actual   Result | 1.   เมื่อเลื่อนเมาส์ไปชี้ที่ Field ส่วนลด แสดงข้อความ “ความยาวไม่เกิน 30   ตัวอักษร”
  |  
Expected   Result | 1.   เมื่อเลื่อนเมาส์ไปชี้ที่ Field ส่วนลด ต้องแสดงข้อความ “ความยาวไม่เกิน 16   ตัวอักษร”
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/55022340-f45c8d00-502c-11e9-9b1d-7f4f6f7ce5d1.png)
![image](https://user-images.githubusercontent.com/45878758/55022356-fb839b00-502c-11e9-9b21-7f277862cc15.png)
![image](https://user-images.githubusercontent.com/45878758/55022362-00484f00-502d-11e9-9083-3eeea16ef044.png)

**Comment by Mickrepick** [comment]
แก้ไข : เมื่อเลื่อนเมาส์ไปชี้ที่ Field ส่วนลด จะแสดงข้อความ “ความยาวไม่เกิน 16 ตัวอักษร”
