### ISSUE TITLE
[รายการขายสินค้า][แก้ไข   หลังรายการ]ช่องแสดงตัวเลข หลังภาษีมูลค่าเพิ่ม สามารถกรอกข้อมูลได้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#231]
Summary   Name | [รายการขายสินค้า][แก้ไข   หลังรายการ]ช่องแสดงตัวเลข หลังภาษีมูลค่าเพิ่ม สามารถกรอกข้อมูลได้
-- | --
Defect No. |  231
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=11253&subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขายสินค้า
  | 6. กดุปุ่ม   แก้ไข หลังรายการ
  | 7.แสดงหน้าจอ   ขายสินค้า
  | 8.   กรอกข้อมูลใน field
  | ภาษีมูลค่าเพิ่ม
  | 9. ตรวจสอบ   ช่องแสดงตัวเลข หลังภาษีมูลค่าเพิ่ม
  |  
Actual   Result | 1.ช่องแสดงตัวเลข   หลังภาษีมูลค่าเพิ่ม สามารถกรอกข้อมูลได้
  |  
Expected   Result | 1.ช่องแสดงตัวเลข   หลังภาษีมูลค่าเพิ่ม ต้องไม่สามารถกรอกข้อมูลได้
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/55022479-3685ce80-502d-11e9-849b-d6b1f1c91d21.png)
![image](https://user-images.githubusercontent.com/45878758/55022490-3be31900-502d-11e9-9f53-8f60b1ccb784.png)
![image](https://user-images.githubusercontent.com/45878758/55022501-41406380-502d-11e9-9b1c-d2d48e3ccf31.png)

**Comment by Mickrepick** [comment]
แก้ไข : ช่องแสดงตัวเลข หลังภาษีมูลค่าเพิ่ม เปลี่ยนเป็น Field ปิดครับ
