### ISSUE TITLE
[รายการเบิกสินค้า]เมื่ออนุมัติสำเร็จจากหน้าจอรายการขายสินค้า ระบบแสดงสถานะ และปุ่มกดหลังรายการในหน้าจอรายการเบิกสินค้าไม่ถูกต้อง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#233]
Summary   Name | [รายการเบิกสินค้า]เมื่ออนุมัติสำเร็จจากหน้าจอรายการขายสินค้า   ระบบแสดงสถานะ และปุ่มกดหลังรายการในหน้าจอรายการเบิกสินค้าไม่ถูกต้อง
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  233
URL | http://nps001.homeip.net:8085/OutboundList.aspx?subDoc=14&menuID=2091
Step | 1. เลือกเมนู งานประจำวัน
  | 2. เลือกเมนูย่อย   รายการขายสินค้า
  | 3. เลือก ขายสด
  | 4. แสดงหน้าจอ   รายการขาย
  | 5. กดปุ่ม   เพิ่มรายการขาย
  | 6. แสดงหน้าจอ   ขายสินค้า
  | 7. กรอกข้อมูล   ขายสินค้า
  | 8. บันทึกสำเร็จ
  | 9. กดปุ่ม อนุมัติ   หลังรายการ
  | 10. อนุมัติสำเร็จ
  | 11. เลือกเมนูย่อย   ใบหยิบเบิกสินค้า
  | 12. เลือก   ใบหยิบเบิกสินค้า
  | 13.   แสดงหน้าจอ รายการเบิกสินค้า
  | 14.   ตรวจสอบรายการที่อนุมัติจากเมนูรายการขายสินค้า
  |  
  |  
Actual   Result | 1. ระบบแสดงสถานะ เป็น   "รออนุมัติ"
  | 2.   ช่องแสดงปุ่มกดหลังรายการแสดงปุ่ม "พิมพ์ , ดู ,   อนุมัติ , แก้ไข , ลบ"
  |  
Expected   Result | 1.   เมื่ออนุมัติสำเร็จในหน้าจอรายการขายสินค้า ระบบจะต้องนำข้อมูลมาแสดงสถานะ "เรียบร้อย"   ในหน้าจอรายการเบิกสินค้า
  | 2.   เมื่ออนุมัติสำเร็จในหน้าจอรายการขายสินค้า ระบบจะต้องนำข้อมูลมาแสดง   โดยแสดงปุ่มกดหลังรายการ "รับสินค้าเข้า" เหมือนหน้าจอ รายการนำเข้าสินค้า
  |  
Tester   Name | Phatcharat.Sun
  |  

![image](https://user-images.githubusercontent.com/45878758/55128732-3b3ea580-5147-11e9-9b95-37672537bbba.png)
![image](https://user-images.githubusercontent.com/45878758/55128734-3da0ff80-5147-11e9-9a52-1cff898ce468.png)
![image](https://user-images.githubusercontent.com/45878758/55128737-40035980-5147-11e9-9f3a-e8aa1f328efc.png)

**Comment by Patthamaporn** [comment]
แก้ไขให้ หน้ารายการเบิกสินค้า มีเอกสารใบจองที่อนุมัติแล้ว
