### ISSUE TITLE
[เบิกสินค้า][เพิ่มใบเบิก]เมื่อเลือกเอกสารจากปุ่ม   นำเข้าจาก... ระบบยังแสดงปุ่ม "นำเข้าจาก…" และสามารถเปลี่ยนเอกสารได้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#234]
Summary   Name | [เบิกสินค้า][เพิ่มใบเบิก]เมื่อเลือกเอกสารจากปุ่ม   นำเข้าจาก... ระบบยังแสดงปุ่ม "นำเข้าจาก…" และสามารถเปลี่ยนเอกสารได้
-- | --
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
Defect No. |  234
URL | http://nps001.homeip.net:8085/OutboundInfo.aspx?subDoc=14
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย ใบหยิบเบิกสินค้า
  | 3.   เลือก ใบหยิบเบิกสินค้า
  | 4.   แสดงหน้าจอ รายการเบิกสินค้า
  | 5.   กดปุ่ม เพิ่มใบเบิก
  | 6.   แสดงหน้าจอ เบิกสินค้า
  | 7.   กดปุ่ม นำเข้าจาก...
  | 8.   แสดง PopUp ค้นหาเอกสาร
  | 9.   เลือกเอกสาร
  | 10.   ตรวจสอบปุ่ม นำเข้าจาก…
  |  
  |  
  |  
Actual Result | เมื่อเลือกเอกสารจากปุ่ม   นำเข้าจาก... ระบบยังแสดงปุ่ม "นำเข้าจาก…" และสามารถเปลี่ยนเอกสารได้
  |  
Expected Result | เมื่อเลือกเอกสารจากปุ่ม   นำเข้าจาก... ระบบต้องไม่แสดงปุ่ม "นำเข้าจาก..." .ให้กด
  |  
Tester Name | Phatcharat.Sun
  |  

![image](https://user-images.githubusercontent.com/45878758/55130593-05e98600-514e-11e9-9e4a-cc7333375877.png)
![image](https://user-images.githubusercontent.com/45878758/55130595-097d0d00-514e-11e9-8d90-c4ab87797c86.png)
![image](https://user-images.githubusercontent.com/45878758/55130601-0bdf6700-514e-11e9-9092-8d7caa4728be.png)

**Comment by Patthamaporn** [comment]
แก้ไข ไม่แสดงปุ่มนำเข้าจาก หลังจากเลือกเอกสารแล้ว
