### ISSUE TITLE
รายการเบิกสินค้า__ค้นหาใน Field วันที่,ถึง ระบบแสดง วันที่ออกใบสั่งซื้อ  ทุกรายการ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#238]
Summary   Name | รายการเบิกสินค้า__ค้นหาใน   Field วันที่,ถึง ระบบแสดง วันที่ออกใบสั่งซื้อ    ทุกรายการ
-- | --
Defect No. | 238
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/OutboundList.aspx?subDoc=14&menuID=2091
Step | 1. เลือกเมนู   งานประจำวัน
  | 2. เลือกเมนูย่อย   ใบหยิบเบิกสินค้า
  | 3. เลือก   ใบหยิบเบิกสินค้า
  | 4. แสดงหน้าจอ   รายการเบิกสินค้า
  | 5.   เลือกข้อมูลใน Field วันที่ "28/03/2562"
  | 6. กดปุ่ม   ค้นหา
  | 7. เลือกข้อมูลใน   Field ถึง "18/02/2562"
  | 8. กดปุ่ม   ค้นหา
  |  
  |  
  |  
Actual   Result | 1.   ค้นหาใน Field วันที่ ระบบแสดง วันที่ออกใบสั่งซื้อ  ทุกรายการ
  | 2.   ค้นหาใน Field ถึง ระบบแสดง วันที่ออกใบสั่งซื้อ  ทุกรายการ
  |  
Expected   Result | 1.   วันที่ออกใบสั่งซื้อ    ต้องแสดงตั้งแต่วันที่ ที่ค้นหาเป็นต้นไป
  | 1.   วันที่ออกใบสั่งซื้อ  ต้องแสดงวันที่ก่อน   จนถึงวันที่ทำการค้นหา
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/55180867-0bca8000-51bd-11e9-943a-7a98964c195d.png)
![image](https://user-images.githubusercontent.com/45878758/55180876-0ec57080-51bd-11e9-8c28-7a256002eaca.png)

**Comment by Mickrepick** [comment]
Test แล้วใช้งานได้
