### ISSUE TITLE
[เบิกสินค้า][เพิ่มใบเบิก]เมื่ออนุมัติสำเร็จ   ในหน้าจอรายการเบิกสินค้า ไม่มีรายการที่อนุมัติสำเร็จมาแสดง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#239]
Summary   Name | [เบิกสินค้า][เพิ่มใบเบิก]เมื่ออนุมัติสำเร็จ   ในหน้าจอรายการเบิกสินค้า ไม่มีรายการที่อนุมัติสำเร็จมาแสดง
-- | --
Defect No. |  
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/OutboundList.aspx?subDoc=14&menuID=2091
  |  
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย ใบหยิบเบิกสินค้า
  | 3.   เลือก ใบหยิบเบิกสินค้า
  | 4.   แสดงหน้าจอ รายการเบิกสินค้า
  | 5.   กดปุ่ม เพิ่มใบเบิก
  | 6.   แสดงหน้าจอ เบิกสินค้า
  | 7.   กดปุ่ม นำเข้าจาก..
  | 8.   เลือกเอกสาร "APS5007"
  | 9.   กดปุ่ม บันทึก
  | 10.   บันทึกสำเร็จ
  | 11.   แสดงหน้าจอ รายการเบิกสินค้า
  | 12.   กดปุ่ม อนุมัติ
  | 13.   อนุมัติสำเร็จ
  | 14.   แสดงหน้าจอ รายการเบิกสินค้า
  |  
Actual Result | เมื่ออนุมัติสำเร็จ   ในหน้าจอ รายการเบิกสินค้า ไม่มีรายการที่อนุมัติสำเร็จมาแสดง
  |  
  |  
  |  
Expected   Result | เมื่ออนุมัติสำเร็จ   ในหน้าจอ รายการเบิกสินค้า มีรายการที่อนุมัติสำเร็จมาแสดง โดยสถานะเป็น   "เรียบร้อย" และช่องแสดงปุ่มกดเป็น "พิมพ์ , ดู"
  |  
  |  
Tester | Phatcharat.Sun
  |  

![image](https://user-images.githubusercontent.com/45878758/55182443-484bab00-51c0-11e9-9760-cc15196cb802.png)
![image](https://user-images.githubusercontent.com/45878758/55182450-4c77c880-51c0-11e9-92df-5b6bda8acc4b.png)
![image](https://user-images.githubusercontent.com/45878758/55182459-500b4f80-51c0-11e9-9595-da6f78445436.png)

**Comment by Patthamaporn** [comment]
แก้ไข หน้ารายการใบเบิกจะมีรายการที่อนุมัติแล้วมาแสดงด้วย
