### ISSUE TITLE
[ขายสินค้า]เมื่อเลือกสินค้า และกด บันทึก ระบบแสดง Error Message   "โปรดเลือกสินค้าก่อนบันทึก"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#241]
Summary   Name | [ขายสินค้า]   เมื่อเลือกสินค้า และกด บันทึก ระบบแสดง Error Message   "โปรดเลือกสินค้าก่อนบันทึก"
-- | --
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
Defect No. |  241
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?subDoc=7
Step | 1.   เลือกเมนู งานประจำ
  | 2.   เลือกเมนูย่อย รายการขายสินค้า
  | 3.   เลือก ขายสด
  | 4.   แสดงหน้าจอ รายการขายสินค้า
  | 5.   กดปุ่ม เพิ่มรายการขาย
  | 6.เลือกลูกค้า
  | 7.   กรอกข้อมูลใน filed ทั้งหมด
  | 8.   กดปุ่ม ค้นหาสินค้า
  | 9.   เลือกสินค้า
  | 10.   กดปุ่ม บันทึก
  | 11.   กด ตกลง
  |  
  |  
  |  
Actual   Result | เมื่อเลือกสินค้า   และกด บันทึก ระบบแสดง Error Message "โปรดเลือกสินค้าก่อนบันทึก"
  |  
  |  
Expected   Result | ระบบสามารถ   "บันทึกสำเร็จ" ได้
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/55313823-ef676580-5492-11e9-9270-c3753b5224a5.png)

![image](https://user-images.githubusercontent.com/45878758/55313826-f1c9bf80-5492-11e9-881f-e987b45beef5.png)

![image](https://user-images.githubusercontent.com/45878758/55313834-f42c1980-5492-11e9-9540-091fe060b31a.png)

![image](https://user-images.githubusercontent.com/45878758/55313839-f68e7380-5492-11e9-90f4-ba11b3f53423.png)

**Comment by Mickrepick** [comment]
Test แล้ว สามารถบันทึกได้
