### ISSUE TITLE
[รายการตรวจสินค้าเข้า][ตรวจสินค้าเข้า]ไม่มีปุ่ม เพิ่มใบตรวจ กับ Tab รูป แล้วหรอคะ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#242]
![image](https://user-images.githubusercontent.com/45878758/55316641-10cb5000-5499-11e9-947a-670a2525ece2.png)
![image](https://user-images.githubusercontent.com/45878758/55316650-132daa00-5499-11e9-95c1-d77c40596545.png)

**Comment by logisprosolution** [comment]
ใช่ครับ
