### ISSUE TITLE
[นำเข้าสินค้า],[เบิกสินค้า]สามารถเพิ่มจำนวนสั่งซื้อได้มั้ยคะ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#243]
![image](https://user-images.githubusercontent.com/45878758/55319657-8fc38700-549f-11e9-8889-90b63e343d43.png)
![image](https://user-images.githubusercontent.com/45878758/55319661-9225e100-549f-11e9-87db-1dc2e2489e86.png)

**Comment by logisprosolution** [comment]
สามารถเพิ่มจำนวนนำเข้า,เบิกสินค้า ได้
ให้เพิ่ม issue enhance เลย ว่าสามารถแก้ไขจำนวนสั่งซื้อได้
