### ISSUE TITLE
[รายการขาย][เพิ่มรายการขาย]เมื่อfield ราคาสั่ง มี 4 ตัวอักษร ระบบแสดงข้อความแจ้งเตือน จำนวนมีค่า 1-10,000

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#244]
Summary   Name | [รายการขาย][เพิ่มรายการขาย]เมื่อราคาสั่งมี 4 ตัวอักษร ระบบแสดงข้อความแจ้งเตือน จำนวนมีค่า 1-10,000
-- | --
Defect No. |  244
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กดปุ่ม   เพิ่มรายการขาย
  | 7.   กรอกข้อมูลทั้งหมดใน Field
  | 8.   เลือกสินค้า
  | 9. field ราคาสั่ง เป็น "1,070.00"
  | 10. กดปุ่ม   บันทึก
  |  
Actual   Result | ระบบแสดงข้อความแจ้งเตือน จำนวนมีค่า 1-10,000
  |  
Expected   Result | ราคาสั่งถ้าไม่เกิน 10,000 สามารถบันทึกได้
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/55321066-ea121700-54a2-11e9-82eb-59c9d3153604.png)
![image](https://user-images.githubusercontent.com/45878758/55321074-f0a08e80-54a2-11e9-976e-8cbce9d613d9.png)

**Comment by Mickrepick** [comment]
แก้ไข : ราคาสั่งไม่เกิน 10,000 สามารถบันทึกได้
