### ISSUE TITLE
[เบิกสินค้า][อนุมัติ   หลังรายการ]ระบบแสดง Message "บันทึกสำเร็จ" และ   "อนุมัติสำเร็จ" เมื่อกดปุ่ม อนุมัติ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#245]
Summary   Name | [เบิกสินค้า][อนุมัติ   หลังรายการ]ระบบแสดง Message "บันทึกสำเร็จ" และ   "อนุมัติสำเร็จ" เมื่อกดปุ่ม อนุมัติ
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  245
URL | http://nps001.homeip.net:8085/OutboundInfo.aspx?subDoc=14
Step | 1. เลือกเมนู งานประจำวัน
  | 2. เลือกเมนูย่อย   ใบหยิบเบิกสินค้า
  | 3. เลือก   ใบหยิบเบิกสินค้า
  | 4. แสดงหน้าจอ   รายการเบิกสินค้า
  | 5. กดปุ่ม อนุมัติ   หลังรายการ
  | 6. แสดงหน้าจอ   เบิกสินค้า (อนุมัติ)
  | 7. กดปุ่ม อนุมัติ
  | 8. ระบบแสดง Message   "ทำการยืนยัน ที่จะอนุมัติข้อมูล?"
  | 9. กดปุ่ม   ตกลง
  | 10.   ระบบแสดง Message "บันทึกสำเร็จ"
  | 11. กดปุ่ม   ตกลง
  | 12.   ระบบแสดง Message "อนุมัติสำเร็จ"
  |  
  |  
Actual   Result | ระบบแสดง Message   "บันทึกสำเร็จ" และ "อนุมัติสำเร็จ" เมื่อกดปุ่ม อนุมัติ
  |  
Expected   Result | ระบบแสดง Message   "อนุมัติสำเร็จ" โดยไม่แสดง "บันทึกสำเร็จ" เมื่อกดปุ่ม   อนุมัติ
  |  

![image](https://user-images.githubusercontent.com/45878758/55321511-095d7400-54a4-11e9-997d-e784016abcdf.png)
![image](https://user-images.githubusercontent.com/45878758/55321519-0d899180-54a4-11e9-9f31-2a9bb2b0b6c0.png)
![image](https://user-images.githubusercontent.com/45878758/55321523-0febeb80-54a4-11e9-9c54-ef45286c710d.png)
![image](https://user-images.githubusercontent.com/45878758/55321527-12e6dc00-54a4-11e9-9811-e3fb8e196864.png)
![image](https://user-images.githubusercontent.com/45878758/55321534-15493600-54a4-11e9-8f39-458971a18ddc.png)

**Comment by Patthamaporn** [comment]
แก้ไข หากอนุมัติแล้วจะมี msg แสดงว่า อนุมัติสำเร็จ แล้วเท่านั้น
