### ISSUE TITLE
[รายการขาย][เพิ่มรายการขาย]Field   ทั้งหมด คำนวณไม่ถูกต้อง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#246]
Summary   Name | [รายการขาย][เพิ่มรายการขาย]Field   ทั้งหมด คำนวณไม่ถูกต้อง
-- | --
Defect No. |  246
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กดปุ่ม   เพิ่มรายการขาย
  | 7.   กรอกข้อมูลทั้งหมดใน Field
  | 8.   เลือกสินค้ามากกว่า 1 รายการ
  | 9. รายการที่ 1 Field รวมยอด "100.00"
  | 10. รายการที่ 2 Field รวมยอด "1,200.00"
  |  
Actual   Result | Field ทั้งหมด   คำนวณ "1,200.00"
  |  
Expected   Result | Field ทั้งหมด   ต้องเป็น "1,300.00"
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/55322313-3579f480-54a6-11e9-8ad7-2bd747379382.png)
![image](https://user-images.githubusercontent.com/45878758/55322315-3743b800-54a6-11e9-9503-b672214378ce.png)
![image](https://user-images.githubusercontent.com/45878758/55322319-390d7b80-54a6-11e9-80d3-7a6f5bc3d83c.png)
![image](https://user-images.githubusercontent.com/45878758/55322327-3e6ac600-54a6-11e9-949b-0001717b6cc9.png)

**Comment by Mickrepick** [comment]
แก้ไข : Field ทั้งหมด และ สุทธิ จะคำนวนถูกต้อง
