### ISSUE TITLE
รายการเบิกสินค้า_กรอกข้อมูลใน Field สถานะผิด แต่ระบบดึงข้อมูลมาแสดงที่ Column แสดงผล

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#247]
Summary   Name | รายการเบิกสินค้า_กรอกข้อมูลใน   Field สถานะผิด แต่ระบบดึงข้อมูลมาแสดงที่ Column แสดงผล
-- | --
Defect No. |  247
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/OutboundList.aspx?subDoc=14&menuID=2091
Step | 1. เลือกเมนู   งานประจำวัน
  | 2. เลือกเมนูย่อย   ใบหยิบเบิกสินค้า
  | 3. เลือก   ใบหยิบเบิกสินค้า
  | 4. แสดงหน้าจอ   รายการเบิกสินค้า
  | 5. กรอกข้อมูลใน Field
  | - ค้นหา : รหัส "   20193/011389 "
  | - สถานะ "   รออนุมัติ "
  | 6. กดปุ่ม ค้นหา
  |  
  |  
  |  
Actual Result | กรอกข้อมูลใน   Field สถานะผิด แต่ระบบดึงข้อมูลมาแสดงที่ Column แสดงผล
  |  
  |  
Expected   Result | ระบบต้องแสดงข้อความใน   Column แสดงผล "ไม่พบรายการ"
  |  
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/55412980-9f6fc800-5592-11e9-97ef-74fb3ebc3c5b.png)

**Comment by Malatoo** [comment]
Edit >> [WebWMSDB20190323].[dbo].[udp_DOC_Trans_Header_lst]
Before >> or (d.subDocTypeID = @subDocTypeIDRef and d.docStatusID = @docStatusSuccess or @docStatusSuccess = 0)
After>> or (@docStatusID = 0 AND @docStatusID = 1) AND (d.subDocTypeID = @subDocTypeIDRef and d.docStatusID = @docStatusSuccess or @docStatusSuccess = 0)
