### ISSUE TITLE
รายการเบิกสินค้า_กรอกข้อมูลใน Field ถึงผิด แต่ระบบดึงข้อมูลมาแสดงที่ Column แสดงผล

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#249]
Summary   Name | รายการเบิกสินค้า_กรอกข้อมูลใน   Field ถึงผิด แต่ระบบดึงข้อมูลมาแสดงที่ Column แสดงผล
-- | --
Defect No. |  249
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/OutboundList.aspx?subDoc=14&menuID=2091
Step | 1. เลือกเมนู   งานประจำวัน
  | 2. เลือกเมนูย่อย   ใบหยิบเบิกสินค้า
  | 3. เลือก   ใบหยิบเบิกสินค้า
  | 4. แสดงหน้าจอ   รายการเบิกสินค้า
  | 5. กรอกข้อมูลใน Field
  | - ค้นหา : รหัส
  | - ถึง
  | 6. กดปุ่ม ค้นหา
  |  
  |  
  |  
Actual Result | กรอกข้อมูลใน   Field ถึงที่ผิด แต่ระบบดึงข้อมูลมาแสดงที่ Column แสดงผล
  |  
  |  
Expected   Result | ระบบต้องแสดงข้อความใน   Column แสดงผล "ไม่พบรายการ"
  |  
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/55417485-fed1d600-559a-11e9-9fed-183250e7a6c7.png)

**Comment by Mickrepick** [comment]
Test แล้วใช้งานได้
