### ISSUE TITLE
[นำเข้าสินค้า][รับสินค้าเข้า   หลังรายการ]field จำนวนสั่งซื้อ ไม่สามารถกรอกข้อมูลได้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#251]
Summary   Name | [นำเข้าสินค้า][รับสินค้าเข้า   หลังรายการ]field จำนวนสั่งซื้อ ไม่สามารถกรอกข้อมูลได้
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  251
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?subDoc=3&ref=11933
Step | 1. เลือกเมนู งานประจำวัน
  | 2. เลือกเมนูย่อย   นำเข้าสินค้า
  | 3. เลือก   นำเข้าสินค้าจากใบสั่งซื้อทั่วไป
  | 4. แสดงหน้าจอ   รายการนำเข้าสินค้า
  | 5. กดปุ่ม   รับสินค้าเข้า หลังรายการ
  | 6. แสดงหน้าจอ   นำเข้าสินค้า
  | 7. ตรวจาสอบ field   จำนวนสั่งซื้อ
  |  
  |  
  |  
  |  
Actual   Result | field จำนวนสั่งซื้อ   ไม่สามารถกรอกข้อมูลได้ เป็น field ปิด
  |  
Expected   Result | field   จำนวนสั่งซื้อสามารถกรอกข้อมูลได้ ไม่ใช่ field ปิด
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/55568187-6f0e6200-5729-11e9-9983-9c7f44265d28.png)
![image](https://user-images.githubusercontent.com/45878758/55568192-7170bc00-5729-11e9-893e-363dd75ee875.png)

**Comment by Patthamaporn** [comment]
แก้ไข หน้านำเข้าสินค้าสามารถกรอกจำนวนสั่งซื้อได้ โดยใช้ jquery ajax
