### ISSUE TITLE
[รายการนำเข้าสินค้า][เพิ่มใบนำเข้า]ไม่สามารถบันทึกข้อมูลได้   ขึ้น Error Message "Error ToDateTime"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#252]
Summary   Name | [รายการนำเข้าสินค้า][เพิ่มใบนำเข้า]ไม่สามารถบันทึกข้อมูลได้   ขึ้น Error Message "Error ToDateTime"
-- | --
Defect No. |  252
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?subDoc=3
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย นำเข้าสินค้า
  | 4. เลือก   นำเข้าสินค้าจากใบสั่งซื้อ
  | 5.   แสดงหน้าจอ รายการนำเข้าสินค้า
  | 6. กดปุ่ม   เพิ่มใบนำเข้า
  | 7. กดปุ่ม   นำเข้าจาก...
  | 8.   ระบุข้อมูลใน Field
  | เลขที่เอกสาร
  | วันที่เอกสาร
  | 9. กดปุ่ม   บันทึก
  | 10. กดปุ่ม   ตกลง
  |  
Actual   Result | ไม่สามารถบันทึกข้อมูลได้   ขึ้น Error Massage "Error ToDateTime"
  |  
Expected   Result | ต้องสามารถบันทึกข้อมูลได้
  |  
Tester   Name | Phatchanok.Sun

![image](https://user-images.githubusercontent.com/45878758/55569099-28216c00-572b-11e9-8d30-7c6e7c0b068a.png)
![image](https://user-images.githubusercontent.com/45878758/55569107-2c4d8980-572b-11e9-96b5-74f57ba52c09.png)
![image](https://user-images.githubusercontent.com/45878758/55569109-2e174d00-572b-11e9-89da-22db3a9cad18.png)
![image](https://user-images.githubusercontent.com/45878758/55569112-3079a700-572b-11e9-8e21-089d84bfd0c7.png)
![image](https://user-images.githubusercontent.com/45878758/55569136-38394b80-572b-11e9-8005-cac853fc98ce.png)
![image](https://user-images.githubusercontent.com/45878758/55569141-3a9ba580-572b-11e9-918a-082ddd45ba92.png)

**Comment by Patthamaporn** [comment]
แก้ไข สามารถบันทึกข้อมูลได้หากไม่ได้กรอกวันที่ใบกำกับภาษี และ วันที่ใบส่งของ
