### ISSUE TITLE
[รายการนำเข้าสินค้า][รับสินค้าเข้า   หลังรายการ]ไม่สามารถบันทึกข้อมูลได้ ขึ้น Error Message "Error   ToDateTime"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#253]
Summary   Name | [รายการนำเข้าสินค้า][รับสินค้าเข้า   หลังรายการ]ไม่สามารถบันทึกข้อมูลได้ ขึ้น Error Message "Error   ToDateTime"
-- | --
Defect No. |  253
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?subDoc=3&ref=11914
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย นำเข้าสินค้า
  | 4. เลือก   นำเข้าสินค้าจากใบสั่งซื้อ
  | 5.   แสดงหน้าจอ รายการนำเข้าสินค้า
  | 6. กดปุ่ม   รับสินค้าเข้า หลังรายการ
  | 7.   ระบุข้อมูลใน Field
  | เลขที่เอกสาร
  | วันที่เอกสาร
  | 8. กดปุ่ม   บันทึก
  | 9. กดปุ่ม   ตกลง
  |  
Actual   Result | ไม่สามารถบันทึกข้อมูลได้   ขึ้น Error Massage "Error ToDateTime"
  |  
Expected   Result | ต้องสามารถบันทึกข้อมูลได้
  |  
Tester   Name | Phatchanok.Sun

![image](https://user-images.githubusercontent.com/45878758/55569206-5d2dbe80-572b-11e9-8da4-304d006b5a8b.png)
![image](https://user-images.githubusercontent.com/45878758/55569208-5ef78200-572b-11e9-8f68-cc3706fc7a52.png)
![image](https://user-images.githubusercontent.com/45878758/55569226-6454cc80-572b-11e9-8fda-4e488b9dfb6d.png)
![image](https://user-images.githubusercontent.com/45878758/55569231-66b72680-572b-11e9-9cbf-22eb2513ce9d.png)

**Comment by Patthamaporn** [comment]
แก้ไข สามารถบันทึกข้อมูลได้หากไม่ได้กรอกวันที่ใบกำกับภาษี และ วันที่ใบส่งของ
