### ISSUE TITLE
[รายการนำเข้าสินค้า][รับสินค้าเข้า   หลังรายการ]เมื่อกดบันทึกรายการที่หน้าจอ นำเข้าสินค้า เอกสารที่อนุมัติมาจาก   ใบสั่งซื้อ ยังแสดงอยู่ในหน้าจอ รายการนำเข้าสินค้า

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#254]
Summary   Name | [รายการนำเข้าสินค้า][รับสินค้าเข้า   หลังรายการ]เมื่อกดบันทึกรายการที่หน้าจอ นำเข้าสินค้า เอกสารที่อนุมัติมาจาก   ใบสั่งซื้อ ยังแสดงอยู่ในหน้าจอ รายการนำเข้าสินค้า
-- | --
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
Defect No. |  254
URL | http://nps001.homeip.net:8085/InboundList.aspx?subDoc=3&menuID=2089
Step | 1.   สร้างใบสั่งซื้อ "APS1020"
  | 2.   อนุมัติสำเร็จ
  | 3.   เลือกเมนู งานประจำวัน
  | 4.   เลือกเมนูย่อย นำเข้าสินค้า
  | 5.   เลือก นำเข้าสินค้าจากใบสั่งซื้อ
  | 6.   แสดงหน้าจอ รายการนำเข้าสินค้า
  | 7.   กดปุ่ม รับสินค้าเข้า หลังรายการ
  | 8.   แสดงหน้าจอ นำเข้าสินค้า
  | 9.   กรอกข้อมูลใน field
  | -   เลขที่เอกสาร "APS2020"
  | 10.   กดปุ่ม บันทึก
  | 11.   บันทึกสำเร็จ
  | 12.   แสดงหน้าจอ รายการนำเข้าสินค้า
  |  
  |  
Actual Result | เมื่อกดบันทึกรายการที่หน้าจอ   นำเข้าสินค้า เลขที่เอกสาร "APS1020" ที่อนุมัติมาจาก ใบสั่งซื้อ   ยังแสดงอยู่ในหน้าจอ รายการนำเข้าสินค้า
  |  
Expected   Result | เมื่อกดบันทึกรายการที่หน้าจอ   นำเข้าสินค้า เลขที่เอกสาร "APS1020" ที่อนุมัติมาจาก ใบสั่งซื้อ   ต้องไม่แสดงในหน้าจอรายการนำเข้าสินค้า
  |  

![image](https://user-images.githubusercontent.com/45878758/55570183-1a6ce600-572d-11e9-9b6e-605ac7873132.png)
![image](https://user-images.githubusercontent.com/45878758/55570195-1e990380-572d-11e9-8c9a-2461ad7e1137.png)
![image](https://user-images.githubusercontent.com/45878758/55570199-20fb5d80-572d-11e9-82c9-fdd101630587.png)
![image](https://user-images.githubusercontent.com/45878758/55570206-235db780-572d-11e9-92cc-98a4a48f5e4c.png)
![image](https://user-images.githubusercontent.com/45878758/55570317-60c24500-572d-11e9-83c3-f97478d8ecc1.png)

**Comment by Patthamaporn** [comment]
หน้ารายการนำเข้า จะไม่แสดงรายการใบสั่งซื้อที่ถูกนำเข้าไปแล้ว
