### ISSUE TITLE
[นำเข้าสินค้า][เพิ่มใบนำเข้า]เมื่อกดบันทึกรายการที่หน้าจอ   นำเข้าสินค้า เลขที่เอกสาร "APS1022" ที่อนุมัติมาจาก ใบสั่งซื้อ   ยังแสดงอยู่ในหน้าจอ รายการนำเข้าสินค้า

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#255]
Summary   Name | [นำเข้าสินค้า][เพิ่มใบนำเข้า]เมื่อกดบันทึกรายการที่หน้าจอ   นำเข้าสินค้า เลขที่เอกสาร "APS1022" ที่อนุมัติมาจาก ใบสั่งซื้อ   ยังแสดงอยู่ในหน้าจอ รายการนำเข้าสินค้า
-- | --
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
Defect No. |  255
URL | http://nps001.homeip.net:8085/PopupDocSelect.aspx?dataId=1
Step | 1.   สร้างใบสั่งซื้อ "APS1022"
  | 2.   อนุมัติสำเร็จ
  | 3.   เลือกเมนู งานประจำวัน
  | 4.   เลือกเมนูย่อย นำเข้าสินค้า
  | 5.   เลือก นำเข้าสินค้าจากใบสั่งซื้อ
  | 6.   แสดงหน้าจอ รายการนำเข้าสินค้า
  | 7.   กดปุ่ม เพิ่มใบนำเข้า
  | 8.   แสดงหน้าจอ นำเข้าสินค้า
  | 9.   กดปุ่ม นำเข้าจาก...
  | 10.   แสดง Popup ค้นหาเอกสาร
  | 11.   เลือกเอกสาร "APS1022"
  | 12.   กรอกข้อมูลใน field
  | -   เลขที่เอกสาร "APS2022"
  | 13.   กดปุ่ม บันทึก
  | 14.   บันทึกสำเร็จ
  |  
  |  
Actual Result | เมื่อกดบันทึกรายการที่หน้าจอ   นำเข้าสินค้า เลขที่เอกสาร "APS1022" ที่อนุมัติมาจาก ใบสั่งซื้อ   ยังแสดงอยู่ในหน้าจอ Popup ค้นหาเอกสาร
  |  
Expected   Result | เมื่อกดบันทึกรายการที่หน้าจอ   นำเข้าสินค้า เลขที่เอกสาร "APS1022" ที่อนุมัติมาจาก ใบสั่งซื้อ   ต้องไม่แสดงในหน้าจอPopup ค้นหาเอกสาร
  |  

![image](https://user-images.githubusercontent.com/45878758/55572331-8bae9800-5731-11e9-9252-15e7dd498193.png)
![image](https://user-images.githubusercontent.com/45878758/55572348-95380000-5731-11e9-8ec5-7b69812fa568.png)
![image](https://user-images.githubusercontent.com/45878758/55572382-a84ad000-5731-11e9-85f2-2416a5ffbab4.png)
![image](https://user-images.githubusercontent.com/45878758/55572386-ac76ed80-5731-11e9-9632-a08077da538d.png)
![image](https://user-images.githubusercontent.com/45878758/55572392-b0a30b00-5731-11e9-862d-63e011e133c8.png)
![image](https://user-images.githubusercontent.com/45878758/55572401-b4369200-5731-11e9-9f33-b016b93008b2.png)
![image](https://user-images.githubusercontent.com/45878758/55572485-e0eaa980-5731-11e9-86b7-6c145f14a7c7.png)

**Comment by Patthamaporn** [comment]
หน้านำเข้า เมื่อมีการนำเข้าเอกสารและบันทึกแล้ว จะไม่แสดงรายการใบสั่งซื้อที่ถูกนำเข้าไปแล้ว
