### ISSUE TITLE
ใบสั่งซื้อ_เพิ่มสินค้าจาก Field จำนวน*รหัสสินค้า ด้วยรหัสสินค้า ระบบแสดง Error Message " ไม่พบสินค้า "

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#257]
Summary   Name | ใบสั่งซื้อ_เพิ่มสินค้าจาก   Field จำนวน*รหัสสินค้า ด้วยรหัสสินค้า ระบบแสดง Error Message "   ไม่พบสินค้า "
-- | --
Defect No. |  257
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/PurchaseInfo.aspx?subDoc=18
URL | http://nps001.homeip.net:8085/PopupGoodsSelectNoPrice.aspx
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย ใบสั่งซื้อสินค้า
  | 3. เลือก สั่งซื้อทั่วไป
  | 4.   แสดงหน้าจอ รายการใบสั่งซื้อสินค้า
  | 5.   กด เพิ่มใบสั่งซื้อ
  | 6.   กรอกข้อมูลใน Field
  | -   จำนวน*รหัสสินค้า
  | 7.   กดปุ่ม เพิ่มรายการเบิก+
  |  
  |  
Actual Result | 1. เพิ่มสินค้าจาก Field จำนวน*รหัสสินค้า ด้วยรหัสสินค้า ระบบแสดง   Error Message " ไม่พบสินค้า "
  | 2.   เพิ่มสินค้าจาก Field จำนวน*รหัสสินค้า ด้วยบาร์โค๊ด ระบบพบสินค้า
  |  
  |  
Expected Result | เมื่อค้นหาด้วยรหัสสินค้า   ต้องพบสินค้า
  |  
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/55578761-d97ecc80-5740-11e9-8134-2dedb1d71d23.png)

**Comment by Mickrepick** [comment]
Test จาก Web Deployed ใช้งานได้ปกติ Tester ดูให้อีกรอบหน่อยนะครับ

**Comment by Vermouthz** [comment]
ขอคอนเฟิร์ม Field จำนวน*รหัสสินค้า ใช้บาร์โค้ดขายสินค้าในการ เพิ่มรายการเบิก โดย comment และปิด Defect

![image](https://user-images.githubusercontent.com/45878758/56461402-a8f38f80-63dc-11e9-9a5d-3f0fd73bd8e1.png)

http://nps001.homeip.net:8085/PurchaseInfo.aspx?subDoc=18

**Comment by Mickrepick** [comment]
Confirm จำนวน*รหัสสินค้า ใช้บาร์โค้ดขายสินค้าในการ เพิ่มรายการเบิก
