### ISSUE TITLE
[ตรวจสินค้าเข้า][ตรวจสอบ หลังรายการ]field จำนวนที่เช็คแล้ว สามารถกรอกได้มั้ยคะ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#259]
field จำนวนที่เช็คแล้ว สามารถกรอกได้มั้ยคะ
![image](https://user-images.githubusercontent.com/45878758/55579306-2020f680-5742-11e9-8971-3e335cdbe38e.png)
http://nps001.homeip.net:8085/CheckerInInfo.aspx?dataId=11946&subDoc=21

**Comment by logisprosolution** [comment]
กรอกไม่ได้ครับ ณ ตอนนี้
