### ISSUE TITLE
[นำเข้าสินค้า][อนุมัติ   หลังรายการ]ระบบดึงข้อมูลมาแสดงใน field เลขที่ใบกำกับภาษี , เลขที่ใบส่งของ ,   ส่งโดย ไม่ถูกต้อง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#262]
Summary   Name | [นำเข้าสินค้า][อนุมัติ   หลังรายการ]ระบบดึงข้อมูลมาแสดงใน field เลขที่ใบกำกับภาษี , เลขที่ใบส่งของ ,   ส่งโดย ไม่ถูกต้อง
-- | --
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
Defect No. | 262
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?dataId=11948&subDoc=3&approve=1
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย นำเข้าสินค้า
  | 3.   เลือก นำข้าสินค้าจากใบสั่งซื้อ
  | 4.   แสดงหน้าจอ รายการนำเข้าสินค้า
  | 5.   กดปุ่ม รับสินค้าเข้า หลังรายการ
  | 6.   แสดงหน้าจอ นำสินค้าเข้า
  | 7.   กรอกข้อมูลใน field
  | - เลขที่ใบกำกับภาษี 20 ตัวอักษร
  | - เลขที่ใบส่งของ 20 ตัวอักษร
  | - ส่งโดย 20 ตัวอักษร
  | 8. กดปุ่ม บันทึก
  | 9.   บันทึกสำเร็จ
  | 10.   แสดงหน้าจอ รายการนำเข้าสินค้า
  | 11.   กดปุ่ม อนุมัติ หลังรายการ
  | 12.   แสดงหน้าจอ นำเข้าสินค้า
  |  
  |  
Actual   Result | ระบบดึงข้อมูลมาแสดงไม่ถูกต้อง   ใน field
  | 1.   เลขที่ใบกำกับภาษี ดึงข้อมูลมาแสดง 10 ตัวอักษร
  | 2.   เลขที่ใบส่งของ ดึงข้อมูลมาแสดง 10 ตัวอักษร
  | 3.   ส่งโดย ดึงข้อมูลมาแสดง 10 ตัวอักษร
  |  
  | ระบบดึงข้อมูลมาแสดงถูกต้อง   ใน field
Expected   Result | 1.   เลขที่ใบกำกับภาษี ดึงข้อมูลมาแสดง 20 ตัวอักษร
  | 2.   เลขที่ใบส่งของ ดึงข้อมูลมาแสดง 20 ตัวอักษร
  | 3.   ส่งโดย ดึงข้อมูลมาแสดง 20 ตัวอักษร
  |  

![image](https://user-images.githubusercontent.com/45878758/55601475-428b3200-578b-11e9-96d8-21069962b6f9.png)
![image](https://user-images.githubusercontent.com/45878758/55601482-4454f580-578b-11e9-9bf7-61e4f6329589.png)
![image](https://user-images.githubusercontent.com/45878758/55601487-474fe600-578b-11e9-8747-556523d070c9.png)
![image](https://user-images.githubusercontent.com/45878758/55601490-49b24000-578b-11e9-8761-01445b72e5e9.png)

**Comment by Patthamaporn** [comment]
แก้ไข สามารถกรอกและแสดงผล หน้านำเข้าสินค้า ฟิลด์เลขที่ใบกำกับภาษี เลขที่ใบส่งของ และ ส่งโดย ได้20ตัวอักษร
