### ISSUE TITLE
[นำเข้าสินค้า][แก้ไข   หลังรายการ]เมื่อระบุข้อูลค้นหาใน field รหัส/ชื่อ , หน่วย ระบบแสดง Error   Message "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#263]
Summary   Name | [นำเข้าสินค้า][แก้ไข   หลังรายการ]เมื่อระบุข้อูลค้นหาใน field รหัส/ชื่อ , หน่วย ระบบแสดง Error   Message "Object reference not set to an instance of an object."
-- | --
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
Defect No. |  263
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?dataId=11948&subDoc=3
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย นำเข้าสินค้า
  | 3.   เลือก นำเข้าสินค้าจากใบสั่งซื้อ
  | 4.   แสดงหน้าจอ รายการนำเข้าสินค้า
  | 5.   กดปุ่ม แก้ไข หลังรายการ
  | 6.   แสดงหน้าจอ นำเข้าสินค้า
  | 7.   กด -------------------ค้นหา----
  | 8.   กรอกข้อมูลใน field รหัส/ชื่อ "8850100101013"
  | 9. กดปุ่ม ค้นหา
  | 10.   กรอกข้อมูลใน field รหัส/ชื่อ "ไวไวปรุงสำเร็จ ลัง"
  | 11. กดปุ่ม ค้นหา
  | 12.   กรอกข้อมูลใน field หน่วย "ซองx1"
  | 13. กดปุ่ม ค้นหา
  |  
  |  
Actual   Result | เมื่อระบุข้อูลค้นหาใน   field รหัส/ชื่อ , หน่วย ระบบแสดง Error Message "Object reference not set   to an instance of an object."
  |  
Expected   Result | สามารถค้นหารายการสินค้าจาก   field รหัส/ชื่อ , หน่วย ได้
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/55603349-8171b580-5794-11e9-8ca2-4ca083952b0b.png)
![image](https://user-images.githubusercontent.com/45878758/55603352-85053c80-5794-11e9-8989-b1484b9d05bd.png)
![image](https://user-images.githubusercontent.com/45878758/55603353-87679680-5794-11e9-9750-87a795262553.png)
![image](https://user-images.githubusercontent.com/45878758/55603355-8afb1d80-5794-11e9-903c-460c9d83e256.png)

**Comment by Mickrepick** [comment]
Test แล้วใช้งานได้
