### ISSUE TITLE
[นำเข้าสินค้า][อนุมัติ   หลังรายการ]เมื่อระบุข้อูลค้นหาใน field รหัส/ชื่อ , หน่วย ระบบแสดง Error   Message "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#264]
Summary   Name | [นำเข้าสินค้า][อนุมัติ   หลังรายการ]เมื่อระบุข้อูลค้นหาใน field รหัส/ชื่อ , หน่วย ระบบแสดง Error   Message "Object reference not set to an instance of an object."
-- | --
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
Defect No. |  264
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?dataId=11948&subDoc=3&approve=1
Step | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย นำเข้าสินค้า
  | 3.   เลือก นำเข้าสินค้าจากใบสั่งซื้อ
  | 4.   แสดงหน้าจอ รายการนำเข้าสินค้า
  | 5.   กดปุ่ม อนุมัติ หลังรายการ
  | 6.   แสดงหน้าจอ นำเข้าสินค้า
  | 7.   กด -------------------ค้นหา----
  | 8.   กรอกข้อมูลใน field รหัส/ชื่อ "1212121"
  | 9.   กดปุ่ม ค้นหา
  | 10.   กรอกข้อมูลใน field รหัส/ชื่อ "ไวไวปรุงสำเร็จ ลัง"
  | 11.   กดปุ่ม ค้นหา
  | 12.   กรอกข้อมูลใน field หน่วย "ซองx1"
  | 13.   กดปุ่ม ค้นหา
  |  
  |  
Actual Result | เมื่อระบุข้อูลค้นหาใน   field รหัส/ชื่อ , หน่วย ระบบแสดง Error Message "Object reference not set   to an instance of an object."
  |  
Expected   Result | สามารถค้นหารายการสินค้าจาก   field รหัส/ชื่อ , หน่วย ได้
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/55603425-cf86b900-5794-11e9-93bb-52233a5d3678.png)
![image](https://user-images.githubusercontent.com/45878758/55603429-d7465d80-5794-11e9-9a46-2699a5cdd600.png)
![image](https://user-images.githubusercontent.com/45878758/55603430-d9a8b780-5794-11e9-86fc-0471477a7c8e.png)
![image](https://user-images.githubusercontent.com/45878758/55603431-dd3c3e80-5794-11e9-9867-61c255a7a50e.png)

**Comment by Mickrepick** [comment]
Test แล้วใช้งานได้
