### ISSUE TITLE
[รายการขาย][แก้ไข   หลังรายการ]Field ทั้งหมด คำนวณไม่ถูกต้อง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#265]
Summary   Name | [รายการขาย][แก้ไข   หลังรายการ]Field ทั้งหมด คำนวณไม่ถูกต้อง
-- | --
Defect No. |  265
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?subDoc=7
Step | 1. Login   WMS on Chorme
  | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย รายการขายสินค้า
  | 3. เลือก   ขายสด
  | 4.   แสดงหน้าจอ รายการขาย
  | 5. กดปุ่ม   เพิ่มรายการขาย
  | 6.   กรอกข้อมูลใน Field ทั้งหมด
  | 7. กดปุ่ม   บันทึก
  | 8.   แสดงหน้าจอ รายการขาย
  | 9. กดปุ่ม   แก้ไข หลังรายการ
  | 10. กดปุ่ม   ค้นหาสินค้า
  | 11. แสดง   PopUp ค้นหาสินค้า
  | 12.   เลือกสินค้า
  | เพิ่มรายการขาย Field ทั้งหมดแสดง   "13,700"
  | แก้ไข หลังรายการ Field ทั้งหมดแสดง   "1,130"
  |  
Actual   Result | Field ทั้งหมด   คำนวณไม่ถูกต้อง
  |  
Expected   Result | Field ทั้งหมด   ต้องคำนวณถูกต้อง
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/55623122-425f5680-57cc-11e9-884f-e60793fd1ac5.png)
![image](https://user-images.githubusercontent.com/45878758/55623125-44291a00-57cc-11e9-9a3f-ace27b84b630.png)
![image](https://user-images.githubusercontent.com/45878758/55623129-468b7400-57cc-11e9-8e8e-891596c39dbb.png)
![image](https://user-images.githubusercontent.com/45878758/55623135-4be8be80-57cc-11e9-8843-68c9b362393a.png)

**Comment by Mickrepick** [comment]
แก้ไข : Field ทั้งหมด และ สุทธิ คำนวณถูกต้อง
