### ISSUE TITLE
[รายการขาย][ดู   หลังรายการ]Field ทั้งหมด คำนวณไม่ถูกต้อง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#266]
Summary   Name | [รายการขาย][ดู   หลังรายการ]Field ทั้งหมด คำนวณไม่ถูกต้อง
-- | --
Defect No. |  266
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=11956&view=1
Step | 1. Login   WMS on Chorme
  | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย รายการขายสินค้า
  | 3. เลือก   ขายสด
  | 4.   แสดงหน้าจอ รายการขาย
  | 5. กดปุ่ม   เพิ่มรายการขาย
  | 6.   กรอกข้อมูลใน Field ทั้งหมด
  | 7. กดปุ่ม   บันทึก
  | 8.   แสดงหน้าจอ รายการขาย
  | 9. กดปุ่ม   ดู หลังรายการ
  | 10. กดปุ่ม   ค้นหาสินค้า
  | 11. แสดง   PopUp ค้นหาสินค้า
  | 12.   เลือกสินค้า
  | เพิ่มรายการขาย Field ทั้งหมดแสดง   "13,700"
  | แก้ไข หลังรายการ Field ทั้งหมดแสดง   "1,130"
  |  
Actual   Result | Field ทั้งหมด   คำนวณไม่ถูกต้อง
  |  
Expected   Result | Field ทั้งหมด   ต้องคำนวณถูกต้อง
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/55624684-e6e39780-57d0-11e9-8800-b4b97e71d2df.png)
![image](https://user-images.githubusercontent.com/45878758/55624690-e8ad5b00-57d0-11e9-98f1-98547c4ab698.png)
![image](https://user-images.githubusercontent.com/45878758/55624694-ea771e80-57d0-11e9-94d9-2cce1c6bd906.png)
![image](https://user-images.githubusercontent.com/45878758/55624713-f531b380-57d0-11e9-840b-fe4a7f9a6e91.png)

**Comment by Mickrepick** [comment]
แก้ไข : Field ทั้งหมด และ สุทธิ คำนวณถูกต้อง
