### ISSUE TITLE
[รายการขาย][อนุมัติ   หลังรายการ]Field ทั้งหมด คำนวณไม่ถูกต้อง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#267]
Summary   Name | [รายการขาย][อนุมัติ   หลังรายการ]Field ทั้งหมด คำนวณไม่ถูกต้อง
-- | --
Defect No. |  267
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=11956&subDoc=7&approve=1
Step | 1. Login   WMS on Chorme
  | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย รายการขายสินค้า
  | 3. เลือก   ขายสด
  | 4.   แสดงหน้าจอ รายการขาย
  | 5. กดปุ่ม   เพิ่มรายการขาย
  | 6.   กรอกข้อมูลใน Field ทั้งหมด
  | 7. กดปุ่ม   บันทึก
  | 8.   แสดงหน้าจอ รายการขาย
  | 9. กดปุ่ม   อนุมัติ หลังรายการ
  | 10. กดปุ่ม   ค้นหาสินค้า
  | 11. แสดง   PopUp ค้นหาสินค้า
  | 12.   เลือกสินค้า
  | เพิ่มรายการขาย Field ทั้งหมดแสดง   "13,700"
  | แก้ไข หลังรายการ Field ทั้งหมดแสดง   "1,130"
  |  
Actual   Result | Field ทั้งหมด   คำนวณไม่ถูกต้อง
  |  
Expected   Result | Field ทั้งหมด   ต้องคำนวณถูกต้อง
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/55625452-07145600-57d3-11e9-885e-a11cac763fd9.png)
![image](https://user-images.githubusercontent.com/45878758/55625455-08de1980-57d3-11e9-9dd3-92038c1ba073.png)
![image](https://user-images.githubusercontent.com/45878758/55625460-0b407380-57d3-11e9-934a-f76e0f56a861.png)
![image](https://user-images.githubusercontent.com/45878758/55625463-109dbe00-57d3-11e9-9b76-4b45168ea6e9.png)

**Comment by Mickrepick** [comment]
แก้ไข : Field ทั้งหมด และ สุทธิ คำนวณถูกต้อง
