### ISSUE TITLE
[รายการขาย][เพิ่มรายการขาย][อนุมัติ   หลังรายการ]Field สารมารถกรอกข้อมูลได้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#268]
Summary   Name | [รายการขาย][เพิ่มรายการขาย][อนุมัติ   หลังรายการ]Field สารมารถกรอกข้อมูลได้
-- | --
Defect No. |  268
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=11757&subDoc=7&approve=1
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กดปุ่ม   เพิ่มรายการขาย
  | 7.   ระบุข้อมูลใน หน้าจอขายสินค้า ทั้งหมด
  | 8. กดปุ่ม   บันทึก
  | 9.   แสดงหน้าจอ รายการขาย
  | 10. กดปุ่ม   อนุมัติ หลังรายการ
  |  
Actual   Result | 1. Field   สารมารถกรอกข้อมูลได้
  |  
Expected   Result | 1. Field   ต้องไม่สารมารถกรอกข้อมูลได้
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/55625568-607c8500-57d3-11e9-8f65-86ac2de85f0d.png)
![image](https://user-images.githubusercontent.com/45878758/55625571-62dedf00-57d3-11e9-81fa-b0ea29f5b512.png)
![image](https://user-images.githubusercontent.com/45878758/55625577-65413900-57d3-11e9-9f88-c1df8f0c44ab.png)
![image](https://user-images.githubusercontent.com/45878758/55625579-67a39300-57d3-11e9-8bb6-480e3f8621c2.png)
![image](https://user-images.githubusercontent.com/45878758/55625589-6d00dd80-57d3-11e9-94d9-1d6191aebf37.png)

**Comment by Patthamaporn** [comment]
หากเข้าอนุมัติที่หน้าขายจะไม่สามารถแก้ไขข้อมูลได้
