### ISSUE TITLE
[ลูกค้า][แก้ไข   หลังรายการ]Field เครดิต ไม่จำค่าที่กำหนดให้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#271]
Summary   Name | [ลูกค้า][แก้ไข   หลังรายการ]Field เครดิต ไม่จำค่าที่กำหนดให้
-- | --
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
Defect No. |  271
URL | http://nps001.homeip.net:8085/CustomerInfo.aspx?dataId=1010
Step | 1. เลือกเมนู   ตั้งค่า
  | 2.   แสดงหน้าจอ รายการลูกค้า
  | 3.   กดปุ่ม เพิ่มลูกค้า
  | 4.   แสดงหน้าจอ เพิ่มลูกค้า
  | 5.   ระบุข้อมูลใน field
  | -   รหัส
  | -   ชื่อภาษาไทย
  | -   ชื่อภาษาอังกฤษ
  | - เครดิต "10000"
  | - ประเภท
  | - สถานะ
  | 6. กดปุ่ม บันทึก
  | 7. บันทึกสำเร็จ
  | 8.   แสดงหน้าจอ รายการลูกค้า
  | 9.   กดปุ่ม แก้ไข หลังรายการ
  | 10.   ตรวจสอบ field เครดิต
  |  
Actual   Result | Field   เครดิต แสดงเป็น ค่าว่าง
  |  
Expected   Result | Field   เครดิต ต้องจำค่าที่ระบุไว้มาแสดง "10000"
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/55667402-012b7d00-5886-11e9-84ba-a9d1d5f8a127.png)
![image](https://user-images.githubusercontent.com/45878758/55667404-02f54080-5886-11e9-9ffe-e93cdf71f40e.png)
![image](https://user-images.githubusercontent.com/45878758/55667405-05579a80-5886-11e9-9eea-74d9aaf1385c.png)
![image](https://user-images.githubusercontent.com/45878758/55667406-0688c780-5886-11e9-90b4-6a95b7cd5815.png)
![image](https://user-images.githubusercontent.com/45878758/55667407-08528b00-5886-11e9-8bb2-fb80409c9ad8.png)

**Comment by Mickrepick** [comment]
แก้ไข : Field เครดิต ดึงข้อมูลออกมาแสดง

**Comment by Vermouthz** [comment]
URL : http://nps001.homeip.net:8085/CustomerInfo.aspx?dataId=1019
Actual Result : 
1. Field เครดิต ดึงข้อมูลมาแสดงไม่ถูกต้อง สร้าง "10,000.00" แต่ในหน้าแก้ไข แสดงเป็น "10.00"
2. เมื่อกด แก้ไข หลังรายการ field เครดิต ไม่สามารถแก้ไขได้

Expected Result : 
1. Field เครดิต เมื่อกดแก้ไข หลังรายการ ดึงข้อมูลมาแสดงถูกต้อง
2. เมื่อกด แก้ไข หลังรายการ field เครดิต สามารถแก้ไขได้

![image](https://user-images.githubusercontent.com/45878758/56494509-b2841100-651c-11e9-8019-1552a402a258.png)
![image](https://user-images.githubusercontent.com/45878758/56494512-b7e15b80-651c-11e9-95e3-afe3092b5b4f.png)
![image](https://user-images.githubusercontent.com/45878758/56494585-ecedae00-651c-11e9-8cf4-a510d0e60bd5.png)

**Comment by Vermouthz** [comment]
ขอโทษค่ะ เปิดผิด Defect
