### ISSUE TITLE
[ลูกค้า][ดู   หลังรายการ]Field เครดิต ไม่จำค่าที่กำหนดให้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#272]
Summary   Name | [ลูกค้า][ดู   หลังรายการ]Field เครดิต ไม่จำค่าที่กำหนดให้
-- | --
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
Defect No. | 272
URL | http://nps001.homeip.net:8085/CustomerInfo.aspx?dataId=1010&view=1
Step | 1. เลือกเมนู   ตั้งค่า
  | 2.   แสดงหน้าจอ รายการลูกค้า
  | 3.   กดปุ่ม เพิ่มลูกค้า
  | 4.   แสดงหน้าจอ เพิ่มลูกค้า
  | 5.   ระบุข้อมูลใน field
  | -   รหัส
  | -   ชื่อภาษาไทย
  | -   ชื่อภาษาอังกฤษ
  | - เครดิต "10000"
  | - ประเภท
  | - สถานะ
  | 6. กดปุ่ม บันทึก
  | 7. บันทึกสำเร็จ
  | 8.   แสดงหน้าจอ รายการลูกค้า
  | 9.   กดปุ่ม ดู หลังรายการ
  | 10.   ตรวจสอบ field เครดิต
  |  
Actual   Result | Field   เครดิต แสดงเป็น ค่าว่าง
  |  
Expected   Result | Field   เครดิต ต้องจำค่าที่ระบุไว้มาแสดง "10000"
  |  

![image](https://user-images.githubusercontent.com/45878758/55667486-2b316f00-5887-11e9-9fc6-7a0e109f7130.png)
![image](https://user-images.githubusercontent.com/45878758/55667489-2cfb3280-5887-11e9-824c-7ddd4c0d43eb.png)
![image](https://user-images.githubusercontent.com/45878758/55667491-31bfe680-5887-11e9-844a-a2b454fe4f64.png)
![image](https://user-images.githubusercontent.com/45878758/55667493-35536d80-5887-11e9-8bc2-c403dd645ce3.png)
![image](https://user-images.githubusercontent.com/45878758/55667495-371d3100-5887-11e9-917d-54cd31140544.png)

**Comment by Mickrepick** [comment]
แก้ไข : Field เครดิต ดึงข้อมูลออกมาแสดง
