### ISSUE TITLE
[นำเข้าสินค้า] [เพิ่มใบนำเข้า] สอบถามข้อความแจ้งเตือนแสดงถูกต้องแล้วใช่มั้ยคะ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#273]
URL : http://nps001.homeip.net:8085/InboundInfo.aspx?subDoc=3
![image](https://user-images.githubusercontent.com/45878758/55741353-40f58e80-5a57-11e9-92a9-d50738342db2.png)

**Comment by logisprosolution** [comment]
ข้อความซ้ำครับ

**Comment by Mickrepick** [comment]
แก้ไข : Field จำนวนสั่งซื้อ ข้อความแจ้งเตือน เป็น "กรุณากรอกจำนวนสั่งซื้อ ตั้งแต่ 1-10,000"
