### ISSUE TITLE
[รายการใบสั่งซื้อสินค้า]เมื่อเลือก   field ยอด "มากไปน้อย" หรือ "น้อยไปมาก" Column ยอด   ไม่เรียงลำดับตามที่เลือก

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#274]
Summary   Name | [รายการใบสั่งซื้อสินค้า]เมื่อเลือก   field ยอด "มากไปน้อย" หรือ "น้อยไปมาก" Column ยอด   ไม่เรียงลำดับตามที่เลือก
-- | --
Defect No. |  274
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/PurchaseList.aspx?subDoc=18&menuID=2085
Step | 1. เลือกเมนู   งานประจำวัน
  | 2.   เลือกเมนูย่อย ใบสั่งซื้อสินค้า
  | 3. เลือก   สั่งซื้อสินค้าทั้วไป
  | 4. แสดงหน้าจอ   รายการใบสั่งซื้อสินค่า
  | 5. เลือก field ยอด   "มากไปน้อย"
  | 6. กดปุ่ม ค้นหา
  | 7. เลือก field ยอด   "น้อยไปมาก"
  | 8. กดปุ่ม ค้นหา
  |  
  |  
  |  
Actual   Result | เมื่อเลือก field ยอด   "มากไปน้อย" หรือ "น้อยไปมาก" Column ยอด   ไม่เรียงลำดับตามที่เลือก
  |  
  |  
Expected   Result | 1. เมื่อเลือก field   ยอด "มากไปน้อย" ระบบต้องแสดง Column ยอด เรียงลำดับจาก มากไปหาน้อย
  | 2. เมื่อเลือก field   ยอด "น้อยไปมาก" ระบบต้องแสดง Column ยอด เรียงลำดับจากน้อยไปหามาก

![image](https://user-images.githubusercontent.com/45878758/55743269-1528d780-5a5c-11e9-9a04-c0b35bcaf44e.png)
![image](https://user-images.githubusercontent.com/45878758/55743272-178b3180-5a5c-11e9-9c53-8765e8b022b4.png)

**Comment by Patthamaporn** [comment]
แก้ไข หน้าใบสั่งซื้อสามารถค้นหาจากการเรียงลำดับคอลัม ยอด ได้
