### ISSUE TITLE
[รายการใบสั่งซื้อสินค้า]ระบบแสดง   Column ยอด ไม่ถูกต้อง "1075.0000"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#275]
Summary   Name | [รายการใบสั่งซื้อสินค้า]ระบบแสดง   Column ยอด ไม่ถูกต้อง "1075.0000"
-- | --
Defect No. | 275
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/PurchaseList.aspx?subDoc=18&menuID=2085
Step | 1. เลือกเมนู   งานประจำวัน
  | 2.   เลือกเมนูย่อย ใบสั่งซื้อสินค้า
  | 3. เลือก   สั่งซื้อสินค้าทั้วไป
  | 4. แสดงหน้าจอ   รายการใบสั่งซื้อสินค่า
  | 5. ตรวจสอบ Column ยอด
  |  
  |  
  |  
  |  
  |  
  |  
Actual   Result | ระบบแสดง Column ยอด   ไม่ถูกต้อง "1075.0000"
  |  
  |  
Expected   Result | ระบบต้องดึงจาก Field   สุทธิ ของรายการนั้นมาแสดงถูกต้อง "1075.00"
  |  

![image](https://user-images.githubusercontent.com/45878758/55743586-e101e680-5a5c-11e9-9b55-9687a624f932.png)

**Comment by Mickrepick** [comment]
แก้ไข : Column ยอด จะมีค่าตรงกับ Field สุทธิ
