### ISSUE TITLE
เช็คทุกหน้าว่า Validate Field ไหน

### ISSUE THREAD

**Issue by Patthamaporn** [logisprosolution/WMS#277]
ในทุกหน้า จะต้องเปลี่ยน Keyword Validate ว่าเป็นของ Field ไหน และให้ focus กลับไป

**Comment by acryforever** [comment]
แก้ไขเรียบร้อยเป็นการแก้ไข การแจ้งเตือนในระบบบังคับกรอก ในส่วนของ งานประจำวัน ทั้งการตั้งค่า และระบบ
