### ISSUE TITLE
หน้าสินค้า จะต้อง Validate Pallet ด้วย

### ISSUE THREAD

**Issue by Patthamaporn** [logisprosolution/WMS#278]
หากหน้าสินค้าไม่มีการตั้งค่าPallet จะต้องมีการ Validate ก่อนบันทึก

**Comment by acryforever** [comment]
เพิ่ม Validate ก่อนบันทึก โดยแจ้งเตือนกรุณาเพิ่มจำนวนพาเลท ตอน New Mode
