### ISSUE TITLE
[รายการขาย][เพิ่มรายการขาย]ระบบแสดงข้อความ   "โปรดเลือกคู่ค้าที่จะเก็บก่อนบันทึก" เมื่อกดปุ่ม Ok Field รวมยอด   คำนวณไม่ถูกต้อง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#280]
Summary   Name | [รายการขาย][เพิ่มรายการขาย]ระบบแสดงข้อความ   "โปรดเลือกคู่ค้าที่จะเก็บก่อนบันทึก" เมื่อกดปุ่ม Ok Field รวมยอด   คำนวณไม่ถูกต้อง
-- | --
Defect No. |  280
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กดปุ่ม   เพิ่มรายการขาย
  | 7.   กรอกข้อมูลใน Field ยกเว้น เลือกลูกค้า
  | 8. กดปุ่ม   ค้นหาสินค้า
  | เพิ่มสินค้า 1 รายการ
  | 9.   กรอกข้อมูลใน Field
  | 10. กดปุ่ม   บันทึก
  | 11. กดปุ่ม   ตกลง
  | 12.   ก่อนทำการบันทึก Field รวมยอด "10,700.00"
  | 13.   เมื่อทำการบัยทึก Field รวมยอด "1,070.00"
  |  
Actual   Result | Field รวมยอด คำนวณ   "1,070.00"
  |  
Expected   Result | Field รวมยอด คำนวณ   "10,700.00"
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/55895345-30bfe980-5be6-11e9-9300-fcada5b7d8ce.png)
![image](https://user-images.githubusercontent.com/45878758/55895353-33224380-5be6-11e9-9007-eec2b2bb0675.png)
![image](https://user-images.githubusercontent.com/45878758/55895357-34ec0700-5be6-11e9-9175-727785723223.png)
![image](https://user-images.githubusercontent.com/45878758/55895364-3b7a7e80-5be6-11e9-821e-a42d4cfc62c2.png)
![image](https://user-images.githubusercontent.com/45878758/55895369-3e756f00-5be6-11e9-88cd-5d3524b9a676.png)
![image](https://user-images.githubusercontent.com/45878758/55895383-446b5000-5be6-11e9-8985-ff4ee0a705ea.png)

**Comment by Patthamaporn** [comment]
แก้ไข เมื่อบันทึกโดยไม่ได้เลือกลูกค้าจะคำนวณ Field รวมยอดถูกต้อง
