### ISSUE TITLE
[Location   Picking]Field ค้นหา:รหัส location picking/รหัสสินค้า/รหัสซื้อขาย ค้นหาจาก   column ไหนได้บ้างคะ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#281]
Summary   Name | [Location   Picking]Field ค้นหา:รหัส location picking/รหัสสินค้า/รหัสซื้อขาย ค้นหาจาก   column ไหนได้บ้างคะ
-- | --
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
Issus No. |  281
URL | http://nps001.homeip.net:8085/LocationList.aspx?menuID=71
  |  

![image](https://user-images.githubusercontent.com/45878758/56460890-16e78900-63d4-11e9-91a8-73f931a4f013.png)

**Comment by logisprosolution** [comment]
ข่องนั้นเลย

**Comment by Vermouthz** [comment]
1. รหัส location picking = Column รหัสตำแหน่งเก็บ
2. รหัสสินค้า = ????
3. รหัสซ์้อขาย = Column โค๊ดสินค้า

**Comment by logisprosolution** [comment]
เพิ่ม field รหัสสินค้าในตาราง และแก้ชื่อโค๊ดสินค้า เป็นรหัสซื้อขายทุกหน้า

**Comment by acryforever** [comment]
![s1](https://user-images.githubusercontent.com/47658214/56493085-16580b00-6518-11e9-80bf-a7cfbbe1a474.png)

เขียน BIZ ของ udp_LOC_Location_lst ใน sql 
เพิ่ม field รหัสสินค้าในตาราง และแก้ชื่อโค๊ดสินค้า
