### ISSUE TITLE
[รายการนำเข้าสินค้า][เพิ่มใบนำเข้า]เมื่อกดปุ่ม   บันทึก ไม่สามารถบันทึกข้อมูลได้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#282]
Summary   Name | [รายการนำเข้าสินค้า][เพิ่มใบนำเข้า]เมื่อกดปุ่ม   บันทึก ไม่สามารถบันทึกข้อมูลได้
-- | --
Defect No. |  282
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?subDoc=3
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย นำเข้าสินค้า
  | 4. เลือก   นำเข้าสินค้าจากใบสั่งซื้อ
  | 5.   แสดงหน้าจอ รายการนำเข้าสินค้า
  | 6. กดปุ่ม   เพิ่มใบนำเข้า
  | 7. กดปุ่ม   นำเข้าจาก...
  | 8.   ระบุข้อมูลใน Field
  | เลขที่เอกสาร
  | วันที่เอกสาร
  | 9. กดปุ่ม   บันทึก
  | 10. กดปุ่ม   ตกลง
  |  
Actual   Result | เมื่อกดปุ่ม บันทึก   ไม่สามารถบันทึกข้อมูลได้
  |  
Expected   Result | ต้องสามารถบันทึกข้อมูลได้
  |  
Tester   Name | Phatchanok.Sun

![image](https://user-images.githubusercontent.com/45878758/56468394-0bd53d00-6456-11e9-9b37-41012e71132f.png)
![image](https://user-images.githubusercontent.com/45878758/56468395-0e379700-6456-11e9-9214-1c54c15ee6ee.png)
![image](https://user-images.githubusercontent.com/45878758/56468396-11328780-6456-11e9-97ab-38bc1ca338a2.png)
![image](https://user-images.githubusercontent.com/45878758/56468400-17c0ff00-6456-11e9-807b-94b768955b0e.png)
![image](https://user-images.githubusercontent.com/45878758/56468402-1d1e4980-6456-11e9-9a3f-1b7cddd6f853.png)

**Comment by Patthamaporn** [comment]
ลองtestใน http://nps001.homeip.net:8085/InboundList.aspx?subDoc=3&menuID=2089 แล้ว โดยใช้ข้อมูลเหมือนกับ tester แต่สามารถบันทึกข้อมูลได้ หาก tester มีข้อมูลในการบันทึกไม่ได้เช่น บันทึกเอกสารเดิมหลายครั้งแล้วไม่บันทึก หรือเหตุการณ์อื่น รบกวนบอกด้วยนะคะ
![image](https://user-images.githubusercontent.com/37695403/56483006-5d7ed580-64f1-11e9-8e2b-99cee9bf43db.png)
![image](https://user-images.githubusercontent.com/37695403/56483008-61aaf300-64f1-11e9-83fa-92bd662cdeee.png)

**Comment by Patthamaporn** [comment]
ใบสั่งซื้อบางตัวเป็นเอกสารเก่าซึ่งใช้สินค้าที่ถูกลบออกไปแล้ว ตอนนี้แก้ไขแล้วรบกวน retest ด้วยนะคะ
