### ISSUE TITLE
[รายการขาย][เพิ่มรายการขาย]เมื่อกดปุ่ม   บันทึก ไม่สามารถบันทึกข้อมูลได้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#283]
Summary   Name | [รายการขาย][เพิ่มรายการขาย]เมื่อกดปุ่ม   บันทึก ไม่สามารถบันทึกข้อมูลได้
-- | --
Defect No. |  283
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กดปุ่ม   เพิ่มรายการขาย
  | 7. กดปุ่ม   เลือกลูกค้า
  | 8. แสดง   PopUp ค้นหาลูกค้า
  | 9. เลือก   ลูกค้า
  | 10.   กรอกข้อมูลขายสินค้าใน field
  | เลขที่เอกสาร
  | วันที่เอกสาร
  | ข้อตกลง
  | 11. กดปุ่ม   ค้นหาสินค้า
  | 12. แสดง   PopUp ค้นหาสินค้า
  | 13. เลือก   สินค้า
  | 14   กรอกข้อมูลรายการสินค้าใน field
  | จำนวนสั่งซื้อ
  | ราคาสั่ง
  | 15. กดปุ่ม   บันทึก
  | 16. กด   ตกลง
  |  
Actual   Result | เมื่อกดปุ่ม บันทึก   ไม่สามารถบันทึกข้อมูลได้
  |  
Expected   Result | ต้องสามารถบันทึกข้อมูลได้
  |  
TesterName | Phatchanok

Retest-Pass--------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/45878758/56468976-cae12680-645d-11e9-84bc-ea025c7c09f2.png)
![image](https://user-images.githubusercontent.com/45878758/56468977-ccaaea00-645d-11e9-9746-9844bc6e07c2.png)
![image](https://user-images.githubusercontent.com/45878758/56468981-d5032500-645d-11e9-8a63-38b5ae9f0604.png)
![image](https://user-images.githubusercontent.com/45878758/56468987-e0eee700-645d-11e9-8684-574895375540.png)

**Comment by Patthamaporn** [comment]
แก้ไขและลองtestตามข้อมูล tester ตอนนี้ใช้ได้แล้ว รบกวน retest อีกรอบนะคะ
![image](https://user-images.githubusercontent.com/37695403/56492364-c415ea80-6515-11e9-85a2-69a1665a3e17.png)
