### ISSUE TITLE
[Location   Picking]Field Priority and คลัง มีวิธีระบุข้อมูลอย่างไรคะ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#284]
Summary   Name | [Location   Picking]Field Priority and คลัง มีวิธีระบุข้อมูลอย่างไรคะ
-- | --
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
Issus No. |  284
URL | http://nps001.homeip.net:8085/LocationInfo.aspx
  |  

![image](https://user-images.githubusercontent.com/45878758/56473014-eebd6000-648f-11e9-9d94-aeb7c86a982e.png)

**Comment by logisprosolution** [comment]
กรอกเป็น ทศนิยมครับ เอาไว้เรียงลำดับ รายการ

ส่วนคลังเดี๋ยวจะเปิดใช้จะบอกครับ
