### ISSUE TITLE
รายการนำเข้าสินค้า_ไม่มี column ยอดในตาราง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#285]
Summary   Name | รายการนำเข้าสินค้า_ไม่มี   column ยอดในตาราง
-- | --
Defect No. |  285
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/InboundList.aspx?subDoc=3&menuID=2089
Step | 1. เลือกเมนู   งานประจำวัน
  | 2.   เลือกเมนูย่อย นำเข้าสินค้า
  | 3. เลือก นำเข้าสินค้าจากใบสั่งซื้อ
  | 4.   แสดงหน้าจอ รายการนำเข้าสินค้า
  |  
  |  
Actual Result | ไม่มี column ยอดในตาราง
  |  
  |  
Expected Result | ต้องมี   colomn ยอดในตาราง
  |  
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/56488889-0d603d00-650a-11e9-9095-0864166c11b5.png)

**Comment by acryforever** [comment]
รายการที่จะแสดง ยอด มีแค่หน้า ใบสั่งซื้อและใบขาย 
มีแสดงยอด ตอนรับสิ้นค้าเข้า
