### ISSUE TITLE
[ค้นหาสินค้า]Field   หมวดย่อย ไม่มี data ให้เลือก

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#286]
Summary Name | [ค้นหาสินค้า]Field   หมวดย่อย ไม่มี data ให้เลือก
-- | --
Version | 2018 © WMS by   Logis Pro Solution co., Ltd. AT-Social!
Defect   No. |  286
URL | http://nps001.homeip.net:8085/PopupGoodsSelectNoPrice.aspx

![image](https://user-images.githubusercontent.com/45878758/56489123-d8a0b580-650a-11e9-9b08-cd7768ea5cbb.png)
![image](https://user-images.githubusercontent.com/45878758/56489124-da6a7900-650a-11e9-8fda-4408a8b8bf9e.png)

**Comment by logisprosolution** [comment]
เลือกหมวดหลักก่อน แล้วจึงมาหมวดย่อย แต่ควรจะ disable controls ให้เรียบร้อย
