### ISSUE TITLE
[ค้นหาสินค้า]Field   ค้นหา:รหัส/ชื่อ ค้นหาจาก บาร์โค๊ดขายสินค้าใช่มั้ยคะ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#287]
Summary   Name | [ค้นหาสินค้า]Field   ค้นหา:รหัส/ชื่อ ค้นหาจาก บาร์โค๊ดขายสินค้าใช่มั้ยคะ
-- | --
Version | 2018 © WMS by   Logis Pro Solution co., Ltd. AT-Social!
Defect No. |  287
URL | http://nps001.homeip.net:8085/PopupGoodsSelectNoPrice.aspx
Remark | ถ้าค้นหาจาก   บาร์โค๊ดขายสินค้าถูกต้องแล้ว รบกวนขอ Comfirm และปิด Issus ค่ะ

![image](https://user-images.githubusercontent.com/45878758/56489243-44831e00-650b-11e9-8b17-6e5050157a73.png)

**Comment by logisprosolution** [comment]
รหัสสินค้า / บาร์โค๊ดสินค้า / ชื่อสินค้า
แก้ตามนี้

**Comment by Mickrepick** [comment]
แก้ไข : Field 'รหัส / ชื่อ' เปลี่ยนเป็น 'รหัสสินค้า / บาร์โค๊ดสินค้า / ชื่อสินค้า'
