### ISSUE TITLE
สอบถาม กรณีแสดง   "ไม่พบรายการ" ตำแหน่งต้องอยู่ Center ของตารางแสดงผลหรือไม่คะ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#288]
Summary   Name | สอบถาม กรณีแสดง   "ไม่พบรายการ" ตำแหน่งต้องอยู่ Center ของตารางแสดงผลหรือไม่คะ
-- | --
Version | 2018 © WMS by   Logis Pro Solution co., Ltd. AT-Social!
Defect No. |  

![image](https://user-images.githubusercontent.com/45878758/56492699-ce84b400-6516-11e9-94c6-885e0be24f21.png)
![image](https://user-images.githubusercontent.com/45878758/56492702-d17fa480-6516-11e9-9e0f-da25b550e33f.png)
![image](https://user-images.githubusercontent.com/45878758/56492705-d3496800-6516-11e9-81e6-e9fcfcf90f0f.png)
![image](https://user-images.githubusercontent.com/45878758/56492706-d5132b80-6516-11e9-95a9-56f9b29d8db2.png)
![image](https://user-images.githubusercontent.com/45878758/56492708-d6dcef00-6516-11e9-9dc0-7484fd826d6f.png)
![image](https://user-images.githubusercontent.com/45878758/56492715-d9d7df80-6516-11e9-8839-ac4b5f86dea1.png)

**Comment by logisprosolution** [comment]
center
 low piority

**Comment by Mickrepick** [comment]
แก้ไข : "ไม่พบรายการ" จะอยู่ตำแหน่ง Center ของตารางแสดงผล
