### ISSUE TITLE
สอบถาม ข้อความแจ้งเตือนด้านล่าง และข้อความแจ้งเตือนใต้ field ค่ะ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#290]
ยึดตามรูปแบบในหน้าจอไหนคะ
![image](https://user-images.githubusercontent.com/45878758/56495556-4f947900-6520-11e9-9f79-62f0a7380c7c.png)

**Comment by logisprosolution** [comment]
เอาคำว่าข้อมูลออก
แบบด้านล่าง
