### ISSUE TITLE
[รายการขาย][แก้ไข   หลังรายการ]เพิ่มสินค้าจาก จำนวน*รหัสสินค้า    Field ภาษีมูลค่าเพื่ม ไม่คำนวณให้ใหม่

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#291]
Summary   Name | [รายการขาย][แก้ไข   หลังรายการ]เพิ่มสินค้าจาก จำนวน*รหัสสินค้า    Field ภาษีมูลค่าเพื่ม ไม่คำนวณให้ใหม่
-- | --
Defect No. |  
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=12136&subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กดปุ่ม   เพิ่มรายการขาย
  | 7.   กรอกข้อมูลใน Field ทั้งหมด
  | 8. กดปุ่ม   บันทึก
  | 9.   แสดงหน้าจอ รายการขาย
  | 10. กดปุ่ม   แก้ไข หลังรายการ
  | 11.   กรอกข้อมูลใน Field
  | จำนวน*รหัสสินค้า
  | 12. กดปุ่ม   เพิ่มรายการเบิก+
  | 13.   กรอกข้อมูลใน Field
  | จำนวนสั่ง
  | ราคาสั่ง
  | ส่วนลดรายการ
  | 14. กดปุ่ม   ลบ หลังรายการ
  | 15. กดปุ่ม   ตกลง
  |  
Actual   Result | เพิ่มสินค้าจาก   จำนวน*รหัสสินค้า  Field ภาษีมูลค่าเพื่ม   ไม่คำนวณให้ใหม่
  |  
Expected   Result | เพิ่มสินค้าจาก   จำนวน*รหัสสินค้า  Field ภาษีมูลค่าเพื่ม   ต้องคำนวณให้ใหม่
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/56498686-16163a80-652d-11e9-895b-5cb76fce74ac.png)
![image](https://user-images.githubusercontent.com/45878758/56498688-18789480-652d-11e9-9036-857924c72f9b.png)
![image](https://user-images.githubusercontent.com/45878758/56498694-1a425800-652d-11e9-8617-2b5ab344eaf7.png)
![image](https://user-images.githubusercontent.com/45878758/56498698-20383900-652d-11e9-9dc8-8bbff1593933.png)

**Comment by acryforever** [comment]
แก้ไข เป็น ยอดรวม คูณ ภาษี หารร้อย
