### ISSUE TITLE
[เพิ่มตำแหน่ง]   สอบถามเกี่ยวกับหน้าจอ เพิ่มตำแหน่งในเมนู ตั้งค่าค่ะ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#292]
Summary   Name | [เพิ่มตำแหน่ง]   สอบถามเกี่ยวกับหน้าจอ เพิ่มตำแหน่งในเมนู ตั้งค่าค่ะ
-- | --
Version | 2018 © WMS by Logis Pro   Solution co., Ltd. AT-Social!
Defect No. |  292
URL | http://nps001.homeip.net:8085/RoleInfo.aspx
Step | 1. เลือกเมนู ระบบ
  | 2. เลือกเมนูย่อย   สิทธิ์การใช้งาน
  | 3. แสดงหน้าจอ   รายการตำแหน่ง
  | 4. กดปุ่ม   เพิ่มตำแหน่ง
  |  
Remark |  

![image](https://user-images.githubusercontent.com/45878758/56556412-2c220a80-65c2-11e9-9870-bfba7ba49239.png)
![image](https://user-images.githubusercontent.com/45878758/56556417-2e846480-65c2-11e9-98bc-c1cf3201fafc.png)

**Comment by acryforever** [comment]
value ยังไม่มีการใช้งาน
