### ISSUE TITLE
[สินค้า]ระบบไม่จำค่า   พาเลทที่เพิ่มไว้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#293]
Summary   Name | [สินค้า]ระบบไม่จำค่า   พาเลทที่เพิ่มไว้
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  293
URL | http://nps001.homeip.net:8085/SkuInfo.aspx?dataId=4055
Step | 1. เลือกเมนู ตั้งค่า
  | 2. เลือกเมนูย่อย   สินค้า
  | 3. แสดงหน้าจอ   รายการสินค้า
  | 4. กดปุ่ม แก้ไข   หลังรายการ
  | 5. แสดงหน้าจอ   ข้อมูลสินค้า
  | 6. เลือก Blog พาเลท
  | 7. กดปุ่ม   เพิ่มประเภทพาเลท
  | 8. กรอกข้อมูลใน field
  | 9. กดปุ่ม   เลือก
  | 10. กดปุ่ม   บันทึก
  | 11. กดปุ่ม   กลับ
  | 12.   แสดงหน้าจอ รายการสินค้า
  | 13. กดปุ่ม   แก้ไข หลังรายการ
  | 14. เลือก   Blog พาเลท
  |  
  |  
  |  
  |  
Actual   Result | ระบบไม่จำค่า   พาเลทที่เพิ่มไว้
  |  
Expected   Result | ระบบต้องจำค่า พาเลท   ที่บันทึกไว้
  |  

![image](https://user-images.githubusercontent.com/45878758/56878891-77d02a80-6a80-11e9-9154-c9bb37188849.png)
![image](https://user-images.githubusercontent.com/45878758/56878894-7a328480-6a80-11e9-990c-33a4679c7fe1.png)
![image](https://user-images.githubusercontent.com/45878758/56878896-7d2d7500-6a80-11e9-8996-bc930ea7888a.png)
![image](https://user-images.githubusercontent.com/45878758/56878915-96cebc80-6a80-11e9-9270-e6877b10cf40.png)
![image](https://user-images.githubusercontent.com/45878758/56878898-7f8fcf00-6a80-11e9-9484-809ba874a678.png)

**Comment by acryforever** [comment]
![s1](https://user-images.githubusercontent.com/47658214/56881465-b23ec500-6a8a-11e9-8edf-131ec4f6d1f3.png)
![s2](https://user-images.githubusercontent.com/47658214/56881466-b23ec500-6a8a-11e9-895e-6e01452e05a1.png)
ผิด Paramistor
