### ISSUE TITLE
[รายการขาย][แก้ไข   หลังรายการ]แก้ไข Field ส่วนลดรายการ ระบบแจ้งเตือน   "สินค้าไม่เพียงพอ"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#294]
Summary   Name | [รายการขาย][แก้ไข   หลังรายการ]แก้ไข Field ส่วนลดหลังรายการ ระบบแจ้งเตือน   "สินค้าไม่เพียงพอ"
-- | --
Defect No. |  294
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=12135&subDoc=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู งานประจำวัน
  | 3.   เลือกเมนูย่อย รายการขายสินค้า
  | 4. เลือก   ขายสด
  | 5.   แสดงหน้าจอ รายการขาย
  | 6. กดปุ่ม   เพิ่มรายการขาย
  | 7.   ระบุข้อมูลใน หน้าจอขายสินค้า ทั้งหมด
  | 8. กดปุ่ม   บันทึก
  | 9.   แสดงหน้าจอ รายการขาย
  | 10. กดปุ่ม   แก้ไข หลังรายการ
  |  
Actual   Result | แก้ไข Field   ส่วนลดรายการ ระบบแจ้งเตือน "สินค้าไม่เพียงพอ"
  |  
Expected   Result | ต้องสามรถแก้ไข   Field ส่วนลดหลังรายการ ได้
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/56889141-d9ec5800-6a9f-11e9-9efd-649499b1d681.png)
![image](https://user-images.githubusercontent.com/45878758/56889144-dc4eb200-6a9f-11e9-9545-3c2f2aa8d0b6.png)
![image](https://user-images.githubusercontent.com/45878758/56889151-deb10c00-6a9f-11e9-8061-56bd2ceecfcb.png)
![image](https://user-images.githubusercontent.com/45878758/56889156-e07acf80-6a9f-11e9-8c7b-a80b4c3f2ff4.png)
![image](https://user-images.githubusercontent.com/45878758/56889159-e2dd2980-6a9f-11e9-8be7-fc048f02357a.png)
![image](https://user-images.githubusercontent.com/45878758/56889176-eb356480-6a9f-11e9-9d99-77d11bee9171.png)
![image](https://user-images.githubusercontent.com/45878758/56889183-f12b4580-6a9f-11e9-8721-aad5f7da542e.png)

**Comment by Patthamaporn** [comment]
แก้ไข สามารถใส่ส่วนลดรายการได้โดยที่ไม่แจ้งเตือนสินค้าไม่เพียงพอ
