### ISSUE TITLE
[รายการขาย][แก้ไข   หลังรายการ]ลบรายการสินค้าออก 1 รายการ Field ภาษีมูลค่าเพื่ม คำนวนณไม่ถูกต้อง   Field สุทธิ ไม่รวม ภาษีมูลค่าเพื่ม ให้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#295]
Summary   Name | [รายการขาย][แก้ไข   หลังรายการ]ลบรายการสินค้าออก 1 รายการ Field ภาษีมูลค่าเพื่ม คำนวนณไม่ถูกต้อง   Field สุทธิ ไม่รวม ภาษีมูลค่าเพื่ม ให้
-- | --
Defect No. |  295
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SaleInfo.aspx?dataId=12139&subDoc=7
Step | 1. Login   WMS on Chorme
  | 1.   เลือกเมนู งานประจำวัน
  | 2.   เลือกเมนูย่อย รายการขายสินค้า
  | 3. เลือก   ขายสด
  | 4.   แสดงหน้าจอ รายการขาย
  | 5. กดปุ่ม   เพิ่มรายการขาย
  | 6.   กรอกข้อมูลใน Field ทั้งหมด
  | 7. กดปุ่ม   บันทึก
  | 8.   แสดงหน้าจอ รายการขาย
  | 9. กดปุ่ม   แก้ไข หลังรายการ
  | 10. กดปุ่ม   ค้นหาสินค้า
  | 11. แสดง   PopUp ค้นหาสินค้า
  | 12.   เลือกสินค้า
  | 13.   กรอกข้อมูลใน Field
  | จำนวนสั่ง
  | ราคาสั่ง
  | ส่วนลดรายการ
  | ภาษีมูลค่าเพิ่ม
  | 11. กดปุ่ม   ลบ หลังรายการ
  | 12. กดปุ่ม   ตกลง
  |  
Actual   Result | ลบรายการสินค้าออก 1   รายการ Field ภาษีมูลค่าเพื่ม คำนวนณไม่ถูกต้อง Field สุทธิ ไม่รวม   ภาษีมูลค่าเพื่ม ให้
  |  
Expected   Result | ลบรายการสินค้าออก 1   รายการ Field ภาษีมูลค่าเพื่ม ต้องคำนวณถูกต้อง Field สุทธิ ต้องรวม   ภาษีมูลค่าเพื่ม
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/56891819-e8d70880-6aa7-11e9-9370-af3f2d948b2f.png)
![image](https://user-images.githubusercontent.com/45878758/56891823-eaa0cc00-6aa7-11e9-9ac3-d87fd3c8da32.png)
![image](https://user-images.githubusercontent.com/45878758/56891827-ec6a8f80-6aa7-11e9-8d31-6d4affe79647.png)
![image](https://user-images.githubusercontent.com/45878758/56891830-ee345300-6aa7-11e9-965a-5111a2156b0b.png)
![image](https://user-images.githubusercontent.com/45878758/56891833-f12f4380-6aa7-11e9-872c-83254e46e21b.png)
![image](https://user-images.githubusercontent.com/45878758/56891838-f5f3f780-6aa7-11e9-90b2-bdb35405f21a.png)
![image](https://user-images.githubusercontent.com/45878758/56891846-fdb39c00-6aa7-11e9-93d0-25291031e250.png)

**Comment by Patthamaporn** [comment]
แก้ไข การคำนวณราคาทั้งหมด
![image](https://user-images.githubusercontent.com/37695403/56953186-24d0a300-6b66-11e9-83cd-62d9210a75fd.png)
