### ISSUE TITLE
[สินค้า]สอบถาม field ที่หายไปค่ะ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#296]
Summary   Name | [สินค้า]สอบถาม   field ที่หายไปค่ะ
-- | --
Date/Time | 30/4/2562
Version | 2018 © WMS by Logis Pro   Solution co., Ltd. AT-Social!
Defect No. |  
URL | http://nps001.homeip.net:8085/SkuInfo.aspx
Question | สาม   field นี้ซ่อนไม่ให้ใช้ หรือตัดออกคะ
  | -   Field หน่วยเติมเต็ม
  | -   Field หน่วยซื้อ
  | -   Field คลังจัดเก็บ
  |  
Remark |  

![image](https://user-images.githubusercontent.com/45878758/56953810-8d6c4f80-6b67-11e9-8ce5-082d626ca260.png)
![image](https://user-images.githubusercontent.com/45878758/56955712-5f3d3e80-6b6c-11e9-9e9a-789823132a1c.png)

**Comment by logisprosolution** [comment]
ปิดการใช้งานไปก่อนครับ อนาคตอาจได้ใช้
