### ISSUE TITLE
ข้อมูลรหัสซื้อขาย

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#297]
ใน Blog ราคาสินค้า
- ไม่แสดง Column ภาษี ที่ตารางแสดงผล นำออกใช่มั้ยคะ
URL : http://nps001.homeip.net:8085/GoodsInfo.aspx?dataId2=4055
![image](https://user-images.githubusercontent.com/45878758/56956185-9a8c3d00-6b6d-11e9-85e9-866237f0f377.png)
![image](https://user-images.githubusercontent.com/45878758/56956202-a546d200-6b6d-11e9-9bca-42af8121a872.png)

**Comment by logisprosolution** [comment]
เอาออกไปก่อนครับ ยังไม่ใช้
