### ISSUE TITLE
CheckerIn

### ISSUE THREAD

**Issue by logisprosolution** [logisprosolution/WMS#30]
- CheckerInList
  -- select * from [Doc_DocInfo] where [docTypeID] = 1(ซื้อ) and approve_date != null and [docStatusID] =1 and [subDocTypeID] =21
 -- if subDocTypeID =21 and docinfo.docStatusID != 1 show editing button
- CheckerInInfo
--show header but disable editing also can remark
 -- load list and header from Doc_DocInfo where id
 -- checkbox in grid (uncheck default)   (event)checked_changed
 -- use textbox add barcord to check grid  (function)find barcode and check
 -- save new docinfo,header,detail ([subDocTypeID] = 21)
 -- if check detail save detail_status = 1
 -- if check all detail save docinfo.docStatusID = 1 else 7

**Comment by Patthamaporn** [comment]
list
ถ้า docStatusID  ไม่ใช่1 จะต้องมีปุ่มให้แก้ไข
info
เพิ่ม remark
checkbox อยุ่ข้างหลัง ไม่ต้องติก
ใช้บาร์โค้ดค้นหาไอดีสินค้า ถ้าเจอสินค้าจะติกอัตโนมัติ
ถ้าเจอสินค้าแล้วเปลี่ยนDetail เป็น1
ถ้าDetailทั้งหมดเป็น1 ตอนเซฟ docStatusID ก็ต้องเป็น1

**Comment by Patthamaporn** [comment]
wait for test
