### ISSUE TITLE
[รายการหมวดย่อย][แก้ไข หลังรายการ]แก้ไขหน้าจอเพิ่มหมวดย่อย

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#308]
Summary   Name | [รายการหมวดย่อย][แก้ไข หลังรายการ]แก้ไขหน้าจอเพิ่มหมวดย่อย
-- | --
Defect No. |  308
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SubCategoryInfo.aspx?dataId=1008&dataId2=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย หมวด
  | 4.   แสดงหน้าจอ รายการหมวดลัก
  | 5. กดปุ่ม   แก้ไข หลังรายการ
  | 6.   แสดงหน้าจอ เพิ่มหมมวดหลัก
  | 7. กดปุ่ม   แก้ไข หลังรายการ
  | 8.   แสดงหน้าจอ เพิ่มหมวดย่อย
  |  
Actual   Result | "รายการหมวดย่อย"   เป็น "รายการหวมดย่อย"
  |  
Expected   Result | "รายการหวมดย่อย"   ต้องเป็น "รายการหมวดย่อย"
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/57026345-ba059180-6c63-11e9-8b7d-d28373216419.png)
![image](https://user-images.githubusercontent.com/45878758/57026351-bbcf5500-6c63-11e9-8533-e50a23bcd453.png)
![image](https://user-images.githubusercontent.com/45878758/57026355-be31af00-6c63-11e9-9a45-f891e6c1044c.png)

**Comment by acryforever** [comment]
แก้ไข field
