### ISSUE TITLE
[รายการหมวดย่อย][ดู หลังรายการ]แก้ไขหน้าจอเพิ่มหมวดย่อย และปุ่ม บันทึก

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#309]
Summary   Name | [รายการหมวดย่อย][ดู หลังรายการ]แก้ไขหน้าจอเพิ่มหมวดย่อย
-- | --
Defect No. |  309
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SubCategoryInfo.aspx?dataId=1008&dataId2=7
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย หมวด
  | 4.   แสดงหน้าจอ รายการหมวดลัก
  | 5. กดปุ่ม   แก้ไข หลังรายการ
  | 6.   แสดงหน้าจอ เพิ่มหมมวดหลัก
  | 7. กดปุ่ม   ดู หลังรายการ
  | 8.   แสดงหน้าจอ เพิ่มหมวดย่อย
  |  
Actual   Result | 1."รายการหมวดย่อย"   เป็น "รายการหวมดย่อย"
  | 2.มีปุ่ม บันทึก
  |  
Expected   Result | 1."รายการหวมดย่อย"   ต้องเป็น "รายการหมวดย่อย"
  | 2.ต้องไม่มี   ปุ่ม บันทึก
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/57026410-f33e0180-6c63-11e9-9029-f2dc5df02a02.png)
![image](https://user-images.githubusercontent.com/45878758/57026415-f5a05b80-6c63-11e9-8493-13c5b584cd98.png)
![image](https://user-images.githubusercontent.com/45878758/57026418-f802b580-6c63-11e9-9b42-75264ba65eae.png)

**Comment by Mickrepick** [comment]
แก้ไข : "รายการหวมดย่อย" ต้องเป็น "รายการหมวดย่อย"
เมื่อกดดูหลังรายการ ไม่มี ปุ่ม บันทึก

**Comment by Vermouthz** [comment]
Retest-failed 16/05/2562

ต้องไม่มี ปุ่ม บันทึก

![image](https://user-images.githubusercontent.com/45878758/57879105-e285b200-7845-11e9-9f29-98dda28b2e20.png)
![image](https://user-images.githubusercontent.com/45878758/57879118-e74a6600-7845-11e9-85a3-2b199a2228e7.png)
![image](https://user-images.githubusercontent.com/45878758/57879169-fa5d3600-7845-11e9-8f99-aeb4c0abbcf5.png)

**Comment by Vermouthz** [comment]
Retest-Failed 21/05/2562---------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/45878758/58093037-ce500500-7bf7-11e9-85e3-0fc67c2fc489.png)
![image](https://user-images.githubusercontent.com/45878758/58093057-d7d96d00-7bf7-11e9-9790-38d56c55e192.png)

**Comment by Vermouthz** [comment]
Retest-Failed 01/06/2562-------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/45878758/58750346-51584180-84bb-11e9-9a0a-3625a0bb76ea.png)
![image](https://user-images.githubusercontent.com/45878758/58750349-561cf580-84bb-11e9-8202-4c24a92cc1c3.png)

**Comment by Vermouthz** [comment]
Retest-Failed 06/06/2562---------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/45878758/59029087-8bdd2800-8887-11e9-97f5-76b07f57cd35.png)
![image](https://user-images.githubusercontent.com/45878758/59029091-8f70af00-8887-11e9-9b80-7322a0743528.png)
