### ISSUE TITLE
[รายการประเภทสินค้า]เมื่อกดปุ่ม   ลบ ระบบแสดง Message "ทำการยืนยัน ที่จะบันทึกข้อมูล ?"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#311]
Summary   Name | [รายการประเภทสินค้า]เมื่อกดปุ่ม   ลบ ระบบแสดง Message "ทำการยืนยัน ที่จะบันทึกข้อมูล ?"
-- | --
Defect No. |  311
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SkuTypeList.aspx?menuID=38
Step | 1. Login WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย ประเภทสินค้า
  | 4.   แสดงหน้าจอ รายการประเภทสินค้า
  | 5. กดปุ่ม   ลบ หลังรายการ
  | 6. กดปุ่ม   OK
  |  
Actual   Result | เมื่อกดปุ่ม ลบ   ระบบแสดง Message "ทำการยืนยัน ที่จะบันทึกข้อมูล ?"
  |  
Expected   Result | เมื่อกดปุ่ม ลบ   ระบบแสดง Message "ทำการยืนยัน ที่จะลบข้อมูล?"
  |  
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/57026679-8bd48180-6c64-11e9-803b-1ec87a83d6e7.png)
![image](https://user-images.githubusercontent.com/45878758/57026685-8e36db80-6c64-11e9-882e-2acd1e7f1a96.png)

**Comment by Mickrepick** [comment]
แก้ไข : เมื่อกดปุ่ม ลบ ระบบจะแสดง Message "ทำการยืนยัน ที่จะลบข้อมูล?"
