### ISSUE TITLE
[รายการหมวดสินค้า][เพิ่มหมวดหลักสินค้า]เมื่อกดปุ่มบันทึก   ระบบไม่ขึ้นข้อความแจ้งเตือน

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#312]
Summary   Name | [รายการหมวดสินค้า][เพิ่มหมวดหลักสินค้า]เมื่อกดปุ่มบันทึก   ระบบไม่ขึ้นข้อความแจ้งเตือน
-- | --
Defect No. |  312
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/CategoryInfo.aspx?dataId=2045&view=1
Step | 1. Login WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย หมวด
  | 4.   แสดงหน้าจอ รายการหมวดสินค้า
  | 5. กดปุ่ม   เพิ่มหมวดลักสินค้า
  | 6.   แสดงหน้าจอ เพิ่มหมวดสินค้า
  | 7.   ระบุข้อมูลใน field
  | - รหัส
  | -   ชื่อภาษาไทย
  | -   ชื่อภาษาอังกฤษ
  | -   ลำดับการจัดเรียง
  | -   ประเภทสินค้า
  | - สถานะ
  | - รูป
  | -   รายละเอียด
  | 8. กดปุ่ม   บันทึก
  | 9.   บันทึกสำเร็จ
  |  
Actual   Result | เมื่อกดปุ่มบันทึก   ระบบไม่ขึ้นข้อความแจ้งเตือน
  |  
Expected   Result | เมื่อกดปุ่มบันทึก   ระบบแจ้งเตือน "ทำการยืนยัน ที่จะบันทึก?"
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/57026771-c1796a80-6c64-11e9-94e7-7311ecc959f9.png)
![image](https://user-images.githubusercontent.com/45878758/57026774-c3dbc480-6c64-11e9-9613-374a88d4ee68.png)
![image](https://user-images.githubusercontent.com/45878758/57026776-c63e1e80-6c64-11e9-800c-8792c3576320.png)

**Comment by Mickrepick** [comment]
แก้ไข : เมื่อกดปุ่มบันทึก ระบบจะแจ้งเตือน Message "ทำการยืนยัน ที่จะบันทึก?"
