### ISSUE TITLE
[รายการหมวดย่อยสินค้า][เพิ่มรายการหมวดย่อยสินค้า]เมื่อกดปุ่ม บันทึก ระบบไม่แสดง Message "ทำการยืนยัน ที่จะบันทึก?"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#313]
Summary   Name | [รายการหมวดย่อยสินค้า][เพิ่มรายการหมวดย่อยสินค้า]เมื่อกดปุ่ม   บันทึก ระบบไม่แสดง Message "ทำการยืนยัน ที่จะบันทึก?"
-- | --
Defect No. |  313
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SubCategoryInfo.aspx?dataId2=2050
Step | 1. Login WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย หมวด
  | 4.   แสดงหน้าจอ รายการหมวดสินค้า
  | 5. กดปุ่ม   แก้ไข หลังรายการ
  | 6.   แสดงหน้าจอ เพิ่มหมวดสินค้า
  | 7. แสดง   Blog รายการหมวดย่อย
  | 8. กดปุ่ม   เพิ่มหมวดย่อยสินค้า
  | 9.   แสดงหน้าจอ เพิ่มหมวดย่อย
  | 10.   ระบุข้อมูลใน field
  | - รหัส
  | -   ชื่อภาษาไทย
  | -   ชื่อภาษาอังกฤษ
  | -   ลำดับการจัดเรียง
  | - สถานะ
  | - รูป
  | -   รายละเอียด
  | 11. กดปุ่ม   บันทึก
  | 12.   บันทึกสำเร็จ
Actual   Result | เมื่อกดปุ่ม บันทึก   ระบบไม่แสดง Message "ทำการยืนยัน ที่จะบันทึก?"
  |  
Expected   Result | เมื่อกดปุ่ม บันทึก   ระบบต้องแสดง Message "ทำการยืนยัน ที่จะบันทึก?"
  | - Cancel
  | - Ok
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/57026910-187f3f80-6c65-11e9-95d5-5a021ffaae99.png)
![image](https://user-images.githubusercontent.com/45878758/57026913-1ae19980-6c65-11e9-87c2-e4b194799c96.png)
![image](https://user-images.githubusercontent.com/45878758/57026918-1ddc8a00-6c65-11e9-986a-7e1b7cde93a4.png)

**Comment by Mickrepick** [comment]
แก้ไข : เมื่อกดปุ่ม บันทึก ระบบจะแสดง Message "ทำการยืนยัน ที่จะบันทึก?"
