### ISSUE TITLE
[รายการหมวดย่อย][เพิ่มรายการหมวดย่อย]เมื่อเลือก   สถานะ เป็น ปิดใช้งาน กดบันทึกแล้ว ไม่มีรายการใน column แสดงผล

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#316]
Summary   Name | [รายการหมวดย่อย][เพิ่มรายการหมวดย่อย]เมื่อเลือก   สถานะ เป็น ปิดใช้งาน กดบันทึกแล้ว ไม่มีรายการใน column แสดงผล
-- | --
Defect No. |  316
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SubCategoryInfo.aspx?dataId2=2050
Step | 1. Login WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย หมวด
  | 4.   แสดงหน้าจอ รายการหมวดสินค้า
  | 5. กดปุ่ม   แก้ไข หลังรายการ
  | 6.   แสดงหน้าจอ เพิ่มหมวดสินค้า
  | 7. แสดง   Blog รายการหมวดย่อย
  | 8.   กรอกข้อมูลใน field
  | - รหัส   "20 ตัวอักษร"
  | -   ชือภาษาไทย "100 ตัวอักษร"
  | -   ชือ่ภาษาอังกฤษ "100 ตัวอักษร"
  | -   ลำดับการจัดเรียง "10,000"
  | - สถานะ   "ปิดใช้งาน"
  | - รูป   "เลือกรูปภาพ"
  | -   รายละเอียด "300 ตัวอักษร"
  | 9. กดปุ่ม   บันทึก
  | 10.   บันทึกสำเร็จ
  | 11.   แสดงหน้าจอ รายการหมวดหลักสินค้า
  |  
Actual   Result | เมื่อเลือก สถานะ เป็น   ปิดใช้งาน กดบันทึกแล้ว ไม่มีรายการใน column แสดงผล
  |  
Expected   Result | เมื่อเลือก สถานะ เป็น   ปิดใช้งาน กดบันทึกแล้ว ต้องมีรายการใน column แสดงผล
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/57027199-f5a15b00-6c65-11e9-9117-0ab21554eb31.png)
![image](https://user-images.githubusercontent.com/45878758/57027202-f76b1e80-6c65-11e9-8587-8edcd8099d2f.png)
![image](https://user-images.githubusercontent.com/45878758/57027206-f934e200-6c65-11e9-8b1b-5e1d5a05ca05.png)
![image](https://user-images.githubusercontent.com/45878758/57027211-fcc86900-6c65-11e9-86a5-c24aa804e05c.png)

**Comment by acryforever** [comment]
![s3](https://user-images.githubusercontent.com/47658214/57118591-82473880-6d8e-11e9-954c-511fb7c7a149.png)

รายการ สถานะมีแต่ข้อมูลเปิดใช้งาน และไม่มีข้อมูลปิดใช้งาน"แก้ไข สโตร์"
