### ISSUE TITLE
[เพิ่ม location   Picking]ไม่กรอกข้อมูล field mandatory ระบบแสดงข้อความไม่ถูกต้อง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#321]
Summary   Name | [เพิ่ม location   Picking]ไม่กรอกข้อมูล field mandatory ระบบแสดงข้อความไม่ถูกต้อง
-- | --
Defect No. |  321
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/LocationInfo.aspx
Step | 1. Login WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย รายการตำแหน่งจัดเก็บ
  | 4.   แสดงหน้าจอ Location Picking
  | 5. กดปุ่ม   เพิ่ม location picking
  | 6.   แสดงหน้าจอ Location
  | 7.   ไม่ระบุข้อมูลใน field
  | - รหัส
  | -   ชือภาษาไทย
  | - คลัง
  | - โซน
  | -   ประเภทการจัดเก็บ
  | 8. กดปุ่ม   บันทึก
  | 9. กดปุ่ม   OK
  |  
Actual   Result | 1.ไม่กรอกข้อมูล Field   คลัง,โซน ระบบแสดงข้อความแจ้งเตือนไม่ถูกต้อง
  | 2.ไม่กรอกข้อมูล field   mandatory ระบบแสดงข้อความด้านล่างไม่ถูกต้อง
  |  
Expected   Result | 1.ไม่กรอกข้อมูล Field   คลัง,โซน ระบบต้องแสดงข้อความ
  | - กรุณากรอกข้อมูล   คลัง
  | - กรุณากรอกข้อมูล โซน
  | 2.ไม่กรอกข้อมูล   field mandatory ระบบแสดงข้อความ     "ไม่สามารถบันทึกข้อมูลได้ :"
  | -   กรุณากรอกข้อมูล รหัส
  | -   กรุณากรอกข้อมูล ชื่อภาษาไทย
  | -   กรุณากรอกข้อมูล คลัง
  | -   กรุณากรอกข้อมูล โซน
  | -   กรุณากรอกข้อมูล ประเภทการจัดเก็บ
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/57073627-d1985500-6d0b-11e9-95d8-37407debfd22.png)
![image](https://user-images.githubusercontent.com/45878758/57073629-d3621880-6d0b-11e9-88d1-0b4fe52fa839.png)
![image](https://user-images.githubusercontent.com/45878758/57073640-db21bd00-6d0b-11e9-9d03-91a6672b6161.png)

**Comment by acryforever** [comment]
แก้ไข Field
