### ISSUE TITLE
[รายการประเภทการจัดเก็บ]เลือกเรียงจาก   น้อยไปมาก ระบบเรียง ลำดับการจัดเรียง ไม่ถูกต้อง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#324]
Summary   Name | [รายการประเภทการจัดเก็บ]เลือกเรียงจาก   น้อยไปมาก ระบบเรียง ลำดับการจัดเรียง ไม่ถูกต้อง
-- | --
Defect No. |  324
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/LocationTypeList.aspx?menuID=72
Step | 1. Login WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย รายการประเภทตำแหน่งจัดเก็บ
  | 4.   แสดงหน้าจอ รายการประเภทการจัดเก็บ
  | 5.   ไม่กรอกข้อมูลใน field
  | -   ค้นหา:รหัส/ชื่อ
  | 6.   ระบุข้อมูลใน Field
  | -   ลำดับการจัดเรียง "น้อยไปมาก"
  | - สถานะ   "ทั้งหมด"
  | 7. กดปุ่ม   ค้นหา หรือ Enter
  |  
Actual   Result | ระบบเรียง   ลำดับการจัดเรียง ไม่ถูกต้อง
  |  
Expected   Result | ระบบต้องเรียง   ลำดับการจัดเรียง น้อยไปมาก
  |  
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/57073864-89c5fd80-6d0c-11e9-9ebe-b9a0a110405c.png)
![image](https://user-images.githubusercontent.com/45878758/57073868-8b8fc100-6d0c-11e9-9795-d910ad500cc0.png)
![image](https://user-images.githubusercontent.com/45878758/57073871-8d598480-6d0c-11e9-9147-d3e2b0f317ac.png)
![image](https://user-images.githubusercontent.com/45878758/57073874-8f234800-6d0c-11e9-9747-320138e3e366.png)

**Comment by acryforever** [comment]
แก้ไข้ Store
