### ISSUE TITLE
[สินค้า][รายการรหัสซื้อขาย]สอบถาม   Column จำนวนคืออะไรคะ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#327]
Summary   Name | [สินค้า][รายการรหัสซื้อขาย]สอบถาม   Column จำนวนคืออะไรคะ
-- | --
Date/Time | 5/4/2562
Version | 2018 © WMS by Logis Pro   Solution co., Ltd. AT-Social!
Defect No. |  327
URL | http://nps001.homeip.net:8085/SkuInfo.aspx?dataId=4055
Question | 1 จำนวน คือ   จำนวนสินค้า ใช่มั้ยคะ
  | 2.   เมื่อกดสร้าง รหัสซื้อขาย Column จำนวน แสดงเป็น "0"
  | 3.   เมื่อสั่งซื้อสินค้า 100 ชิ้น Column จำนวน แสดงเป็น "100"
  |  
  |  
Remark |  

![image](https://user-images.githubusercontent.com/45878758/57158487-c0d00800-6e0d-11e9-9b34-fa1e01e41179.png)

**Comment by logisprosolution** [comment]
ใช่ครับ แต่ต้องโชว์เป็นคลัง
คลัง1 (50) , คลัง2 (20) , คลัง3(30)
