### ISSUE TITLE
[สินค้า][เพิ่มรหัสซื้อขาย]สอบถาม   field ส่วนลด และส่วนเพิ่ม ต้องดึงไปแสดงใน ใบสั่งซื้อสินค้ามั้ยคะ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#329]
Summary   Name | [สินค้า][เพิ่มรหัสซื้อขาย]สอบถาม   field ส่วนลด และส่วนเพิ่ม ต้องดึงไปแสดงใน ใบสั่งซื้อสินค้ามั้ยคะ
-- | --
Date/Time | 5/4/2562
Version | 2018 © WMS by Logis Pro   Solution co., Ltd. AT-Social!
Defect No. |  329
URL | http://nps001.homeip.net:8085/GoodsInfo.aspx?dataId=1041&dataId2=4055
URL | http://nps001.homeip.net:8085/PurchaseInfo.aspx?subDoc=18
Question | Field ส่วนลด   และ field ส่วนเพิ่ม เมื่อคั้งค่าไว้ ต้องดึงไปแสดงในหน้าจอ   สั่งซื้อสินค้ามั้ยคะ
  |  
  |  
  |  
  |  
Remark |  

![image](https://user-images.githubusercontent.com/45878758/57158991-08a35f00-6e0f-11e9-9af7-324a3a3c97ba.png)

**Comment by logisprosolution** [comment]
เอาไว้ เดี๋ยว เตือนพี่อีกทีนะ ตอนนี้ยังไม่ทำ
