### ISSUE TITLE
[รายการตำแหน่งจัดเก็บ][เพิ่ม   Location]สอบถาม ไม่มีปุ่ม เพิ่มพาเลท หรอคะ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#330]
Summary   Name | [รายการตำแหน่งจัดเก็บ][เพิ่ม   Location]สอบถาม ไม่มีปุ่ม เพิ่มพาเลท หรอคะ
-- | --
Date/Time | 5/4/2562
Version | 2018 © WMS by Logis Pro   Solution co., Ltd. AT-Social!
Defect No. |  330
URL | http://nps001.homeip.net:8085/LocationInfo.aspx?dataId=2
Question | ไม่มีปุ่มเพิ่ม   พาเลท หรอคะ
  |  
  |  
  |  
  |  
Remark |  

![image](https://user-images.githubusercontent.com/45878758/57162705-38576480-6e19-11e9-91c2-dab5070597fd.png)

**Comment by logisprosolution** [comment]
ไม่มีเพิ่มครับ เพิ่มจากหน้านำเข้า
แต่ถ้านำเข้าไปใน location นั้นแล้ว จะต้องโชว์ครับ
