### ISSUE TITLE
[ใบสั่งซื้อ][แก้ไข   หลังรายการ] เพิ่มสินค้า 1 รายการ แต่เมื่อบันทึก ระบบแสดง 3 รายการ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#335]
Summary   Name | [ใบสั่งซื้อ][แก้ไข   หลังรายการ] เพิ่มสินค้า 1 รายการ แต่เมื่อบันทึก ระบบแสดง 3 รายการ
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  335
URL | http://nps001.homeip.net:8085/PurchaseInfo.aspx?dataId=12141&subDoc=18
  | http://nps001.homeip.net:8085/SkuInfo.aspx?dataId=4055
  |  
Step | 1. Login
  | 2. เลือกเมนู ตั้งค่า
  | 3. เลือกเมนูย่อย   สินค้า
  | 4. แสดงหน้าจอ   รายการสินค้า
  | 5. กดปุ่ม แก้ไข   หลังรายการ
  | 6. แสดงหน้าจอ   ข้อมูลสินค้า
  | 7. กดปุ่ม   เพิ่มรหัสซื้อขาย
  | 8. แสดงหน้าจอ   เพิ่มรหัสซื้อขาย
  | 9. สร้างสินค้า 1   รายการ "APS2003 กล้องสีเขียว ระบบออโต้ ลังx24"
  | 10. กดปุ่ม บันทึก
  | 11. บันทึกสำเร็จ
  | 12. เลือกเมนู   งานประจำวัน
  | 13. เลือกเมนูย่อย   ใบสั่งซื้อสินค้า
  | 14. เลือก   สั่งซื้อทั่วไป
  | 15. แสดงหน้าจอ   รายการใบสั่งซื้อสินค้า
  | 16. กดปุ่ม   เพิ่มใบสั่งซื้อ
  | 17. แสดงหน้าจอ   ใบสั่งซื้อ
  | 18. เลือกคู่ค้า
  | 19. กดปุ่ม   ค้นหาสินค้า
  | 20. เลือกสินค้า 1   รายการ "APS2003 กล้องสีเขียว ระบบออโต้ ลังx24"
  | 21. กรอก   จำนวนสั่งซื้อ "100"
  | 22. กดปุ่ม บันทึก
  | 23. บันทึกสำเร็จ
  | 24. แสดงหน้าจอ   รายการใบสั่งซื้อสินค้า
  | 25. กดปุ่ม แก้ไข   หลังรายการ
  |  
  |  
Actual   Result | เมื่อเพิ่มสินค้า 1   รายการ และกดบันทึก ระบบแสดง 3 รายการ
  |  
Expected   Result | ระบบต้องแสดงตามรายการที่เพิ่ม   เมื่อเพิ่ม 1 รายการ ก็ต้องแสดง 1 รายการ
  |  

![image](https://user-images.githubusercontent.com/45878758/57176488-f3681800-6e82-11e9-815a-4c689b026a16.png)
![image](https://user-images.githubusercontent.com/45878758/57176493-f95df900-6e82-11e9-9f94-d67abc6f4d24.png)
![image](https://user-images.githubusercontent.com/45878758/57176494-fbc05300-6e82-11e9-8923-c9e9e635edc6.png)
![image](https://user-images.githubusercontent.com/45878758/57176496-fd8a1680-6e82-11e9-8d96-7efba5c6588f.png)
![image](https://user-images.githubusercontent.com/45878758/57176498-ffec7080-6e82-11e9-8b38-6c07c7d21d5c.png)
![image](https://user-images.githubusercontent.com/45878758/57176501-024eca80-6e83-11e9-8642-f2aea79435f3.png)

**Comment by acryforever** [comment]
เกิดจากติ๊ก ค่าตั้งต้น พาเลทมากกว่าหนึ่งรายการในหน้าสิ้นค้า จึงต้องแก้ไข สิ้นค้า มีเพลียง 1 พาเลท
