### ISSUE TITLE
[ใบสั่งซื้อ][ดู   หลังรายการ] เพิ่มสินค้า 1 รายการ แต่เมื่อบันทึก ระบบแสดง 3 รายการ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#336]
Summary   Name | [ใบสั่งซื้อ][ดู   หลังรายการ] เพิ่มสินค้า 1 รายการ แต่เมื่อบันทึก ระบบแสดง 3 รายการ
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  336
URL | http://nps001.homeip.net:8085/PurchaseInfo.aspx?dataId=12141&view=1
  | http://nps001.homeip.net:8085/SkuInfo.aspx?dataId=4055
  |  
Step | 1. Login
  | 2. เลือกเมนู ตั้งค่า
  | 3. เลือกเมนูย่อย   สินค้า
  | 4. แสดงหน้าจอ   รายการสินค้า
  | 5. กดปุ่ม แก้ไข   หลังรายการ
  | 6. แสดงหน้าจอ   ข้อมูลสินค้า
  | 7. กดปุ่ม   เพิ่มรหัสซื้อขาย
  | 8. แสดงหน้าจอ   เพิ่มรหัสซื้อขาย
  | 9. สร้างสินค้า 1   รายการ "APS2003 กล้องสีเขียว ระบบออโต้ ลังx24"
  | 10. กดปุ่ม บันทึก
  | 11. บันทึกสำเร็จ
  | 12. เลือกเมนู   งานประจำวัน
  | 13. เลือกเมนูย่อย   ใบสั่งซื้อสินค้า
  | 14. เลือก   สั่งซื้อทั่วไป
  | 15. แสดงหน้าจอ   รายการใบสั่งซื้อสินค้า
  | 16. กดปุ่ม   เพิ่มใบสั่งซื้อ
  | 17. แสดงหน้าจอ   ใบสั่งซื้อ
  | 18. เลือกคู่ค้า
  | 19. กดปุ่ม   ค้นหาสินค้า
  | 20. เลือกสินค้า 1   รายการ "APS2003 กล้องสีเขียว ระบบออโต้ ลังx24"
  | 21. กรอก   จำนวนสั่งซื้อ "100"
  | 22. กดปุ่ม บันทึก
  | 23. บันทึกสำเร็จ
  | 24. แสดงหน้าจอ   รายการใบสั่งซื้อสินค้า
  | 25. กดปุ่ม ดู   หลังรายการ
  |  
  |  
Actual   Result | เมื่อเพิ่มสินค้า 1   รายการ และกดบันทึก ระบบแสดง 3 รายการ
  |  
Expected   Result | ระบบต้องแสดงตามรายการที่เพิ่ม   เมื่อเพิ่ม 1 รายการ ก็ต้องแสดง 1 รายการ
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/57176525-4c37b080-6e83-11e9-937b-e1872ecdc9a7.png)
![image](https://user-images.githubusercontent.com/45878758/57176527-50fc6480-6e83-11e9-9076-c35173d7c4c4.png)
![image](https://user-images.githubusercontent.com/45878758/57176529-55288200-6e83-11e9-8947-9195c0249fdd.png)
![image](https://user-images.githubusercontent.com/45878758/57176531-58237280-6e83-11e9-929d-ed3402dd5613.png)
![image](https://user-images.githubusercontent.com/45878758/57176532-59ed3600-6e83-11e9-9ea6-4ce56b6bef0e.png)
![image](https://user-images.githubusercontent.com/45878758/57176534-5c4f9000-6e83-11e9-9e2a-4cb28651a9d2.png)

**Comment by acryforever** [comment]
เกิดจากติ๊ก ค่าตั้งต้น พาเลทมากกว่าหนึ่งรายการในหน้าสิ้นค้า จึงต้องแก้ไข สิ้นค้า มีเพลียง 1 พาเลท
