### ISSUE TITLE
[เพิ่มรหัสซื้อขาย][เพิ่มราคาสินค้า]สอบถาม   ประเภทราคาขาย เมื่อเลือกจะดึง ราคาไปแสดงใน ใบสั่งซื้อมั้ยคะ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#338]
Summary   Name | [เพิ่มรหัสซื้อขาย][เพิ่มราคาสินค้า]สอบถาม   ประเภทราคาขาย เมื่อเลือกจะดึง ราคาไปแสดงใน ใบสั่งซื้อมั้ยคะ
-- | --
Date/Time | 5/4/2562
Version | 2018 © WMS by Logis Pro   Solution co., Ltd. AT-Social!
Defect No. |  338
URL | http://nps001.homeip.net:8085/GoodsInfo.aspx?dataId=1041&dataId2=4055
  | http://nps001.homeip.net:8085/PurchaseInfo.aspx?subDoc=18
Question | 1. ถ้าสร้าง   ราคาขายไว้มากกว่า 1  รายการ   เมื่อเลือกสินค้า ราคาสั่งจะถึง ราคาไหนมาแสดง และอ้างอิงจากอะไรคะ
  | 2.   ถ้ามีการกำหนด field สวนลด , ส่วนเพิ่มในตั้งค่าไว้ จะดึงมาแสดงใน   หน้าจอใบสั่งซื้อมั้ยคะ
  |  
  |  
Remark |  

![image](https://user-images.githubusercontent.com/45878758/57176908-42fd1280-6e88-11e9-8b42-b76c2a81f58b.png)
![image](https://user-images.githubusercontent.com/45878758/57176909-455f6c80-6e88-11e9-8073-96ce8fce278b.png)
![image](https://user-images.githubusercontent.com/45878758/57176911-46909980-6e88-11e9-8130-3c2dd529f6be.png)

**Comment by logisprosolution** [comment]
จะต้องมี default ราคาด้วย

**Comment by logisprosolution** [comment]
ยัง ไม่โชว์ส่วนลด ส่วนเพิ่มครับ ติดไว้ก่อนนะ
