### ISSUE TITLE
รายการหมวดสินค้า_Column ลำดับการจัดเรียง ไม่เรียงลำดับจาก "มากไปน้อย" และ "น้อยไปมาก"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#340]
Summary   Name | รายการหมวดสินค้า_Column   ลำดับการจัดเรียง ไม่เรียงลำดับจาก "มากไปน้อย" และ   "น้อยไปมาก"
-- | --
Defect No. |  340
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/CategoryList.aspx?menuID=11
Step | 1. Login
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย หมวด
  | 4.   แสดงหน้าจอ รายการหมวดสินค้า
  | 5.   ไม่กรอกข้อมูลใน field
  | -   ค้นหา:รหัส/ชื่อ
  | 6.   ระบุข้อมูลใน Field
  | -   ลำดับการจัดเรียง "มากไปน้อย","น้อยไปมาก"
  | - สถานะ   "ทั้งหมด"
  | 7. กดปุ่ม ค้นหา หรือ   Enter
  |  
  |  
Actual   Result | Column   ลำดับการจัดเรียง ไม่เรียงลำดับจาก "มากไปน้อย" และ   "น้อยไปมาก"
  |  
  |  
Expected   Result | Column   ลำดับการจัดเรียง ต้องเรียงลำดับจาก "มากไปน้อย" และ   "น้อยไปมาก"
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/57184576-95b9e700-6ee7-11e9-9d2f-960c8205cdd8.png)
![image](https://user-images.githubusercontent.com/45878758/57184578-98b4d780-6ee7-11e9-8aed-38a8f65c62fb.png)

**Comment by acryforever** [comment]
แก้ไข store
