### ISSUE TITLE
 [Location   Picking]สอบถาม Screen และ field ประเภทสินค้าค้นหาจากอะไร แคะกำหนดค่าจากไหนคะ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#341]
Summary   Name | [Location   Picking]สอบถาม Screen และ field ประเภทสินค้าค้นหาจากอะไร แคะกำหนดค่าจากไหนคะ
-- | --
Date/Time | 5/5/2562
Version | 2018 © WMS by Logis Pro   Solution co., Ltd. AT-Social!
Defect No. |  
URL | http://nps001.homeip.net:8085/ZoneInfo.aspx?dataId=3004&dataId2=2009
Question | 1. field   ประเภทสินค้า กำหนดค่าจากไหน
  | 2.   field ประเภทสินค้า ใช้สำหรับค้นหาอะไรคะ แล้วเช็คจากตรงไหน   ถ้าเลือกสต็อกน้อยกว่าหรือเท่ากับ 0
  | 3.   Location Picking ต้องแสดงเหมือน เมนูรายการตำแหน่งจัดเก็บมั้ยคะ
  |  
  |  
Remark |  

![image](https://user-images.githubusercontent.com/45878758/57198426-d58ed600-6f9c-11e9-9c73-b70af6dfd3a6.png)

**Comment by logisprosolution** [comment]
เอาหน้า LocationList เป็นหลักครับ 
หน้าที่มาจากzone จะต้องเหมือน locationList ทุกอย่าง
