### ISSUE TITLE
Location_เมื่อกดเข้ามาในหน้าจอ Location ระบบแสดงหน้าจอยืดออกแล้วค่อยกลับมาเป็นปกติ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#344]
Summary   Name | Location_เมื่อกดเข้ามาในหน้าจอ   Location ระบบแสดงหน้าจอยืดออกแล้วค่อยกลับมาเป็นปกติ
-- | --
Defect No. |  344
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/LocationList.aspx?menuID=71
Step | 1. เลือกเมนู   "ตั้งค่า"
  | 2.   เลือกเมนูย่อย "รายการตำแหน่งจัดเก็บ"
  | 3.   แสดงหน้าจอ Location
  |  
  |  
Actual   Result | เมื่อกดเข้ามาในหน้าจอ   Location ระบบแสดงหน้าจอยืดออกแล้วค่อยกลับมาเป็นปกติ
  |  
  |  
Expected   Result | หน้าจอต้องไม่ยืดออก
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/57201853-98d8d400-6fc8-11e9-8c16-9df70900f531.png)
![image](https://user-images.githubusercontent.com/45878758/57201854-9b3b2e00-6fc8-11e9-948a-70a497557f24.png)
![image](https://user-images.githubusercontent.com/45878758/57201855-9d04f180-6fc8-11e9-88a4-d1169267d2b1.png)

**Comment by Mickrepick** [comment]
แก้ไขแล้วครับ
