### ISSUE TITLE
[เพิ่มรหัสซื้อขาย][แก้ไข   หลังรายการ]Field "คลัง","โซน" ไม่ดึงค่าที่บันทึกไว้มา

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#350]
Summary   Name | [เพิ่มรหัสซื้อขาย][แก้ไข   หลังรายการ]Field "คลัง","โซน" ไม่ดึงค่าที่บันทึกไว้มา
-- | --
Defect No. |  350
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/GoodsInfo.aspx?dataId=1052&dataId2=4071
  |  
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย สินค้า
  | 4.   แสดงหน้าจอ รายการสินค้า
  | 5. กดปุ่ม   แก้ไข หลังรายการ
  | 6.   แสดงหน้าจอ ข้อมูลสินค้า
  | 7. Blog   รายการรหัสซื้อขาย
  | 8. กดปุ่ม   เพิ่มรหัสซื้อขาย
  | 9.   แสดงหน้าจอ เพิ่มรหัสซื้อขาย
  | 10. เลือก   CheckBox "SKU"
  | 11. เลือก   การกำหนดตำแหน่งหยิบ "หาตามประเภทตำแหน่งเก็บ"
  | 12.   ระบุข้อมูลการกำหนดตำแหน่งหยิบใน field
  | -   ประเภทตำแหน่งเก็บ
  | 13. กดปุ่ม   บันทึก
  | 14.   บันทึกสำเร็จ
  | 15.   แสดงหน้าจอ ข้อมูลสินค้า
  | 16. กดปุ่ม   แก้ไข หลังรายการรหัสซื้อขาย
  | 17.   แสดงหน้าจอ เพิ่มรหัสซื้อขาย
  | 18.   ตรวจสอบ field
  | -   ประเภทตำแหน่งเก็บ
  |  
Actual   Result | Field   "คลัง","โซน" ไม่ดึงค่าที่บันทึกไว้มา
  |  
  |  
Expected   Result | Field   "คลัง","โซน" ต้องดึงค่าที่บันทึกไว้มา
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/57399577-bf328580-71fb-11e9-9531-5f41504924a8.png)
![image](https://user-images.githubusercontent.com/45878758/57399584-c22d7600-71fb-11e9-8d20-4110448ee765.png)
![image](https://user-images.githubusercontent.com/45878758/57399588-c48fd000-71fb-11e9-9dfd-e556a8a787da.png)
![image](https://user-images.githubusercontent.com/45878758/57399590-c6599380-71fb-11e9-8c9e-326fe5ddfa60.png)
![image](https://user-images.githubusercontent.com/45878758/57399608-cf4a6500-71fb-11e9-9908-098df9a55f86.png)

**Comment by Mickrepick** [comment]
แก้ไข : Field CheckBox "ใช้ข้อมูลSku" เมื่อติกเครื่องหมาย จะดึงข้อมูลจาก SUK ถูกต้อง

**Comment by Vermouthz** [comment]
Retest-Failed 21/05/2562----------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/45878758/58092607-bb890080-7bf6-11e9-9c24-1af9d8d750e2.png)
![image](https://user-images.githubusercontent.com/45878758/58092610-bd52c400-7bf6-11e9-86d2-31a8f10ad22a.png)
![image](https://user-images.githubusercontent.com/45878758/58092616-bfb51e00-7bf6-11e9-92a4-e5524db1d6cc.png)
![image](https://user-images.githubusercontent.com/45878758/58092635-c5aaff00-7bf6-11e9-8d36-4ed3d45cb307.png)

**Comment by Vermouthz** [comment]
Retest-Failed 01/06/2562----------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/45878758/58750274-74362600-84ba-11e9-8fd9-64e8a5c1e449.png)
![image](https://user-images.githubusercontent.com/45878758/58750275-75ffe980-84ba-11e9-91b3-3b6cf796ef6e.png)
![image](https://user-images.githubusercontent.com/45878758/58750277-77c9ad00-84ba-11e9-97b7-ca181e4e582e.png)
![image](https://user-images.githubusercontent.com/45878758/58750283-7d26f780-84ba-11e9-8df9-086af3b19bba.png)

**Comment by Vermouthz** [comment]
Retest-Failed 06/06/2562-----------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/45878758/59028914-0f4a4980-8887-11e9-92be-83a6f540564e.png)
![image](https://user-images.githubusercontent.com/45878758/59028916-107b7680-8887-11e9-83a5-c1bb188887f6.png)
![image](https://user-images.githubusercontent.com/45878758/59028918-12ddd080-8887-11e9-8963-53325a90b7a7.png)
![image](https://user-images.githubusercontent.com/45878758/59028926-183b1b00-8887-11e9-9be5-df7cbb75182b.png)
