### ISSUE TITLE
[เพิ่มรหัสซื้อขาย][แก้ไข   หลังรายการ]Field CheckBox "ใช้ข้อมูลSku" แสดงไม่ถูกต้อง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#351]
Summary   Name | [เพิ่มรหัสซื้อขาย][แก้ไข   หลังรายการ]Field CheckBox "ใช้ข้อมูลSku" แสดงไม่ถูกต้อง
-- | --
Defect No. |  351
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/GoodsInfo.aspx?dataId2=4071
  |  
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย สินค้า
  | 4.   แสดงหน้าจอ รายการสินค้า
  | 5. กดปุ่ม   แก้ไข หลังรายการ
  | 6.   แสดงหน้าจอ ข้อมูลสินค้า
  | 7. Blog   รายการรหัสซื้อขาย
  | 8. กดปุ่ม   เพิ่มรหัสซื้อขาย
  | 9.   แสดงหน้าจอ เพิ่มรหัสซื้อขาย
  | 10. เลือก   CheckBox "SKU"
  | 11.   ระบุข้อมูลใน field
  | - ประเภท   Packsize
  | 12. เลือก   การกำหนดตำแหน่งเก็บ "ระบุที่อยู่"
  | 13.   ระบุข้อมูลการกำหนดตำแหน่งเก็บใน field
  | - คลัง
  | - โซน
  | -   ตำแหน่งเก็บ
  | 14. กดปุ่ม   บันทึก
  | 15.   บันทึกสำเร็จ
  | 12.   แสดงหน้าจอ ข้อมูลสินค้า
  | 13. กดปุ่ม   แก้ไข หลังรายการรหัสซื้อขาย
  | 14.   แสดงหน้าจอ เพิ่มรหัสซื้อขาย
  | 15.   ตรวจสอบ field
  | - คลัง
  | - โซน
  | -   ตำแหน่งเก็บ
  |  
Actual   Result | Field CheckBox   "ใช้ข้อมูลSku" แสดงไม่ถูกต้อง
  |  
  |  
Expected   Result | Field CheckBox   "ใช้ข้อมูลSku" แสดงไม่ถูกต้อง ต้องมีเครื่องหมายติกเลือก
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/57399741-146e9700-71fc-11e9-8f8d-b54c3591f83d.png)
![image](https://user-images.githubusercontent.com/45878758/57399744-159fc400-71fc-11e9-8ea5-186aa6901c01.png)
![image](https://user-images.githubusercontent.com/45878758/57399746-18021e00-71fc-11e9-9850-a5fc7e22070d.png)
![image](https://user-images.githubusercontent.com/45878758/57399749-19cbe180-71fc-11e9-86ac-bbaf9489d924.png)
![image](https://user-images.githubusercontent.com/45878758/57399759-1e909580-71fc-11e9-80d8-f513948d8b3d.png)

**Comment by Mickrepick** [comment]
แก้ไข : Field CheckBox "ใช้ข้อมูลSku" เมื่อติกเครื่องหมาย จะดึงข้อมูลจาก SUK ถูกต้อง
