### ISSUE TITLE
[ข้อมูลสินค้า][เลือกคู่ค้า]แก้ไขหน้าจอ   PopUp ค้นหาคู่ค้า

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#353]
Summary   Name | [ข้อมูลสินค้า][เลือกคู่ค้า]แก้ไขหน้าจอ   PopUp ค้นหาคู่ค้า
-- | --
Defect No. |  353
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/PopupSKU_Supplier.aspx
Step | 1. Login WMS on Chorme
  | 2.เลือกเมนู   ตั้งค่า
  | 3.เลือกเมนูย่อย   สินค้า
  | 4.   แสดงหน้าจอ รายการสินค้า
  | 5. กดปุ่ม   เพิ่มสินค้า
  | 6.   แสดงหน้าจอ ข้อมูลสินค้า
  | 7. กด Tab   ผู้จัดจำหน่าย
  | 8. แสดง   Tab ผู้จัดจำหน่าย
  | 9. กดปุ่ม   เลือกคู่ค้า
  | 10. แสดง   PopUp ค้นหาคู่ค้า
  |  
Actual   Result | 1.Column   "รหัสคู่ค้า" เป็น "รหัสลูกค้า"
  | 2.Column   "ชื่อคู่ค้าภาษาไทย" เป็น "ชื่อลูกค้าภาษาไทย"
  | 3.Column   "ชื่อคู่ค้าภาษาอังกฤษ" เป็น "ชื่อลูกค้าภาษาอังกฤษ"
  |  
Expected   Result | 1.Column   "รหัสลูกค้า" ต้องเป็น "รหัสคู่ค้า"
  | 2.Column   "ชื่อลูกค้าภาษาไทย" ต้องเป็น "ชื่อคู่ค้าภาษาไทย"
  | 3.Column   "ชื่อลูกค้าภาษาอังกฤษ" ต้องเป็น "ชื่อคู่ค้าภาษาอังกฤษ"
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/57400048-cd34d600-71fc-11e9-8965-66076cee5cfb.png)
![image](https://user-images.githubusercontent.com/45878758/57400061-d58d1100-71fc-11e9-9b10-fe600849206a.png)

**Comment by Mickrepick** [comment]
แก้ไข : 
1.Column "รหัสลูกค้า" ต้องเป็น "รหัสคู่ค้า"
2.Column "ชื่อลูกค้าภาษาไทย" ต้องเป็น "ชื่อคู่ค้าภาษาไทย"
3.Column "ชื่อลูกค้าภาษาอังกฤษ" ต้องเป็น "ชื่อคู่ค้าภาษาอังกฤษ"
