### ISSUE TITLE
[เพิ่มสินค้า][Tab   ข้อมูลสินค้า]แก้ไขหน้าจอข้อมูลสินค้า

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#354]
Summary   Name | [เพิ่มสินค้า][Tab   ข้อมูลสินค้า]แก้ไขหน้าจอข้อมูลสินค้า
-- | --
Defect No. |  354
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SkuInfo.aspx
Step | 1. Login WMS on Chorme
  | 2.เลือกเมนู   ตั้งค่า
  | 3.เลือกเมนูย่อย   สินค้า
  | 4.   แสดงหน้าจอ รายการสินค้า
  | 5. กดปุ่ม   เพิ่มสินค้า
  | 6.   แสดงหน้าจอ ข้อมูลสินค้า
  | 7. กด Tab   ข้อมูลสินค้า
  | 8. แสดง   Tab ข้อมูลสินค้า
  |  
Actual   Result | 1.ไม่มี Field ค้นหา   "สถานะ"
  | 2.ไม่มี Column แสดงผล   "สถานะ"
  |  
Expected   Result | 1.เพิ่ม Field ค้นหา   "สถานะ" ระบบแสดงรายการเลือก
  | - ทั้งหมด
  | - ใช้งาน
  | -   ปิดใช้งาน
  | 2.เพิ่ม Column แสดงผล   "สถานะ" ระบบแสดงรายการ
  | - เครื่องหมายถูก
  | - เครื่องหมายกากบาท
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/57400134-0705dc80-71fd-11e9-9c6b-7e1fda990570.png)
![image](https://user-images.githubusercontent.com/45878758/57439003-453be400-726f-11e9-9b9b-94d6fc9c85c3.png)

**Comment by acryforever** [comment]
มีการแก้ไขแล้ว
