### ISSUE TITLE
[เพิ่มรหัสซื้อขาย][เพิ่มราคาขาย]Blog   ไม่สมบูรณ์

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#355]
Summary   Name | [เพิ่มรหัสซื้อขาย][เพิ่มราคาขาย]Blog   ไม่สมบูรณ์
-- | --
Defect No. |  355
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/GoodsPriceTabInfo.aspx?dataId2=1045&dataId3=4057
Step | 1. Login WMS on Chorme
  | 2.เลือกเมนู   ตั้งค่า
  | 3.เลือกเมนูย่อย   สินค้า
  | 4.   แสดงหน้าจอ รายการสินค้า
  | 5. กดปุ่ม   เพิ่มสินค้า
  | 6.   แสดงหน้าจอ ข้อมูลสินค้า
  | 7.   กรอกข้อมูลใน field ที่ Tab
  | -   ข้อมูลสินค้า
  | -   ตั้งค่าสนิค้า
  | -   การจัดเก็บ
  | -   การเก็บรักษา
  | -   ผู้จัดจำหน่าย
  | 8. กดปุ่ม   บันทึก
  | 9.   บันทึกสำเร็จ
  | 10. กดปุ่ม   เพิ่มรหัสซื้อขาย
  | 11.   แสดงหน้าจอ เพิ่มรหัสซื้อขาย
  | 12.   กรอกข้อมูลใน field ที่ Tab
  | -   ข้อมูลรหัสซื้อขาย
  | -   ตั้งค่ารหัสซื้อขาย
  | -   การจัดเก็บ
  | - พาเลท
  | 13. กดปุ่ม   บันทึก
  | 14.   บันทึกสำเร็จ
  | 15. กดปุ่ม   เพิ่มราคาขาย
  | 16.   แสดงหน้าจอ เพิ่มราคาสินค้า
  |  
Actual   Result | Blog ไม่สมบูรณ์
  |  
  |  
Expected   Result | Blog ต้องคลุมทุก   Field
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/57400242-3d435c00-71fd-11e9-8682-cc4b44bc2d21.png)
![image](https://user-images.githubusercontent.com/45878758/57400247-403e4c80-71fd-11e9-8f77-fe9739cf71ae.png)
![image](https://user-images.githubusercontent.com/45878758/57400254-42081000-71fd-11e9-85de-22334333e302.png)
![image](https://user-images.githubusercontent.com/45878758/57400259-43d1d380-71fd-11e9-9616-bf8c92565bf5.png)
![image](https://user-images.githubusercontent.com/45878758/57400262-459b9700-71fd-11e9-93c3-2fbf7c2b6597.png)
![image](https://user-images.githubusercontent.com/45878758/57400264-47655a80-71fd-11e9-916f-de722dafb64c.png)
![image](https://user-images.githubusercontent.com/45878758/57400276-4c2a0e80-71fd-11e9-8081-bbd91c0f641b.png)

**Comment by Mickrepick** [comment]
แก้ไข : Blog คลุมทุก Field
