### ISSUE TITLE
[เพิ่มรหัสซื้อขาย][เพิ่มราคาขาย]ระบบแจ้งข้อความใต้   Field ไม่ถูกต้อง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#356]
Summary   Name | [เพิ่มรหัสซื้อขาย][เพิ่มราคาขาย]ระบบแจ้งข้อความใต้   Field ไม่ถูกต้อง
-- | --
Defect No. |  356
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/GoodsInfo.aspx?dataId2=4071
  | http://nps001.homeip.net:8085/GoodsPriceTabInfo.aspx?dataId2=1054&dataId3=4071
Step | 1. Login WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย สินค้า
  | 4.   แสดงหน้าจอ รายการสินค้า
  | 5. กดปุ่ม   แก้ไข หลังรายการ
  | 6.   แสดงหน้าจอ ข้อมูลสินค้า
  | 7. Blog   รายการรหัสซื้อขาย
  | 8. กดปุ่ม   แก้ไข หลังรายการรหัสซื้อขาย
  | 9.   แสดงหน้าจอ เพิ่มรหัสซื้อขาย
  | 10. กดปุ่ม   เพิ่มราคาขาย
  | 11.   แสดงหน้าจอ เพิ่มราคาสินค้า
  | 12.   ไม่ระบุข้อมูลใน field
  | -   ประเภทราคาขาย
  | - ราคา
  | - ป้ายราคา
  | 13. กดปุ่ม   บันทึก
  | 14. กดปุ่ม   กลับ
  |  
Actual   Result | 1.Field   "ราคา"ระบบต้องแสดงข้อความใต้ field "กรุณากรอกราคา"
  | 2.ระบบแสดงข้อความด้านล่าง   ไม่ถูกต้อง
  |  
Expected   Result | 1.ระบบต้องแสดงข้อความใต้ field "กรุณากรอกราคา"
  | 2.ระบบแสดงข้อความด้านล่าง
  | ไม่สามารถบันทึกข้อมูลได้   :
  | -   กรุณาเลือกประเภทราคาขาย
  | -   กรุณากรอกราคา
  | -   กรุณาเลือกป้ายราคา
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/57400351-7976bc80-71fd-11e9-8aa3-c43896fbf31b.png)
![image](https://user-images.githubusercontent.com/45878758/57400355-7c71ad00-71fd-11e9-9ea5-10a282395dce.png)
![image](https://user-images.githubusercontent.com/45878758/57400359-7e3b7080-71fd-11e9-9681-f86223cb2ea7.png)
![image](https://user-images.githubusercontent.com/45878758/57400364-80053400-71fd-11e9-89c8-2a420b947a5e.png)
![image](https://user-images.githubusercontent.com/45878758/57400380-872c4200-71fd-11e9-8186-5c174152a9d0.png)

**Comment by Mickrepick** [comment]
แก้ไข :  1. ระบบต้องแสดงข้อความใต้ field "กรุณากรอกราคา"
2. ระบบแสดงข้อความด้านล่าง
ไม่สามารถบันทึกข้อมูลได้ :
 - กรุณาเลือกประเภทราคาขาย
 - กรุณากรอกราคา
 - กรุณาเลือกป้ายราคา
