### ISSUE TITLE
[รายการสินค้า]Field   "ประเภทสินค้า" ระบบแสดงประเภทสินค้าไม่ถูกต้อง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#357]
Summary   Name | [รายการสินค้า]Field   "ประเภทสินค้า" ระบบแสดงประเภทสินค้าไม่ถูกต้อง
-- | --
Defect No. |  357
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SkuList.aspx?menuID=35
Step | 1. Login WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย สินค้า
  | 4.   แสดงหน้าจอ รายการสินค้า
  | 5.   ระบุข้อมูลใน field
  | - เลือก   ประเภท
  | 6. กดปุ่ม   ค้นหา หรือ Enter
  |  
Actual   Result | เมื่อ ค้นหาจาก Field   "ประเภทสินค้า" ระบบแสดงประเภทสินค้าไม่ถูกต้อง
  |  
  |  
Expected   Result | เมื่อ ค้นหาจาก Field   "ประเภทสินค้า" ระบบต้องแสดงประเภทสินค้าเฉพาะประเภทที่ค้นหา
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/57400465-c65a9300-71fd-11e9-9364-2602c2c9e22d.png)
![image](https://user-images.githubusercontent.com/45878758/57400494-d07c9180-71fd-11e9-93a1-9ff063f78258.png)

**Comment by acryforever** [comment]
![2019-05-17 (2)](https://user-images.githubusercontent.com/47658214/57905381-8bf99180-78a0-11e9-93e7-6112fe29a8bf.png)
