### ISSUE TITLE
[รายการสินค้า]Field   "หมวดหลัก" ระบบแสดงหมวดหลักไม่ถูกต้อง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#358]
Summary   Name | [รายการสินค้า]Field   "หมวดหลัก" ระบบแสดงหมวดหลักไม่ถูกต้อง
-- | --
Defect No. |  358
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SkuList.aspx?menuID=35
Step | 1. Login WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย สินค้า
  | 4.   แสดงหน้าจอ รายการสินค้า
  | 5.   ระบุข้อมูลใน field
  | - เลือก   หมวดหลัก
  | 6. กดปุ่ม   ค้นหา หรือ Enter
  |  
Actual   Result | เมื่อ ค้นหาจาก Field   "หมวดหลัก" ระบบแสดงหมวดหลักไม่ถูกต้อง
  |  
  |  
Expected   Result | เมื่อ ค้นหาจาก Field   "หมวดหลัก" ระบบต้องแสดงเฉพาะหมวดหลักที่ค้นหา
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/57400770-7203e300-71fe-11e9-8817-24fb265c243c.png)
![image](https://user-images.githubusercontent.com/45878758/57400790-7a5c1e00-71fe-11e9-98d9-16fc95fd51b2.png)

**Comment by acryforever** [comment]
แก้ไข base 
![2019-05-17](https://user-images.githubusercontent.com/47658214/57904835-9e72cb80-789e-11e9-991c-c2d9aca16c6d.png)
