### ISSUE TITLE
[รายการสินค้า][ลบ   หลังรายการ]เมื่อกดปุ่ม ลบ ระบบแสดง Message "ทำการยืนยัน   ที่จะบันทึกข้อมูล ?"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#360]
Summary   Name | [รายการสินค้า][ลบ   หลังรายการ]เมื่อกดปุ่ม ลบ ระบบแสดง Message "ทำการยืนยัน   ที่จะบันทึกข้อมูล ?"
-- | --
Defect No. |  360
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SkuList.aspx?menuID=35
Step | 1. Login WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย สินค้า
  | 4.   แสดงหน้าจอ รายการสินค้า
  | 5. กดปุ่ม   ลบ หลังรายการ
  | 6. กดปุ่ม   OK
  |  
Actual   Result | เมื่อกดปุ่ม ลบ   ระบบแสดง Message "ทำการยืนยัน ที่จะบันทึกข้อมูล ?"
  |  
  |  
Expected   Result | เมื่อกดปุ่ม ลบ   ระบบแสดง Message "ทำการยืนยัน ที่จะลบข้อมูล?"
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/57401242-6bc23680-71ff-11e9-8e91-b40ba152e84d.png)
![image](https://user-images.githubusercontent.com/45878758/57401254-6fee5400-71ff-11e9-84f6-f8bb0d6a2210.png)

**Comment by Mickrepick** [comment]
แก้ไข : เมื่อกดปุ่ม ลบ ระบบจะแสดง Message "ทำการยืนยัน ที่จะลบข้อมูล?"
