### ISSUE TITLE
[เพิ่มสินค้า][…   หลังรายการ หน่วยนับ]เมื่อกดปุ่ม "บันทึก" ไม่สามารถบันทึกข้อมูลได้   ระบบขึ้น Error Message "@seq is not a parameter for procedure   udp_SKU_Unit_ups."

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#361]
Summary   Name | [เพิ่มสินค้า][…   หลังรายการ หน่วยนับ]เมื่อกดปุ่ม "บันทึก" ไม่สามารถบันทึกข้อมูลได้   ระบบขึ้น Error Message "@seq is not a parameter for procedure   udp_SKU_Unit_ups."
-- | --
Defect No. |  361
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SkuInfo.aspx
  | http://nps001.homeip.net:8085/PopupUnitInfo.aspx
Step | 1. Login WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย สินค้า
  | 4.   แสดงหน้าจอ รายการสินค้า
  | 5. กดปุ่ม   เพิ่มสินค้า
  | 6.   แสดงหน้าจอ ข้อมูลสินค้า
  | 7. กดปุ่ม   ... หลัง field หน่วยนับ
  |  
Actual   Result | เมื่อกดปุ่ม   "บันทึก" ไม่สามารถบันทึกข้อมูลได้ ระบบขึ้น Error Message
  | "@seq is not a   parameter for procedure udp_SKU_Unit_ups."
  |  
Expected   Result | เมื่อกดปุ่ม   "บันทึก" ต้องสามารถบันทึกข้อมูลได้
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/57401327-9a401180-71ff-11e9-828e-318c906f6f27.png)
![image](https://user-images.githubusercontent.com/45878758/57401328-9c09d500-71ff-11e9-86f4-84cbdf9e69e9.png)
![image](https://user-images.githubusercontent.com/45878758/57401330-9dd39880-71ff-11e9-9853-e40bda8dd34e.png)
![image](https://user-images.githubusercontent.com/45878758/57401346-a4621000-71ff-11e9-92ed-f8c7443854bb.png)

**Comment by acryforever** [comment]
เปิดพารามิสเตอร์ที่โดนปิดใน BIZ
