### ISSUE TITLE
 [เพิ่มสินค้า][…   เพิ่มยี่ห้อ]เมื่อกดปุ่ม "บันทึก" ยังคงอยู่หน้าเดิม   ระบบไม่บันทึกข้อมูลให้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#362]
Summary   Name | [เพิ่มสินค้า][…   เพิ่มยี่ห้อ]เมื่อกดปุ่ม "บันทึก" ยังคงอยู่หน้าเดิม   ระบบไม่บันทึกข้อมูลให้
-- | --
Defect No. |  362
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SkuInfo.aspx
  | http://nps001.homeip.net:8085/PopupBrandInfo.aspx
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย สินค้า
  | 4.   แสดงหน้าจอ รายการสินค้า
  | 5. กดปุ่ม   เพิ่มสินค้า
  | 6.   แสดงหน้าจอ ข้อมูลสินค้า
  | 7. กดปุ่ม   ... หลัง field ยี่ห้อ
  | 8. แสดง   PopUp เพิ่มยี่ห้อ
  | 9.   ระบุข้อมูลใน field
  | - รหัส
  | -   ชื่อภาษาไทย
  | -   ชื่อภาษาอังกฤษ
  | -   ลำดับการจัดเรียง
  | - สถานะ
  | -   รายละเอียด
  | 10. กดปุ่ม   บันทึก
  | 11.   บันทึกสำเร็จ
  |  
Actual   Result | เมื่อกดปุ่ม   "บันทึก" ยังคงอยู่หน้าเดิม ระบบไม่บันทึกข้อมูลให้
  |  
  |  
Expected   Result | เมื่อกดปุ่ม   "บันทึก" ต้องสามารถ บันทึก ข้อมูลได้
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/57401484-f440d700-71ff-11e9-9751-325f17161d10.png)
![image](https://user-images.githubusercontent.com/45878758/57401489-f6a33100-71ff-11e9-8180-55ea03e59b60.png)
![image](https://user-images.githubusercontent.com/45878758/57401496-facf4e80-71ff-11e9-8648-cd7141cd778f.png)

**Comment by Patthamaporn** [comment]
แก้ไข สามารถบันทึกยี่ห้อในหน้าข้อมูลสินค้าได้
