### ISSUE TITLE
[เพิ่มสินค้า]Field   "หน่วยแสดงผล" ไม่มี ปุ่ม "..." หลัง field เพื่อแสดงหน้าจอ   เพื่มหน่วย

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#363]
Summary   Name | [เพิ่มสินค้า]Field   "หน่วยแสดงผล" ไม่มี ปุ่ม "..." หลัง field เพื่อแสดงหน้าจอ   เพื่มหน่วย
-- | --
Defect No. |  363
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SkuInfo.aspx
  |  
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย สินค้า
  | 4.   แสดงหน้าจอ รายการสินค้า
  | 5. กดปุ่ม   เพิ่มสินค้า
  | 6.   แสดงหน้าจอ ข้อมูลสินค้า
  | 7. กดปุ่ม   ... หลัง field หน่วยแสดงผล
  |  
Actual   Result | Field   "หน่วยแสดงผล" ไม่มี ปุ่ม "..." หลัง field เพื่อแสดงหน้าจอ   เพื่มหน่วย
  |  
  |  
Expected   Result | Field   "หน่วยแสดงผล" ต้องมี ปุ่ม "..." หลัง field   เพื่อแสดงหน้าจอ เพื่มหน่วย
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/57401655-526dba00-7200-11e9-9e7d-0c7e4268f16e.png)
![image](https://user-images.githubusercontent.com/45878758/57401670-58639b00-7200-11e9-9c35-7ea0a421d2e4.png)

**Comment by Mickrepick** [comment]
เพิ่มปุ่ม "..." หลัง field เพื่อแสดงหน้าจอ เพิ่มหน่วย
