### ISSUE TITLE
[เพิ่มสินค้า][Tab   การเก็บรักษา]Field   "อายุสินค้า","อายุสินค้าก่อนรับ","อายุสินค้าก่อนส่ง"   ต้องมี "(วัน)" ด้วย

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#364]
Summary   Name | [เพิ่มสินค้า][Tab   การเก็บรักษา]Field   "อายุสินค้า","อายุสินค้าก่อนรับ","อายุสินค้าก่อนส่ง"   ต้องมี "(วัน)" ด้วย
-- | --
Defect No. |  364
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SkuInfo.aspx
Step | 1. Login WMS on Chorme
  | 2.เลือกเมนู   ตั้งค่า
  | 3.เลือกเมนูย่อย   สินค้า
  | 4.   แสดงหน้าจอ รายการสินค้า
  | 5. กดปุ่ม   เพิ่มสินค้า
  | 6.   แสดงหน้าจอ ข้อมูลสินค้า
  | 7. กด Tab   การเก็บรักษา
  | 8. แสดง   Tab การเก็บรักษา
  |  
Actual   Result | Field   "อายุสินค้า","อายุสินค้าก่อนรับ","อายุสินค้าก่อนส่ง"   ต้องมี "(วัน)" ด้วย
  |  
  |  
Expected   Result | Field   "อายุสินค้า","อายุสินค้าก่อนรับ","อายุสินค้าก่อนส่ง"   ต้องมี "(วัน)" ด้วย
  | -   อายุสินค้า (วัน)
  | -   อายุสินค้าก่อนรับ (วัน)
  | -   อายุสินค้าก่อนส่ง (วัน)
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/57401889-93fe6500-7200-11e9-986b-728a29abb3fe.png)

**Comment by acryforever** [comment]
![2019-05-17 (2)](https://user-images.githubusercontent.com/47658214/57927346-e95d0500-78d7-11e9-9f1b-f85cf547831c.png)
