### ISSUE TITLE
[เพิ่มสินค้า]เมื่อไม่กรอก   field mandatory ระบบแสดงข้อความไม่ถูกต้อง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#365]
Summary   Name | [เพิ่มสินค้า]เมื่อไม่กรอก   field mandatory ระบบแสดงข้อความไม่ถูกต้อง
-- | --
Defect No. |  365
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SkuInfo.aspx
Step | 1. Login WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย สินค้า
  | 4.   แสดงหน้าจอ รายการสินค้า
  | 5. กดปุ่ม   เพิ่มสินค้า
  | 6.   แสดงหน้าจอ ข้อมูลสินค้า
  | 7.   ไม่ระบุข้อมูลใน field
  | -   กรอกรหัสสินค้า
  | -   กรอกขื่อสินค้าภาษาไทย
  | -   เลือกยี่ห้อ
  | -   เลือกประเภทสินค้า
  | -   เลือกหมวดหลัก
  | -   เลือกหมวดย่อย
  | -   เลือกหน่วยนับ
  | -   เลือกหน่วยแสดงผล
  | -   เลือกประเภทการตัดสต็อก
  | -   เลือกสต๊อคติดลบ
  | -   เลือกผู้อนุมัติ
  | -   เลือกประเภทต้นทุน
  | -   เลือกเงื่อนไขการจัดเก็บ
  | -   อายุสินค้า
  | -   อายุสินค้าก่อนรับ
  | -   อายุสินค้าก่อนส่ง
  | 8. กดปุ่ม   บันทึก
  | 9. กดปุ่ม   OK
  |  
Actual   Result | เมื่อไม่กรอก field   mandatory ระบบแสดงข้อความไม่ถูกต้อง
  |  
  |  
Expected   Result | เมื่อไม่กรอก field   mandatory ระบบต้องแสดงข้อความถูกต้อง
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/57402100-bd1ef580-7200-11e9-9e22-8321cf8af914.png)
![image](https://user-images.githubusercontent.com/45878758/57402104-bee8b900-7200-11e9-81d2-26db65b50973.png)
![image](https://user-images.githubusercontent.com/45878758/57402106-c0b27c80-7200-11e9-91af-a1ae19cbc991.png)
![image](https://user-images.githubusercontent.com/45878758/57402109-c27c4000-7200-11e9-8762-52257d16a134.png)
![image](https://user-images.githubusercontent.com/45878758/57402184-efc8ee00-7200-11e9-9a6e-fac11da9b8e8.png)

**Comment by acryforever** [comment]
แก้ไข Message Alret Error
