### ISSUE TITLE
 [เพิ่มสินค้า][รายการสินค้า][แก้ไขหลังรายการ]Field   "ประเภท Packsize" ระบบไม่จำค่าที่เลือกไว้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#366]
Summary   Name | [เพิ่มสินค้า][รายการสินค้า][แก้ไขหลังรายการ]Field   "ประเภท Packsize" ระบบไม่จำค่าที่เลือกไว้
-- | --
Defect No. |  366
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SkuInfo.aspx?dataId=4062
  |  
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย สินค้า
  | 4.   แสดงหน้าจอ รายการสินค้า
  | 5. กดปุ่ม   เพิ่มสินค้า
  | 6.   แสดงหน้าจอ ข้อมูลสินค้า
  | 7.   ระบุข้อมูลใน field
  | -   เงื่อนไขการจัดเก็บ "SKU"
  | - ประเภท   Packsize "ลัง"
  | 9.   บันทึกสำเร็จ
  | 10.   แสดงหน้าจอ รายการสินค้า
  | 11. กดปุ่ม   แก้ไข หลังรายการ
  | 12.   แสดงหน้าจอ ข้อมูลสินค้า
  | 13.   ตรวจสอบ field "Packsize"
  |  
Actual   Result | Field "ประเภท   Packsize" ระบบไม่จำค่าที่เลือกไว้
  |  
  |  
Expected   Result | Field "ประเภท   Packsize" ต้องแสดงข้อมูลที่เลือกไว้
  | -   ต้องแสดงข้อมูล "ลัง"
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/57402284-2bfc4e80-7201-11e9-9361-3d46fd0f1f15.png)
![image](https://user-images.githubusercontent.com/45878758/57402289-2dc61200-7201-11e9-89e6-dd24b36691a1.png)
![image](https://user-images.githubusercontent.com/45878758/57402290-30286c00-7201-11e9-89df-74761cdbc8f2.png)
![image](https://user-images.githubusercontent.com/45878758/57402297-34ed2000-7201-11e9-9528-ae09aa1b35e5.png)

**Comment by acryforever** [comment]
เพิ่ม Field ใน Store ที่ udp_SKU_SKU_ups
เพิ่ม Field Code Behight Field ของ packingTypeID
