### ISSUE TITLE
Location_เมื่อกดค้นหาด้วย "รหัสซื้อขาย" ระบบไม่พบรายการ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#370]
Summary   Name | Location_เมื่อกดค้นหาด้วย   "รหัสซื้อขาย" ระบบไม่พบรายการ
-- | --
Defect No. |  370
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/LocationList.aspx?menuID=71
Step | 1. Login
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย รายการตำแหน่งจัดเก็บ
  | 4.   แสดงหน้าจอ Location Picking
  | 5.   ระบุข้อมูลใน field
  | -   ประเภทสินค้า "สต็อกน้อยกว่าหรือเท่ากับ 0"
  | -   ประเภทตำแหน่งจัดเก็บ "ประเภทการจัดเก็บ"
  | -   ค้นหา:รหัส location picking/รหัสสินค้า/รหัสซื้อขาย "รหัสซื้อขาย"
  | 6.   กดปุ่ม ค้นหา หรือ Enter
  |  
  |  
Actual   Result | เมื่อกดค้นหาด้วย   "รหัสซื้อขาย" ระบบไม่พบรายการ
  |  
  |  
Expected   Result | เมื่อกดค้นหาด้วย   "รหัสซื้อขาย" ระบบต้องพบรายการ
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/57586720-1732fa00-7524-11e9-9baf-0c54b3fb160a.png)
![image](https://user-images.githubusercontent.com/45878758/57586721-19955400-7524-11e9-86e0-af09a351d95c.png)

**Comment by acryforever** [comment]
แก้ไขStore
