### ISSUE TITLE
[ใบสั่งซื้อ][ดู   หลังรายการ] เมื่อเพิ่มสินค้า และกดบันทึก ระบบไม่แสดงรายการสินค้า

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#373]
Summary   Name | [ใบสั่งซื้อ][ดู   หลังรายการ] เมื่อเพิ่มสินค้า และกดบันทึก ระบบไม่แสดงรายการสินค้า
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  373
URL | http://nps001.homeip.net:8085/PurchaseInfo.aspx?dataId=12177&view=1
  |  
Step | 1. Login
  | 2. เลือกเมนู ตั้งค่า
  | 3. เลือกเมนูย่อย   สินค้า
  | 4. แสดงหน้าจอ   รายการสินค้า
  | 5. กดปุ่ม แก้ไข   หลังรายการ
  | 6. แสดงหน้าจอ   ข้อมูลสินค้า
  | 7. กดปุ่ม   เพิ่มรหัสซื้อขาย
  | 8. แสดงหน้าจอ   เพิ่มรหัสซื้อขาย
  | 9. สร้างสินค้า 1   รายการ "APS2003 กล้องสีเขียว ชิ้นx1"
  | 10. กดปุ่ม บันทึก
  | 11. บันทึกสำเร็จ
  | 12. เลือกเมนู   งานประจำวัน
  | 13. เลือกเมนูย่อย   ใบสั่งซื้อสินค้า
  | 14. เลือก   สั่งซื้อทั่วไป
  | 15. แสดงหน้าจอ   รายการใบสั่งซื้อสินค้า
  | 16. กดปุ่ม   เพิ่มใบสั่งซื้อ
  | 17. แสดงหน้าจอ   ใบสั่งซื้อ
  | 18. เลือกคู่ค้า
  | 19. กดปุ่ม   ค้นหาสินค้า
  | 20. เลือกสินค้า 1   รายการ "APS2003 กล้องสีเขียว ชิ้นx1"
  | 21. กรอก   จำนวนสั่งซื้อ "100"
  | 22. กดปุ่ม บันทึก
  | 23. บันทึกสำเร็จ
  | 24. แสดงหน้าจอ   รายการใบสั่งซื้อสินค้า
  | 25. กดปุ่ม ดู   หลังรายการ
  |  
  |  
Actual   Result | เมื่อเพิ่มสินค้า   และกดบันทึก ระบบไม่แสดงรายการสินค้า
  |  
Expected   Result | ระบบต้องแสดงรายการสินค้า
  |  

![image](https://user-images.githubusercontent.com/45878758/57668406-661a8580-7631-11e9-883b-c06862cd1a5e.png)
![image](https://user-images.githubusercontent.com/45878758/57668408-67e44900-7631-11e9-825f-449f26065865.png)
![image](https://user-images.githubusercontent.com/45878758/57668412-69ae0c80-7631-11e9-99a4-a488be620468.png)
![image](https://user-images.githubusercontent.com/45878758/57668415-6ca8fd00-7631-11e9-9b4d-e83f56e86d4b.png)
![image](https://user-images.githubusercontent.com/45878758/57668417-6fa3ed80-7631-11e9-9f44-9a27923f1a5d.png)
![image](https://user-images.githubusercontent.com/45878758/57668421-72064780-7631-11e9-9bab-59d9434e760d.png)

**Comment by Mickrepick** [comment]
Test แล้วใช้งานได้ปกติครับ ขอปิด Issues
