### ISSUE TITLE
[ใบสั่งซื้อ][แก้ไข   หลังรายการ] เมื่อเพิ่มสินค้า และกดบันทึก ระบบไม่แสดงรายการสินค้า

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#374]
Summary   Name | [ใบสั่งซื้อ][แก้ไข   หลังรายการ] เมื่อเพิ่มสินค้า และกดบันทึก ระบบไม่แสดงรายการสินค้า
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  374
URL | http://nps001.homeip.net:8085/PurchaseInfo.aspx?dataId=12177&subDoc=18
  |  
Step | 1. Login
  | 2. เลือกเมนู ตั้งค่า
  | 3. เลือกเมนูย่อย   สินค้า
  | 4. แสดงหน้าจอ   รายการสินค้า
  | 5. กดปุ่ม แก้ไข   หลังรายการ
  | 6. แสดงหน้าจอ   ข้อมูลสินค้า
  | 7. กดปุ่ม   เพิ่มรหัสซื้อขาย
  | 8. แสดงหน้าจอ   เพิ่มรหัสซื้อขาย
  | 9. สร้างสินค้า 1   รายการ "APS2003 กล้องสีเขียว ชิ้นx1"
  | 10. กดปุ่ม บันทึก
  | 11. บันทึกสำเร็จ
  | 12. เลือกเมนู   งานประจำวัน
  | 13. เลือกเมนูย่อย   ใบสั่งซื้อสินค้า
  | 14. เลือก   สั่งซื้อทั่วไป
  | 15. แสดงหน้าจอ   รายการใบสั่งซื้อสินค้า
  | 16. กดปุ่ม   เพิ่มใบสั่งซื้อ
  | 17. แสดงหน้าจอ   ใบสั่งซื้อ
  | 18. เลือกคู่ค้า
  | 19. กดปุ่ม   ค้นหาสินค้า
  | 20. เลือกสินค้า 1   รายการ "APS2003 กล้องสีเขียว ชิ้นx1"
  | 21. กรอก   จำนวนสั่งซื้อ "100"
  | 22. กดปุ่ม บันทึก
  | 23. บันทึกสำเร็จ
  | 24. แสดงหน้าจอ   รายการใบสั่งซื้อสินค้า
  | 25. กดปุ่ม แก้ไข   หลังรายการ
  |  
  |  
Actual   Result | เมื่อเพิ่มสินค้า   และกดบันทึก ระบบไม่แสดงรายการสินค้า
  |  
Expected   Result | ระบบต้องแสดงรายการสินค้า
  |  

![image](https://user-images.githubusercontent.com/45878758/57668530-db865600-7631-11e9-8b1f-8ce3c4801589.png)
![image](https://user-images.githubusercontent.com/45878758/57668536-dde8b000-7631-11e9-9667-e8da14359879.png)
![image](https://user-images.githubusercontent.com/45878758/57668542-df19dd00-7631-11e9-8baa-31eef4352104.png)
![image](https://user-images.githubusercontent.com/45878758/57668544-e0e3a080-7631-11e9-8b57-7f8dbf1f340d.png)
![image](https://user-images.githubusercontent.com/45878758/57668547-e2ad6400-7631-11e9-9262-0396f1a05110.png)
![image](https://user-images.githubusercontent.com/45878758/57668551-e4772780-7631-11e9-87b1-2b5ea338d842.png)

**Comment by Mickrepick** [comment]
Test แล้วใช้งานได้ปกติครับ ขอปิด Issues
