### ISSUE TITLE
[ใบสั่งซื้อ][อนุมัติ   หลังรายการ] เมื่อเพิ่มสินค้า และกดบันทึก ระบบไม่แสดงรายการสินค้า

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#375]
Summary   Name | [ใบสั่งซื้อ][อนุมัติ   หลังรายการ] เมื่อเพิ่มสินค้า และกดบันทึก ระบบไม่แสดงรายการสินค้า
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  375
URL | http://nps001.homeip.net:8085/PurchaseInfo.aspx?dataId=12177&subDoc=18&approve=1
  |  
Step | 1. Login
  | 2. เลือกเมนู ตั้งค่า
  | 3. เลือกเมนูย่อย   สินค้า
  | 4. แสดงหน้าจอ   รายการสินค้า
  | 5. กดปุ่ม แก้ไข   หลังรายการ
  | 6. แสดงหน้าจอ   ข้อมูลสินค้า
  | 7. กดปุ่ม   เพิ่มรหัสซื้อขาย
  | 8. แสดงหน้าจอ   เพิ่มรหัสซื้อขาย
  | 9. สร้างสินค้า 1   รายการ "APS2003 กล้องสีเขียว ชิ้นx1"
  | 10. กดปุ่ม บันทึก
  | 11. บันทึกสำเร็จ
  | 12. เลือกเมนู   งานประจำวัน
  | 13. เลือกเมนูย่อย   ใบสั่งซื้อสินค้า
  | 14. เลือก   สั่งซื้อทั่วไป
  | 15. แสดงหน้าจอ   รายการใบสั่งซื้อสินค้า
  | 16. กดปุ่ม   เพิ่มใบสั่งซื้อ
  | 17. แสดงหน้าจอ   ใบสั่งซื้อ
  | 18. เลือกคู่ค้า
  | 19. กดปุ่ม   ค้นหาสินค้า
  | 20. เลือกสินค้า 1   รายการ "APS2003 กล้องสีเขียว ชิ้นx1"
  | 21. กรอก   จำนวนสั่งซื้อ "100"
  | 22. กดปุ่ม บันทึก
  | 23. บันทึกสำเร็จ
  | 24. แสดงหน้าจอ   รายการใบสั่งซื้อสินค้า
  | 25. กดปุ่ม อนุมัติ   หลังรายการ
  |  
  |  
Actual   Result | เมื่อเพิ่มสินค้า   และกดบันทึก ระบบไม่แสดงรายการสินค้า
  |  
Expected   Result | ระบบต้องแสดงรายการสินค้า
  |  

![image](https://user-images.githubusercontent.com/45878758/57668648-2bfdb380-7632-11e9-88da-8c44c0760477.png)
![image](https://user-images.githubusercontent.com/45878758/57668651-2dc77700-7632-11e9-8995-a164f3cc91dd.png)
![image](https://user-images.githubusercontent.com/45878758/57668654-3029d100-7632-11e9-9350-a5e566aee17d.png)
![image](https://user-images.githubusercontent.com/45878758/57668659-328c2b00-7632-11e9-990d-a0a94a6e93a0.png)
![image](https://user-images.githubusercontent.com/45878758/57668662-3455ee80-7632-11e9-9062-b92c45f1d4be.png)
![image](https://user-images.githubusercontent.com/45878758/57668665-361fb200-7632-11e9-8c4f-f0ea5a7a2e25.png)

**Comment by Mickrepick** [comment]
Test แล้วใช้งานได้ปกติครับ ขอปิด Issues
