### ISSUE TITLE
สินค้า_เพิ่มราคาสินค้า_แก้ไขหลังรายการ_Blog ไม่สมบูรณ์

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#380]
Summary   Name | สินค้า_เพิ่มราคาสินค้า_แก้ไขหลังรายการ_Blog   ไม่สมบูรณ์
-- | --
Defect No. |  380
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/GoodsPriceTabInfo.aspx?dataId2=1023&dataId3=3
Step | 1. Login
  | 2.เลือกเมนู   ตั้งค่า
  | 3.เลือกเมนูย่อย   สินค้า
  | 4.   แสดงหน้าจอ รายการสินค้า
  | 5.   กดปุ่ม แก้ไข หลังรายการ
  | 6.   แสดงหน้าจอ ข้อมูลสินค้า
  | 7.   Blog รายการรหัสซื้อขาย
  | 8.   กดปุ่ม แก้ไข หลังรายการรหัสซื้อขาย
  | 9.   แสดงหน้าจอ เพิ่มรหัสซื้อขาย
  | 10.   Blog ราคาสินค้า
  | 11.   กดปุ่ม แก้ไข หลังรายการ
  | 12.   แสดงหน้าจอ เพิ่มราคาสินค้า
  |  
  |  
Actual   Result | Blog ไม่สมบูรณ์
  |  
  |  
Expected   Result | Blog   ต้องคลุมทุก Field
  |  
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/57757761-6180ca80-7720-11e9-9748-8273ff28b836.png)
![image](https://user-images.githubusercontent.com/45878758/57757767-6776ab80-7720-11e9-9213-ef2a2701be04.png)
![image](https://user-images.githubusercontent.com/45878758/57757773-6ba2c900-7720-11e9-9792-83990dbd12c9.png)
![image](https://user-images.githubusercontent.com/45878758/57757778-6e9db980-7720-11e9-8d61-663dc724c1ed.png)

**Comment by acryforever** [comment]
ตรวจสอบมีการแก้ไขแล้ว
