### ISSUE TITLE
[รายการตำแหน่งจัดเก็บ]Column   จำนวน ดึงค่าตาม Format "จำนวนเต็ม/เศษ หน่วย" -->  "10/3 ลัง"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#384]
Summary   Name | [รายการตำแหน่งจัดเก็บ]Column   จำนวน ดึงค่าตาม Format "จำนวนเต็ม/เศษ หน่วย" -->  "10/3 ลัง"
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  384
URL | http://nps001.homeip.net:8085/LocationList.aspx?menuID=71
Step | 1. Login
  | 2. เลือกเมนู   รายการตำแหน่งจัดเก็บ
  | 3. แสดงหน้าจอ   Location
  |  
  |  
  |  
  |  
  |  
Actual   Result | Column จำนาน แสดงไม่ถูกต้อง
  |  
Expected   Result | Column จำนวน   ดึงค่าตาม Format "จำนวนเต็ม/เศษ หน่วย" -->  "10/3 ลัง"
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/57908155-91a7a500-78a9-11e9-8582-e998f0293ac9.png)

**Comment by Mickrepick** [comment]
แก้ไข : Column จำนวน ดึงค่าตาม Format "จำนวนเต็ม/เศษ หน่วยแสดงผล"
