### ISSUE TITLE
[ข้อมูลสินค้า][เพิ่มสินค้า]เปลี่ยนชื่อใน   tab พาเลท เป็น บรรจุภัณฑ์

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#386]
Summary   Name | [ข้อมูลสินค้า][เพิ่มสินค้า]เปลี่ยนชื่อใน   tab พาเลท เป็น บรรจุภัณฑ์
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  386
URL | http://nps001.homeip.net:8085/SkuInfo.aspx
Step | 1. Login
  | 2. เลือกเมนู ตั้งค่า
  | 3. เลือกเมนูย่อย   สินค้า
  | 4. แสดงหน้าจอ   รายการสินค้า
  | 5. กดปุ่ม เพิ่มสินค้า
  | 6. แสดงหน้าจอ   ข้อมูลสินค้า
  | 7. เลือก Tab พาเลท
  |  
Actual   Result | 1. ชื่อ Tab พาเลท
  | 2. ชื่อ Column   ประเภทพาเลท
  | 3. ชื่อ Button   เพิ่มประเภทพาเลท
  |  
  |  
Expected   Result | 1. เปลี่ยนชื่อ Tab   "พาเลท" เป็น "บรรจุภัณฑ์"
  | 2. เปลี่ยนชื่อ Column   "ประเภทพาเลท" เป็น "ประเภทบรรจุภัณฑ์"
  | 3. เปลี่ยนชื่อ Button   "เพิ่มประเภทพาเลท" เป็น "เพิ่มประเภทบรรจุภัณฑ์"
  |  

![image](https://user-images.githubusercontent.com/45878758/57909202-4c38a700-78ac-11e9-80f4-1f086c961387.png)

**Comment by Mickrepick** [comment]
แก้ไข : 

1. เปลี่ยนชื่อ Tab "พาเลท" เป็น "บรรจุภัณฑ์"
2. เปลี่ยนชื่อ Column "ประเภทพาเลท" เป็น "ประเภทบรรจุภัณฑ์"
3. เปลี่ยนชื่อ Button "เพิ่มประเภทพาเลท" เป็น "เพิ่มประเภทบรรจุภัณฑ์"
