### ISSUE TITLE
[ข้อมูลสินค้า][แก้ไข   หลังรายการ]ไม่กรอก field mandatory อายุสินค้า ระบบสามารถบันทึกได้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#388]
Summary   Name | [ข้อมูลสินค้า][แก้ไข   หลังรายการ]ไม่กรอก field mandatory อายุสินค้า ระบบสามารถบันทึกได้
-- | --
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
Defect No. |  388
URL | http://nps001.homeip.net:8085/SkuInfo.aspx?dataId=3018
Step | 1. Login
  | 2. เลือกเมนู ตั้งค่า
  | 3. เลือกเมนู สินค้า
  | 4. แสดงหน้าจอ   รายการสินค้า
  | 5. กดปุ่ม แก้ไข   หลังรายการ
  | 6. แสดงหน้าจอ   ข้อมูลสินค้า
  | 7. ไม่กรอก field
  | - อายุสินค้า
  | - อายุสินค้าก่อนรับ
  | -อายุสินค้าก่อนส่ง
  |  
  |  
Actual   Result | ไม่กรอก field   mandatory อายุสินค้า ระบบสามารถบันทึกได้
  |  
Expected   Result | 1.   ต้องแสดงข้อความใต้ Field
  | - กรุณากรอกอายุสินค้า
  | -   กรุณากรอกอายุสินค้าก่อนรับ
  | -   กรุณากรอกอายุสินค้าก่อนส่ง
  | 2.   ต้องแสดง ข้อความด้านล่าว
  | -   กรุณากรอกอายุสินค้า
  | -   กรุณากรอกอายุสินค้าก่อนรับ
  | -   กรุณากรอกอายุสินค้าก่อนส่ง
  |  

![image](https://user-images.githubusercontent.com/45878758/57966750-59bf6100-7980-11e9-8ef8-e243f0e3b32b.png)
![image](https://user-images.githubusercontent.com/45878758/57966752-5c21bb00-7980-11e9-8d2a-b8b5be327022.png)

**Comment by Mickrepick** [comment]
แก้ไข : 
แสดงข้อความใต้ Field
- กรุณากรอกอายุสินค้า
- กรุณากรอกอายุสินค้าก่อนรับ
- กรุณากรอกอายุสินค้าก่อนส่ง
แสดงข้อความด้านล่าง
- กรุณากรอกอายุสินค้า
- กรุณากรอกอายุสินค้าก่อนรับ
- กรุณากรอกอายุสินค้าก่อนส่ง
