### ISSUE TITLE
ข้อมูลสินค้า_แก้ไขหลังรายการ_กดกลับใน Popup เพิ่มยี่ห้อ field ยี่ห้อเปลี่ยนเป็นกรุณาเลือก

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#389]
Summary   Name | ข้อมูลสินค้า_แก้ไขหลังรายการ_กดกลับใน   Popup เพิ่มยี่ห้อ field ยี่ห้อเปลี่ยนเป็นกรุณาเลือก
-- | --
Defect No. |  389
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SkuInfo.aspx?dataId=3
URL | http://nps001.homeip.net:8085/PopupBrandInfo.aspx
Step | 1. Login
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย สินค้า
  | 4.   แสดงหน้าจอ รายการสินค้า
  | 5.   กดปุ่ม แก้ไข หลังรายการ
  | 6.   แสดงหน้าจอ ข้อมูลสินค้า
  | 7.   กดปุ่ม ... หลัง field ยี่ห้อ
  | 8.   แสดง PopUp เพิ่มยี่ห้อ
  | 9.   กดปุ่ม กลับ
  |  
  |  
  |  
Actual   Result | กดกลับใน   Popup เพิ่มยี่ห้อ field ยี่ห้อเปลี่ยนเป็น "กรุณาเลือก"
  |  
Expected   Result | field   ยี่ห้อต้องจำค่าเดิมไว้
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/57966917-8d9b8600-7982-11e9-8b77-270b8ade9c20.png)
![image](https://user-images.githubusercontent.com/45878758/57966918-90967680-7982-11e9-9e98-a768b58cf28b.png)
![image](https://user-images.githubusercontent.com/45878758/57966921-955b2a80-7982-11e9-9823-ec10ddce0e18.png)
![image](https://user-images.githubusercontent.com/45878758/57966923-97bd8480-7982-11e9-865f-ea42d2d9013d.png)

**Comment by acryforever** [comment]
AutoCompleteType="Disabled"

**Comment by acryforever** [comment]
<button type="button" class="btn default" onclick="CancelDialog();">กลับ</button>
