### ISSUE TITLE
[นำเข้าสินค้า][รับสินค้าเข้า]Field   คลัง , โซน , ตำแหน่งจัดเก็บ ไม่ดึงค่ามาจาก ตั้งค่า

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#391]
Summary   Name | [นำเข้าสินค้า][รับสินค้าเข้า]Field   คลัง , โซน , ตำแหน่งจัดเก็บ ไม่ดึงค่ามาจาก ตั้งค่า
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  391
URL | http://nps001.homeip.net:8085/InboundInfo.aspx?subDoc=3&ref=12199
  | http://nps001.homeip.net:8085/GoodsInfo.aspx?dataId=1041&dataId2=4055
Step | 1.Login
  | 2.   เลือกเมนู งานประจำวัน
  | 3. เลือกเมนูย่อย   นำเข้าสินค้า
  | 4. แสดงหน้าจอ   รายการนำเข้าสินค้า
  | 5. กดปุ่ม   รับสินค้าเข้า หลังรายการ
  | 6. แสดงหน้าจอ   นำสินค้าเข้า
  | 7. เลือก Tab   การจัดเก็บสินค้า
  |  
Actual   Result | Field คลัง , โซน ,   ตำแหน่งจัดเก็บ ไม่ดึงค่ามาจาก ตั้งค่า
  |  
Expected   Result | 1. Field คลัง , โซน ,   ตำแหน่งจัดเก็บ Default มาให้จาก รหัสซื้อขาย ใน การกำหนดตำแหน่งเก็บ
  | 2. เมื่อ Default   ค่ามาให้ ก็ยังสามารถเปลี่ยน field คลัง , โซน , ตำแหน่งจัดเก็บ ได้
  |  

![image](https://user-images.githubusercontent.com/45878758/58065380-b94f8380-7baf-11e9-8928-09dc60419fb2.png)

**Comment by Malatoo** [comment]
![Uploading too02.png…]()

**Comment by Malatoo** [comment]
![too02-1](https://user-images.githubusercontent.com/49140473/59148829-b5d54c80-8a37-11e9-8bb2-b17bab3de348.jpg)
