### ISSUE TITLE
[ใบสั่งซื้อ][เพิ่มใบสั่งซื้อ]สามารถเลือกสินค้าที่ไม่ได้กำหนดให้เป็น   "ซื้อได้" ได้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#392]
Summary   Name | [ใบสั่งซื้อ][เพิ่มใบสั่งซื้อ]สามารถเลือกสินค้าที่ไม่ได้กำหนดให้เป็น   "ซื้อได้" ได้
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  392
URL | http://nps001.homeip.net:8085/GoodsInfo.aspx?dataId=1054&dataId2=3
  | http://nps001.homeip.net:8085/PurchaseInfo.aspx?subDoc=18
Step | 1. ตั้งค่า   รหัสซื้อขาย
  | 2. ไม่เลือก CheckBox   ซื้อได้
  | 3. เลือกเมนู   งานประจำวัน
  | 4. เลือกเมนูย่อย   ใบสั่งซื้อสินค้า
  | 5. เลือก   สั่งซื้อทั่วไป
  | 6. แสดงหน้าจอ   รายการใบสั่งซื้อสินค้า
  | 7. กดปุ่ม   เพิ่มใบสั่งซื้อ
  | 8. แสงดหน้าจอ   ใบสั่งซื้อ
  | 9. กดปุ่ม ค้นหาสินค้า
  | 10. แสดง PopUp   ค้นหาสินค้า
  | 11. เลือกสินค้า   "ลีโอ"
  |  
  |  
Actual   Result | ระบบสามารถเลือกสินค้าที่ไม่ได้กำหนดให้   "ซื้อได้" และสามารถบันทึกสำเร็จได้
  |  
Expected   Result | ต้องไม่สามารถเลือกสินค้าได้   และแสดง Error Message "ไม่พบสินค้า"
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/58066105-31b74400-7bb2-11e9-96ad-1bf664a5ba40.png)
![image](https://user-images.githubusercontent.com/45878758/58066111-34199e00-7bb2-11e9-85b1-f90deeb79ace.png)
![image](https://user-images.githubusercontent.com/45878758/58066117-35e36180-7bb2-11e9-9537-5192e8cf6e84.png)
![image](https://user-images.githubusercontent.com/45878758/58066120-3845bb80-7bb2-11e9-9b7a-6e7becac0e23.png)
![image](https://user-images.githubusercontent.com/45878758/58066124-3aa81580-7bb2-11e9-8b85-fdd0e43854c5.png)

**Comment by Mickrepick** [comment]
แก้ไข : ไม่สามารถเลือกสินค้าได้ และแสดง Error Message "ไม่พบสินค้า"

และหน้า SaleInfo ถ้าไม่เลือก CheckBox ขายได้ จากหน้า GoodsInfo จะแสดง Error Message "ไม่พบสินค้า"

**Comment by Vermouthz** [comment]
กรณีที่ไม่เลือก Checkbox ซื้อได้ ในหน้าจอใบสั่งซื้อ ระบบแสดง Message "ไม่สามารถใช้สินค้านี้ได้เนื่องจากไม่ได้ตั้งสิทธิ์การซื้อ!" ถูกต้องไหมครับ ขอคอนเฟิร์มด้วยครับ

http://nps001.homeip.net:8085/PurchaseInfo.aspx?subDoc=18

![image](https://user-images.githubusercontent.com/45878758/58827959-80fb7b00-866e-11e9-92d3-9a6a15c2275e.png)

![image](https://user-images.githubusercontent.com/45878758/58827963-85279880-866e-11e9-9606-b21a315112a8.png)

**Comment by Mickrepick** [comment]
ใช่ครับ
