### ISSUE TITLE
[ใบสั่งซื้อ][เพิ่มใบสั่งซื้อ]   เลือกรายการสินค้าที่เป็น "ซื้อได้" ระบบแสดง Error Message "   ไม่พบสินค้า"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#393]
Summary   Name | [ใบสั่งซื้อ][เพิ่มใบสั่งซื้อ]   เลือกรายการสินค้าที่เป็น "ซื้อได้" ระบบแสดง Error Message "   ไม่พบสินค้า"
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  393
URL | http://nps001.homeip.net:8085/GoodsInfo.aspx?dataId=1058&dataId2=4063
  | http://nps001.homeip.net:8085/PurchaseInfo.aspx?subDoc=18
Step | 1. เลือกเมนู ตั้งค่า
  | 2. เลือกเมนูย่อย   สินค้า
  | 3. แสดงหน้าจอ   รายการสินค้า
  | 4. กดปุ่ม แก้ไข   หลังรายการ
  | 5. แสดงหน้าจอ   ข้อมูลสินค้
  | 6. Blog   รายการรหัสซื้อขาย
  | 7. กดปุ่ม แก้ไข   หลังรายการ
  | 8. แสดงหน้าจอ   เพิ่มรหัสซื้อขาย
  | 9. เลือก Tab   ตั้งค่ารหัสซื้อขาย
  | 10.   เปลี่ยนที่ไม่ได้เลือก CheckBox  ซื้อได้   เป็น เลือก CheckBox ซื้อได้
  | 11. บันทึกสำเร็จ
  | 12. เลือกเมนู   งานประจำวัน
  | 13. เลือกเมนูย่อย   ใบสั่งซื้อสินค้า
  | 14. เลือก   สั่งซื้อทั่วไป
  | 15. แสดงหน้าจอ   รายการใบสั่งซื้อสินค้า
  | 16. กดปุ่ม   เพิ่มใบสั่งซื้อ
  | 17. แสดงหน้าจอ   ใบสั่งซื้อ
  | 18. กดปุ่ม   ค้นหาสินค้า
  | 19. แสดง PopUp   ค้นหาสินค้า
  | 20 .   เลือกรายการสินค้า
  |  
  |  
  |  
Actual   Result | เลือกรายการสินค้าที่เป็น   "ซื้อได้" ระบบแสดง Error Message " ไม่พบสินค้า"   ไม่สามารถเลือกได้
  |  
Expected   Result | ระบบต้องสามารถเลือกรายการสินค้าที่เป็น   "ซื้อได้" ได้
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/58066627-52809900-7bb4-11e9-990d-44069d4e4b3a.png)
![image](https://user-images.githubusercontent.com/45878758/58066629-54e2f300-7bb4-11e9-9b85-8479111570eb.png)
![image](https://user-images.githubusercontent.com/45878758/58066630-56acb680-7bb4-11e9-855f-c8e111cf1be2.png)
![image](https://user-images.githubusercontent.com/45878758/58066632-57dde380-7bb4-11e9-9eb0-fd3eb8198baf.png)

**Comment by acryforever** [comment]
แก้ไข Store
