### ISSUE TITLE
[ใบสั่งซื้อ][เพิ่มใบสั่งซื้อ]เมื่อใช้เลขที่เอกสารซ้ำ   ระบบทำการบันทึกสำเร็จ และมีเลขที่เอกสารซ้ำกันใน Column แสดงผล

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#394]
Summary   Name | [ใบสั่งซื้อ][เพิ่มใบสั่งซื้อ]เมื่อใช้เลขที่เอกสารซ้ำ   ระบบทำการบันทึกสำเร็จ และมีเลขที่เอกสารซ้ำกันใน Column แสดงผล
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  394
URL | http://nps001.homeip.net:8085/PurchaseInfo.aspx?subDoc=18
Step | 1. เลือกเมนู งานประจำวัน
  | 2. เลือกเมนูย่อย   ใบสั่งซื้อสินค้า
  | 3. เลือก   สั่งซื้อทั่วไป
  | 4. แสดงหน้าจอ   รายการใบสั่งซื้อสินค้า
  | 5. กดปุ่ม   เพิ่มใบสั่งซื้อ
  | 6. แสดงหน้าจอ   ใบสั่งซื้อ
  | 7. ระบุข้อมูลใน field
  | - เลขที่เอกสาร   "APS1010" ซ้ำกับที่มีในระบบ
  | 8. กดปุ่ม บันทึก
  | 9. แสดง Message   "เลขที่เอกสารถูกใช้แล้วต้องการเปลี่ยนแปลงเลขที่เอกสาร 201905/012208   อัตโนมัติหรือไม่?"
  | 10. กดปุ่ม Cancel
  |  
  |  
Actual   Result | เมื่อกดปุ่ม Cancel   ระบบทำการบันทึกสำเร็จ มีเลขที่เอกสารซ้ำกันใน Column แสดงผล
  |  
Expected   Result | เมื่อกดปุ่ม Cancel   ต้องไม่ทำการบันทึก และยังคงหน้าเดิมไว้
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/58067789-ea808180-7bb8-11e9-8a1a-9031d31439c1.png)
![image](https://user-images.githubusercontent.com/45878758/58067790-ec4a4500-7bb8-11e9-95dc-f89ae203c899.png)
![image](https://user-images.githubusercontent.com/45878758/58067792-ee140880-7bb8-11e9-83fa-bb88c6ec72f6.png)
![image](https://user-images.githubusercontent.com/45878758/58067793-efddcc00-7bb8-11e9-87e9-25c9807dfcf8.png)

**Comment by acryforever** [comment]
ตรวจสอบโปรแกรมไม่เจอปัญหาดังกล่าวเดี่ยวจะทำการอัพโค๊ดขึ้นไปใหม่ครับ
![image](https://user-images.githubusercontent.com/47658214/58395868-70e30a80-8074-11e9-8648-b7baf80c078b.png)

![image](https://user-images.githubusercontent.com/47658214/58395884-7f312680-8074-11e9-9609-4a74d70c643f.png)

![image](https://user-images.githubusercontent.com/47658214/58395895-8b1ce880-8074-11e9-8f3a-ec9fcf32b02d.png)
