### ISSUE TITLE
[เพิ่มหมวดย่อย][ดู   หลังรายการ]ระบบดึงค่า Field "สถานะ" มาไม่ถูกต้อง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#399]
Summary   Name | [เพิ่มหมวดย่อย][ดู   หลังรายการ]ระบบดึงค่า Field "สถานะ" มาไม่ถูกต้อง
-- | --
Defect No. |  399
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SubCategoryInfo.aspx?dataId=3063&dataId2=2050
Step | 1. Login WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย หมวด
  | 4.   แสดงหน้าจอ รายการหมวดสินค้า
  | 5. กดปุ่ม   แก้ไข หลังรายการ
  | 6.   แสดงหน้าจอ เพิ่มหมวดสินค้า
  | 7. แสดง   Blog รายการหมวดย่อย
  | 8. กดปุ่ม   ดู หลังรายการ
  | 9.   แสดงหน้าจอ เพิ่มหมวดย่อย
  | 10.   ระบุข้อมูลใน field
  | - รหัส
  | -   ชื่อภาษาไทย
  | -   ชื่อภาษาอังกฤษ
  | -   ลำดับการจัดเรียง
  | - สถานะ   "ปิดใช้งาน"
  | - รูป
  | -   รายละเอียด
  | 11. กดปุ่ม   บันทึก
  | 12.   บันทึกสำเร็จ
  | 13.   แสดงหน้าจอ รายการหมวดหลักสินค้า
  | 14. กดปุ่ม   ดู หลังรายการ
  |  
Actual   Result | ระบบดึงค่า Field   "สถานะ" มาไม่ถูกต้อง
  |  
Expected   Result | ระบบต้องดึงค่า Field   "สถานะ" มาถูกต้อง
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/58106159-d9179380-7c11-11e9-88ca-899d6fd80065.png)
![image](https://user-images.githubusercontent.com/45878758/58106164-dae15700-7c11-11e9-890e-281863d5e79d.png)
![image](https://user-images.githubusercontent.com/45878758/58106169-dd43b100-7c11-11e9-8c0e-e03763cee30e.png)
![image](https://user-images.githubusercontent.com/45878758/58106178-dfa60b00-7c11-11e9-87f6-9c1696c77fb0.png)
![image](https://user-images.githubusercontent.com/45878758/58106193-e46abf00-7c11-11e9-8335-5f2c8952a544.png)

**Comment by Mickrepick** [comment]
แก้ไข : ระบบดึงค่า Field "สถานะ" มาถูกต้อง
