### ISSUE TITLE
[รายการคลัง][แก้ไข   หลังรายการ]แก้ไข เมื่อกดปุ่ม ลบ หลังรายการ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#400]
Summary   Name | [รายการคลัง][แก้ไข   หลังรายการ]แก้ไข เมื่อกดปุ่ม ลบ หลังรายการ
-- | --
Defect No. |  400
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/WareHouseInfo.aspx?dataId=2014
Step | 1. Login WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย คลัง
  | 4.   แสดงหน้าจอ รายการคลัง
  | 5. กดปุ่ม   เพิ่มคลัง
  | 6.   แสดงหน้าจอ เพิ่มคลัง
  | 7.   ระบุข้อมูลใน field
  | 8. กดปุ่ม   บันทึก
  | 9.   บันทึกสำเร็จ
  | 10.   แสดงหน้าจอ รายการคลัง
  | 11. กดปุ่ม   แก้ไข หลังรายการ
  | 12.   แสดงหน้าจอ เพิ่มคลัง
  | 13. Blog   รายการโซน
  | 14. กดปุ่ม   ลบ หลังรายการ
  |  
Actual   Result | 1.เมื่อกดปุ่ม ลบ   ระบบแสดง Message "ทำการยืนยัน ที่จะบันทึกข้อมูล?"
  | 2.เมื่อกดปุ่ม ตกลง   ระบบไม่ทำการ ลบ ข้อมูลให้
  |  
Expected   Result | 1.เมื่อกดปุ่ม ลบ   ระบบต้องแสดง Message "ทำการยืนยัน ที่จะลบข้อมูล?"
  | 2.เมื่อกดปุ่ม   ตกลง ระบบต้องทำการลบข้อมูล
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/58106356-33b0ef80-7c12-11e9-8eea-749a4ab82814.png)
![image](https://user-images.githubusercontent.com/45878758/58106362-36134980-7c12-11e9-9807-5d3b46340df8.png)
![image](https://user-images.githubusercontent.com/45878758/58106380-3a3f6700-7c12-11e9-97fe-6b9608171748.png)
![image](https://user-images.githubusercontent.com/45878758/58106392-3e6b8480-7c12-11e9-9c93-fd9ae5f3b1af.png)

**Comment by Mickrepick** [comment]
แก้ไข : 

1.เมื่อกดปุ่ม ลบ ระบบแสดง Message "ทำการยืนยัน ที่จะลบข้อมูล?"

2.เมื่อกดปุ่ม ตกลง ระบบทำการลบข้อมูล
