### ISSUE TITLE
[เพิ่ม location][แก้ไข หลังรายการ]เมื่อทำการเพิ่ม location แล้วกดปุ่ม บันทึก   ระบบไม่ทำการบันทึกรายการให้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#403]
Summary   Name | [เพิ่ม location][แก้ไข หลังรายการ]เมื่อทำการเพิ่ม location แล้วกดปุ่ม บันทึก   ระบบไม่ทำการบันทึกรายการให้
-- | --
Defect No. |  403
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/LocationInfo.aspx?dataId2=3010&pageState=ZoneInfo
Step | 1. Login WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย คลัง
  | 4.   แสดงหน้าจอ รายการคลัง
  | 5. กดปุ่ม   เพิ่มคลัง
  | 6.   แสดงหน้าจอ เพิ่มคลัง
  | 7.   ระบุข้อมูลใน field
  | 8. กดปุ่ม   บันทึก
  | 9.   บันทึกสำเร็จ
  | 10.   แสดงหน้าจอ รายการคลัง
  | 11. กดปุ่ม   แก้ไข หลังรายการ
  | 12.   แสดงหน้าจอ เพิ่มคลัง
  | 13. Blog   รายการโซน
  | 14. กดปุ่ม   แก้ไข หลังรายการ
  | 15.   แสดงหน้าจอ เพิ่มโซน
  | 16. Blog   Location Picking
  | 17. กดปุ่ม   เพิ่ม location
  | 18. เลือก   Tab รายการ
  | 19.   ระบุข้อมูลทุก field
  | - รหัส   "20 ตัวอักษร"
  | -   ชื่อภาษาไทย "100 ตัวอักษร"
  | -   ชื่อภาษาอังกฤษ "100 ตัวอักษร"
  | - Priority
  | - โซน
  | -   ประเภทการจัดเก็บ
  | - สถานะ   "ใช้งาน"
  | -   รายละเอียด "300 ตัวอักษร"
  | - รูปภาพ
  | 20. กดปุ่ม   บันทึก
  |  
Actual   Result | เมื่อทำการเพิ่ม   location แล้วกดปุ่ม บันทึก ระบบไม่ทำการบันทึกรายการให้
  |  
Expected   Result | เมื่อทำการเพิ่ม   location แล้วกดปุ่ม บันทึก ระบบต้องทำการบันทึกรายการให้
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/58107094-60b1d200-7c13-11e9-83a2-7793974f93dd.png)
![image](https://user-images.githubusercontent.com/45878758/58107095-63142c00-7c13-11e9-9f88-10d77acd5f5f.png)
![image](https://user-images.githubusercontent.com/45878758/58107100-64ddef80-7c13-11e9-8129-4590e6d3cce4.png)
![image](https://user-images.githubusercontent.com/45878758/58107122-6effee00-7c13-11e9-89d9-8455addce4b0.png)

**Comment by Mickrepick** [comment]
แก้ไข : 
       เข้าจากคลัง                                                                            เข้าจากรายการตำแหน่งจัดเก็บ
1. เลือกเมนู ตั้งค่า                                                                      1. เลือกเมนู ตั้งค่า    
2. เลือกเมนูย่อย คลัง                                                                 2. เลือกเมนูย่อย รายการตำแหน่งจัดเก็บ
3. แสดงหน้าจอ รายการคลัง                                                       3. กดปุ่ม เพิ่มLocation
4. กดปุ่ม เพิ่มคลัง                                                                          จะสามารถเลือกคลังกับโซนได้
5. แสดงหน้าจอ เพิ่มคลัง
6. ระบุข้อมูลใน field
7. กดปุ่ม บันทึก
8. บันทึกสำเร็จ
9. แสดงหน้าจอ รายการคลัง
10. กดปุ่ม แก้ไข หลังรายการ
11. แสดงหน้าจอ เพิ่มคลัง
12. Blog รายการโซน
13. กดปุ่ม แก้ไข หลังรายการ
14. แสดงหน้าจอ เพิ่มโซน
15. Blog Location Picking
16. กดปุ่ม เพิ่ม location
ระบบจะ fix คลังกับโซนให้ไม่สามารถแก้ไขได้
