### ISSUE TITLE
[รายการสินค้า]ระบบแสดงรายการหมวดย่อยไม่ครบ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#406]
Summary   Name | [รายการสินค้า]ระบบแสดงรายการหมวดย่อยไม่ครบ
-- | --
Defect No. |  406
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/SkuList.aspx?menuID=35
  | http://nps001.homeip.net:8085/CategoryInfo.aspx?dataId=1&view=1
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย สินค้า
  | 4.   แสดงหน้าจอ รายการสินค้า
  | 5.   ระบุข้อมูลใน field
  | - เลือก   หมวดหลัก
  | - เลือก   หมวดย่อย
  | 6.   เลือกเมนู ตั้งค่า
  | 7.   เลือกเมนูย่อย หมวด
  | 8.   แสดงหน้าจอ รายการหมวดสินค้า
  | 9. กดปุ่ม   ดู หลังรายการ
  | 10.   แสดงหน้าจอ เพิ่มหมวดสินค้า
  | 11.   ตรวจสอบรายการหมวดย่อย
  |  
Actual   Result | ระบบแสดงรายการหมวดย่อยไม่ครบ
  |  
Expected   Result | ระบบต้องแสดงรายการหมวดย่อยที่สร้างไว้
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/58468464-cb10c800-8167-11e9-8469-3ece667888dd.png)
![image](https://user-images.githubusercontent.com/45878758/58468477-ce0bb880-8167-11e9-9bf5-f56e60f29e22.png)
![image](https://user-images.githubusercontent.com/45878758/58468479-d06e1280-8167-11e9-9ccf-491eb5c9ff28.png)

**Comment by Mickrepick** [comment]
แก้ไข : select ข้อมูลหน้า CategoryInfo ผิดครับ 
หน้า SKU ถูกแล้วครับ
