### ISSUE TITLE
[เพิ่มราคาขาย][เพิ่มใบสั่งซื้อ]เมื่อ   เพิ่มราคาสินค้า เลือกเป็น ปิดใช้งาน ในใบสั่งซื้อ Field "ราคาสั่ง"   เป็น 10000

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#408]
Summary   Name | [เพิ่มราคาขาย][เพิ่มใบสั่งซื้อ]เมื่อ   เพิ่มราคาสินค้า เลือกเป็น ปิดใช้งาน ในใบสั่งซื้อ Field "ราคาสั่ง"   เป็น 10000
-- | --
Defect No. |  408
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/GoodsPriceTabInfo.aspx?dataId=3064&dataId2=1058
  | http://nps001.homeip.net:8085/PurchaseInfo.aspx?subDoc=18
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย สินค้า
  | 4.   แสดงหน้าจอ รายการสินค้า
  | 5. กดปุ่ม   แก้ไข หลังรายการ
  | 6.   แสดงหน้าจอ ข้อมูลสินค้า
  | 7. Blog   รายการรหัสซื้อขาย
  | 8. กดปุ่ม   แก้ไข หลังรายการรหัสซื้อขาย
  | 9.   แสดงหน้าจอ เพิ่มรหัสซื้อขาย
  | 10. กดปุ่ม   เพิ่มราคาขาย
  | 11.   แสดงหน้าจอ เพิ่มราคาสินค้า
  | 12.   ระบุข้อมูลใน field
  | -   ประเภทราคาขาย
  | - ราคา   "10,000.00"
  | - ป้ายราคา
  | - ส่วนลด   "10,000.00"
  | - สถานะ   "ปิดใช้งาน"
  | 13. กดปุ่ม   บันทึก
  | 14.   บันทึกสำเร็จ
  | 15.   เลือกเมนู งานประจำวัน
  | 16.   เลือกเมนูย่อย ใบสั่งซื้อสินค้า
  | 17. เลือก   สั่งซื้อทั่วไป
  | 18.   แสดงหน้าจอ รายการใบสั่งซื้อสินค้า
  | 19. กดปุ่ม   เพิ่มใบสั่งซื้อ
  | 20.   แสดงหน้าจอ ใบสั่งซื้อ
  | 21. กดปุ่ม   ค้นหาสินค้า
  |  
Actual   Result | เมื่อ เพิ่มราคาสินค้า   เลือกเป็น ปิดใช้งาน ในใบสั่งซื้อ Field "ราคาสั่ง" เป็น 10000
  |  
Expected   Result | เมื่อ เพิ่มราคาสินค้า   เลือกเป็น ปิดใช้งาน ในใบสั่งซื้อ Field "ราคาสั่ง" ต้องเป็น 0.00
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/58473833-cb16c500-8173-11e9-917c-8ddfd9aa59bb.png)
![image](https://user-images.githubusercontent.com/45878758/58473835-cd791f00-8173-11e9-9bba-074c9615f39a.png)
![image](https://user-images.githubusercontent.com/45878758/58473840-d10ca600-8173-11e9-8f0d-27827ae72fee.png)
![image](https://user-images.githubusercontent.com/45878758/58473844-d2d66980-8173-11e9-93ab-b2309982890c.png)
![image](https://user-images.githubusercontent.com/45878758/58473847-d4079680-8173-11e9-8538-5365e3bff09f.png)
![image](https://user-images.githubusercontent.com/45878758/58473854-d669f080-8173-11e9-8be3-3c8b55698ef3.png)
![image](https://user-images.githubusercontent.com/45878758/58473857-d79b1d80-8173-11e9-8734-4d8b9f980644.png)
![image](https://user-images.githubusercontent.com/45878758/58473861-dbc73b00-8173-11e9-8a67-cbf0f8c56972.png)

**Comment by Mickrepick** [comment]
เวลาสั่งซื้อ กรณีที่ add สินค้ามาแล้ว
ราคาสั่งซื้อจะเท่ากับ 0.00 
กรณีขาย จะเอามาจากราคา แต่ส่วนลด ส่วนเพิ่ม ยังไม่ถูกนำมาใช้(feature)
