### ISSUE TITLE
[เพิ่มรหัสซื้อขาย][แก้ไข   หลังรายการ] เมื่อเปลี่ยน field คลัง เป็น "กรุณาเลือก"   ระบบไม่เปลี่ยน โซนและตำแหน่งเก็บ เป็น "กรุณาเลือก"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#411]
Summary   Name | [เพิ่มรหัสซื้อขาย][แก้ไข   หลังรายการ] เมื่อเปลี่ยน field คลัง เป็น "กรุณาเลือก"   ระบบไม่เปลี่ยน โซนและตำแหน่งเก็บ เป็น "กรุณาเลือก"
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  411
URL | http://nps001.homeip.net:8085/GoodsInfo.aspx?dataId=1041&dataId2=4055
Step | 1. เลือกเมนู ตั้งค่า
  | 2. เลือกเมนูย่อย   สินค้า
  | 3. แสดงหน้าจอ   รายการสินค้า
  | 4. กดปุ่ม แก้ไข   หลังรายการ
  | 5. แสดงหน้าจอ   ข้อมูลสินค้า
  | 6. Blog   รายการรหัสซื้อขาย
  | 7. กดปุ่ม แก้ไข   หลังรายการ
  | 8. แสดงหน้าจอ   เพิ่มรหัสซื้อขาย
  | 9. เลือก Tab   การจัดเก็บ
  | 10. Field คลัง , โซน   , ตำแหน่งเก็บ มีข้อมูลเดิมอยู่
  | 11. เปลี่ยน field   คลัง เป็น "กรุณาเลือก"
  |  
  |  
Actual   Result | 1. เมื่อเปลี่ยน field   คลัง เป็น "กรุณาเลือก" ระบบไม่เปลี่ยน โซนและตำแหน่งเก็บ เป็น   "กรุณาเลือก"
  | 2. เมื่อเปลี่ยน field   โซน เป็น "กรุณาเลือก" ระบบไม่เปลี่ยน ตำแหน่งเก็บ เป็น   "กรุณาเลือก"
  |  
  |  
Expected   Result | 1. เมื่อเปลี่ยน field   คลัง เป็น "กรุณาเลือก" ระบบต้องเปลี่ยน โซนและตำแหน่งเก็บ เป็น   "กรุณาเลือก"
  | 2. เมื่อเปลี่ยน field   โซน เป็น "กรุณาเลือก" ระบบต้องเปลี่ยน ตำแหน่งเก็บ เป็น   "กรุณาเลือก"
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/58539014-a4629800-8220-11e9-997c-f26c4a1aea78.png)
![image](https://user-images.githubusercontent.com/45878758/58539022-a6c4f200-8220-11e9-8741-fa7e86b6c346.png)
![image](https://user-images.githubusercontent.com/45878758/58539026-a9274c00-8220-11e9-978d-28a4725e9c8e.png)

**Comment by Patthamaporn** [comment]
แก้ไข 
1. เมื่อเปลี่ยน field คลัง เป็น "กรุณาเลือก" ระบบต้องเปลี่ยน โซนและตำแหน่งเก็บ เป็น "กรุณาเลือก
2. เมื่อเปลี่ยน field โซน เป็น "กรุณาเลือก" ระบบต้องเปลี่ยน ตำแหน่งเก็บ เป็น "กรุณาเลือก"
