### ISSUE TITLE
Summary   Name | [รายการผู้ใช้][แก้ไข หลังรายการ][Blog รายละเอียด][Tab ที่อยู่][แกเไข หลังรายการ] เมื่อกดปุ่ม แก้ไข   หลังรายการที่อยู่ ระบบไม่ แสดงหน้าจอเพิ่มที่อยู่ แต่ขึ้นเป็น TextBox แทน

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#412]
Summary   Name | [รายการผู้ใช้][แก้ไข หลังรายการ][Blog รายละเอียด][Tab ที่อยู่][แกเไข หลังรายการ] เมื่อกดปุ่ม แก้ไข   หลังรายการที่อยู่ ระบบไม่ แสดงหน้าจอเพิ่มที่อยู่ แต่ขึ้นเป็น TextBox แทน
-- | --
Defect No. |  412
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/UserInfo.aspx?dataId=1012
Step | 1. Login WMS on Chorme
  | 2.   เลือกเมนู ระบบ
  | 3.   เลือกเมนูย่อย ผู้ใช้งาน
  | 4.   แสดงหน้าจอ รายการผู้ใช้งาน
  | 5. กดปุ่ม   เพิ่มผู้ใช้งาน
  | 6.   แสดงหน้าจอ ผู้ใช้งาน
  | 7.   กรอกข้อมูลใน feld
  | 8. กดปุ่ม   บันทึก
  | 9.   บันทึกสำเร็จ
  | 10.   แสดงหน้าจอ รายการผู้ใช้งาน
  | 11. กดปุ่ม   แก้ไข หลังรายการ
  | 12.   แสดงหน้าจอ รายการผู้ใช้งาน
  | 13. กดปุ่ม   แก้ไข หลังรายการ Blog รายละเอียด
  | 14.   แสดงหน้าจอ เพิ่มที่อยู่
  |  
Actual   Result | เมื่อกดปุ่ม แก้ไข   หลังรายการที่อยู่ ระบบไม่ แสดงหน้าจอเพิ่มที่อยู่ แต่ขึ้นเป็น TextBox แทน
  |  
Expected   Result | เมื่อกดปุ่ม แก้ไข   หลังรายการที่อยู่ ระบบต้องแสดงหน้าจอเพิ่มที่อยู่ (แก้ไข)
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/58546810-61102580-8230-11e9-98c9-7e6fce6f7eb4.png)
![image](https://user-images.githubusercontent.com/45878758/58546817-63727f80-8230-11e9-88e9-0938af0852c8.png)
![image](https://user-images.githubusercontent.com/45878758/58546822-653c4300-8230-11e9-86d6-356bf4192852.png)
![image](https://user-images.githubusercontent.com/45878758/58546829-67060680-8230-11e9-8c39-3ffeb5504bd3.png)
![image](https://user-images.githubusercontent.com/45878758/58546844-6bcaba80-8230-11e9-89ac-e060ef1057d9.png)
![image](https://user-images.githubusercontent.com/45878758/58546848-6f5e4180-8230-11e9-8204-9a0242117132.png)

**Comment by Patthamaporn** [comment]
แก้ไข สามารถเข้าหน้าที่อยู่หลังจากกดแก้ไขในหน้าผู้ใช้งาน
