### ISSUE TITLE
[รายการตำแหน่ง][ดู   หลังรายการ]เมื่อกดปุ่ม ดู หลังรายการระบบ แสดงหน้าจอ   "รายการกำหนดสิทธิ์"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#413]
Summary   Name | [รายการตำแหน่ง][ดู   หลังรายการ]เมื่อกดปุ่ม ดู หลังรายการระบบ แสดงหน้าจอ   "รายการกำหนดสิทธิ์"
-- | --
Defect No. |  413
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/RoleInfo.aspx
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู ระบบ
  | 3.   เลือกเมนูย่อย สิทธิ์การใช้งาน
  | 4.   แสดงหน้าจอ รายการตำแหน่ง
  | 5. กดปุ่ม   ดู
  | 6.   แสดงหน้าจอ เพิ่มตำแหน่ง
  |  
Actual   Result | เมื่อกดปุ่ม   ดู หลังรายการระบบ แสดงหน้าจอ "รายการกำหนดสิทธิ์"
  |  
Expected   Result | ระบบต้องแสดงหน้าจอ   เพิ่มตำแหน่ง
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/58548199-0c21de80-8233-11e9-80f5-af25803884f1.png)
![image](https://user-images.githubusercontent.com/45878758/58548204-10e69280-8233-11e9-858a-12c9a357961e.png)
![image](https://user-images.githubusercontent.com/45878758/58548216-17750a00-8233-11e9-8170-d1ba8b2481d0.png)

**Comment by Patthamaporn** [comment]
แก้ไข เมื่อกดดูในหน้ารายการตำแหน่ง จะไปหน้าเพิ่มตำแหน่ง
