### ISSUE TITLE
ข้อมูลสินค้า_ ... หลัง Field ยี่ห้อ_เพิ่มยี่ห้อ_เมื่อกดปุ่มบันทึก ระบบไม่ทำการปิด Pop up และไม่ขึ้น Message บันทึกสำเร็จ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#415]
Summary   Name | ข้อมูลสินค้า_   ... หลัง Field ยี่ห้อ_เพิ่มยี่ห้อ_เมื่อกดปุ่มบันทึก ระบบไม่ทำการปิด Pop up   และไม่ขึ้น Message บันทึกสำเร็จ
-- | --
Defect No. |  415
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/PopupBrandInfo.aspx
Step | 1. Login
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย สินค้า
  | 4.   แสดงหน้าจอ รายการสินค้า
  | 5.   กดปุ่ม แก้ไข หลังรายการ
  | 6.   แสดงหน้าจอ ข้อมูลสินค้า
  | 7.   กดปุ่ม ... หลัง field ยี่ห้อ
  | 8.   แสดง PopUp เพิ่มยี่ห้อ
  | 9.   ระบุข้อมูลใน field
  | 10.   กดปุ่ม บันทึก
  |  
  |  
Actual   Result | กดปุ่มบันทึก   ระบบไม่ทำการปิด Pop up และไม่ขึ้น Message บันทึกสำเร็จ
  |  
Expected   Result | เมื่อกดปุ่มบันทึก   ระบบต้องปิดหน้าจอ Pop up และขึ้น Message บันทึกสำเร็จ
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/58550083-370e3180-8237-11e9-8586-5fdbf0c72dfb.png)
![image](https://user-images.githubusercontent.com/45878758/58550105-3ecdd600-8237-11e9-885e-3b1d512cbf6c.png)
![image](https://user-images.githubusercontent.com/45878758/58550109-41303000-8237-11e9-857c-d8c6d62f2c35.png)

**Comment by Mickrepick** [comment]
แก้ไข : เมื่อกดปุ่มบันทึก จะขึ้น Message บันทึกสำเร็จ แล้วปิดหน้า Popup
