### ISSUE TITLE
 [รายการผู้ใช้][เพิ่มผู้ใช้งาน]เมื่อ   กดปุ่มบันทึก แสดง Message "บันทึกข้อมูลล้มเหลว"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#416]
Summary   Name | [รายการผู้ใช้][เพิ่มผู้ใช้งาน]เมื่อ   กดปุ่มบันทึก แสดง Message "บันทึกข้อมูลล้มเหลว"
-- | --
Defect No. |  416
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/UserInfo.aspx
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู ระบบ
  | 3.   เลือกเมนูย่อย ผู้ใช้งาน
  | 4.   แสดงหน้าจอ รายการผู้ใช้งาน
  | 5. กดปุ่ม   เพิ่มผู้ใช้งาน
  | 6.   แสดงหน้าจอ ผู้ใช้งาน
  | 7.   ระบุข้อมูลทุก field ใน Tab
  | - พนักงาน
  | -   ข้อมูลส่วนตัว
  | -   เข้าใช้งาน
  | 8. ระบุ   สถานะ เป็น "ใช้งาน"
  | 9. กดปุ่ม   บันทึก
  |  
Actual   Result | 1.เมื่อ   กดปุ่มบันทึก แสดง Message "บันทึกข้อมูลล้มเหลว"
  |  
Expected   Result | 1.เมื่อ กดปุ่มบันทึก   ระบบต้องแสดง Message "บันทึกสำเร็จ"
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/58577982-e8ca5400-8271-11e9-9826-13ddaf97ae74.png)
![image](https://user-images.githubusercontent.com/45878758/58577984-ebc54480-8271-11e9-9df4-ce2edb3b831f.png)
![image](https://user-images.githubusercontent.com/45878758/58577989-ef58cb80-8271-11e9-8601-bf43366f7767.png)

**Comment by Patthamaporn** [comment]
แก้ไข หากบันทึกผ่านแล้ว ระบบจะแสดง Message "บันทึกสำเร็จ"
