### ISSUE TITLE
[รายการผู้ใช้][เพิ่มผู้ใช้]เมื่อกดปุ่ม   เพิ่ม อุปกรณ์ขนย้าย โดยยังไม่มีการบันทึกผู้ใช้งาน ระบบแสดงหน้าจอ Server Error   in '/' Application

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#418]
Summary   Name | [รายการผู้ใช้][เพิ่มผู้ใช้]เมื่อกดปุ่ม   เพิ่ม อุปกรณ์ขนย้าย โดยยังไม่มีการบันทึกผู้ใช้งาน ระบบแสดงหน้าจอ Server Error   in '/' Application
-- | --
Defect No. |  418
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/UserInfo.aspx
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู ระบบ
  | 3.   เลือกเมนูย่อย ผู้ใช้งาน
  | 4.   แสดงหน้าจอ รายการผู้ใช้งาน
  | 5. กดปุ่ม   เพิ่มผู้ใช้งาน
  | 6.   แสดงหน้าจอ ผู้ใช้งาน
  | 7.   ไม่ระบุข้อมูลทุก field
  | 8. Blog   รายละเอียด
  | 9. Tab   อุปกรณ์ขนย้าย
  | 10. กดปุ่ม   เพิ่ม
  |  
Actual   Result | เมื่อกดปุ่ม   เพิ่ม อุปกรณ์ขนย้าย โดยยังไม่มีการบันทึกผู้ใช้งาน ระบบแสดงหน้าจอ Server Erroe   in '/' Application
  |  
Expected   Result | เมื่อกดปุ่ม เพิ่ม   อุปกรณ์ขนย้าย โดยยังไม่มีการบันทึกผู้ใช้งาน ระบบต้องแสดง Error Message   "ต้องบันทึกรายการก่อน ดำเนินการต่อ"
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/58556602-9aec2680-8246-11e9-98ef-105fdede5403.png)
![image](https://user-images.githubusercontent.com/45878758/58556611-a0e20780-8246-11e9-9d59-76f5fd7ce24e.png)

**Comment by Patthamaporn** [comment]
แก้ไข สามารถกดpopupเลือกอุปกรณ์ได้โดยไม่มี error
