### ISSUE TITLE
[รายการผู้ใช้งาน][แก้ไข   หลังรายการ][Tab ที่อยู่]ระบบไม่ทำการลบขอมูลให้ เมื่อกดปุ่ม ลบ หลังรายการที่อยู่

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#419]
Summary   Name | [รายการผู้ใช้งาน][แก้ไข   หลังรายการ][Tab ที่อยู่]เมื่อกดปุ่ม ตกลง ที่จะลบข้อมูล   ระบบไม่ทำการลบข้อมูลให้
-- | --
Defect No. |  419
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/UserInfo.aspx?dataId=1012
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู ระบบ
  | 3.   เลือกเมนูย่อย ผู้ใช้งาน
  | 4.   แสดงหน้าจอ รายการผู้ใช้งาน
  | 5. กดปุ่ม   เพิ่มผู้ใช้งาน
  | 6.   แสดงหน้าจอ ผู้ใช้งาน
  | 7.   ระบุข้อมูลใน field
  | 8. กดปุ่ม   บันทึก
  | 9.   บันทึกสำเร็จ
  | 10.   แสดงหน้าจอ รายการผู้ใช้งาน
  | 11. กดปุ่ม   แก้ไข หลังรายการ
  | 12.   แสดงหน้าจอ ผู้ใช้งาน
  | 13. Blog   รายละเอียด
  | 14. Tab   ที่อยู่
  | 15. กดปุ่ม   ลบ หลังรายการ
  |  
Actual   Result | เมื่อกดปุ่ม   ตกลง ที่จะลบข้อมูล ระบบไม่ทำการลบข้อมูลให้
  |  
Expected   Result | เมื่อกดปุ่ม ตกลง   ที่จะลบข้อมูล ระบบต้องทำการลบข้อมูลให้
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/58558033-fc61c480-8249-11e9-88d7-ad9c35b53596.png)
![image](https://user-images.githubusercontent.com/45878758/58558039-fe2b8800-8249-11e9-9c42-441458e8e4fc.png)
![image](https://user-images.githubusercontent.com/45878758/58558054-07b4f000-824a-11e9-9279-fa7f1bc12be0.png)

**Comment by Patthamaporn** [comment]
แก้ไข หากลบรายการที่อยู่ในหน้าพนักงาน รายการที่ลบไปแล้วจะไม่แสดง
