### ISSUE TITLE
[เพิ่มผู้ใช้งาน][รายละเอียด][ดู   หลังรายการ]เมื่อกดปุ่ม ดู ระบบไม่เข้าหน้าจอ เพิ่มที่อยู่ ให้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#420]
Summary   Name | [เพิ่มผู้ใช้งาน][รายละเอียด][ดู   หลังรายการ]เมื่อกดปุ่ม ดู ระบบไม่เข้าหน้าจอ เพิ่มที่อยู่ ให้
-- | --
Defect No. |  420
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/UserInfo.aspx?dataId=1012
Step | 1. Login WMS on Chorme
  | 2.   เลือกเมนู ระบบ
  | 3.   เลือกเมนูย่อย ผู้ใช้งาน
  | 4.   แสดงหน้าจอ รายการผู้ใช้งาน
  | 5. กดปุ่ม   เพิ่มผู้ใช้งาน
  | 6.   แสดงหน้าจอ ผู้ใช้งาน
  | 7.   ระบุข้อมูลใน field
  | 8. กดปุ่ม   บันทึก
  | 9.   บันทึกสำเร็จ
  | 10.   แสดงหน้าจอ รายการผู้ใช้งาน
  | 11. กดปุ่ม   แก้ไข หลังรายการ
  | 12.   แสดงหน้าจอ ผู้ใช้งาน
  | 13. Blog   รายละเอียด
  | 14. Tab   ที่อยู่
  | 15. กดปุ่ม   เพิ่มที่อยู่
  | 16.   แสดงหน้าจอ เพิ่มที่อยู่
  | 17.   ระบุข้อมูลทุก field
  | 18. กดปุ่ม   บันทึก
  | 19.   บันทึกสำเร็จ
  | 20.   แสดงหน้าจอ ผู้ใช้งาน
  | 21. Blog   รายละเอียด
  | 22. Tab   ที่อยู่
  | 23. กดปุ่ม   ดู หลังรายการ
  |  
Actual   Result | เมื่อกดปุ่ม   ดู ระบบไม่เข้าหน้าจอ เพิ่มที่อยู่ ให้
  |  
Expected   Result | เมื่อกดปุ่ม ดู   ระบบต้องเข้าหน้าจอ เพิ่มที่อยู่ ให้
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/58566009-fecc1a80-8259-11e9-82af-3a46650eb71f.png)
![image](https://user-images.githubusercontent.com/45878758/58566011-fffd4780-8259-11e9-8e04-88480b1897da.png)
![image](https://user-images.githubusercontent.com/45878758/58566015-01c70b00-825a-11e9-949c-4f516d2f1437.png)
![image](https://user-images.githubusercontent.com/45878758/58566017-0390ce80-825a-11e9-8a12-675f2511c006.png)
![image](https://user-images.githubusercontent.com/45878758/58566032-0a1f4600-825a-11e9-909e-0e9489cb8d71.png)

**Comment by Patthamaporn** [comment]
แก้ไข หน้าพนักงานจะสามารถกดดูและแก้ไขได้
