### ISSUE TITLE
[รายการตำแหน่ง][เพิ่มตำแหน่ง]เมื่อกดปุ่ม   บันทึก ข้อมูล ระบบแสดง Error messenger "Invalid object name  WebWMSDB.dbo.PMS_Menu ."

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#421]
Summary   Name | [รายการตำแหน่ง][เพิ่มตำแหน่ง]เมื่อกดปุ่ม   บันทึก ข้อมูล ระบบแสดง Error messenger "Invalid object name  WebWMSDB.dbo.PMS_Menu ."
-- | --
Defect No. |  421
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/RoleInfo.aspx
Step | 1. Login WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย สิทธิ์การใช้งาน
  | 4.   แสดงหน้าจอ รายการตำแหน่ง
  | 5. กดปุ่ม   เพิ่มตำแหน่ง
  | 6.   แสดงหน้าจอ เพิ่มตำแหน่ง
  | 7.   ระบุข้อมูลทุก field
  | 8. กดปุ่ม   บันทึก
  |  
Actual   Result | เมื่อกดปุ่ม   บันทึก ข้อมูล ระบบแสดง Error messenger "Invalid object name  WebWMSDB.dbo.PMS_Menu ."
  |  
Expected   Result | เมื่อกดปุ่ม บันทึก   ข้อมูล ต้องไม่ขึ้น Error Messenger
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/58568753-fc1ff400-825e-11e9-95f7-a9f8d3d5dcca.png)
![image](https://user-images.githubusercontent.com/45878758/58568762-00e4a800-825f-11e9-8cf9-f6c3b7b5a065.png)

**Comment by Mickrepick** [comment]
แก้ไขแล้วครับ
