### ISSUE TITLE
[รายการตำแหน่ง][เพิ่มตำแหน่ง]แก้ไขข้อความแจ้งเตือน   เมื่อไม่กรอก Field mandatory

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#422]
Summary   Name | [รายการตำแหน่ง][เพิ่มตำแหน่ง]แก้ไขข้อความแจ้งเตือน   เมื่อไม่กรอก Field mandatory
-- | --
Defect No. |  422
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/RoleInfo.aspx
Step | 1. Login WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย สิทธิ์การใช้งาน
  | 4.   แสดงหน้าจอ รายการตำแหน่ง
  | 5. กดปุ่ม   เพิ่มตำแหน่ง
  | 6.   แสดงหน้าจอ เพิ่มตำแหน่ง
  | 7.   ระบุข้อมูลทุก field
  | 8. กดปุ่ม   บันทึก
  |  
Actual   Result | 1.   ระบบแสดงข้อความแจ้งเตือนใต้ field
  | -   กรุณากรอกชื่อรายการ
  | 2.   ไม่สามารถบันทึกข้อมูลได้ :
  | -   กรุณากรอกชื่อรายการ
Expected   Result | 1.   ระบบแสดงข้อความแจ้งเตือนใต้ field
  | -   กรุณากรอกชื่อตำแหน่ง
  | 2.   ไม่สามารถบันทึกข้อมูลได้ :
  | -   กรุณากรอกชื่อตำแหน่ง

TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/58569190-d6471f00-825f-11e9-9988-3afea0cff0eb.png)
![image](https://user-images.githubusercontent.com/45878758/58569211-de06c380-825f-11e9-83e8-624341294de9.png)

**Comment by Mickrepick** [comment]
แก้ไข :  
1. ระบบแสดงข้อความแจ้งเตือนใต้ field
    กรุณากรอกชื่อตำแหน่ง
2. ไม่สามารถบันทึกข้อมูลได้ :
    - กรุณากรอกชื่อตำแหน่ง
