### ISSUE TITLE
[เพิ่มรหัสซื้อขาย][แก้ไข   หลังรายการ][Tab บรรจุภัณฑ์]เมื่อกดปุ่ม OK ระบบลบรายการ โดยไม่แสดง Message   "ลบสำเร็จ"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#449]
Summary   Name | [เพิ่มรหัสซื้อขาย][แก้ไข   หลังรายการ][Tab บรรจุภัณฑ์]เมื่อกดปุ่ม OK ระบบลบรายการ โดยไม่แสดง Message   "ลบสำเร็จ"
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  449
URL | http://nps001.homeip.net:8085/GoodsInfo.aspx?dataId=1042&dataId2=4055
Step | 1. เลือกเมนู ตั้งค่า
  | 2. เลือกเมนูย่อย   สินค้า
  | 3. แสดงหน้าจอ   รายการสินค้า
  | 4. กดปุ่ม แก้ไข   หลังรายการ
  | 5. แสดงหน้าจอ   ข้อมูลสินค้า
  | 6. Blog   รายการรหัสซื้อขาย
  | 7. กดปุ่ม แก้ไข   หลังรายการ
  | 8. แสดงหน้าจอ   เพิ่มรหัสซื้อขาย
  | 9. เลือก Tab   บรรจุภัณฑ์
  | 10. กดปุ่ม ลบ   หลังรายการ
  | 11. แสดง Message   ยืนยันที่จะลบ
  | 12. กดปุ่ม OK
  |  
  |  
Actual   Result | เมื่อกดปุ่ม OK   ระบบลบรายการ โดยไม่แสดง Message "ลบสำเร็จ"
  |  
Expected   Result | เมื่อกดปุ่ม OK   ระบบลบรายการ โดยต้องแสดง Message "ลบสำเร็จ"
  |  

![image](https://user-images.githubusercontent.com/45878758/58606535-075a3a80-82c6-11e9-90a4-5abfc18e5dc3.png)
![image](https://user-images.githubusercontent.com/45878758/58606538-0a552b00-82c6-11e9-9386-60a82f083f2b.png)
![image](https://user-images.githubusercontent.com/45878758/58606539-0c1eee80-82c6-11e9-9f80-876f4aae7b8c.png)
![image](https://user-images.githubusercontent.com/45878758/58606540-0de8b200-82c6-11e9-95b9-da71f0a22963.png)

**Comment by Mickrepick** [comment]
แก้ไข : เมื่อกดปุ่ม OK ระบบลบรายการ ระบบจะแสดง Message "ลบข้อมูลสำเร็จ"
