### ISSUE TITLE
[ข้อมูลสินค้า][เพิ่มสินค้า]   เปลี่ยนหัวข้อ "ระดับในการตั้งค่าตำแหน่งหยิบ"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#450]
Summary   Name | [ข้อมูลสินค้า][เพิ่มสินค้า]   เปลี่ยนหัวข้อ "ระดับในการตั้งค่าตำแหน่งหยิบ"
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  450
URL | http://nps001.homeip.net:8085/SkuInfo.aspx
Step | 1. เลือกเมนู ตั้งค่า
  | 2. เลือกเมนูย่อย   สินค้า
  | 3. แสดงหน้าจอ   รายการสินค้า
  | 4. กดปุ่ม เพิ่มสินค้า
  | 5. แสดงหน้าจอ   ข้อมูลสินค้า
  | 6. เลือก Tab   การจัดเก็บ
  |  
  |  
Actual   Result | ระบบแสดงหัวข้อ   "ระดับในการตั้งค่าตำแหน่งหยิบ"
  |  
Expected   Result | ต้องเปลี่ยนจาก   "ระดับในการตั้งค่าตำแหน่งหยิบ" เป็น   "ระดับตัวเลือกในการกำหนดตำแหน่งเก็บ และหยิบ"
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/58608234-d3364800-82cc-11e9-8603-29e01fa39545.png)

**Comment by Mickrepick** [comment]
แก้ไข : เปลี่ยนจาก "ระดับในการตั้งค่าตำแหน่งหยิบ" เป็น "ระดับตัวเลือกในการกำหนดตำแหน่งเก็บ และหยิบ"
