### ISSUE TITLE
[ข้อมูลสินค้า][แก้ไข   หลังรายการ] เปลี่ยนหัวข้อ "ระดับในการตั้งค่าตำแหน่งหยิบ"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#451]
Summary   Name | [ข้อมูลสินค้า][แก้ไข   หลังรายการ] เปลี่ยนหัวข้อ "ระดับในการตั้งค่าตำแหน่งหยิบ"
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. | 451
URL | http://nps001.homeip.net:8085/SkuInfo.aspx?dataId=4055
Step | 1. เลือกเมนู ตั้งค่า
  | 2. เลือกเมนูย่อย   สินค้า
  | 3. แสดงหน้าจอ   รายการสินค้า
  | 4. กดปุ่ม เพิ่มสินค้า
  | 5. แสดงหน้าจอ   ข้อมูลสินค้า
  | 6. เลือก Tab   การจัดเก็บ
  |  
  |  
Actual   Result | ระบบแสดงหัวข้อ   "ระดับในการตั้งค่าตำแหน่งหยิบ"
  |  
Expected   Result | ต้องเปลี่ยนจาก   "ระดับในการตั้งค่าตำแหน่งหยิบ" เป็น   "ระดับตัวเลือกในการกำหนดตำแหน่งเก็บ และหยิบ"
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/58608162-86eb0800-82cc-11e9-96b8-251087a91549.png)

**Comment by Mickrepick** [comment]
Issues นี้เหมือนกับ Issues ที่ 450 ใช่ไหมครับ
