### ISSUE TITLE
[ใบสั่งซื้อ][PopUp ค้นหาสินค้า] สอบถามถ้าเลือก field สามารถซื้อได้เป็น "ปิดใช้งาน" แต่รหัสสินค้า เลือก CheckBox ซื้อได้ จะสามารถเลือกสินค้าได้มั้ยคะ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#452]
Summary Name | [ใบสั่งซื้อ][PopUp   ค้นหาสินค้า] สอบถามถ้าเลือก field สามารถซื้อได้เป็น "ปิดใช้งาน"   แต่รหัสสินค้า เลือก CheckBox ซื้อได้ จะสามารถเลือกสินค้าได้มั้ยคะ
-- | --
Defect   No. | 452
URL | http://nps001.homeip.net:8085/SkuInfo.aspx?dataId=4055
  | http://nps001.homeip.net:8085/GoodsInfo.aspx?dataId=1041&dataId2=4055
  | http://nps001.homeip.net:8085/PopupGoodsSelectNoPrice.aspx
  |  
  |  
  |  
  |  
Step | 1.   เลือกเมนู ตั้งค่า
  | 2.   เลือกเมนูย่อย สินค้า
  | 3.   แสดงหน้าจอ รายการสินค้า
  | 4. กดปุ่ม   แก้ไข หลังรายการ
  | 5.   แสดงหน้าจอ ข้อมูลสินค้า
  | 6. เลือก   Tab การตั้งค่า
  | 7. เลือก   field สามารถซื้อได้ เป็น "ปิดใช้งาน"
  | 8.   บันทึกสำเร็จ
  | 9. Blog   รายการรหัสซื้อขาย
  | 10. กดปุ่ม   แก้ไข หลังรายการ
  | 11.   แสดงหน้าจอ เพิ่มรหัสซื้อขาย
  | 12. เลือก   Tab การตั้งค่า
  | 13. เลือก   CheckBox ซื้อได้
  | 14.   บันทึกสำเร็จ
  | 15.   เลือกเมนู งานประจำวัน
  | 16.   เลือกเมนูย่อย ใบสั่งซือสินค้า
  | 17. เลือก   สั่งซื้อทั่วไป
  | 18.   แสดงหน้าจอ รายการใบสั่งซื้อสินค้า
  | 19. กดปุ่ม   เพิ่มสินค้า
  | 20.   แสดงหน้าจอ ใบสั่งซื้อ
  | 21. กดปุ่ม   ค้นหาสินค้า
  | 22. เลือก   สินค้า
  |  
Question | ถ้าเลือกในหน้าจอข้อมูลสินค้า field สามารถซื้อได้ เป็น   "ปิดใช้งาน"
  | แต่ในหน้าจอเพิ่มรหัสซื้อขาย   เลือก CheckBox ซื้อได้
  | 1.  สามารถเลือกสินค้าชิ้นนั้นในเมนู   ใบสั่งซื้อได้มั้ย?
  | 2. ถ้าเลือกไม่ได้ ต้องแสดง Error   Message ว่าอะรไรคะ
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/58609076-82c0e980-82d0-11e9-9405-62834c52964f.png)
![image](https://user-images.githubusercontent.com/45878758/58609080-85bbda00-82d0-11e9-8716-cfe0437791af.png)
![image](https://user-images.githubusercontent.com/45878758/58609083-881e3400-82d0-11e9-977a-e2ca09c1f4f0.png)
![image](https://user-images.githubusercontent.com/45878758/58609099-9704e680-82d0-11e9-9a0f-c636ed858187.png)

**Comment by logisprosolution** [comment]
สินค้า ถ้าปิดการใช้งาน   รหัสซื้อขายทั้งหมด ต้องใช้ไม่ได้ครับ เพราะสินค้า คือคุมทั้งหมด
ถ้าเปิด ก็อิงตามรหัสซื้อขายรายตัว
