### ISSUE TITLE
[คลัง][Location   Piking]ระบบไม่แสดง "เครื่องหมายถูก" และ   "เครื่องหมายกากบาท" ใน Column สถานะ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#453]
Summary   Name | [คลัง][Location   Piking]ระบบไม่แสดง "เครื่องหมายถูก" และ   "เครื่องหมายกากบาท" ใน Column สถานะ
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  453
URL | http://nps001.homeip.net:8085/ZoneInfo.aspx?dataId=3008&dataId2=2012
Step | 1. เลือกเมนู ตั้งค่า
  | 2. เลือกเมนูย่อย คลัง
  | 3. แสดงหน้าจอ   รายการคลัง
  | 4. กดปุ่ม แก้ไข   หลังรายการ
  | 5. แสดงหน้าจอ   เพิ่มคลัง
  | 6. Blog รายการโซน
  | 7. กดปุ่ม แก้ไข   หลังรายการ
  | 8. แสดงหน้าจอ   เพิ่มโซน
  | 9. Blog Location   Picking
  |  
  |  
Actual   Result | ระบบไม่แสดง   "เครื่องหมายถูก" และ "เครื่องหมายกากบาท" ใน Column สถานะ
  |  
Expected   Result | ระบบต้องแสดง   "เครื่องหมายถูก" และ "เครื่องหมายกากบาท" ใน Column สถานะ   ตาม field สถานะที่กำหนดไว้
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/58615417-3cc25080-82e5-11e9-966b-52ad3f7f15a4.png)
![image](https://user-images.githubusercontent.com/45878758/58615423-40ee6e00-82e5-11e9-884b-c6611007fb24.png)
![image](https://user-images.githubusercontent.com/45878758/58615427-421f9b00-82e5-11e9-9054-f76a7ca39935.png)

**Comment by Patthamaporn** [comment]
แก้ไข แสดง "เครื่องหมายถูก" และ "เครื่องหมายกากบาท" ใน Column สถานะที่รายการตำแหน่งจัดเก็บในหน้าข้อมูลโซน
