### ISSUE TITLE
[ตรวจสินค้าเข้า][ตรวจสอบ   หลังรายการ] ไม่มีปุ่มบันทึก และ field เลขที่เอกสาร กรอกข้อมูลไม่ได้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#454]
Summary   Name | [ตรวจสินค้าเข้า][ตรวจสอบ   หลังรายการ] ไม่มีปุ่มบันทึก และ field เลขที่เอกสาร กรอกข้อมูลไม่ได้
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  454
URL | http://nps001.homeip.net:8085/CheckerInInfo.aspx?dataId=12262&subDoc=21
Step | 1. เลือกเมนู   งานประจำวัน
  | 2. เลือกเมนูย่อย   ตรวจสอบสินค้าเข้า
  | 3. เลือก   ตรวจสอบสินค้าเข้า
  | 4. แสดงหน้าจอ   รายการตรวจสินค้าเข้า
  | 5. กดปุ่ม ตรวจสอบ   หลังรายการ
  | 6. แสดงหน้าจอ   ตรวจสินค้าเข้า
  |  
  |  
Actual   Result | 1. หน้าจอ   ตรวจสินค้าเข้า ไม่มีปุ่ม บันทึก
  | 2. Field เลขที่เอกสาร   แก้ไขไม่ได้
  |  
Expected   Result | 1. หน้าจอ   ตรวจสินค้าเข้า ต้องมีปุ่ม บันทึก เพื่อทำการบันทึกรายการได้
  | 2. Field เลขที่เอกสาร   ต้องสามารถกรอกข้อมูลได้
  |  

![image](https://user-images.githubusercontent.com/45878758/58744349-ad937500-846b-11e9-8e69-bda91e9bff89.png)
![image](https://user-images.githubusercontent.com/45878758/58744351-b08e6580-846b-11e9-8615-93ebf03c1ed1.png)

**Comment by Patthamaporn** [comment]
แก้ไข: สามารถ แก้ไขField เลขที่เอกสาร ในหน้าแก้ไขได้แต่ไม่สามารถแก้ไขในหน้าอนุมัติได้
