### ISSUE TITLE
[ข้อมูลสินค้า][แก้ไข   หลังรายการ][Tab ผู้จัดจำหน่าย] ระบบลบรายการผู้จัดจำหน่าย โดยไม่มี Message   "ลบข้อมูลสำเร็จ"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#456]
Summary   Name | [ข้อมูลสินค้า][แก้ไข   หลังรายการ][Tab ผู้จัดจำหน่าย] ระบบลบรายการผู้จัดจำหน่าย โดยไม่มี Message   "ลบข้อมูลสำเร็จ"
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  456
URL | http://nps001.homeip.net:8085/SkuInfo.aspx?dataId=4055
  |  
Step | 1.เลือกเมนู ตั้งค่า
  | 2. เลือกเมนูย่อย   สินค้า
  | 3. แสดงหน้าจอ   รายการสินค้า
  | 4. กดปุ่ม แก้ไข   หลังรายการ
  | 5. แสดงหน้า   ข้อมูลสินค้า
  | 6. เลือก Tab   ผู้จัดจำหน่าย
  | 7. กดปุ่ม ลบ   หลีงรายการผู้จัดจำหน่าย
  | 8. กดปุ่ม OK
  |  
  |  
Actual   Result | ระบบลบรายการผู้จัดจำหน่าย   โดยไม่มี Message "ลบข้อมูลสำเร็จ"
  |  
Expected   Result | ระบบลบรายการผู้จัดจำหน่าย   โดยมี Message "ลบข้อมูลสำเร็จ"
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/58744882-dd924680-8472-11e9-8a73-dd357195e106.png)
![image](https://user-images.githubusercontent.com/45878758/58744883-e1be6400-8472-11e9-93cf-972fe3f84183.png)
![image](https://user-images.githubusercontent.com/45878758/58744891-fbf84200-8472-11e9-9305-415e5dbb6440.png)

**Comment by Mickrepick** [comment]
แก้ไข : ระบบลบรายการผู้จัดจำหน่าย จะมี Message "ลบข้อมูลสำเร็จ" ขึ้นมา
