### ISSUE TITLE
[ข้อมูลสินค้า][แก้ไข   หลังรายการ][Tab [บรรจุภัณฑ์] ระบบลบรายการผู้จัดจำหน่าย โดยไม่มี Message   "ลบข้อมูลสำเร็จ"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#458]
Summary   Name | [ข้อมูลสินค้า][แก้ไข   หลังรายการ][Tab [บรรจุภัณฑ์] ระบบลบรายการผู้จัดจำหน่าย โดยไม่มี Message   "ลบข้อมูลสำเร็จ"
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. | 458
URL | http://nps001.homeip.net:8085/SkuInfo.aspx?dataId=4055
  |  
Step | 1.เลือกเมนู ตั้งค่า
  | 2. เลือกเมนูย่อย   สินค้า
  | 3. แสดงหน้าจอ   รายการสินค้า
  | 4. กดปุ่ม แก้ไข   หลังรายการ
  | 5. แสดงหน้า   ข้อมูลสินค้า
  | 6. เลือก Tab   บรรจุภัณฑ์
  | 7. กดปุ่ม ลบ   หลีงรายการบรรจุภัณฑ์
  | 8. กดปุ่ม OK
  |  
  |  
Actual   Result | ระบบลบรายการบรรจุภัณฑ์   โดยไม่มี Message "ลบข้อมูลสำเร็จ"
  |  
Expected   Result | ระบบลบรายการบรรจุภัณฑ์   โดยมี Message "ลบข้อมูลสำเร็จ"
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/58745150-4da2cb80-8477-11e9-88f6-ab0b9e41140a.png)
![image](https://user-images.githubusercontent.com/45878758/58745151-4f6c8f00-8477-11e9-8d90-d371ffc3d282.png)
![image](https://user-images.githubusercontent.com/45878758/58745154-57c4ca00-8477-11e9-8273-cdb233470912.png)

**Comment by Mickrepick** [comment]
แก้ไข : ระบบลบรายการบรรจุภัณฑ์ โดยมี Message "ลบข้อมูลสำเร็จ"
