### ISSUE TITLE
[รายการคลัง]ระบบแสดง   Message "บันทึกสำเร็จ" เมื่อกดปุ่ม ลบ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#460]
Summary   Name | [รายการคลัง]ระบบแสดง   Message "บันทึกสำเร็จ" เมื่อกดปุ่ม ลบ
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  460
URL | http://nps001.homeip.net:8085/WareHouseList.aspx?menuID=76
  |  
Step | 1. เลือกเมนู ตั้งค่า
  | 2. เลือกเมนูย่อย คลัง
  | 3. แสดงหน้าจอ   รายการคลัง
  | 4. กดปุ่ม ลบ   หลังรายการ
  | 5. กดปุ่ม OK
  |  
  |  
  |  
Actual   Result | ระบบแสดง Message   "บันทึกสำเร็จ"
  |  
Expected   Result | ระบบแสดง Message   "ลบข้อมูลสำเร็จ"
  |  

![image](https://user-images.githubusercontent.com/45878758/58749475-14874d00-84b1-11e9-9854-213176da72a8.png)
![image](https://user-images.githubusercontent.com/45878758/58749476-16e9a700-84b1-11e9-84e7-e38468b5aa24.png)
![image](https://user-images.githubusercontent.com/45878758/58749477-194c0100-84b1-11e9-873f-13ab9a78ac7b.png)

**Comment by Mickrepick** [comment]
แก้ไข : เมื่อกดปุ่มลบหลังรายการ ระบบแสดง Message "ลบข้อมูลสำเร็จ"
