### ISSUE TITLE
[เพิ่มรหัสซื้อขาย][แก้ไข   หลังรายการ]Field "การกำหนดตำแหน่งเก็บ" แสดงข้อมูลไม่ถูกต้อง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#461]
Summary   Name | [เพิ่มรหัสซื้อขาย][แก้ไข   หลังรายการ]Field "การกำหนดตำแหน่งเก็บ" แสดงข้อมูลไม่ถูกต้อง
-- | --
Defect No. |  461
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL | http://nps001.homeip.net:8085/GoodsInfo.aspx?dataId=1060&dataId2=4069&view=1
  |  
Step | 1. Login   WMS on Chorme
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย สินค้า
  | 4.   แสดงหน้าจอ รายการสินค้า
  | 5. กดปุ่ม   แก้ไข หลังรายการ
  | 6.   แสดงหน้าจอ ข้อมูลสินค้า
  | 7. Blog   รายการรหัสซื้อขาย
  | 8. กดปุ่ม   เพิ่มรหัสซื้อขาย
  | 9.   แสดงหน้าจอ เพิ่มรหัสซื้อขาย
  | 10. เลือก   CheckBox "SKU"
  | 11.   ระบุข้อมูลใน field
  | - ประเภท   Packsize
  | 12. เลือก   การกำหนดตำแหน่งเก็บ "ระบุที่อยู่"
  | 13.   ระบุข้อมูลการกำหนดตำแหน่งเก็บใน field
  | - คลัง
  | - โซน
  | -   ตำแหน่งเก็บ
  | 14. กดปุ่ม   บันทึก
  | 15.   บันทึกสำเร็จ
  | 12.   แสดงหน้าจอ ข้อมูลสินค้า
  | 13. กดปุ่ม   แก้ไข หลังรายการรหัสซื้อขาย
  | 14.   แสดงหน้าจอ เพิ่มรหัสซื้อขาย
  | 15.   ตรวจสอบ field
  | - คลัง
  | - โซน
  | -   ตำแหน่งเก็บ
  |  
Actual   Result | Field   "การกำหนดตำแหน่งเก็บ" แสดงข้อมูลไม่ถูกต้อง
  |  
Expected   Result | Field   "การกำหนดตำแหน่งเก็บ" แสดงข้อมูลถูกต้อง
  |  
TesterName | Phatchanok

![image](https://user-images.githubusercontent.com/45878758/58750207-8d8aa280-84b9-11e9-9021-9b98fc142e15.png)
![image](https://user-images.githubusercontent.com/45878758/58750298-b52e3a80-84ba-11e9-94f6-b758020202fd.png)
![image](https://user-images.githubusercontent.com/45878758/58750309-e149bb80-84ba-11e9-9495-a0b8eae1e7ca.png)

**Comment by Mickrepick** [comment]
แก้ไข : Field "การกำหนดตำแหน่งเก็บ" แสดงข้อมูลถูกต้อง
