### ISSUE TITLE
[คลัง][Location   Picking][แก้ไข หลังรายการ]ระบบแสดง Message "บันทึกสำเร็จ"   เมื่อทำการ ลบ รายการ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#462]
Summary   Name | [คลัง][Location   Picking][แก้ไข หลังรายการ]ระบบแสดง Message "บันทึกสำเร็จ"   เมื่อทำการ ลบ รายการ
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  462
URL | http://nps001.homeip.net:8085/ZoneInfo.aspx?dataId=3008&dataId2=2012
  |  
Step | 1. เลือกเมนู ตั้งค่า
  | 2. เลือกเมนูย่อย คลัง
  | 3. แสดงหน้าจอ   รายการคลัง
  | 4. กดปุ่ม แก้ไข   หลังรายการ
  | 5. แสดงหน้าจอ   เพิ่มคลัง
  | 6. Blog รายการโซน
  | 7. กดปุ่ม แก้ไข   หลังรายการ
  | 8. แสดงหน้าจอ   เพิ่มโซน
  | 9. Blog Location   Picking
  | 10. กดปุ่ม ลบ   หลังรายการ
  | 11. กดปุ่ม OK
  |  
  |  
  |  
Actual   Result | ระบบแสดง Message   "บันทึกสำเร็จ"
  |  
Expected   Result | ระบบต้องแสดง Message   "ลบข้อมูลสำเร็จ"
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/58752132-c59edf00-84d3-11e9-923e-0c129a4d0479.png)
![image](https://user-images.githubusercontent.com/45878758/58752133-c8013900-84d3-11e9-89b9-535b1f8b40d9.png)
![image](https://user-images.githubusercontent.com/45878758/58752134-c9cafc80-84d3-11e9-84c7-4a96b1d4acbb.png)

**Comment by Mickrepick** [comment]
แก้ไข : เมื่อกดปุ่มลบหลังรายการ ระบบต้องแสดง Message "ลบข้อมูลสำเร็จ"
