### ISSUE TITLE
[รายการตำแหน่ง]เมื่อกดปุ่ม   ดู หลังรายการ ระบบต้องแสดงหน้าจอ เพิ่มตำแหน่ง

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#464]
Summary   Name | [รายการตำแหน่ง]เมื่อกดปุ่ม   ดู หลังรายการ ระบบต้องแสดงหน้าจอ เพิ่มตำแหน่ง
-- | --
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
Defect No. |  464
URL | http://nps001.homeip.net:8085/RoleList.aspx?menuID=60
  | http://nps001.homeip.net:8085/RoleMenu.aspx?dataId=12&view=1
Step | 1. เลือกเมนู ตั้งค่า
  | 2. เลือกเมนูย่อย   สิทธิ์การใช้งาน
  | 3. แสดงหน้าจอ   รายการตำแหน่ง
  | 4. กดปุ่ม ดู   หลังรายการ
  |  
  |  
  |  
Actual   Result | เมื่อกดปุ่ม ดู   หลังรายการ ระบบแสดงหน้าจอ สิทธิ์การใช้งาน
  |  
Expected   Result | เมื่อกดปุ่ม ดู   หลังรายการ ระบบต้องแสดงหน้าจอ เพิ่มตำแหน่ง
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/58753470-d65a4f80-84e9-11e9-897f-66c8e0f9a2fa.png)
![image](https://user-images.githubusercontent.com/45878758/58753471-d8241300-84e9-11e9-886f-6ec5a3682230.png)

**Comment by Patthamaporn** [comment]
แก้ไข หลังจากกดดูในหน้ารายการตำแหน่งแล้ว จะเป็นหน้าจอข้อมูลตำแหน่ง ไม่ใช่หน้าจอสิทธิ์
