### ISSUE TITLE
[สิทธิ์การใช้งาน][รายการผู้ใช้งาน]เมื่อเลือก   สิทธิ์การใช้งานเป็น "ดู" เท่านั้น ที่หน้าจอ รายการผู้ใช้งาน   ต้องไม่แสดงปุ่ม เพิ่มเพิ่มผู้ใช้งาน , แก้ไข และลบ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#465]
Summary   Name | [สิทธิ์การใช้งาน][รายการผู้ใช้งาน]เมื่อเลือก   สิทธิ์การใช้งานเป็น "ดู" เท่านั้น ที่หน้าจอ รายการผู้ใช้งาน   ต้องไม่แสดงปุ่ม เพิ่มเพิ่มผู้ใช้งาน , แก้ไข และลบ
-- | --
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
Defect No. |  465
URL | http://nps001.homeip.net:8085/RoleMenu.aspx?dataId=8
  | http://nps001.homeip.net:8085/UserList.aspx?menuID=43
Step | 1.   Login
  | 2.   เลือกเมนู ระบบ
  | 3.   เลือกเมนูย่อย สิทธิ์การใช้งาน
  | 4.   แสดงหน้าจอ รายการตำแหน่ง
  | 5.   กดปุ่ม กำหนดสิทธิ์ หลังรายการตำแหน่ง "sit"
  | 6.   แสดงหน้าจอ รายการกำหนดสิทธิ์
  | 7.  รายการ รายการผู้ใช้งาน
  | -   เลือก CheckBox  "ดู"
  | 8.   กดปุ่ม บันทึก
  | 9.   บันทึกสำเร็จ
  | 10.   เลือกเมนู ระบบ
  | 11.   เลือกเมนูย่อย ผู้ใช้งาน
  | 12.   แสดงหน้าจอ รายการผู้ใช้งาน
  |  
  |  
  |  
Actual   Result | เมื่อเลือก   สิทธิ์การใช้งานเป็น "ดู" เท่านั้น หน้าจอ รายการผู้ใช้งาน แสดงปุ่ม   ดู , เพิ่มเพิ่มผู้ใช้งาน , แก้ไข และลบ
  |  
Expected   Result | เมื่อเลือก   สิทธิ์การใช้งานเป็น "ดู" เท่านั้น ที่หน้าจอ รายการผู้ใช้งาน   ต้องไม่แสดงปุ่ม เพิ่มเพิ่มผู้ใช้งาน , แก้ไข และลบ
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/58753746-410d8a00-84ee-11e9-89f8-e83d42e33e9a.png)
![image](https://user-images.githubusercontent.com/45878758/58753748-42d74d80-84ee-11e9-94da-a48917bb4339.png)
![image](https://user-images.githubusercontent.com/45878758/58753750-45d23e00-84ee-11e9-8973-9db727f5931b.png)
![image](https://user-images.githubusercontent.com/45878758/58753771-829e3500-84ee-11e9-8a43-fd897fcf165c.png)

**Comment by Patthamaporn** [comment]
แก้ไข ผู้ใช้งานไม่สามารถเพิ่ม แก้ไข ลบ รายการผู้ใช้งานได้ หากไม่ได้มีการตั้งสิทธิ์
