### ISSUE TITLE
[สิทธิ์การใช้งาน][รายการผู้ใช้งาน]เมื่อเลือก   สิทธิ์การใช้งานเป็น "ลบ" เท่านั้น หน้าจอรายการผู้ใช้งาน   ต้องไม่แสดงปุ่ม ดู , แก้ไข และเพิ่มผู้ใช้งาน

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#467]
Summary   Name | [สิทธิ์การใช้งาน][รายการผู้ใช้งาน]เมื่อเลือก   สิทธิ์การใช้งานเป็น "ลบ" เท่านั้น หน้าจอรายการผู้ใช้งาน   ต้องไม่แสดงปุ่ม ดู , แก้ไข และเพิ่มผู้ใช้งาน
-- | --
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
Defect No. | 467
URL | http://nps001.homeip.net:8085/RoleMenu.aspx?dataId=8
  | http://nps001.homeip.net:8085/UserList.aspx?menuID=43
Step | 1.   Login
  | 2.   เลือกเมนู ระบบ
  | 3.   เลือกเมนูย่อย สิทธิ์การใช้งาน
  | 4.   แสดงหน้าจอ รายการตำแหน่ง
  | 5.   กดปุ่ม กำหนดสิทธิ์ หลังรายการตำแหน่ง "sit"
  | 6.   แสดงหน้าจอ รายการกำหนดสิทธิ์
  | 7.  รายการ รายการผู้ใช้งาน
  | -   เลือก CheckBox  "ลบ"
  | 8.   กดปุ่ม บันทึก
  | 9.   บันทึกสำเร็จ
  | 10.   เลือกเมนู ระบบ
  | 11.   เลือกเมนูย่อย ผู้ใช้งาน
  | 12.   แสดงหน้าจอ รายการผู้ใช้งาน
  |  
Actual   Result | เมื่อเลือก   สิทธิ์การใช้งานเป็น "ลบ" เท่านั้น หน้าจอรายการผู้ใช้งาน แสดงปุ่ม ดู   , เพิ่มผู้ใช้งาน , แก้ไข และลบ
  |  
Expected   Result | เมื่อเลือก   สิทธิ์การใช้งานเป็น "ลบ" เท่านั้น หน้าจอรายการผู้ใช้งาน   ต้องไม่แสดงปุ่ม ดู , แก้ไข และเพิ่มผู้ใช้งาน
  |  

![image](https://user-images.githubusercontent.com/45878758/58753988-4ff63b80-84f2-11e9-87d3-3825556f78b3.png)
![image](https://user-images.githubusercontent.com/45878758/58753989-51bfff00-84f2-11e9-84de-a0360b71f98b.png)
![image](https://user-images.githubusercontent.com/45878758/58753992-5edcee00-84f2-11e9-99cd-fe8b4bb11cd2.png)

**Comment by Patthamaporn** [comment]
แก้ไข ผู้ใช้งานไม่สามารถเพิ่ม แก้ไข ลบ รายการผู้ใช้งานได้ หากไม่ได้มีการตั้งสิทธิ์
