### ISSUE TITLE
[สิทธิ์การใช้งาน][รายการผู้ใช้งาน}เมื่อเลือก   สิทธิ์การใช้งานเป็น "แก้ไข" เท่านั้น หน้าจอรายการผู้ใช้งาน   ต้องไม่แสดงปุ่ม ดู , เพิ่มผู้ใช้งาน และลบ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#469]
Summary   Name | [สิทธิ์การใช้งาน][รายการผู้ใช้งาน}เมื่อเลือก   สิทธิ์การใช้งานเป็น "แก้ไข" เท่านั้น หน้าจอรายการผู้ใช้งาน   ต้องไม่แสดงปุ่ม ดู , เพิ่มผู้ใช้งาน และลบ
-- | --
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
Defect No. | 469
URL | http://nps001.homeip.net:8085/RoleMenu.aspx?dataId=8
  | http://nps001.homeip.net:8085/UserList.aspx?menuID=43
Step | 1.   Login
  | 2.   เลือกเมนู ระบบ
  | 3.   เลือกเมนูย่อย สิทธิ์การใช้งาน
  | 4.   แสดงหน้าจอ รายการตำแหน่ง
  | 5.   กดปุ่ม กำหนดสิทธิ์ หลังรายการตำแหน่ง "sit"
  | 6.   แสดงหน้าจอ รายการกำหนดสิทธิ์
  | 7.  รายการ รายการผู้ใช้งาน
  | -   เลือก CheckBox  "แก้ไข"
  | 8.   กดปุ่ม บันทึก
  | 9.   บันทึกสำเร็จ
  | 10.   เลือกเมนู ระบบ
  | 11.   เลือกเมนูย่อย ผู้ใช้งาน
  | 12.   แสดงหน้าจอ รายการผู้ใช้งาน
  |  
Actual   Result | เมื่อเลือก   สิทธิ์การใช้งานเป็น "แก้ไข" เท่านั้น หน้าจอรายการผู้ใช้งาน แสดงปุ่ม   ดู , เพิ่มผู้ใช้งาน , แก้ไข และลบ
  |  
Expected   Result | เมื่อเลือก   สิทธิ์การใช้งานเป็น "แก้ไข" เท่านั้น หน้าจอรายการผู้ใช้งาน   ต้องไม่แสดงปุ่ม ดู , เพิ่มผู้ใช้งาน และลบ
  |  

![image](https://user-images.githubusercontent.com/45878758/58754090-c2b3e680-84f3-11e9-88d0-22aaf569064c.png)
![image](https://user-images.githubusercontent.com/45878758/58754092-c47daa00-84f3-11e9-852c-faa4b55b0073.png)
![image](https://user-images.githubusercontent.com/45878758/58754094-c6e00400-84f3-11e9-906f-00019fc58a2b.png)

**Comment by Patthamaporn** [comment]
แก้ไข ผู้ใช้งานไม่สามารถเพิ่ม แก้ไข ลบ รายการผู้ใช้งานได้ หากไม่ได้มีการตั้งสิทธิ์
