### ISSUE TITLE
สิทธิ์การใช้งาน_Location_เมื่อเลือก   สิทธิ์การใช้งานเป็น "ดู" เท่านั้น หน้าจอ Location ต้องไม่แสดงปุ่ม   เพิ่ม location

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#496]
Summary   Name | สิทธิ์การใช้งาน_Location_เมื่อเลือก   สิทธิ์การใช้งานเป็น "แก้ไข" เท่านั้น หน้าจอ Location   ต้องไม่แสดงปุ่ม เพิ่ม location
-- | --
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
Defect No. | 496
URL | http://nps001.homeip.net:8085/RoleMenu.aspx?dataId=8
  | http://nps001.homeip.net:8085/LocationList.aspx?menuID=71
Step | 1. Login
  | 2.   เลือกเมนู ระบบ
  | 3.   เลือกเมนูย่อย สิทธิ์การใช้งาน
  | 4.   แสดงหน้าจอ รายการตำแหน่ง
  | 5.   กดปุ่ม กำหนดสิทธิ์ หลังรายการตำแหน่ง "sit"
  | 6.   แสดงหน้าจอ รายการกำหนดสิทธิ์
  | 7.  รายการ รายการตำแหน่งจัดเก็บ
  | -   เลือก CheckBox  "แก้ไข"
  | 8.   กดปุ่ม บันทึก
  | 9.   บันทึกสำเร็จ
  | 10.   เลือกเมนู ตั้งค่า
  | 11.   เลือกเมนูย่อย รายการตำแหน่งจัดเก็บ
  | 12.   แสดงหน้าจอ Location
  |  
Actual   Result | เมื่อเลือก   สิทธิ์การใช้งานเป็น "แก้ไข" เท่านั้น หน้าจอ Location แสดงปุ่ม แก้ไข   และเพิ่ม location
  |  
Expected   Result | เมื่อเลือก   สิทธิ์การใช้งานเป็น "แก้ไข" เท่านั้น หน้าจอ Location   ต้องไม่แสดงปุ่ม เพิ่ม location
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/58767233-aa56d100-85b2-11e9-83bd-b2ca4388fffa.png)
![image](https://user-images.githubusercontent.com/45878758/58767235-acb92b00-85b2-11e9-9b91-88c64f3870e4.png)
![image](https://user-images.githubusercontent.com/45878758/58767236-afb41b80-85b2-11e9-83f4-2c44b3f13f37.png)

**Comment by Patthamaporn** [comment]
แก้ไข ผู้ใช้งานไม่สามารถเพิ่มรายการตำแหน่งเก็บได้ หากไม่ได้มีการตั้งสิทธิ์
