### ISSUE TITLE
สิทธิ์การใช้งาน_Location_เมื่อเลือก   สิทธิ์การใช้งานเป็น "ลบ" เท่านั้น หน้าจอ Location ต้องไม่แสดงปุ่ม   เพิ่ม location

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#497]
Summary   Name | สิทธิ์การใช้งาน_Location_เมื่อเลือก   สิทธิ์การใช้งานเป็น "ลบ" เท่านั้น หน้าจอ Location ต้องไม่แสดงปุ่ม   เพิ่ม location
-- | --
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
Defect No. | 497
URL | http://nps001.homeip.net:8085/RoleMenu.aspx?dataId=8
  | http://nps001.homeip.net:8085/LocationList.aspx?menuID=71
Step | 1. Login
  | 2.   เลือกเมนู ระบบ
  | 3.   เลือกเมนูย่อย สิทธิ์การใช้งาน
  | 4.   แสดงหน้าจอ รายการตำแหน่ง
  | 5.   กดปุ่ม กำหนดสิทธิ์ หลังรายการตำแหน่ง "sit"
  | 6.   แสดงหน้าจอ รายการกำหนดสิทธิ์
  | 7.  รายการ รายการตำแหน่งจัดเก็บ
  | -   เลือก CheckBox  "ลบ"
  | 8.   กดปุ่ม บันทึก
  | 9.   บันทึกสำเร็จ
  | 10.   เลือกเมนู ตั้งค่า
  | 11.   เลือกเมนูย่อย รายการตำแหน่งจัดเก็บ
  | 12.   แสดงหน้าจอ Location
  |  
Actual   Result | เมื่อเลือก   สิทธิ์การใช้งานเป็น "ลบ" เท่านั้น หน้าจอ Location แสดงปุ่ม ลบ   และเพิ่ม location
  |  
Expected   Result | เมื่อเลือก   สิทธิ์การใช้งานเป็น "ลบ" เท่านั้น หน้าจอ Location ต้องไม่แสดงปุ่ม   เพิ่ม location
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/58767357-2d2c5b80-85b4-11e9-8d7c-4e73c8e1a020.png)
![image](https://user-images.githubusercontent.com/45878758/58767359-30274c00-85b4-11e9-8a38-053a1319f32e.png)
![image](https://user-images.githubusercontent.com/45878758/58767361-31f10f80-85b4-11e9-826b-05ce0698742a.png)

**Comment by Patthamaporn** [comment]
แก้ไข ผู้ใช้งานไม่สามารถเพิ่มรายการตำแหน่งเก็บได้ หากไม่ได้มีการตั้งสิทธิ์
