### ISSUE TITLE
สิทธิ์การใช้งาน_รายการป้ายราคา_เมื่อเลือก   สิทธิ์การใช้งานเป็น "ดู" เท่านั้น หน้าจอ รายการป้ายราคา   ต้องไม่แสดงปุ่มลบ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#498]
Summary   Name | สิทธิ์การใช้งาน_รายการป้ายราคา_เมื่อเลือก   สิทธิ์การใช้งานเป็น "ดู" เท่านั้น หน้าจอ รายการป้ายราคา   ต้องไม่แสดงปุ่มลบ
-- | --
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
Defect No. |  498
URL | http://nps001.homeip.net:8085/RoleMenu.aspx?dataId=8
  | http://nps001.homeip.net:8085/PriceTagList.aspx?menuID=75
Step | 1. Login
  | 2.   เลือกเมนู ระบบ
  | 3.   เลือกเมนูย่อย สิทธิ์การใช้งาน
  | 4.   แสดงหน้าจอ รายการตำแหน่ง
  | 5.   กดปุ่ม กำหนดสิทธิ์ หลังรายการตำแหน่ง "sit"
  | 6.   แสดงหน้าจอ รายการกำหนดสิทธิ์
  | 7.  รายการ รายการป้ายราคา
  | -   เลือก CheckBox  "ดู"
  | 8.   กดปุ่ม บันทึก
  | 9.   บันทึกสำเร็จ
  | 10.   เลือกเมนู ตั้งค่า
  | 11.   เลือกเมนูย่อย ป้ายราคา
  | 12.   แสดงหน้าจอ รายการป้ายราคา
  |  
Actual   Result | เมื่อเลือก   สิทธิ์การใช้งานเป็น "ดู" เท่านั้น หน้าจอ รายการป้ายราคา แสดงปุ่ม ดู   และลบ
  |  
Expected   Result | เมื่อเลือก   สิทธิ์การใช้งานเป็น "ดู" เท่านั้น หน้าจอ รายการป้ายราคา   ต้องไม่แสดงปุ่มลบ
  |  

![image](https://user-images.githubusercontent.com/45878758/58767574-76ca7580-85b7-11e9-85cd-2b97e1909f6f.png)
![image](https://user-images.githubusercontent.com/45878758/58767577-78943900-85b7-11e9-9eb2-e7d8cce47a83.png)
![image](https://user-images.githubusercontent.com/45878758/58767578-7af69300-85b7-11e9-86c1-093684e3b5b9.png)

**Comment by Patthamaporn** [comment]
แก้ไข ผู้ใช้งานไม่สามารถลบรายการป้ายราคาได้ หากไม่ได้มีการตั้งสิทธิ์
