### ISSUE TITLE
สิทธิ์การใช้งาน_รายการป้ายราคา_เมื่อเลือก   สิทธิ์การใช้งานเป็น "ดู" เท่านั้น หน้าจอ รายการป้ายราคา   ต้องไม่แสดงปุ่มลบ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#499]
Summary   Name | สิทธิ์การใช้งาน_รายการป้ายราคา_เมื่อเลือก   สิทธิ์การใช้งานเป็น "เพิ่ม" เท่านั้น หน้าจอ รายการป้ายราคา   ต้องไม่แสดงปุ่มลบ
-- | --
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
Defect No. |  499
URL | http://nps001.homeip.net:8085/RoleMenu.aspx?dataId=8
  | http://nps001.homeip.net:8085/PriceTagList.aspx?menuID=75
Step | 1. Login
  | 2.   เลือกเมนู ระบบ
  | 3.   เลือกเมนูย่อย สิทธิ์การใช้งาน
  | 4.   แสดงหน้าจอ รายการตำแหน่ง
  | 5.   กดปุ่ม กำหนดสิทธิ์ หลังรายการตำแหน่ง "sit"
  | 6.   แสดงหน้าจอ รายการกำหนดสิทธิ์
  | 7.  รายการ รายการป้ายราคา
  | -   เลือก CheckBox  "เพิ่ม"
  | 8.   กดปุ่ม บันทึก
  | 9.   บันทึกสำเร็จ
  | 10.   เลือกเมนู ตั้งค่า
  | 11.   เลือกเมนูย่อย ป้ายราคา
  | 12.   แสดงหน้าจอ รายการป้ายราคา
  |  
Actual   Result | เมื่อเลือก   สิทธิ์การใช้งานเป็น "เพิ่ม" เท่านั้น หน้าจอ รายการป้ายราคา แสดงปุ่ม   เพิ่มป้ายราคา และลบ
  |  
Expected   Result | เมื่อเลือก   สิทธิ์การใช้งานเป็น "เพิ่ม" เท่านั้น หน้าจอ รายการป้ายราคา   ต้องไม่แสดงปุ่มลบ
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/58767689-6adfb300-85b9-11e9-95b2-b3d06b13cb6b.png)
![image](https://user-images.githubusercontent.com/45878758/58767690-6ca97680-85b9-11e9-9d42-2af7ab0f465d.png)
![image](https://user-images.githubusercontent.com/45878758/58767693-6e733a00-85b9-11e9-9c05-bf61ccad233c.png)

**Comment by Patthamaporn** [comment]
แก้ไข ผู้ใช้งานไม่สามารถลบรายการป้ายราคาได้ หากไม่ได้มีการตั้งสิทธิ์

**Comment by Patthamaporn** [comment]
หมายถึงเพิ่มไม่ใช่ดูใช่ไหมคะ
