### ISSUE TITLE
หน้าประวัติส่วนตัว ไม่พบข้อมูล

### ISSUE THREAD

**Issue by logisprosolution** [logisprosolution/WMS#50]
![image](https://user-images.githubusercontent.com/30793831/45009863-b0744d00-b034-11e8-9bc5-cac406a11d74.png)
![image](https://user-images.githubusercontent.com/30793831/45009866-b2d6a700-b034-11e8-94be-20ccbd32a593.png)

**Comment by Patthamaporn** [comment]
wait for test
