### ISSUE TITLE
ผู้ใช้งาน_แก้ไข   หลังรายการผู้ใช้งาน_เมื่อกดปุ่ม บันทึก ระบบแสดง Error   Message"บันทึกข้อมูลล้มเหลว"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#501]
Summary   Name | ผู้ใช้งาน_แก้ไข   หลังรายการผู้ใช้งาน_เมื่อกดปุ่ม บันทึก ระบบแสดง Error   Message"บันทึกข้อมูลล้มเหลว"
-- | --
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
Defect No. |  501
URL | http://nps001.homeip.net:8085/UserInfo.aspx?dataId=1019
  |  
Step | 1. เลือกเมนู   ระบบ
  | 2.   เลือกเมนูย่อย ผู้ใช้งาน
  | 3.   แสดงหน้าจอ รายการผู้ใช้งาน
  | 4.   กดปุ่ม แก้ไข หลังรายาร
  | 5.   แก้ไขข้อมูลใน field
  | 6.   กดปุ่ม บันทึก
  |  
  |  
  |  
Actual   Result | เมื่อกดปุ่ม   บันทึก ระบบแสดง Message"บันทึกข้อมูลล้มเหลว"
  |  
Expected   Result | เมื่อกดปุ่ม   บันทึก ระบบต้องแสดง Message "บันทึกข้อมูลสำเร็จ" ที่มุมล่างขวา
  |  
  |  

![image](https://user-images.githubusercontent.com/45878758/58799739-470b8400-8630-11e9-8111-653745671fb4.png)
![image](https://user-images.githubusercontent.com/45878758/58799744-48d54780-8630-11e9-84aa-3ea9a10878ce.png)
![image](https://user-images.githubusercontent.com/45878758/58799747-4b37a180-8630-11e9-87fe-b066e397443d.png)

**Comment by Patthamaporn** [comment]
แก้ไข หากแก้ไขแล้วกดปุ่ม บันทึก ระบบจะแสดง Message "บันทึกข้อมูลสำเร็จ" ที่มุมล่างขวา
