### ISSUE TITLE
คลัง_Locationpicking_แก้ไขหลังรายการ_ใน Column ชื่อภาษาอังกฤษแสดง "&nbsp;"

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#502]
Summary   Name | คลัง_Locationpicking_แก้ไขหลังรายการ_ใน   Column ชื่อภาษาอังกฤษแสดง "& nbsp;"
-- | --
Defect No. |  502
Version | 2018 © WMS by Logis   Pro Solution co., Ltd. AT-Social!
URL |  
Step | 1. Login
  | 2.   เลือกเมนู ตั้งค่า
  | 3.   เลือกเมนูย่อย คลัง
  | 4.   แสดงหน้าจอ รายการคลัง
  | 5.   กดปุ่ม เพิ่มคลัง
  | 6.   แสดงหน้าจอ เพิ่มคลัง
  | 7.   ระบุข้อมูลใน field
  | 8.   กดปุ่ม บันทึก
  | 9.   บันทึกสำเร็จ
  | 10.   แสดงหน้าจอ รายการคลัง
  | 11.   กดปุ่ม แก้ไข หลังรายการ
  | 12.   แสดงหน้าจอ เพิ่มคลัง
  | 13.   Blog รายการโซน
  | 14.   กดปุ่ม แก้ไข หลังรายการ
  | 15.   แสดงหน้าจอ เพิ่มโซน
  | 16.   Blog Location Picking
  | 17.   กดปุ่ม แก้ไข หลังรายการ
  | 18.   แสดงหน้าจอ Location
  | 18.   เลือก Tab รายการ
  | 19.   ไม่ใส่ข้อมูลใน Field ชื่อภาษาอังกฤษ
  | 20.   บันทึกข้อมูลสำเร็จ
  | 21.   กดปุ่มกลับ
  | 22.   แสดงหน้าจอ เพิ่มโซน
  | 23. Blog Location   Picking
  |  
Actual   Result | ใน   Column ชื่อภาษาอังกฤษแสดง "& nbsp;"
  |  
Expected   Result | ต้องไม่มีข้อความใน   Column ชื่อภาษาอังกฤษ เหมือนในหน้าจอ Location
  |  
TesterName | Nuttanun

![image](https://user-images.githubusercontent.com/45878758/58820601-3b828200-865d-11e9-9d73-9857e83c70de.png)
![image](https://user-images.githubusercontent.com/45878758/58820625-4ccb8e80-865d-11e9-8bd5-3678f20ccc74.png)
![image](https://user-images.githubusercontent.com/45878758/58820634-50f7ac00-865d-11e9-901e-d8e5c6d8acbf.png)
![image](https://user-images.githubusercontent.com/45878758/58820638-53f29c80-865d-11e9-9474-33ca0b45edf7.png)
![image](https://user-images.githubusercontent.com/45878758/58820640-56ed8d00-865d-11e9-8119-4e14a9941a15.png)

**Comment by Mickrepick** [comment]
แก้ไขแล้ว : ถ้าไม่กรอกข้อมูลใน Field ชื่อภาษาอังกฤษ ใน Column ชื่อภาษาอังกฤษจะว่าง
