### ISSUE TITLE
ผู้ใช้งาน_แก้ไข   หลังรายการผู้ใช้งาน_ระบบต้องแสดงข้อความแจ้งเตือนด้านล่างแค่ 1 ชุด ใน Blog   ผู้ใช้งาน

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#503]
Summary   Name | ผู้ใช้งาน_แก้ไข   หลังรายการผู้ใช้งาน_ระบบต้องแสดงข้อความแจ้งเตือนด้านล่างแค่ 1 ชุด ใน Blog   ผู้ใช้งาน
-- | --
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
Defect No. |  503
URL | http://nps001.homeip.net:8085/UserInfo.aspx?dataId=1019
  |  
Step | 1. เลือกเมนู   ระบบ
  | 2.   เลือกเมนูย่อย ผู้ใช้งาน
  | 3.   แสดงหน้าจอ รายการผู้ใช้งาน
  | 4.   กดปุ่ม แก้ไข หลังรายการ
  | 5.   แสดงหน้าจอ ผู้ใช้งาน
  | 6.   ไม่กรอกข้อมูลใน field ทั้งหมด
  | 7.   กดปุ่ม บันทึก
  |  
  |  
  |  
Actual   Result | ระบบแสดงข้อความแจ้งเตือนด้านล่าง   2 ชุม
  |  
Expected   Result | ระบบต้องแสดงข้อความแจ้งเตือนด้านล่างแค่   1 ชุด ใน Blog ผู้ใช้งาน
  |  

![image](https://user-images.githubusercontent.com/45878758/58826203-5d363600-866a-11e9-9689-008036331871.png)
![image](https://user-images.githubusercontent.com/45878758/58826209-60312680-866a-11e9-8b8b-a6d1f7f5d91b.png)

**Comment by Mickrepick** [comment]
แก้ไข : จะขึ้นข้อความแจ้งเตือนด้านล่างแค่ 1 ชุด
