### ISSUE TITLE
สินค้า_ข้อมูลสินค้า_ต้องไม่สามารถเลือกสินค้าที่   ปิดใช้งาน ในหน้าจอ ใบสั่งซื้อ ได้

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#504]
Summary   Name | สินค้า_ข้อมูลสินค้า_ต้องไม่สามารถเลือกสินค้าที่   ปิดใช้งาน ในหน้าจอ ใบสั่งซื้อ ได้
-- | --
Version | 2018   © WMS by Logis Pro Solution co., Ltd. AT-Social!
Defect No. | 504
URL | http://nps001.homeip.net:8085/SkuInfo.aspx?dataId=4055
  | http://nps001.homeip.net:8085/PurchaseInfo.aspx?subDoc=18
Step | 1.   เลือกเมนู ตั้งค่า
  | 2.   เลือกเมนูย่อย สินค้า
  | 3.   แสดงหน้าจอรายการสินค้า
  | 4.   กดปุ่ม แก้ไช หลังรายการ
  | 5.   แสดงหน้าจอ ข้อมูลสินค้า
  | 6.   เลือก Tab ตั้งค่าสินค้า
  | 7.   เลือก field สามารถซือได้ เป็น "ปิดใช้งาน"
  | 8.   เลือกเมนู งานประจำวัน
  | 9.   เลือกเมนูย่อย ใบสั่งซื้อสินค้า
  | 10.   เลือก สั่งซื้อทั่วไป
  | 11.   แสดงหน้าจอ รายการใบสั่งซื้อสินค้า
  | 12.   กดปุ่ม เพิ่มใบสั่งซื้อ
  | 13.   แสดงหน้าจอ ใบสั่งซื้อ
  | 14.   กดปุ่ม ค้นหาสินค้า
  | 15.   แสดง PopUp ค้นหาสินค้า
  | 16.   เลือกสินค้า
  |  
  |  
  |  
Actual Result | ระบบสามารถเลือกสินค้าที่   "ปิดใช้งาน" อยู่มาแสดงใน Column แสดงผลได้
  |  
Expected   Result | ระบบต้องไม่สามรถเลือกสินค้าที่   "ปิดใช้งาน" อยู่ได้ และแสดง Error Message   "ไม่สามารถใช้สินค้านี้ได้เนื่องจากไม่ได้ตั้งสิทธิ์การซื้อ"
  |  

![image](https://user-images.githubusercontent.com/45878758/59005051-3f252d00-8846-11e9-8614-55bcacf509bc.png)
![image](https://user-images.githubusercontent.com/45878758/59005052-40eef080-8846-11e9-917c-06d8dce1ce3c.png)
![image](https://user-images.githubusercontent.com/45878758/59005054-43514a80-8846-11e9-98d0-2dc34b1e05cd.png)
![image](https://user-images.githubusercontent.com/45878758/59005060-451b0e00-8846-11e9-92ea-238f7b1b6fa3.png)
![image](https://user-images.githubusercontent.com/45878758/59005061-46e4d180-8846-11e9-944d-934018329d3b.png)
![image](https://user-images.githubusercontent.com/45878758/59005066-4815fe80-8846-11e9-9526-ebb709df742b.png)

**Comment by Patthamaporn** [comment]
แก้ไข หากสินค้าไม่ได้ตั้งค่าให้ซื้อได้จะแจ้งเตือนว่า ไม่สามารถใช้สินค้านี้ได้เนื่องจากไม่ได้ตั้งสิทธิ์การซื้อ
