### ISSUE TITLE
ปริ้นรายงาน  WMS ใช้ไม่ได้

### ISSUE THREAD

**Issue by logisprosolution** [logisprosolution/WMS#528]
ปริ้นรายงาน  WMS ใช้ไม่ได้

**Comment by Mickrepick** [comment]
ทุกหน้าของระบบ

**Comment by logisprosolution** [comment]
รายงาน
default วันที่กำหนดส่ง ค่าว่าง

เลือก ประเภทเอกสาร วันที่กำหนดส่ง ค่าว่าง
