### ISSUE TITLE
แก้ไขหน้า default

### ISSUE THREAD

**Issue by logisprosolution** [logisprosolution/WMS#55]
เอาหน้า dashboard (index) ของ layout2 มาใส่หน้า default
ให้มันไม่โล่งเฉยๆ

ส่วนนี้
![image](https://user-images.githubusercontent.com/30793831/45010363-53c66180-b037-11e8-9c44-13ec04fc8d85.png)

**Comment by Patthamaporn** [comment]
wait for test
