### ISSUE TITLE
หน้าตรวจเข้า ออก   เพิ่มจำนวนคงเหลือ

### ISSUE THREAD

**Issue by logisprosolution** [logisprosolution/WMS#59]
ใน LIST รายการสินค้า ตองมีﬁeld จํานวนคงเหลือ 
![image](https://user-images.githubusercontent.com/30793831/47414718-dfd54980-d79b-11e8-8f05-2b2cc7ebd6e1.png)
จำนวคงเหลือ คือ จำนวนที่สั่ง - จำนวนที่เช็ค

**Comment by Patthamaporn** [comment]
wait for test
