### ISSUE TITLE
ใบนําเขา/ใบจัดเก็บ ตั้งค่าการอ่านจาก

### ISSUE THREAD

**Issue by logisprosolution** [logisprosolution/WMS#61]
ใบนําเขา/ใบจัดเก็บ
ตั้งค่าได้ว่าให้อ่านจากเพื่่อสร้างใบนําเข้าได้จาก 
ใบสั่งซื้อ หรือ ใบเช็คสินคาเขา หรือ รายการสินคาในใบเช็ค 
(Implement )แลวแตjหนhางาน 

ในความหมายคือ ทุกหน้าเอกสาร จะต้องตั้งได้ว่า จะนำเข้าจาก ใบอะไรได้บ้าง
วิธี- ตั้ง parameter ใน web.config ด้วยตัวแปร 
Inbound_ImportSubDoc = "10001(PO),1002(CI)"
outbound_ImportSubDoc = "10003(SO)"

**Comment by Patthamaporn** [comment]
wait for test
