### ISSUE TITLE
[ตรวจสินค้าเข้า] สอบถามค่ะ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#85]
Step 
1. เลือกเมนู ตรวจสอบสินค้าเข้า
2. กดเพิ่มใบตรวจสินค้า หรือ กดตรวจสอบหลังรายการ
Q
1. Field วันที่เอกสาร สามารถเลือกวันที่ หลังปัจจุบันได้มั้ยคะ ถ้าได้มีกำหนดมั้ยว่ากี่วันนับจากวันที่ปัจจุบัน
เช่น วันที่ปัจจุบัน 13/3/2562 ใส่ใน field  20/3/2562
2. Field วันที่เอกสาร สามารถเลือกวันที่ก่อนปัจจุบันได้มั้ยคะ ถ้าได้มีกำหนดมั้ยว่ากี่วันนับจากวันที่ปัจจุบัน
เช่น วันที่ปัจจุบัน 13/3/2562 ใส่ใน field 1/3/2562
3. Field วันที่ใบส่งของ ตรงนี้ต้องใส่วันที่อะไรคะ
4. ถ้าใส่ จำนวนที่เช็คแล้วมากกว่า จำนวนสั่งซื้อ ระบบแสดง Error Message "จำนวนสินค้าที่เช็คแล้วมากกว่าจำนวนสินค้าในสต็อก" ถ้าเปลี่ยนเป็น "จนวนสินค้าที่เช็คแล้วมากกว่าจำนวนสั่งซื้อ" จะเข้าใจง่ายกว่ามั้ยคะ ขอ Confirm ค่ะ
![image](https://user-images.githubusercontent.com/45878758/53677895-ed6e8300-3ce9-11e9-9496-69491cc5707d.png)

Phatcharat.Sun--------------------------2/3/2562

**Comment by logisprosolution** [comment]
วันที่ ณตอนนี้้ ทั้งระบบ เปิดให้กรอกย้อนหลังได้ แล้วจะ ใส่วันอะไรก็ได้ครับ
"จำนวนสินค้าที่เช็คแล้วมากกว่าจำนวนนำเข้า"
