### ISSUE TITLE
[รายการนำเข้าสินค้า] สอบถามค่ะ

### ISSUE THREAD

**Issue by Vermouthz** [logisprosolution/WMS#86]
1. ถ้ามีการสร้างรายการใบสั่งซื้อสินค้า และอนุมัติแล้ว เมื่อเข้ามาในหน้าจอรายการนำเข้าสินค้า สามารถค้นหาเจอรายการสินค้ามั้ยคะ หรือว่าต้องนำเข้าจาก.. และกดบันทึก ถึงจะสามารถค้นหารายการเจอคะ
- ถ้าค้นหาโดยยังไม่ได้เพิ่มใบนำเข้า จะค้นหาไม่เจอ
- ถ้าเพิ่มใบนำเข้าแล้ว จะค้นหาเจอ
2. Version WMS ที่แล้ว มีปุ่ม รับสินค้าเข้า หลังรายการ
[ISSUS_รายการนำเข้าสินค้า ไม่พบรายการที่อนุมัติมาจากหน้าจอรายการใบสั่งซื้อ_25620302_Phatcharat.xlsx](https://github.com/logisprosolution/WMS/files/2921985/ISSUS_._25620302_Phatcharat.xlsx)

Phatcharat-----------------------------------------2/3/2562

**Comment by logisprosolution** [comment]
สร้างรายการใบสั่งซื้อสินค้า และอนุมัติแล้ว
รายการจะไปโผล่ที่หน้า นำเข้าสินค้า InboundList สามารถกด action เพิ่มได้เลย
